import { existsSync, statSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { isDeepStrictEqual } from "node:util";
import type { AirDocument } from "@anvil/air";
import {
  bundleHash,
  type Certification,
  certifyBundle,
  deploymentArtifactHash,
  GENERATION_METADATA_FILE,
  IDEMPOTENCY_STORE_CONTRACT_FILE,
  type IdempotencyStoreContract,
  idempotencyStoreContract,
  idempotencyStoreContractDigest,
  ledgerDeploymentInputDigest,
  parseIdempotencyStoreContract,
  readBundleDir,
  resourceOptionsFromGenerationMetadata,
} from "@anvil/generators";
import type { Command } from "commander";
import { recommendsExplicitIdempotencyKey, requiresExplicitIdempotencyKey } from "../explain.js";
import type { CliIO } from "../io.js";
import type { CommandContext } from "./context.js";
import { loadAir } from "./shared.js";

export type IdempotencyStoreContractState = "fresh" | "missing" | "corrupt" | "stale";

/**
 * Read and verify the generated store contract and compiler-owned bundle bytes
 * against canonical AIR and the persisted generator inputs.
 *
 * The CLI deliberately consumes the generator-owned contract instead of
 * independently deriving Firestore coordinates. This keeps Terraform, runtime
 * configuration, status, and operator guidance on one source of truth.
 */
export interface IdempotencyStoreInspection {
  state: IdempotencyStoreContractState;
  path: string;
  expected: IdempotencyStoreContract;
  stored: IdempotencyStoreContract | null;
  detail: string;
}

export function inspectIdempotencyStore(
  air: AirDocument,
  bundle: string,
  files: Readonly<Record<string, string>>,
  certification: Certification = certifyBundle({ ...files }, air),
): IdempotencyStoreInspection {
  const path = join(bundle, IDEMPOTENCY_STORE_CONTRACT_FILE);
  const resourceOptions =
    resourceOptionsFromGenerationMetadata(files[GENERATION_METADATA_FILE]) ?? {};
  const expected = idempotencyStoreContract(air, resourceOptions);
  const raw = files[IDEMPOTENCY_STORE_CONTRACT_FILE];
  if (raw === undefined) {
    return {
      state: "missing",
      path,
      expected,
      stored: null,
      detail: `${IDEMPOTENCY_STORE_CONTRACT_FILE} is missing; recompile the bundle.`,
    };
  }

  let stored: IdempotencyStoreContract;
  try {
    stored = parseIdempotencyStoreContract(raw);
  } catch (error) {
    return {
      state: "corrupt",
      path,
      expected,
      stored: null,
      detail: error instanceof Error ? error.message : String(error),
    };
  }

  if (!isDeepStrictEqual(stored, expected)) {
    return {
      state: "stale",
      path,
      expected,
      stored,
      detail:
        `${IDEMPOTENCY_STORE_CONTRACT_FILE} does not match canonical AIR; ` +
        "recompile before planning or proving ledger readiness.",
    };
  }

  if (certification.bundleHash !== bundleHash({ ...files })) {
    return {
      state: "stale",
      path,
      expected,
      stored,
      detail:
        "The generated-byte judgement does not bind the current bundle hash; recompute it or recompile before planning ledger readiness.",
    };
  }

  const generatedBytesCheck = certification.checks.find(
    (check) => check.id === "contract.generated-bytes-agree",
  );
  if (generatedBytesCheck?.status !== "passed") {
    return {
      state: "stale",
      path,
      expected,
      stored,
      detail:
        generatedBytesCheck?.detail ??
        "The compiler-owned generated-byte check is missing; recompile before planning or proving ledger readiness.",
    };
  }

  return {
    state: "fresh",
    path,
    expected,
    stored,
    detail:
      expected.backend === "firestore"
        ? "The generated Firestore store contract and every compiler-owned bundle byte match canonical AIR and persisted generation inputs."
        : "Canonical AIR does not require a managed idempotency store, and every compiler-owned bundle byte matches its deterministic projection.",
  };
}

interface DeployLedgerOptions {
  project?: string;
  database?: string;
  databaseMode?: "shared" | "dedicated";
  location?: string;
  ttlSeconds?: string;
  json?: boolean;
  tfvars?: boolean;
}

export function registerDeployLedger(parent: Command, ctx: CommandContext): void {
  parent
    .command("ledger")
    .summary("Inspect durable-write coverage and the generated Firestore ledger contract.")
    .description(
      "Read-only and offline. Lists every approved write and its idempotency posture, verifies deploy/idempotency-store.json plus every compiler-owned generated byte against canonical AIR and persisted generator inputs, and prints the selected Firestore database/collection/ANVIL_LEDGER coordinate. Shared mode (default) uses an existing platform-owned trust-domain database; dedicated mode creates one capability-owned database. Static wiring is not live readiness: after applying the reviewed Terraform plan, require the deployed /readyz probe to return 200. Firestore Native is the built-in managed backend; Firebase client SDKs, AlloyDB, and Spanner are not silently substituted.",
    )
    .argument("<dir>", "bundle directory or air.yaml")
    .option("--project <id>", "resolve {project_id} in the planned ledger URI")
    .option("--database <id>", "exact Firestore Native database id, including (default)")
    .option(
      "--database-mode <mode>",
      "shared (existing trust-domain database) or dedicated (create one database)",
      "shared",
    )
    .option(
      "--location <location>",
      "reviewed immutable Firestore location; required only in dedicated mode",
    )
    .option(
      "--ttl-seconds <seconds>",
      "completed replay-result retention (60..31536000; defaults from the generated contract)",
    )
    .option("--json", "emit one machine-readable offline readiness report")
    .option(
      "--tfvars",
      "emit only Terraform input JSON (requires --project and --database; dedicated also requires --location)",
    )
    .action(async (dir: string, opts: DeployLedgerOptions) => {
      ctx.code = await runDeployLedger(dir, opts, ctx.io);
    });
}

/**
 * The durable-write/operator surface. Coordinates come only from the generated
 * store contract and are accepted only when both the contract and generated
 * bundle still match their deterministic projections. This command never
 * probes a provider; `/readyz` is the post-apply proof.
 */
export async function runDeployLedger(
  dir: string,
  opts: DeployLedgerOptions,
  io: CliIO,
): Promise<number> {
  const optionError = validateLedgerOptions(opts);
  if (optionError) {
    io.err(optionError);
    return 1;
  }

  let air: ReturnType<typeof loadAir>;
  try {
    air = loadAir(dir);
  } catch (error) {
    io.err(error instanceof Error ? error.message : String(error));
    return 1;
  }
  const bundle = resolveBundleRoot(dir);
  let files: Record<string, string>;
  try {
    files = readBundleDir(bundle);
  } catch (error) {
    io.err(error instanceof Error ? error.message : String(error));
    return 1;
  }
  const inspection = inspectIdempotencyStore(air, bundle, files);
  if (inspection.state !== "fresh") {
    io.err(`Idempotency store contract is ${inspection.state}: ${inspection.detail}`);
    return 1;
  }

  const contract = inspection.expected;
  const managedStoreOperationIds = new Set<string>(contract.requirement.operationIds);
  const writes = air.operations
    .filter((operation) => operation.state === "approved" && operation.effect.kind === "mutation")
    .map((operation) => ({
      id: operation.id,
      command: operation.cli.command,
      idempotency: {
        mode: operation.idempotency.mode,
        mechanism: operation.idempotency.mechanism,
        key: operation.idempotency.key ?? null,
        keyDerivation: operation.idempotency.keyDerivation,
        explicitKeyRequired: requiresExplicitIdempotencyKey(operation),
        explicitKeyRecommended: recommendsExplicitIdempotencyKey(operation),
      },
      retries: operation.retries.mode,
      managedStoreRequired: managedStoreOperationIds.has(operation.id),
    }));

  if (contract.backend === "none") {
    return renderNoStore(air.service.id, inspection, writes, opts, io);
  }

  const ttlSeconds = parseLedgerTtlSeconds(
    opts.ttlSeconds,
    contract.firestore.retention.resultTtlSecondsDefault,
  );
  if (ttlSeconds === null) {
    io.err("--ttl-seconds must be an integer from 60 to 31536000.");
    return 1;
  }
  const databaseMode = opts.databaseMode ?? "shared";
  if (databaseMode === "dedicated" && opts.database === "(default)") {
    io.err("Dedicated mode requires a named --database id, not (default).");
    return 1;
  }
  if (databaseMode === "dedicated" && opts.database === undefined) {
    io.err("Dedicated mode requires --database so Terraform can create the exact named database.");
    return 1;
  }
  if (databaseMode === "dedicated" && opts.location === undefined) {
    io.err(
      "Dedicated mode requires --location because a Firestore database location is immutable after creation.",
    );
    return 1;
  }
  if (databaseMode === "shared" && opts.location !== undefined) {
    io.err(
      "--location is not accepted in shared mode: the platform-owned database already has an immutable location.",
    );
    return 1;
  }
  if (opts.tfvars === true && (opts.project === undefined || opts.database === undefined)) {
    io.err(
      "--tfvars requires --project and --database so the emitted input has no unresolved store coordinate.",
    );
    return 1;
  }

  const runtimeUri =
    opts.project === undefined || opts.database === undefined
      ? null
      : contract.firestore.runtimeUri.resolvedTemplate
          .replace("{project_id}", opts.project)
          .replace("{database_id}", opts.database);
  const currentBundleHash = bundleHash({ ...files });
  const runtimeArtifactHash = deploymentArtifactHash({ ...files });
  const storeContractDigest = idempotencyStoreContractDigest(contract);
  const deploymentInput =
    opts.project === undefined || opts.database === undefined
      ? null
      : {
          bundleHash: currentBundleHash,
          databaseId: opts.database,
          databaseMode,
          expectedProjectId: opts.project,
          location: databaseMode === "dedicated" ? (opts.location ?? null) : null,
          namespace: contract.firestore.namespace,
          resultTtlSeconds: ttlSeconds,
          runtimeArtifactHash,
          storeContractDigest,
        };
  const deploymentInputDigest =
    deploymentInput === null ? null : ledgerDeploymentInputDigest(deploymentInput);
  const terraformInputs = {
    ...(deploymentInput
      ? {
          anvil_bundle_hash: currentBundleHash,
          anvil_expected_project_id: deploymentInput.expectedProjectId,
          anvil_ledger_input_digest: deploymentInputDigest,
        }
      : {}),
    ledger_database_mode: databaseMode,
    ...(opts.database ? { ledger_database_id: opts.database } : {}),
    ledger_location: databaseMode === "dedicated" ? (opts.location ?? null) : null,
    ledger_result_ttl_seconds: ttlSeconds,
  };
  if (opts.tfvars === true) {
    io.out(JSON.stringify(terraformInputs, null, 2));
    return 0;
  }

  const report = {
    schemaVersion: 1,
    serviceId: air.service.id,
    bundleHash: currentBundleHash,
    contract: {
      path: inspection.path,
      state: inspection.state,
      required: true,
      backend: contract.backend,
      digest: storeContractDigest,
    },
    writes,
    store: {
      provider: "google-cloud-firestore-native",
      project: opts.project ?? null,
      databaseId: opts.database ?? null,
      databaseTerraformVariable: contract.firestore.database.idTerraformVariable,
      provisioningMode: databaseMode,
      databaseModeTerraformVariable: contract.firestore.database.provisioningModeTerraformVariable,
      databaseModeDefault: contract.firestore.database.provisioningModeDefault,
      databaseMode: contract.firestore.databaseMode,
      location: opts.location ?? null,
      locationRequiredFor: contract.firestore.location.requiredFor,
      locationImmutable: contract.firestore.location.immutable,
      provisioning: contract.firestore.provisioning,
      namespace: contract.firestore.namespace,
      collectionGroup: contract.firestore.collectionGroup,
      indexing: contract.firestore.indexing,
      runtimeEnvironmentVariable: contract.firestore.runtimeUri.environmentVariable,
      runtimeUri,
      runtimeUriTemplate: contract.firestore.runtimeUri.resolvedTemplate,
      deploymentArtifactHash: runtimeArtifactHash,
      ttlField: contract.firestore.retention.ttlField,
      resultTtlSeconds: ttlSeconds,
      inProgressExpires: contract.firestore.retention.inProgressExpires,
      maxReplayResultBytes: contract.firestore.retention.maxReplayResultBytes,
      iamRole: contract.firestore.iam.role,
      iamScope: contract.firestore.iam.scope,
    },
    staticWiring: { state: "fresh", detail: inspection.detail },
    deploymentInput:
      deploymentInput === null
        ? {
            state: "unresolved",
            digest: null,
            detail:
              "Pass --project and --database to bind reviewed non-secret inputs to this bundle.",
          }
        : {
            state: "bound",
            digest: deploymentInputDigest,
            values: deploymentInput,
            detail:
              "Terraform recomputes this digest and requires the actual Cloud Build project to equal expectedProjectId.",
          },
    liveReadiness: {
      state: "unverified",
      path: contract.firestore.readiness.path,
      method: contract.firestore.readiness.method,
      mutates: contract.firestore.readiness.mutates,
      deploymentStartupGate: contract.firestore.readiness.deploymentStartupGate,
      livenessRestartOnProviderFailure:
        contract.firestore.readiness.livenessRestartOnProviderFailure,
      expected: { httpStatus: 200, body: { ready: true, service: air.service.id } },
      detail:
        "Only the deployed /readyz data-plane probe can prove the database exists and the runtime identity can reach it.",
    },
    terraformInputs,
    guarantees: {
      exactlyOnce: false,
      completedReplayRetentionSeconds: ttlSeconds,
      completedReplay: "same key and request fingerprint returns the stored result until expiry",
      conflictingReplay: "same key with a different request fingerprint is refused",
      concurrentReplay: "an existing in-progress reservation is refused, not re-executed",
      crashBoundary:
        "an upstream success followed by a crash before completion remains in_progress and requires operator reconciliation",
      oversizedSuccessfulResponse: `a successful response above ${contract.firestore.retention.maxReplayResultBytes} serialized bytes remains in_progress for operator reconciliation`,
      scope:
        "the document key follows the service/environment/upstream credential-profile namespace; when inbound identity is verified, the request fingerprint separately binds that principal; without inbound identity, the key is a shared operation coordinate",
    },
    cloudCallsMade: false,
  };
  if (opts.json === true) {
    io.out(JSON.stringify(report, null, 2));
    return 0;
  }

  renderFirestorePlan(
    air.service.id,
    inspection.path,
    contract,
    writes,
    {
      ...opts,
      runtimeUri,
      ttlSeconds,
      bundleHash: currentBundleHash,
      deploymentInputDigest,
      runtimeArtifactHash,
      storeContractDigest,
    },
    io,
  );
  return 0;
}

type StoreInspection = IdempotencyStoreInspection;
type WriteSummary = {
  id: string;
  command: string;
  idempotency: {
    mode: string;
    mechanism: string;
    key: string | null;
    keyDerivation: string;
    explicitKeyRequired: boolean;
    explicitKeyRecommended: boolean;
  };
  retries: string;
  managedStoreRequired: boolean;
};

function renderNoStore(
  serviceId: string,
  inspection: StoreInspection,
  writes: WriteSummary[],
  opts: DeployLedgerOptions,
  io: CliIO,
): number {
  if (opts.tfvars === true) {
    io.out("{}");
    return 0;
  }
  if (opts.json === true) {
    io.out(
      JSON.stringify(
        {
          schemaVersion: 1,
          serviceId,
          contract: {
            path: inspection.path,
            state: inspection.state,
            required: false,
            backend: "none",
          },
          writes,
          staticWiring: { state: "fresh", detail: inspection.detail },
          liveReadiness: {
            state: "not-required",
            detail: "No approved mutation requires the managed idempotency store.",
          },
          cloudCallsMade: false,
        },
        null,
        2,
      ),
    );
    return 0;
  }
  io.out(`Idempotency write plan — ${serviceId}`);
  io.out(`  contract: fresh — ${inspection.path}`);
  renderWrites(writes, io);
  io.out("");
  io.out("Managed store — NOT REQUIRED");
  io.out(
    "  No approved mutation has idempotency mode `required`; this Terraform projection omits ledger resources and runtime IAM, and sets ANVIL_LEDGER to an explicit empty value.",
  );
  io.out(
    "  If this removes the last required write, the reviewed apply detaches access but ABANDON preserves replay evidence, TTL, and index policy; a prior dedicated database is also preserved.",
  );
  io.out(
    "  Reintroducing a preserved ledger requires reviewed imports of both field policies; dedicated mode also imports its database.",
  );
  io.out(
    "  This does not make non-idempotent writes safe: `none` remains non-retryable, and approval/confirmation still apply.",
  );
  io.out("  No cloud call was made.");
  return 0;
}

function renderFirestorePlan(
  serviceId: string,
  contractPath: string,
  contract: Extract<IdempotencyStoreContract, { backend: "firestore" }>,
  writes: WriteSummary[],
  opts: Omit<DeployLedgerOptions, "ttlSeconds"> & {
    bundleHash: string;
    deploymentInputDigest: string | null;
    runtimeUri: string | null;
    runtimeArtifactHash: string;
    storeContractDigest: string;
    ttlSeconds: number;
  },
  io: CliIO,
): void {
  const provisioningMode = opts.databaseMode ?? contract.firestore.database.provisioningModeDefault;
  const database =
    opts.database ?? `var.${contract.firestore.database.idTerraformVariable} (required)`;
  io.out(`Idempotency write plan — ${serviceId}`);
  io.out(`  contract: fresh — ${contractPath}`);
  renderWrites(writes, io);
  io.out("");
  io.out("Managed store — REQUIRED");
  io.out("  backend: Google Cloud Firestore Native (no Firebase client SDK)");
  io.out(`  database: ${database}`);
  io.out(`  provisioning mode: ${provisioningMode}`);
  io.out(`  collection group: ${contract.firestore.collectionGroup}`);
  if (provisioningMode === "dedicated") {
    io.out(`  location: ${opts.location} — immutable after first creation`);
  } else {
    io.out(
      "  location: owned by the existing shared database; omit --location (it is accepted only for dedicated mode)",
    );
  }
  io.out(
    `  ANVIL_LEDGER: ${opts.runtimeUri ?? `${contract.firestore.runtimeUri.resolvedTemplate} (pass --project and --database to resolve)`}`,
  );
  io.out(`  certified bundle hash: ${opts.bundleHash}`);
  io.out(`  deployed runtime artifact hash: ${opts.runtimeArtifactHash}`);
  io.out(`  store contract digest: ${opts.storeContractDigest}`);
  io.out(
    opts.deploymentInputDigest === null
      ? "  reviewed input digest: unresolved — pass --project and --database to bind it"
      : `  reviewed input digest: ${opts.deploymentInputDigest}`,
  );
  io.out(
    "  project identity: Cloud Build must submit with --project; Terraform refuses any actual project that differs from the reviewed expected project.",
  );
  io.out(
    `  retention: completed results ${opts.ttlSeconds}s; in-progress reservations never auto-expire`,
  );
  io.out(
    `  replay result ceiling: ${contract.firestore.retention.maxReplayResultBytes} serialized bytes; larger successful responses remain in_progress for reconciliation`,
  );
  io.out(`  IAM: ${contract.firestore.iam.role}, conditionally scoped to the selected database`);
  io.out(
    "  IAM boundary: Firestore does not isolate collection groups. A shared database may contain only capabilities in one reviewed trust/regulatory domain; use dedicated mode across trust boundaries.",
  );
  io.out(
    "  Console caveat: Google Cloud console access does not enforce Firestore database IAM conditions; restrict console users separately and administer through condition-aware APIs/client libraries.",
  );
  io.out(
    provisioningMode === "dedicated"
      ? "  Terraform creates and delete-protects the dedicated database, then applies TTL/index policies before Cloud Run."
      : "  Terraform does not create or import the platform-owned shared database; it applies only this capability's TTL/index policies before Cloud Run.",
  );
  io.out("  The collection materializes on the first atomic reservation.");
  io.out(
    `  shared prerequisite: ${contract.firestore.provisioning.requiredSharedApis.join(", ")} enabled (not owned by this capability module)`,
  );
  io.out(
    `  capacity: ${contract.firestore.provisioning.databaseQuotaSlotsPerCapability[provisioningMode]} per-capability database quota slots; default single-field indexes disabled`,
  );
  io.out(
    provisioningMode === "dedicated"
      ? "  decommission: dedicated database + both field policies use ABANDON; runtime IAM/config detaches while evidence and policy remain"
      : "  decommission: both field policies use ABANDON; runtime IAM/config detaches and the shared database remains platform-owned",
  );
  io.out(
    provisioningMode === "dedicated"
      ? "  reintroduction: import the preserved database and both field policies into reviewed Terraform state before apply"
      : "  reintroduction: import only both preserved field policies; never import the shared database into capability state",
  );
  io.out("");
  io.out("Static wiring — FRESH");
  io.out(
    "  The store contract and every compiler-owned bundle byte match their deterministic projection. This is not live proof.",
  );
  io.out(
    "  Archive the emitted tfvars and the planned idempotency_store output together; the matching digest binds the plan, but is not an apply receipt.",
  );
  io.out("");
  io.out("Live readiness — UNVERIFIED");
  io.out("  After applying the exact reviewed Terraform plan, require:");
  io.out(
    `    curl --fail --silent --show-error "$ANVIL_SERVICE_URL${contract.firestore.readiness.path}"`,
  );
  io.out(`  Expected: HTTP 200 with {"ready":true,"service":"${serviceId}"}.`);
  io.out(
    "  /healthz is insufficient. /readyz performs a non-mutating data-plane check with the runtime identity.",
  );
  io.out(
    "  Cloud Run startup is gated on readiness; transient provider failure does not trigger a liveness restart loop.",
  );
  if (provisioningMode === "dedicated" && opts.project) {
    io.out(
      `  Before first apply, verify the immutable location is offered: gcloud firestore locations list --project ${shellQuote(opts.project)}`,
    );
  }
  io.out("");
  io.out("Guarantee boundary");
  io.out(
    "  Atomic reservation blocks concurrent duplicates; a completed same-key/same-request replay returns the stored result.",
  );
  io.out(
    "  This is not exactly-once execution. A crash after upstream success stays in_progress for deliberate reconciliation, and completed replay protection ends after the configured TTL.",
  );
  io.out(
    "  The document key follows the service/environment/upstream credential-profile namespace. With verified inbound identity, the fingerprint also binds the principal, so cross-caller raw-key reuse conflicts before upstream. Without inbound identity, the raw key is a shared operation coordinate.",
  );
  io.out(
    "  A successful response above the Firestore replay-result ceiling remains in_progress for reconciliation rather than reopening the duplicate window.",
  );
  io.out(
    "  Firestore Native is the generated production backend. AlloyDB or Spanner require an explicitly registered backend plus separately reviewed infrastructure; Anvil never silently switches stores.",
  );
  io.out("  No cloud call was made.");
}

function renderWrites(writes: WriteSummary[], io: CliIO): void {
  io.out("");
  io.out(`Approved writes — ${writes.length}`);
  if (writes.length === 0) {
    io.out("  (none)");
    return;
  }
  for (const write of writes) {
    const carrier =
      write.idempotency.key === null
        ? write.idempotency.mechanism
        : `${write.idempotency.mechanism}:${write.idempotency.key}`;
    io.out(`  ${write.id}`);
    io.out(`    command: ${write.command}`);
    io.out(
      `    idempotency: ${write.idempotency.mode} · carrier ${carrier} · retries ${write.retries}`,
    );
    io.out(
      `    caller key: ${write.idempotency.explicitKeyRequired ? "required" : write.idempotency.explicitKeyRecommended ? "recommended (request-fingerprint fallback)" : "not required"}`,
    );
    io.out(
      `    durable store: ${write.managedStoreRequired ? "required" : "not required by this operation's AIR contract"}`,
    );
  }
}

function validateLedgerOptions(opts: DeployLedgerOptions): string | null {
  if (opts.json === true && opts.tfvars === true)
    return "Choose either --json or --tfvars, not both.";
  if (
    opts.databaseMode !== undefined &&
    opts.databaseMode !== "shared" &&
    opts.databaseMode !== "dedicated"
  ) {
    return "Invalid --database-mode: expected shared or dedicated.";
  }
  if (opts.project !== undefined && !isGcpProjectId(opts.project)) {
    return "Invalid --project: expected a lowercase GCP project id (6-30 characters, starting with a letter and ending with a letter or digit).";
  }
  if (opts.database !== undefined && !isFirestoreDatabaseId(opts.database)) {
    return "Invalid --database: expected (default) or a 4-63 character Firestore database id.";
  }
  if (opts.location !== undefined && !isFirestoreLocationId(opts.location)) {
    return "Invalid --location: expected a Firestore regional or multi-region location id (lowercase letters, digits, and hyphens).";
  }
  return null;
}

function parseLedgerTtlSeconds(value: string | undefined, fallback: number): number | null {
  if (value === undefined) return fallback;
  if (!/^[0-9]+$/.test(value)) return null;
  const parsed = Number(value);
  return Number.isSafeInteger(parsed) && parsed >= 60 && parsed <= 31_536_000 ? parsed : null;
}

function isGcpProjectId(value: string): boolean {
  return /^[a-z][a-z0-9-]{4,28}[a-z0-9]$/.test(value);
}

function isFirestoreLocationId(value: string): boolean {
  return /^[a-z][a-z0-9-]{1,31}[a-z0-9]$/.test(value);
}

function isFirestoreDatabaseId(value: string): boolean {
  return value === "(default)" || /^[a-z][a-z0-9-]{2,61}[a-z0-9]$/.test(value);
}

function resolveBundleRoot(input: string): string {
  const absolute = resolve(input);
  return existsSync(absolute) && statSync(absolute).isDirectory() ? absolute : dirname(absolute);
}

function shellQuote(value: string): string {
  return `'${value.replaceAll("'", "'\"'\"'")}'`;
}
