import type { AirDocument } from "@anvil/air";
import { operationSafetyInputKeys } from "@anvil/air";

/**
 * Generate a conformance test (spec §16) shipped with the bundle. A generated
 * tool that cannot test its own safety contract is not production-ready. The
 * test asserts the compiled manifest matches AIR's safety posture.
 */
export function generateConformanceTest(air: AirDocument): string {
  const approved = air.operations.filter((o) => o.state === "approved");
  const unsafe = approved.filter((o) => o.confirmation.required).map((o) => o.id);
  const idempotencyRequired = approved
    .filter((o) => o.idempotency.mode === "required")
    .map((o) => o.id);
  const nonRetryable = approved
    .filter((o) => o.effect.kind === "mutation" && o.retries.mode !== "safe")
    .map((o) => o.id);
  // Tool names for the hook<->executor agreement check. The hook must ASK where a
  // human must sign off, DENY (pre-flight) where the model must supply confirm,
  // and DENY where an idempotency key is missing. `confirm: true` is passed for
  // the idempotency cases so they clear the confirmation gate first.
  const humanApprovalTools = approved
    .filter((o) => o.confirmation.humanApproval === true)
    .map((o) => ({ tool: o.mcp.toolName, confirmInput: operationSafetyInputKeys(o).confirm }));
  const modelConfirmTools = approved
    .filter((o) => o.confirmation.required && o.confirmation.humanApproval !== true)
    .map((o) => ({ tool: o.mcp.toolName, confirmInput: operationSafetyInputKeys(o).confirm }));
  // Human-approval ops always ASK first, so the idempotency-deny rule is only
  // reachable (via the hook) for non-human ops cleared with confirm:true.
  const keyTools = approved
    .filter(
      (o) =>
        o.idempotency.mode === "required" &&
        o.idempotency.keyDerivation !== "request_fingerprint" &&
        o.confirmation.humanApproval !== true,
    )
    .map((o) => ({
      tool: o.mcp.toolName,
      confirmInput: operationSafetyInputKeys(o).confirm,
    }));
  const cleanReadTool = approved.find((o) => o.effect.kind === "read" && !o.confirmation.required)
    ?.mcp.toolName;

  return `// Generated by Anvil — conformance tests for "${air.service.id}".
// Verifies the compiled runtime manifest preserves AIR's safety contract.
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { decide } from "../plugin/hookcore.mjs";

const manifest = JSON.parse(
  readFileSync(fileURLToPath(new URL("../runtime/operations.manifest.json", import.meta.url)), "utf8"),
);
const byId = Object.fromEntries(manifest.operations.map((o) => [o.id, o]));

describe("${air.service.id} conformance", () => {
  it("compiles every approved operation", () => {
    expect(manifest.operations).toHaveLength(${approved.length});
  });

  it.each(${JSON.stringify(unsafe)})("requires confirmation for %s", (id) => {
    expect(byId[id]?.confirmation?.required).toBe(true);
  });

  it.each(${JSON.stringify(idempotencyRequired)})("requires an idempotency key for %s", (id) => {
    expect(byId[id]?.idempotency?.mode).toBe("required");
  });

  it.each(${JSON.stringify(nonRetryable)})("never auto-retries %s", (id) => {
    expect(byId[id]?.retries?.mode).toBe("none");
  });
});

// The hook is the outer enforcement ring (plugin/hookcore.mjs). It is only
// honest if it agrees with the runtime: it must ASK/DENY exactly where the
// executor would refuse. Drift here means the plugin lies about the contract.
describe("${air.service.id} hook <-> executor agreement", () => {
  it("denies an unknown tool (tamper/staleness guard)", () => {
    expect(decide("definitely_not_a_tool", {}).decision).toBe("deny");
  });

  it.each(${JSON.stringify(humanApprovalTools)})("asks for human approval on $tool", ({ tool, confirmInput }) => {
    // Human-approval ops escalate to the dialog even if the model supplies confirm.
    expect(decide(tool, { [confirmInput]: true }).decision).toBe("ask");
  });

  it.each(${JSON.stringify(modelConfirmTools)})("denies $tool until confirmation", ({ tool }) => {
    expect(decide(tool, {}).decision).toBe("deny");
  });

  it.each(${JSON.stringify(keyTools)})("denies $tool without an idempotency key", ({ tool, confirmInput }) => {
    // confirm:true clears the confirmation gate so the idempotency rule is reached.
    const d = decide(tool, { [confirmInput]: true });
    expect(d.decision).toBe("deny");
    expect(d.reason).toMatch(/idempotency/i);
  });
${
  cleanReadTool
    ? `
  it("allows a clean approved read (${cleanReadTool})", () => {
    expect(decide("${cleanReadTool}", {}).decision).toBe("allow");
  });`
    : ""
}
});
`;
}
