import type { AirDocument } from "@anvil/air";

/**
 * Generate a conformance test (spec §16) shipped with the bundle. A generated
 * tool that cannot test its own safety contract is not production-ready. The
 * test asserts the compiled manifest matches AIR's safety posture.
 */
export function generateConformanceTest(air: AirDocument): string {
  const approved = air.operations.filter((o) => o.state === "approved");
  const unsafe = approved.filter((o) => o.confirmation.required).map((o) => o.id);
  const idempotencyRequired = approved
    .filter((o) => o.idempotency.mode === "required")
    .map((o) => o.id);
  const nonRetryable = approved
    .filter((o) => o.effect.kind === "mutation" && o.retries.mode !== "safe")
    .map((o) => o.id);
  // Tool names for the hook<->executor agreement check: the hook must ASK where
  // the executor would refuse for confirmation, and DENY where it would refuse
  // for a missing idempotency key. `confirm: true` is passed for the idempotency
  // cases so they clear the confirmation gate first (the executor's order).
  const confirmTools = approved.filter((o) => o.confirmation.required).map((o) => o.mcp.toolName);
  const keyTools = approved
    .filter((o) => o.idempotency.mode === "required")
    .map((o) => o.mcp.toolName);
  const cleanReadTool = approved.find((o) => o.effect.kind === "read" && !o.confirmation.required)
    ?.mcp.toolName;

  return `// Generated by Anvil — conformance tests for "${air.service.id}".
// Verifies the compiled runtime manifest preserves AIR's safety contract.
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { decide } from "../plugin/hookcore.mjs";

const manifest = JSON.parse(
  readFileSync(fileURLToPath(new URL("../runtime/operations.manifest.json", import.meta.url)), "utf8"),
);
const byId = Object.fromEntries(manifest.operations.map((o) => [o.id, o]));

describe("${air.service.id} conformance", () => {
  it("compiles every approved operation", () => {
    expect(manifest.operations).toHaveLength(${approved.length});
  });

  it.each(${JSON.stringify(unsafe)})("requires confirmation for %s", (id) => {
    expect(byId[id]?.confirmation?.required).toBe(true);
  });

  it.each(${JSON.stringify(idempotencyRequired)})("requires an idempotency key for %s", (id) => {
    expect(byId[id]?.idempotency?.mode).toBe("required");
  });

  it.each(${JSON.stringify(nonRetryable)})("never auto-retries %s", (id) => {
    expect(byId[id]?.retries?.mode).toBe("none");
  });
});

// The hook is the outer enforcement ring (plugin/hookcore.mjs). It is only
// honest if it agrees with the runtime: it must ASK/DENY exactly where the
// executor would refuse. Drift here means the plugin lies about the contract.
describe("${air.service.id} hook <-> executor agreement", () => {
  it("denies an unknown tool (tamper/staleness guard)", () => {
    expect(decide("definitely_not_a_tool", {}).decision).toBe("deny");
  });

  it.each(${JSON.stringify(confirmTools)})("asks for human confirmation on %s", (tool) => {
    expect(decide(tool, {}).decision).toBe("ask");
  });

  it.each(${JSON.stringify(keyTools)})("denies %s without an idempotency key", (tool) => {
    // confirm:true clears the confirmation gate so the idempotency rule is reached.
    const d = decide(tool, { confirm: true });
    expect(d.decision).toBe("deny");
    expect(d.reason).toMatch(/idempotency/i);
  });
${
  cleanReadTool
    ? `
  it("allows a clean approved read (${cleanReadTool})", () => {
    expect(decide("${cleanReadTool}", {}).decision).toBe("allow");
  });`
    : ""
}
});
`;
}
