import type { AirDocument } from "@anvil/air";

/**
 * Generate a conformance test (spec §16) shipped with the bundle. A generated
 * tool that cannot test its own safety contract is not production-ready. The
 * test asserts the compiled manifest matches AIR's safety posture.
 */
export function generateConformanceTest(air: AirDocument): string {
  const approved = air.operations.filter((o) => o.state === "approved");
  const unsafe = approved.filter((o) => o.confirmation.required).map((o) => o.id);
  const idempotencyRequired = approved
    .filter((o) => o.idempotency.mode === "required")
    .map((o) => o.id);
  const nonRetryable = approved
    .filter((o) => o.effect.kind === "mutation" && o.retries.mode !== "safe")
    .map((o) => o.id);

  return `// Generated by Anvil — conformance tests for "${air.service.id}".
// Verifies the compiled runtime manifest preserves AIR's safety contract.
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

const manifest = JSON.parse(
  readFileSync(fileURLToPath(new URL("../runtime/operations.manifest.json", import.meta.url)), "utf8"),
);
const byId = Object.fromEntries(manifest.operations.map((o) => [o.id, o]));

describe("${air.service.id} conformance", () => {
  it("compiles every approved operation", () => {
    expect(manifest.operations).toHaveLength(${approved.length});
  });

  it.each(${JSON.stringify(unsafe)})("requires confirmation for %s", (id) => {
    expect(byId[id]?.confirmation?.required).toBe(true);
  });

  it.each(${JSON.stringify(idempotencyRequired)})("requires an idempotency key for %s", (id) => {
    expect(byId[id]?.idempotency?.mode).toBe("required");
  });

  it.each(${JSON.stringify(nonRetryable)})("never auto-retries %s", (id) => {
    expect(byId[id]?.retries?.mode).toBe("none");
  });
});
`;
}
