import type { AirDocument } from "@anvil/air";
import { stringify as toYaml } from "yaml";

/**
 * Deployment artifacts for Cloud Run. Anvil emits these at build time; it holds
 * no cloud credentials and never applies them — a human/CI does.
 *
 * **One owner per concern** (this is the whole point of the file). Earlier Anvil
 * emitted five overlapping mechanisms — a knative `service.yaml`, an
 * `iam.plan.json`, per-env `overlays/`, a `gcloud run deploy` step, *and*
 * Terraform — that set the same image tag / env vars / IAM three different ways
 * and drifted. Now:
 *
 *   - **Terraform** owns all infrastructure *and* runtime configuration: the
 *     service account, Artifact Registry, Secret Manager + its IAM, the Firestore
 *     idempotency ledger + its IAM, the Cloud Run service (image, env vars,
 *     scaling, resources, ingress), and invoker IAM. It is the single source of
 *     truth for every deployable setting.
 *   - **Cloud Build** owns the pipeline: build the prebuilt image, push it, and
 *     run `terraform apply` with the built image tag. It sets *no* runtime config
 *     of its own — it only hands Terraform the image tag and project/region.
 *   - **Dockerfile** owns the container (prebuilt runtime, never rebuilds Anvil).
 *
 * No file contains literal `PROJECT`/`REGION` placeholders; everything flows
 * through Terraform variables, so the bundle is applyable as emitted.
 */
export function generateDeploy(air: AirDocument): Record<string, string> {
  return {
    "deploy/Dockerfile": dockerfile(),
    "deploy/.dockerignore": dockerignore(),
    "deploy/cloudbuild.yaml": cloudBuild(air),
    "deploy/terraform/main.tf": terraformMain(air),
    "deploy/terraform/variables.tf": terraformVariables(air),
    "deploy/env.schema.json": `${JSON.stringify(envSchema(safeHost(air.service.servers[0]?.url)), null, 2)}\n`,
    "deploy/secrets.required.yaml": toYaml(secretsContract(air)),
    "deploy/README.md": deployReadme(air),
  };
}

/** True when the surface has a required-idempotency mutation → needs Firestore. */
function needsLedger(air: AirDocument): boolean {
  return air.operations.some(
    (o) => o.effect.kind === "mutation" && o.idempotency.mode === "required",
  );
}

/**
 * A *prebuilt* runtime image: the bundle is already compiled JS (generated by
 * Anvil), so the container installs production deps and copies the runtime — it
 * never rebuilds Anvil packages inside the image. Distroless, non-root.
 */
function dockerfile(): string {
  return `# Generated by Anvil — prebuilt, single-purpose Cloud Run runtime.
# The bundle is already compiled; we only fetch production dependencies. No
# in-image build of Anvil packages (the runtime is thin by construction).
FROM node:22-slim AS deps
WORKDIR /app
COPY package.json pnpm-lock.yaml* ./
RUN corepack enable && pnpm install --prod --frozen-lockfile || pnpm install --prod

FROM gcr.io/distroless/nodejs22-debian12
WORKDIR /app
ENV NODE_ENV=production
# Compiled runtime + its production node_modules only.
COPY --from=deps /app/node_modules ./node_modules
COPY package.json ./
COPY runtime ./runtime
EXPOSE 8080
USER nonroot
CMD ["runtime/server.js"]
`;
}

function dockerignore(): string {
  return ["cli", "mcp", "mock", "skill", "docs", "tests", "deploy", "*.test.*", "src"].join("\n");
}

/**
 * Cloud Build owns the pipeline only: build → push → `terraform apply`. It sets
 * no runtime config; it passes Terraform the built image tag (`$SHORT_SHA`) and
 * project/region. Terraform is the single owner of the deployed service, so the
 * image tag has exactly one source of truth.
 */
function cloudBuild(air: AirDocument): string {
  const id = air.service.id;
  const image = "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/" + `${id}-tools:$SHORT_SHA`;
  return toYaml({
    steps: [
      {
        id: "build",
        name: "gcr.io/cloud-builders/docker",
        args: ["build", "-f", "deploy/Dockerfile", "-t", image, "."],
      },
      { id: "push", name: "gcr.io/cloud-builders/docker", args: ["push", image] },
      {
        id: "apply",
        name: "hashicorp/terraform",
        entrypoint: "sh",
        args: [
          "-c",
          [
            "cd deploy/terraform",
            "terraform init -input=false",
            // Terraform owns every deployed setting; Cloud Build only supplies the
            // image tag it just built plus project/region. No env vars, IAM, or
            // scaling are set here — that would be a second owner.
            "terraform apply -input=false -auto-approve" +
              ' -var project_id="$PROJECT_ID"' +
              ' -var region="${_REGION}"' +
              ' -var ar_repo="${_AR_REPO}"' +
              ' -var image_tag="$SHORT_SHA"' +
              ' -var anvil_env="${_ANVIL_ENV}"',
          ].join(" && "),
        ],
      },
    ],
    images: [image],
    substitutions: {
      _REGION: "us-central1",
      _AR_REPO: "anvil",
      _ANVIL_ENV: "prod",
    },
    options: { logging: "CLOUD_LOGGING_ONLY" },
  });
}

/**
 * Terraform is the single owner of infrastructure *and* runtime configuration.
 * Every deployed setting — SA, Artifact Registry, Secret + IAM, Firestore ledger
 * + IAM, the Cloud Run service (image, env vars, scaling, resources, ingress),
 * invoker IAM — is declared here and nowhere else.
 */
function terraformMain(air: AirDocument): string {
  const id = air.service.id;
  const secret = air.service.auth.type !== "none";
  const ledger = needsLedger(air);
  const host = safeHost(air.service.servers[0]?.url) ?? "";
  return `# Generated by Anvil — Cloud Run runtime for "${id}" (one tool surface).
# Anvil emits this plan; it does not apply it (no cloud credentials held). This
# file is the single owner of every deployed setting for this service.

resource "google_service_account" "runtime" {
  account_id   = "${id}-tools"
  display_name = "Anvil runtime for ${id}"
  project      = var.project_id
}

resource "google_artifact_registry_repository" "anvil" {
  location      = var.region
  repository_id = var.ar_repo
  format        = "DOCKER"
  project       = var.project_id
}

# Least privilege: logging / trace / metrics only, scoped to this SA.
resource "google_project_iam_member" "logging" {
  project = var.project_id
  role    = "roles/logging.logWriter"
  member  = "serviceAccount:\${google_service_account.runtime.email}"
}

resource "google_project_iam_member" "trace" {
  project = var.project_id
  role    = "roles/cloudtrace.agent"
  member  = "serviceAccount:\${google_service_account.runtime.email}"
}

resource "google_project_iam_member" "metrics" {
  project = var.project_id
  role    = "roles/monitoring.metricWriter"
  member  = "serviceAccount:\${google_service_account.runtime.email}"
}
${
  secret
    ? `
resource "google_secret_manager_secret" "auth_token" {
  secret_id = "${id}-auth-token"
  project   = var.project_id
  replication { auto {} }
}

# Scoped to this one secret — never a project-wide secret role.
resource "google_secret_manager_secret_iam_member" "runtime_reads_token" {
  secret_id = google_secret_manager_secret.auth_token.id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:\${google_service_account.runtime.email}"
}
`
    : ""
}${
  ledger
    ? `
# Durable idempotency ledger. Required: the runtime fails closed on
# required-idempotency mutations outside dev without it.
resource "google_firestore_database" "ledger" {
  name        = "(default)"
  location_id = var.region
  type        = "FIRESTORE_NATIVE"
  project     = var.project_id
}

resource "google_project_iam_member" "runtime_ledger" {
  project = var.project_id
  role    = "roles/datastore.user"
  member  = "serviceAccount:\${google_service_account.runtime.email}"
}
`
    : ""
}
resource "google_cloud_run_v2_service" "tools" {
  name     = "${id}-tools"
  location = var.region
  project  = var.project_id
  ingress  = "INGRESS_TRAFFIC_INTERNAL_ONLY"

  template {
    service_account = google_service_account.runtime.email
    scaling {
      min_instance_count = var.min_instances
      max_instance_count = var.max_instances
    }
    containers {
      image = "\${var.region}-docker.pkg.dev/\${var.project_id}/\${var.ar_repo}/${id}-tools:\${var.image_tag}"
      resources { limits = { cpu = "1", memory = "512Mi" } }
      ports { container_port = 8080 }

      env {
        name  = "ANVIL_SERVICE_ID"
        value = "${id}"
      }
      env {
        name  = "ANVIL_ENV"
        value = var.anvil_env
      }
      env {
        name  = "ANVIL_ALLOWED_HOSTS"
        value = "${host}"
      }
      env {
        name  = "ANVIL_AUTH_PROFILE"
        value = var.anvil_env
      }
      env {
        name  = "ANVIL_OTEL_EXPORTER"
        value = "cloud_trace"
      }
      env {
        name  = "ANVIL_LEDGER"
        value = ${ledger ? '"firestore://\\${var.project_id}/(default)"' : '""'}
      }${
        secret
          ? `
      env {
        name = "ANVIL_${id.toUpperCase()}_TOKEN"
        value_source {
          secret_key_ref {
            secret  = google_secret_manager_secret.auth_token.secret_id
            version = "latest"
          }
        }
      }`
          : ""
      }
    }
  }
}

# Least privilege: only named callers may invoke this internal service.
resource "google_cloud_run_v2_service_iam_member" "invokers" {
  for_each = toset(var.invoker_members)
  name     = google_cloud_run_v2_service.tools.name
  location = var.region
  project  = var.project_id
  role     = "roles/run.invoker"
  member   = each.value
}
`;
}

function terraformVariables(air: AirDocument): string {
  const prod = air.service.environment === "prod";
  return `variable "project_id" { type = string }
variable "region" {
  type    = string
  default = "us-central1"
}
variable "ar_repo" {
  type    = string
  default = "anvil"
}
variable "image_tag" { type = string }
variable "anvil_env" {
  type    = string
  default = "prod"
}
variable "min_instances" {
  type    = number
  default = ${prod ? 1 : 0}
}
variable "max_instances" {
  type    = number
  default = 10
}
variable "invoker_members" {
  type    = list(string)
  default = []
}
`;
}

function secretsContract(air: AirDocument): unknown {
  const id = air.service.id;
  if (air.service.auth.type === "none") return { service: id, secrets: [] };
  return {
    service: id,
    secrets: [
      {
        name: `${id}-auth-token`,
        env: `ANVIL_${id.toUpperCase()}_TOKEN`,
        // Provisioned by Terraform; populate the version out of band.
        source: "google_secret_manager_secret.auth_token",
        scopes: air.service.auth.scopes,
      },
    ],
  };
}

function deployReadme(air: AirDocument): string {
  const id = air.service.id;
  return `# Deploying \`${id}-tools\` to Cloud Run

Anvil emits these artifacts; you (or CI) apply them. Cloud Run is the canonical
runtime target, generated from AIR — nothing here is hand-written.

**One owner per concern.** Terraform owns every deployed setting (service
account, Artifact Registry, ${air.service.auth.type !== "none" ? "Secret Manager, " : ""}${needsLedger(air) ? "the Firestore idempotency ledger, " : ""}the Cloud Run service, its
env vars, scaling, and IAM). Cloud Build only builds/pushes the image and runs
\`terraform apply\` with the built tag. There is no second place that sets an
image tag, env var, or IAM binding — so nothing can drift.

## Build & deploy (Cloud Build → Terraform)
\`\`\`bash
gcloud builds submit --config deploy/cloudbuild.yaml \\
  --substitutions _REGION=us-central1,_ANVIL_ENV=prod
\`\`\`
Cloud Build builds the prebuilt image, pushes it to Artifact Registry, then runs
\`terraform apply\` passing the image tag. First run provisions the service
account, Artifact Registry repo, ${air.service.auth.type !== "none" ? "Secret Manager secret, " : ""}${needsLedger(air) ? "Firestore ledger, " : ""}Cloud Run
service, and least-privilege IAM.

To apply Terraform directly (e.g. for a plan review):
\`\`\`bash
cd deploy/terraform
terraform init
terraform apply -var project_id=PROJECT -var image_tag=SHORT_SHA
\`\`\`

## Safety notes
- **Durable ledger is mandatory outside dev.** \`ANVIL_LEDGER\` points at Firestore
  (set by Terraform); the runtime refuses required-idempotency mutations if it is
  missing (fail closed). The deployed image must register a Firestore ledger
  backend at boot (\`registerLedgerBackend("firestore", …)\`) — the seam is in
  \`@anvil/runtime\`.
- **Internal ingress** keeps the surface pinned; the host allowlist
  (\`ANVIL_ALLOWED_HOSTS\`) pins upstream egress.
- **No keys are stored**: callers use their own service account + ID token; the
  runtime SA reads only its own secret.

See \`terraform/main.tf\` for the exact resources and \`env.schema.json\` for the
runtime env contract.
`;
}

function envSchema(host?: string): unknown {
  return {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    type: "object",
    required: ["ANVIL_SERVICE_ID", "ANVIL_ENV", "ANVIL_ALLOWED_HOSTS"],
    properties: {
      ANVIL_SERVICE_ID: { type: "string" },
      ANVIL_ARTIFACT_VERSION: { type: "string" },
      ANVIL_ENV: { type: "string", enum: ["dev", "staging", "prod"] },
      ANVIL_ALLOWED_HOSTS: {
        type: "string",
        description: "Comma-separated egress allowlist.",
        examples: [host ?? "api.internal.example.com"],
      },
      ANVIL_LEDGER: {
        type: "string",
        description:
          "Durable idempotency ledger backend URI (e.g. firestore://PROJECT/(default)). Required outside dev for required-idempotency mutations.",
      },
      ANVIL_AUTH_PROFILE: { type: "string" },
      ANVIL_POLICY_BUNDLE: { type: "string" },
      ANVIL_OTEL_EXPORTER: { type: "string", examples: ["cloud_trace"] },
    },
  };
}

function safeHost(url?: string): string | undefined {
  if (!url) return undefined;
  try {
    return new URL(url).hostname;
  } catch {
    return undefined;
  }
}
