import type { AirDocument } from "@anvil/air";
import { stringify as toYaml } from "yaml";

/**
 * Deployment artifacts (spec: "Deployment artifacts"). Each generated tool
 * surface becomes one small, stateless Cloud Run service. Build time produces
 * these; run time only serves.
 */
export function generateDeploy(air: AirDocument): Record<string, string> {
  const id = air.service.id;
  const host = safeHost(air.service.servers[0]?.url);
  return {
    "deploy/Dockerfile": dockerfile(),
    "deploy/cloudrun.service.yaml": cloudRunService(air),
    "deploy/env.schema.json": `${JSON.stringify(envSchema(host), null, 2)}\n`,
    "deploy/secrets.required.yaml": toYaml({
      service: id,
      secrets: [
        {
          name: `${id}-auth-token`,
          env: `ANVIL_${id.toUpperCase()}_TOKEN`,
          source: "projects/PROJECT/secrets/" + `${id}-auth-token/versions/latest`,
          scopes: air.service.auth.scopes,
        },
      ],
    }),
    "deploy/artifact-metadata.json": `${JSON.stringify(
      {
        service: id,
        version: air.service.version,
        anvilVersion: air.anvilVersion,
        operations: air.operations.length,
        approved: air.operations.filter((o) => o.state === "approved").length,
        sourceKind: air.service.source.kind,
      },
      null,
      2,
    )}\n`,
  };
}

function dockerfile(): string {
  return `# Generated by Anvil. Distroless, single-purpose runtime for one tool surface.
FROM node:22-slim AS build
WORKDIR /app
COPY package.json pnpm-lock.yaml* ./
RUN corepack enable && (pnpm install --frozen-lockfile || pnpm install)
COPY . .
RUN pnpm build && pnpm prune --prod

FROM gcr.io/distroless/nodejs22-debian12
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules
COPY package.json .
EXPOSE 8080
CMD ["dist/server.js"]
`;
}

function cloudRunService(air: AirDocument): string {
  const id = air.service.id;
  return toYaml({
    apiVersion: "serving.knative.dev/v1",
    kind: "Service",
    metadata: {
      name: `${id}-tools`,
      annotations: { "run.googleapis.com/ingress": "internal" },
    },
    spec: {
      template: {
        metadata: {
          annotations: {
            "autoscaling.knative.dev/minScale": air.service.environment === "prod" ? "1" : "0",
            "autoscaling.knative.dev/maxScale": "10",
            // Lower than a typical web API: do not stampede fragile upstreams.
            "run.googleapis.com/execution-environment": "gen2",
          },
        },
        spec: {
          containerConcurrency: 40,
          timeoutSeconds: 60,
          serviceAccountName: `${id}-tools@PROJECT.iam.gserviceaccount.com`,
          containers: [
            {
              image: `REGION-docker.pkg.dev/PROJECT/anvil/${id}-tools:${air.service.version}`,
              ports: [{ containerPort: 8080 }],
              resources: { limits: { cpu: "1", memory: "512Mi" } },
              env: [
                { name: "ANVIL_SERVICE_ID", value: id },
                { name: "ANVIL_ARTIFACT_VERSION", value: String(air.service.version) },
                { name: "ANVIL_ENV", value: air.service.environment ?? "prod" },
                { name: "ANVIL_ALLOWED_HOSTS", value: safeHost(air.service.servers[0]?.url) ?? "" },
                { name: "ANVIL_AUTH_PROFILE", value: air.service.environment ?? "prod" },
              ],
              startupProbe: { httpGet: { path: "/readyz" } },
              livenessProbe: { httpGet: { path: "/healthz" } },
            },
          ],
        },
      },
    },
  });
}

function envSchema(host?: string): unknown {
  return {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    type: "object",
    required: ["ANVIL_SERVICE_ID", "ANVIL_ENV", "ANVIL_ALLOWED_HOSTS"],
    properties: {
      ANVIL_SERVICE_ID: { type: "string" },
      ANVIL_ARTIFACT_VERSION: { type: "string" },
      ANVIL_ENV: { type: "string", enum: ["dev", "staging", "prod"] },
      ANVIL_ALLOWED_HOSTS: {
        type: "string",
        description: "Comma-separated egress allowlist.",
        examples: [host ?? "api.internal.example.com"],
      },
      ANVIL_AUTH_PROFILE: { type: "string" },
      ANVIL_POLICY_BUNDLE: { type: "string" },
      ANVIL_OTEL_EXPORTER: { type: "string" },
    },
  };
}

function safeHost(url?: string): string | undefined {
  if (!url) return undefined;
  try {
    return new URL(url).hostname;
  } catch {
    return undefined;
  }
}
