import { createHash } from "node:crypto";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { type AirDocument, type AuthRequirement, airToJson } from "@anvil/air";
import {
  credentialProfileName,
  DEFAULT_LEDGER_RESULT_TTL_SECONDS,
  envPrefix,
  firestoreLedgerCollection,
} from "@anvil/runtime";
import { buildSync } from "esbuild";
import { stringify as toYaml } from "yaml";
import { compiledOperations } from "./catalog.js";
import { generateRuntimeServer } from "./entrypoints.js";
import { buildToolResources, type ResourceOptions } from "./resources.js";

/**
 * Deployment artifacts for Cloud Run. Anvil emits these at build time; it holds
 * no cloud credentials and never applies them — a human/CI does.
 *
 * **One owner per concern** (this is the whole point of the file). Earlier Anvil
 * emitted five overlapping mechanisms — a knative `service.yaml`, an
 * `iam.plan.json`, per-env `overlays/`, a `gcloud run deploy` step, *and*
 * Terraform — that set the same image tag / env vars / IAM three different ways
 * and drifted. Now:
 *
 *   - **Terraform** owns all infrastructure *and* runtime configuration: the
 *     service account, Artifact Registry, Secret Manager + its IAM, the Firestore
 *     idempotency ledger + its IAM, the Cloud Run service (image, env vars,
 *     scaling, resources, ingress), and invoker IAM. It is the single source of
 *     truth for every deployable setting.
 *   - **Cloud Build** owns the pipeline: build the prebuilt image, push it, and
 *     produce a reviewable Terraform plan with the built image tag. It sets *no*
 *     runtime config and never applies the plan.
 *   - **Dockerfile** owns the container (prebuilt runtime, never rebuilds Anvil).
 *
 * No file contains literal `PROJECT`/`REGION` placeholders; everything flows
 * through Terraform variables, so the bundle is applyable as emitted.
 */
export function generateDeploy(
  air: AirDocument,
  resourceOptions: ResourceOptions = {},
): Record<string, string> {
  const runtime = deployRuntime(air, resourceOptions);
  return {
    "deploy/Dockerfile": dockerfile(),
    // Cloud Build uses the bundle root as context with `-f deploy/Dockerfile`.
    // Docker therefore discovers this Dockerfile-specific ignore file; a
    // `deploy/.dockerignore` would be ignored and upload the whole bundle.
    "deploy/Dockerfile.dockerignore": dockerignore(),
    ...runtime,
    "deploy/cloudbuild.yaml": cloudBuild(air),
    "deploy/terraform/main.tf": terraformMain(air),
    "deploy/terraform/variables.tf": terraformVariables(air),
    "deploy/env.schema.json": `${JSON.stringify(envSchema(safeHost(air.service.servers[0]?.url)), null, 2)}\n`,
    "deploy/secrets.required.yaml": toYaml(secretsContract(air)),
    "deploy/credentials.required.yaml": toYaml(credentialContract(air)),
    "deploy/README.md": deployReadme(air),
  };
}

/** True when the surface has a required-idempotency mutation → needs Firestore. */
function needsLedger(air: AirDocument): boolean {
  return air.operations.some(
    (o) =>
      o.state === "approved" && o.effect.kind === "mutation" && o.idempotency.mode === "required",
  );
}

/**
 * A *prebuilt* runtime image: the bundle is already compiled JS (generated by
 * Anvil), so the container installs production deps and copies the runtime — it
 * never rebuilds Anvil packages inside the image. Distroless, non-root.
 */
function dockerfile(): string {
  return `# Generated by Anvil — hermetic, prebundled Cloud Run runtime.
# deploy/runtime/server.js already contains its exact Anvil + MCP dependencies.
# The image performs no registry access or dependency resolution.
FROM gcr.io/distroless/nodejs22-debian12
WORKDIR /app
ENV NODE_ENV=production
COPY deploy/runtime ./runtime
EXPOSE 8080
USER nonroot
CMD ["runtime/server.js"]
`;
}

function dockerignore(): string {
  // `deploy/runtime` is the only application payload copied by the hermetic
  // Dockerfile, so never exclude the deploy tree from the build context.
  return ["cli", "mcp", "mock", "skill", "docs", "tests", "*.test.*", "src"].join("\n");
}

function deployRuntime(air: AirDocument, resourceOptions: ResourceOptions): Record<string, string> {
  const source = generateRuntimeServer(air);
  const result = buildSync({
    stdin: {
      contents: source,
      sourcefile: "runtime/server.js",
      resolveDir: dirname(fileURLToPath(import.meta.url)),
      loader: "js",
    },
    bundle: true,
    platform: "node",
    format: "esm",
    target: "node22",
    treeShaking: true,
    minify: true,
    legalComments: "none",
    // A few transitive CommonJS modules use dynamic require for Node built-ins.
    // ESM has no ambient require, so provide a local createRequire seam while
    // keeping every third-party package bundled into this single file.
    banner: {
      js: 'import{createRequire as __anvilCreateRequire}from"node:module";const require=__anvilCreateRequire(import.meta.url);',
    },
    sourcemap: false,
    write: false,
    logLevel: "silent",
  });
  const server = result.outputFiles[0]?.text;
  if (!server) throw new Error("Failed to bundle the deploy runtime.");
  return {
    "deploy/runtime/package.json": `${JSON.stringify(
      { name: `${air.service.id}-anvil-runtime`, private: true, type: "module" },
      null,
      2,
    )}\n`,
    "deploy/runtime/server.js": server,
    "deploy/runtime/air.json": airToJson(air),
    "deploy/runtime/resources.json": `${JSON.stringify(
      buildToolResources(air, resourceOptions),
      null,
      2,
    )}\n`,
    "deploy/runtime/operations.manifest.json": `${JSON.stringify(compiledOperations(air), null, 2)}\n`,
  };
}

/**
 * Cloud Build owns the pipeline only: build → push → `terraform apply`. It sets
 * no runtime config; it passes Terraform the immutable build id (`$BUILD_ID`) and
 * project/region. Terraform is the single owner of the deployed service, so the
 * image tag has exactly one source of truth.
 */
function cloudBuild(air: AirDocument): string {
  const id = air.service.id;
  const cloudId = googleResourcePrefix(id);
  // The ${...} tokens are Cloud Build substitution variables (expanded by
  // Cloud Build at runtime), NOT JS interpolation — so they stay in a plain
  // string; only `id` is a real JS value, concatenated in.
  const image = `\${_REGION}-docker.pkg.dev/\${PROJECT_ID}/\${_AR_REPO}/${cloudId}-tools:$BUILD_ID`;
  return toYaml({
    steps: [
      {
        id: "build",
        name: "gcr.io/cloud-builders/docker",
        args: ["build", "-f", "deploy/Dockerfile", "-t", image, "."],
      },
      // Push targets the Artifact Registry repo, which is a **platform prereq**
      // (created out of band), so there is no bootstrap cycle where push would
      // need a repo a later Terraform step has not created yet.
      { id: "push", name: "gcr.io/cloud-builders/docker", args: ["push", image] },
      {
        id: "terraform-workdir",
        name: "ubuntu",
        entrypoint: "bash",
        args: [
          "-ceu",
          "test ! -e /workspace/tf-work; mkdir /workspace/tf-work; cp deploy/terraform/*.tf /workspace/tf-work/",
        ],
      },
      {
        id: "operator-inputs",
        name: "gcr.io/cloud-builders/gcloud",
        args: ["storage", "cp", "${_TFVARS_URI}", "/workspace/tf-work/operator.auto.tfvars.json"],
      },
      {
        id: "plan",
        name: "hashicorp/terraform",
        entrypoint: "sh",
        args: [
          "-c",
          [
            // Durable remote state (GCS) is mandatory: an ephemeral build container
            // has no local state, so init MUST bind the shared backend or every
            // build would try to recreate existing resources.
            'terraform -chdir=/workspace/tf-work init -input=false -backend-config="bucket=${_TF_STATE_BUCKET}"' +
              ' -backend-config="prefix=${_TF_STATE_PREFIX}"',
            // Cloud Build produces a **plan**, never an auto-approved apply — a
            // capability deploy can change IAM, ingress, and secrets, which must
            // pass a review/approval gate. Apply is a separate, promoted step.
            "terraform -chdir=/workspace/tf-work plan -input=false -out=tfplan" +
              ' -var project_id="$PROJECT_ID"' +
              ' -var region="${_REGION}"' +
              ' -var ar_repo="${_AR_REPO}"' +
              ' -var image_tag="$BUILD_ID"' +
              ' -var anvil_env="${_ANVIL_ENV}"',
            // Human-readable plan artifact for the review pack.
            "terraform -chdir=/workspace/tf-work show -no-color tfplan > /workspace/tf-work/tfplan.txt",
          ].join(" && "),
        ],
      },
    ],
    images: [image],
    // Publish the plan so a promotion step (or a human) can review, then
    // `terraform apply tfplan` behind an approval — see deploy/README.md.
    artifacts: {
      objects: {
        location: "gs://${_TF_STATE_BUCKET}/plans/${BUILD_ID}",
        paths: ["tf-work/tfplan", "tf-work/tfplan.txt", "tf-work/.terraform.lock.hcl"],
      },
    },
    substitutions: {
      _REGION: "us-central1",
      _AR_REPO: "anvil",
      _ANVIL_ENV: "prod",
      // Names/references and connector settings only; no secret values. Build
      // fails until the operator supplies this reviewed external input.
      _TFVARS_URI: "gs://REPLACE_WITH_INPUT_BUCKET/anvil/operator.auto.tfvars.json",
      // Durable Terraform state — a GCS bucket that must already exist (prereq).
      _TF_STATE_BUCKET: "REPLACE_WITH_TF_STATE_BUCKET",
      _TF_STATE_PREFIX: `anvil/${id}-tools`,
    },
    options: { logging: "CLOUD_LOGGING_ONLY" },
  });
}

/**
 * Terraform is the single owner of every *per-capability* deployed setting — SA,
 * Secret + IAM, its isolated ledger database, the Cloud Run service (image, env
 * vars, scaling, resources, ingress), and invoker IAM. Shared project-level
 * foundations (Artifact Registry repo and Terraform state bucket) are
 * prerequisites, not owned here.
 */
function terraformMain(air: AirDocument): string {
  const id = air.service.id;
  const cloudId = googleResourcePrefix(id);
  const ledgerDatabase = `${cloudId}-ledger`;
  const ledgerCollection = firestoreLedgerCollection(id);
  const ledger = needsLedger(air);
  const host = safeHost(air.service.servers[0]?.url) ?? "";
  return `# Generated by Anvil — Cloud Run runtime for "${id}" (one tool surface).
# Anvil emits this plan; it does not apply it (no cloud credentials held). This
# file is the single owner of every *per-capability* setting for this service.
#
# Platform prerequisites (shared, project-level; NOT owned here — Anvil must not
# pretend each capability owns the customer's foundation):
#   - the Artifact Registry repo "\${var.ar_repo}" (images are pushed to it)
#   - the GCS bucket backing Terraform state (bound at 'terraform init' below)
# Bootstrap these once per project before applying this module.

terraform {
  # Durable remote state — required. 'terraform init' binds bucket/prefix via
  # -backend-config so an ephemeral CI container never starts from empty state.
  backend "gcs" {}
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = ">= 5.0"
    }
  }
}

provider "google" {
  project = var.project_id
  region  = var.region
}

resource "google_service_account" "runtime" {
  account_id   = "${cloudId}-tools"
  display_name = "Anvil runtime for ${id}"
  project      = var.project_id
}

# Least privilege: logging / trace / metrics only, scoped to this SA.
resource "google_project_iam_member" "logging" {
  project = var.project_id
  role    = "roles/logging.logWriter"
  member  = "serviceAccount:\${google_service_account.runtime.email}"
}

resource "google_project_iam_member" "trace" {
  project = var.project_id
  role    = "roles/cloudtrace.agent"
  member  = "serviceAccount:\${google_service_account.runtime.email}"
}

resource "google_project_iam_member" "metrics" {
  project = var.project_id
  role    = "roles/monitoring.metricWriter"
  member  = "serviceAccount:\${google_service_account.runtime.email}"
}
${
  ledger
    ? `
# Durable idempotency state is isolated in a named database owned by this
# capability. Delete protection and prevent_destroy keep replay evidence from
# disappearing with an accidental infrastructure teardown.
resource "google_firestore_database" "ledger" {
  project                 = var.project_id
  name                    = "${ledgerDatabase}"
  location_id             = var.region
  type                    = "FIRESTORE_NATIVE"
  delete_protection_state = "DELETE_PROTECTION_ENABLED"
  deletion_policy         = "DELETE"

  lifecycle {
    prevent_destroy = true
  }
}

# Firestore deletes completed replay results after their expires_at timestamp.
# In-progress reservations deliberately omit that field and are never
# auto-reclaimed, because expiry cannot prove an upstream mutation stopped.
resource "google_firestore_field" "ledger_result_expiry" {
  project    = var.project_id
  database   = google_firestore_database.ledger.name
  collection = "${ledgerCollection}"
  field      = "expires_at"

  ttl_config {}
}

# roles/datastore.user is a project IAM binding, but its condition limits this
# runtime SA to the exact named database above. Without the condition, one Anvil
# service could read another service's cached mutation results.
resource "google_project_iam_member" "runtime_ledger" {
  project = var.project_id
  role    = "roles/datastore.user"
  member  = "serviceAccount:\${google_service_account.runtime.email}"
  condition {
    title       = "anvil-${cloudId}-ledger-only"
    description = "Restrict the Anvil runtime to its isolated idempotency database."
    expression  = "resource.name == 'projects/\${var.project_id}/databases/\${google_firestore_database.ledger.name}'"
  }
}
`
    : ""
}
resource "google_cloud_run_v2_service" "tools" {
  name     = "${cloudId}-tools"
  location = var.region
  project  = var.project_id
  # Defaults to internal-only. A connector target (e.g. Gemini Enterprise) that
  # is reached over the public internet sets var.ingress = "INGRESS_TRAFFIC_ALL"
  # and relies on the server's own inbound OAuth check (see var.env below), never
  # on network reachability alone.
  ingress = var.ingress

  template {
    service_account = google_service_account.runtime.email
    scaling {
      min_instance_count = var.min_instances
      max_instance_count = var.max_instances
    }
    containers {
      image = "\${var.region}-docker.pkg.dev/\${var.project_id}/\${var.ar_repo}/${cloudId}-tools:\${var.image_tag}"
      resources { limits = { cpu = "1", memory = "512Mi" } }
      ports { container_port = 8080 }

      env {
        name  = "ANVIL_SERVICE_ID"
        value = "${id}"
      }
      env {
        name  = "ANVIL_ENV"
        value = var.anvil_env
      }
      env {
        name  = "ANVIL_ALLOWED_HOSTS"
        value = "${host}"
      }
      env {
        name  = "ANVIL_AUTH_PROFILE"
        value = var.anvil_env
      }
      env {
        name  = "ANVIL_OTEL_EXPORTER"
        value = "cloud_trace"
      }
      env {
        name  = "ANVIL_LEDGER"
        value = ${ledger ? `"firestore://\${var.project_id}/\${google_firestore_database.ledger.name}/${id}"` : '""'}
      }
      env {
        name  = "ANVIL_LEDGER_RESULT_TTL_SECONDS"
        value = tostring(var.ledger_result_ttl_seconds)
      }
      # Outbound (upstream) credential resolution. ANVIL_CREDENTIALS chooses
      # storage only for static values; grants still route per operation.
      # ANVIL_SECRET_PROJECT resolves shorthand sm://<secret> references.
      env {
        name  = "ANVIL_CREDENTIALS"
        value = var.credentials
      }
      env {
        name  = "ANVIL_SECRET_PROJECT"
        value = coalesce(var.secret_project, var.project_id)
      }
      # Additional plain env — a connector target injects its inbound-auth
      # contract (ANVIL_INBOUND_*) here so the server self-enforces the platform's
      # token. Empty by default.
      dynamic "env" {
        for_each = var.env
        content {
          name  = env.key
          value = env.value
        }
      }
      # Upstream credential *references* as PLAIN env: the VALUE is a Secret
      # Manager resource name (sm://…), which the runtime dereferences at call
      # time and TTL-caches — so 'latest' rotates without a new revision. Grant
      # this SA access via var.credential_secret_ids below. See
      # deploy/credentials.required.yaml for exactly which keys this surface reads.
      dynamic "env" {
        for_each = var.credential_secret_refs
        content {
          name  = env.key
          value = env.value
        }
      }
    }
  }
}

# Least privilege: only named callers may invoke this internal service.
resource "google_cloud_run_v2_service_iam_member" "invokers" {
  for_each = toset(var.invoker_members)
  name     = google_cloud_run_v2_service.tools.name
  location = var.region
  project  = var.project_id
  role     = "roles/run.invoker"
  member   = each.value
}

# Scoped read access to each upstream credential secret referenced by
# var.credential_secret_refs (client secrets, assertion keys, bearer tokens).
# One binding per secret — never a project-wide secret role. Pass the secret IDs
# (projects/P/secrets/S) so the binding is explicit and least-privilege.
resource "google_secret_manager_secret_iam_member" "runtime_reads_credential" {
  for_each  = toset(var.credential_secret_ids)
  secret_id = each.value
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:\${google_service_account.runtime.email}"
}

# A connector reached by an external platform (Gemini Enterprise calls the /mcp
# URL over the internet) sets allow_unauthenticated = true. Cloud Run then admits
# the request at the network edge, and the SERVER enforces the OAuth token — the
# resource-server check is the real gate, not IAM. Defaults to false.
resource "google_cloud_run_v2_service_iam_member" "public" {
  count    = var.allow_unauthenticated ? 1 : 0
  name     = google_cloud_run_v2_service.tools.name
  location = var.region
  project  = var.project_id
  role     = "roles/run.invoker"
  member   = "allUsers"
}
`;
}

function terraformVariables(air: AirDocument): string {
  const prod = air.service.environment === "prod";
  return `variable "project_id" { type = string }
variable "region" {
  type    = string
  default = "us-central1"
}
variable "ar_repo" {
  type    = string
  default = "anvil"
}
variable "image_tag" { type = string }
variable "anvil_env" {
  type    = string
  default = "prod"
}
variable "min_instances" {
  type    = number
  default = ${prod ? 1 : 0}
}
variable "max_instances" {
  type    = number
  default = 10
}
variable "ledger_result_ttl_seconds" {
  type        = number
  default     = ${DEFAULT_LEDGER_RESULT_TTL_SECONDS}
  description = "Completed idempotency result retention. In-progress reservations never expire automatically."
  validation {
    condition     = var.ledger_result_ttl_seconds >= 60 && var.ledger_result_ttl_seconds <= 31536000 && floor(var.ledger_result_ttl_seconds) == var.ledger_result_ttl_seconds
    error_message = "ledger_result_ttl_seconds must be an integer from 60 to 31536000."
  }
}
variable "invoker_members" {
  type    = list(string)
  default = []
}
# Ingress posture. Internal-only by default; a public connector target overrides
# this to "INGRESS_TRAFFIC_ALL" (its own inbound OAuth check is the real gate).
variable "ingress" {
  type    = string
  default = "INGRESS_TRAFFIC_INTERNAL_ONLY"
}
# When true, bind allUsers as run.invoker (public reach). Only safe when the
# server self-enforces auth — a connector target sets this alongside var.env.
variable "allow_unauthenticated" {
  type    = bool
  default = false
}
# Extra plain env for the runtime container — a connector target injects its
# ANVIL_INBOUND_* inbound-auth contract here. Secrets never go here.
variable "env" {
  type    = map(string)
  default = {}
  validation {
    condition     = alltrue([for value in values(var.env) : !can(regex("^REPLACE_ME", value))])
    error_message = "Replace every REPLACE_ME env scaffold value before planning."
  }
}
# Generated by anvil deploy credentials --tfvars to make incomplete non-secret
# OAuth configuration fail at plan time. Resolve each entry into var.env, then
# remove it; a non-empty map is deliberately invalid.
variable "anvil_unresolved_config" {
  type    = map(string)
  default = {}
  validation {
    condition     = length(var.anvil_unresolved_config) == 0
    error_message = "Resolve every anvil_unresolved_config entry into var.env before planning."
  }
}
# Static credential storage override (env | secret_manager). OAuth grants and
# delegated identity always route per operation and cannot be overridden here.
variable "credentials" {
  type    = string
  default = ""
  validation {
    condition     = contains(["", "env", "secret_manager"], var.credentials)
    error_message = "credentials must be empty, env, or secret_manager."
  }
}
# Default GCP project for shorthand sm://<secret> credential references. Empty ⇒
# falls back to project_id.
variable "secret_project" {
  type    = string
  default = ""
}
# Upstream credential references as PLAIN env: ENV_NAME → Secret Manager resource
# name (sm://projects/P/secrets/S/versions/latest). The runtime dereferences and
# TTL-caches them, so 'latest' rotates without a redeploy. Names, never values.
variable "credential_secret_refs" {
  type    = map(string)
  default = {}
}
# Secret IDs (projects/P/secrets/S) this SA may read — one scoped secretAccessor
# binding each. Provide the secrets backing credential_secret_refs here.
variable "credential_secret_ids" {
  type    = list(string)
  default = []
}
`;
}

function secretsContract(air: AirDocument): unknown {
  return {
    service: air.service.id,
    secrets: [],
    note: "The legacy one-token contract is intentionally empty. Upstream auth is per operation; use credentials.required.yaml with credential_secret_refs and credential_secret_ids.",
  };
}

/* -------------------------------------------------------------------------- */
/* Upstream (outbound) credential contract                                     */
/* -------------------------------------------------------------------------- */

/** How the runtime will resolve a given auth requirement — one row per shape. */
export interface CredentialRequirement {
  /** The operations this shape covers (canonical names), for the operator. */
  operations: string[];
  /** Concrete runtime profile after applying the source security-scheme suffix. */
  profile: string;
  /** The AuthRequirement discriminator, human-readable. */
  auth: string;
  /** Which resolver runs it: `env` (static), `delegated` (token exchange), `workload_identity`. */
  resolver: "env" | "delegated" | "workload_identity" | "unsupported";
  /** Env vars the resolver MUST find (names only — never values). */
  required: string[];
  /** Alternative complete config groups; at least one group must be supplied. */
  requiredOneOf?: string[][];
  /** Env vars it will use if present (carrier overrides, scopes, actor token). */
  optional: string[];
  /** Any human note (e.g. OBO needs a validated inbound caller token). */
  note?: string;
}

/**
 * The outbound credential contract: for every distinct auth shape across the
 * surface, the exact env vars the runtime resolver reads to reach the upstream.
 * This is the deploy-time companion to the runtime resolvers in
 * `@anvil/runtime/credentials.ts` — names only, so an operator (or `anvil deploy
 * credentials`) knows precisely what to provision, and never has to guess.
 *
 * `profile` is the auth-profile name (uppercased into the `ANVIL_<PROFILE>_*`
 * prefix). At deploy Terraform sets `ANVIL_AUTH_PROFILE` to the environment
 * (e.g. `prod`), so keys read `ANVIL_PROD_*`. Any value may be a Secret Manager
 * reference (`sm://…`), dereferenced at call time so `latest` rotates without a
 * redeploy — see the header note.
 */
export function credentialContract(
  air: AirDocument,
  profile: string = air.service.environment ?? "prod",
): {
  service: string;
  profileEnvVar: string;
  profileDefault: string;
  secretReferences: string;
  coarseOverride: string;
  requirements: CredentialRequirement[];
} {
  // Union every operation's auth (fall back to the service default), keyed by
  // classification so we emit one row per shape, not one per operation.
  const byShape = new Map<string, CredentialRequirement>();
  for (const o of air.operations.filter((operation) => operation.state === "approved")) {
    const auth: AuthRequirement = o.auth ?? air.service.auth;
    if (auth.type === "none") continue;
    const concreteProfile = credentialProfileName(profile, auth);
    const req = credentialRow(auth, concreteProfile);
    const shapeKey = `${concreteProfile}\0${req.auth}`;
    const existing = byShape.get(shapeKey);
    if (existing) existing.operations.push(o.canonicalName);
    else {
      byShape.set(shapeKey, {
        ...req,
        profile: concreteProfile,
        operations: [o.canonicalName],
      });
    }
  }
  return {
    service: air.service.id,
    profileEnvVar: "ANVIL_AUTH_PROFILE",
    profileDefault: profile,
    secretReferences:
      "Any value below may be a Secret Manager reference — `sm://projects/P/secrets/S/versions/V`, " +
      "a bare `projects/*/secrets/*/versions/*`, or shorthand `sm://<secret>` (needs ANVIL_SECRET_PROJECT). " +
      "The runtime dereferences it at call time and TTL-caches it, so `latest` rotates without a redeploy.",
    coarseOverride:
      "ANVIL_CREDENTIALS selects storage for static api-key/basic/bearer values only (env | secret_manager). " +
      "OAuth grants and delegated identity always route per operation. Unset defaults static values to Secret Manager references; an unsupported value fails closed.",
    requirements: [...byShape.values()],
  };
}

/** Classify one auth requirement into the env-var contract the runtime will read. */
function credentialRow(
  auth: AuthRequirement,
  profile: string,
): Omit<CredentialRequirement, "operations" | "profile"> {
  const p = envPrefix(profile);
  const isObo = auth.type === "oauth2_on_behalf_of";
  const isJwtBearer = auth.type === "jwt_bearer" && auth.provider?.grant === "jwt_bearer";
  const importedEndpoint = Boolean(auth.provider?.tokenEndpoint);
  const endpointRequired = importedEndpoint ? [] : [`${p}_TOKEN_ENDPOINT`];
  const endpointAlternatives = importedEndpoint
    ? [[`ANVIL_CREDENTIAL_HOSTS`], [`${p}_TOKEN_ENDPOINT`]]
    : undefined;
  const endpointOptional = importedEndpoint
    ? [`ANVIL_CREDENTIAL_HOSTS`, `${p}_TOKEN_ENDPOINT`]
    : [];

  if (auth.type === "workload_identity") {
    return {
      auth: "workload_identity",
      resolver: "workload_identity",
      required: [],
      optional: [`${p}_AUDIENCE`],
      note: "Mints a GCP ID token (for the audience) or access token from the metadata server — no client secret. The runtime service account IS the identity.",
    };
  }
  if (isObo) {
    const method = auth.provider?.clientAuth ?? "client_secret_basic";
    const clientCredential =
      method === "private_key_jwt" ? `${p}_CLIENT_ASSERTION_KEY` : `${p}_CLIENT_SECRET`;
    const actorRequired = auth.delegation?.actor ? [`${p}_ACTOR_TOKEN`] : [];
    return {
      auth:
        `${auth.type} (on-behalf-of, principal=${auth.principal ?? "delegated"}, ` +
        `client_auth=${method}, token_endpoint=${auth.provider?.tokenEndpoint ?? `${p}_TOKEN_ENDPOINT`})`,
      resolver: "delegated",
      required: [...endpointRequired, `${p}_CLIENT_ID`, clientCredential, ...actorRequired],
      ...(endpointAlternatives ? { requiredOneOf: endpointAlternatives } : {}),
      optional: [...endpointOptional, `${p}_AUDIENCE`, `${p}_RESOURCE`, `${p}_SCOPES`],
      note:
        "RFC 8693 token exchange. Needs a validated inbound caller token (the subject_token). " +
        "For an imported token endpoint, either admit its exact host with ANVIL_CREDENTIAL_HOSTS " +
        `or override it with ${p}_TOKEN_ENDPOINT. When delegation.actor is declared, ` +
        "ANVIL_<P>_ACTOR_TOKEN is required; a missing actor token fails closed.",
    };
  }
  if (isJwtBearer) {
    return {
      auth: `jwt_bearer (RFC 7523 assertion, token_endpoint=${auth.provider?.tokenEndpoint ?? `${p}_TOKEN_ENDPOINT`})`,
      resolver: "delegated",
      required: [...endpointRequired, `${p}_CLIENT_ID`, `${p}_CLIENT_ASSERTION_KEY`],
      ...(endpointAlternatives ? { requiredOneOf: endpointAlternatives } : {}),
      optional: [...endpointOptional, `${p}_AUDIENCE`, `${p}_SCOPES`],
      note:
        "The runtime signs a JWT assertion with ANVIL_<P>_CLIENT_ASSERTION_KEY (a PEM private key — provision it as an sm:// reference). " +
        "For an imported token endpoint, admit its exact host with ANVIL_CREDENTIAL_HOSTS or override *_TOKEN_ENDPOINT.",
    };
  }
  if (auth.type === "oauth2_client_credentials") {
    const method = auth.provider?.clientAuth ?? "client_secret_basic";
    const required = [...endpointRequired, `${p}_CLIENT_ID`];
    required.push(
      method === "private_key_jwt" ? `${p}_CLIENT_ASSERTION_KEY` : `${p}_CLIENT_SECRET`,
    );
    return {
      auth: `oauth2_client_credentials (${method}, token_endpoint=${auth.provider?.tokenEndpoint ?? `${p}_TOKEN_ENDPOINT`})`,
      resolver: "delegated",
      required,
      ...(endpointAlternatives ? { requiredOneOf: endpointAlternatives } : {}),
      optional: [...endpointOptional, `${p}_AUDIENCE`, `${p}_SCOPES`],
      note: "RFC 6749 §4.4 — a service principal, no user identity. For an imported token endpoint, admit its exact host with ANVIL_CREDENTIAL_HOSTS or override *_TOKEN_ENDPOINT.",
    };
  }
  if (auth.type === "api_key") {
    return {
      auth: "api_key",
      resolver: "env",
      required: [`${p}_API_KEY`],
      optional: [`${p}_API_KEY_HEADER`, `${p}_API_KEY_QUERY`],
      note: "Carrier defaults to the `X-API-Key` header; override per gateway (Apigee/Kong often `apikey` as a query param, Azure `Ocp-Apim-Subscription-Key`) via AIR `provider.apiKey` or the *_API_KEY_HEADER / *_API_KEY_QUERY env override.",
    };
  }
  if (auth.type === "basic") {
    return {
      auth: "basic",
      resolver: "env",
      required: [`${p}_USERNAME`, `${p}_PASSWORD`],
      optional: [],
    };
  }
  if (
    auth.type === "mtls" ||
    auth.type === "custom_header" ||
    auth.type === "oauth2_authorization_code"
  ) {
    return {
      auth: `${auth.type} (unsupported)`,
      resolver: "unsupported",
      required: [],
      optional: [],
      note: "Anvil does not currently model the transport certificate or custom header carrier. Runtime and certification fail closed; enrich the auth model before approval.",
    };
  }
  return {
    auth: `${auth.type} (static bearer)`,
    resolver: "env",
    required: [`${p}_TOKEN`],
    optional: [],
    note: "A pre-issued bearer token read from the env (provision it as an sm:// reference).",
  };
}

function deployReadme(air: AirDocument): string {
  const id = air.service.id;
  const cloudId = googleResourcePrefix(id);
  return `# Deploying \`${cloudId}-tools\` to Cloud Run

Anvil emits these artifacts; you (or CI) apply them. Cloud Run is the canonical
runtime target, generated from AIR service \`${id}\` — nothing here is hand-written.

**One owner per concern.** Terraform owns every *per-capability* deployed setting
(service account, ${needsLedger(air) ? "the ledger IAM binding, " : ""}the Cloud Run service, its env
vars, scaling, and IAM). Cloud Build only builds/pushes the image and produces a
Terraform **plan** — it sets no image tag, env var, or IAM binding of its own, so
nothing can drift.

## Platform prerequisites (once per project)
These are **shared, project-level** foundations. Anvil does not own them — a
capability module must not fight another over a singleton:
- an **Artifact Registry** Docker repo named \`${"$"}{ar_repo}\` (images are pushed here);
- a **GCS bucket** for Terraform remote state;${
    needsLedger(air)
      ? `
- capacity for one named Firestore database (\`${cloudId}-ledger\`); Terraform
  creates and delete-protects it for this capability instead of sharing the
  project's \`(default)\` database;`
      : ""
  }
- required APIs enabled (run, artifactregistry, firestore, secretmanager, iam).

## Build & plan (Cloud Build)
\`operator.auto.tfvars.json\` is an external, reviewed input containing resource
names/references and connector settings—never secret values. Generate the
credential portion with:
\`\`\`bash
anvil deploy credentials . --env prod --project YOUR_PROJECT --tfvars \\
  > /SAFE_EXTERNAL_DIR/operator.auto.tfvars.json
# Edit the file: replace every REPLACE_ME value, satisfy each listed choice,
# then set anvil_unresolved_config to {}. Terraform refuses an incomplete file.
gcloud storage cp /SAFE_EXTERNAL_DIR/operator.auto.tfvars.json \\
  gs://YOUR_INPUT_BUCKET/anvil/operator.auto.tfvars.json
\`\`\`
If a target kit contributes settings, merge its documented tfvars into that
external input before upload. The reviewed plan is the point where all inputs
become immutable.

\`\`\`bash
gcloud builds submit --config deploy/cloudbuild.yaml \\
  --substitutions _REGION=us-central1,_ANVIL_ENV=prod,_TF_STATE_BUCKET=YOUR_STATE_BUCKET,_TFVARS_URI=gs://YOUR_INPUT_BUCKET/anvil/operator.auto.tfvars.json
\`\`\`
Cloud Build builds the prebuilt image, pushes it, then runs \`terraform init\`
(binding the GCS backend) and \`terraform plan -out=tfplan\` in an external work
directory. The plan, rendered plan, and provider lock are uploaded below
\`gs://<state-bucket>/plans/<build-id>/tf-work/\`. **It does not apply** — a
capability deploy can change IAM, ingress, and scoped secret access.

## Apply (promoted, after review)
\`\`\`bash
TF_WORK=/SAFE_EXTERNAL_DIR/apply-${id}
test ! -e "$TF_WORK"
mkdir -p "$TF_WORK"
cp deploy/terraform/*.tf "$TF_WORK/"
gcloud storage cp "gs://YOUR_STATE_BUCKET/plans/BUILD_ID/tf-work/tfplan" "$TF_WORK/tfplan"
gcloud storage cp "gs://YOUR_STATE_BUCKET/plans/BUILD_ID/tf-work/tfplan.txt" "$TF_WORK/tfplan.txt"
gcloud storage cp "gs://YOUR_STATE_BUCKET/plans/BUILD_ID/tf-work/.terraform.lock.hcl" "$TF_WORK/.terraform.lock.hcl"
terraform -chdir="$TF_WORK" init \\
  -backend-config="bucket=YOUR_STATE_BUCKET" \\
  -backend-config="prefix=anvil/${id}-tools"
terraform -chdir="$TF_WORK" show -no-color tfplan  # compare to reviewed tfplan.txt
terraform -chdir="$TF_WORK" apply tfplan           # exact reviewed plan; no -var here
\`\`\`

## Upstream credentials (outbound)
How the runtime reaches the API it fronts. \`deploy/credentials.required.yaml\`
lists the exact env vars per auth shape (names only) — provision each secret in
Secret Manager, then either:

- **Reference (recommended, rotates live):** pass the secret's *resource name* as
  a PLAIN env var via \`var.credential_secret_refs\` (\`ANVIL_<PROFILE>_CLIENT_SECRET\`
  = \`sm://projects/…/secrets/…/versions/latest\`) and grant read with
  \`var.credential_secret_ids\`. The runtime dereferences it at call time and
  TTL-caches it, so \`latest\` rotates without a new revision.

Resolution is per-operation by the auth shape: static \`api_key\`/\`basic\`/bearer read
directly; \`oauth2_client_credentials\` (RFC 6749 §4.4), on-behalf-of (RFC 8693 token
exchange, using the validated inbound caller token as the subject), \`jwt_bearer\`
(RFC 7523), and \`workload_identity\` (GCP metadata) mint a token from
\`ANVIL_<PROFILE>_TOKEN_ENDPOINT\`. \`ANVIL_CREDENTIALS\` selects only where static
api-key/basic/bearer values are read; it never changes OAuth grant routing. Run
\`anvil deploy credentials <dir> --env <env> --project <PROJECT_ID>\` for the
provisioning plan, or add \`--tfvars\` for external Terraform input JSON.
Token endpoints imported from the API specification are untrusted until the
operator sets \`ANVIL_CREDENTIAL_HOSTS\` to their exact public host(s); alternatively,
set \`ANVIL_<PROFILE>_TOKEN_ENDPOINT\` explicitly. Put this non-secret setting in
\`var.env\` before planning.

## Safety notes
- **Durable ledger is mandatory outside dev.** \`ANVIL_LEDGER\` points at Firestore
  (set by Terraform); the runtime refuses required-idempotency mutations if it is
  missing (fail closed). Terraform creates a delete-protected named database for
  this service and grants its runtime SA conditionally scoped access to only that
  database. \`/readyz\` performs a field-masked, non-mutating data-plane lookup
  and returns 503 if the database is missing, inaccessible, or unavailable.
  The prebundled backend uses atomic create and update-time preconditions.
  Completed replay results carry \`expires_at\` and are subject to the generated
  Firestore TTL policy; \`var.ledger_result_ttl_seconds\` defaults to
  ${DEFAULT_LEDGER_RESULT_TTL_SECONDS} seconds (seven days). Expiry is also
  enforced logically before replay because provider TTL deletion is
  asynchronous. In-progress reservations never carry a TTL and are never
  auto-reclaimed: time passing cannot prove an upstream mutation stopped. Cached
  results can contain application response data, so set the shortest retention
  your retry window and data policy permit. The database uses \`var.region\` and
  one Firestore database quota slot; review that quota when adopting many
  services in one project.
- **Remote state is required.** Without the GCS backend an ephemeral build would
  start from empty state and try to recreate live resources.
- **Lock down the state + plan bucket.** Terraform state and the published plan
  (\`tfplan\`, and the human-readable \`tfplan.txt\`) can contain sensitive values.
  The \`_TF_STATE_BUCKET\` must use uniform bucket-level access, restricted IAM (no
  broad developer/public read), a retention/lifecycle policy, and encryption per
  your policy. If \`tfplan.txt\` exposes more than you want in the review pack, drop
  the \`terraform show\` step / its artifact path from \`cloudbuild.yaml\`.
- **Internal ingress** keeps the surface pinned; the host allowlist
  (\`ANVIL_ALLOWED_HOSTS\`) pins upstream egress.
- **No keys are stored**: callers use their own service account + ID token; the
  runtime SA reads only its own secret.

See \`terraform/main.tf\` for the exact resources and \`env.schema.json\` for the
runtime env contract.
`;
}

function envSchema(host?: string): unknown {
  return {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    type: "object",
    required: ["ANVIL_SERVICE_ID", "ANVIL_ENV", "ANVIL_ALLOWED_HOSTS"],
    properties: {
      ANVIL_SERVICE_ID: { type: "string" },
      ANVIL_ARTIFACT_VERSION: { type: "string" },
      ANVIL_ENV: { type: "string", enum: ["dev", "staging", "prod"] },
      ANVIL_ALLOWED_HOSTS: {
        type: "string",
        description: "Comma-separated egress allowlist.",
        examples: [host ?? "api.internal.example.com"],
      },
      ANVIL_BASE_URL: {
        type: "string",
        description:
          "Override the compiled-in upstream base URL (loopback self-test, staging smoke). When set without ANVIL_ALLOWED_HOSTS, egress pins to this URL's host.",
      },
      ANVIL_LEDGER: {
        type: "string",
        description:
          "Durable idempotency ledger backend URI (firestore://PROJECT/DATABASE/SERVICE_NAMESPACE). Required outside dev for required-idempotency mutations.",
      },
      ANVIL_LEDGER_RESULT_TTL_SECONDS: {
        type: "string",
        pattern: "^[1-9][0-9]*$",
        default: String(DEFAULT_LEDGER_RESULT_TTL_SECONDS),
        description:
          "Completed replay-result retention in seconds (60..31536000). In-progress reservations never expire automatically.",
      },
      ANVIL_AUTH_PROFILE: {
        type: "string",
        description:
          "Selects the upstream credential profile: the ANVIL_<PROFILE>_* prefix. Defaults per env (e.g. prod → ANVIL_PROD_*).",
      },
      ANVIL_POLICY_BUNDLE: { type: "string" },
      ANVIL_OTEL_EXPORTER: { type: "string", examples: ["cloud_trace"] },
      ANVIL_CREDENTIALS: {
        type: "string",
        enum: ["env", "secret_manager"],
        description:
          "Storage selector for static api-key/basic/bearer values. OAuth grants and delegated identity always route per operation. Unset defaults static values to Secret Manager references.",
      },
      ANVIL_SECRET_PROJECT: {
        type: "string",
        description:
          "Default GCP project for shorthand `sm://<secret>` credential references. Full `sm://projects/…` references do not need it.",
      },
      ANVIL_CREDENTIAL_HOSTS: {
        type: "string",
        description:
          "Comma-separated exact public host allowlist for token endpoints imported from API specifications. Not needed when ANVIL_<PROFILE>_TOKEN_ENDPOINT is explicitly operator-configured.",
      },
    },
    // Per-profile upstream credential env vars (names by convention). Any value
    // may be a Secret Manager reference (`sm://…`), dereferenced at call time.
    // See deploy/credentials.required.yaml for exactly which apply to this surface.
    patternProperties: {
      "^ANVIL_[A-Z0-9_]+_(TOKEN|API_KEY|API_KEY_HEADER|API_KEY_QUERY|USERNAME|PASSWORD|TOKEN_ENDPOINT|CLIENT_ID|CLIENT_SECRET|CLIENT_ASSERTION_KEY|AUDIENCE|RESOURCE|SCOPES|ACTOR_TOKEN)$":
        {
          type: "string",
          description:
            "Upstream credential (ANVIL_<PROFILE>_*). Static schemes (api_key/basic/bearer) read directly; OAuth grants (client_credentials, RFC 8693 OBO, RFC 7523 jwt-bearer) mint a token from *_TOKEN_ENDPOINT. Provision secrets as `sm://` references.",
        },
    },
  };
}

function safeHost(url?: string): string | undefined {
  if (!url) return undefined;
  try {
    return new URL(url).hostname;
  } catch {
    return undefined;
  }
}

/**
 * Provider-specific projection for GCP resource names. Service-account ids are
 * the tightest consumer (30 chars including Anvil's `-tools` suffix), so every
 * deployment resource shares one deterministic <=24-char prefix.
 */
export function googleResourcePrefix(serviceId: string): string {
  const slug = serviceId
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  if (slug.length <= 24 && slug === serviceId) return slug;
  // A provider projection is not injective (`foo_bar` and `foo-bar` both slug
  // to `foo-bar`). Preserve the readable stem but bind every transformed or
  // truncated id to its canonical identity with a stable digest.
  const digest = createHash("sha256").update(serviceId).digest("hex").slice(0, 12);
  return `${slug.slice(0, 11).replace(/-+$/g, "")}-${digest}`;
}
