import type { AirDocument } from "@anvil/air";
import { stringify as toYaml } from "yaml";
import { KUBERNETES_REPLACE_PREFIX, kubernetesWorkloadName } from "./deploy-kubernetes.js";
import type { ResourceOptions } from "./resources.js";

/**
 * A GitHub Actions workflow that runs the release GATES and produces the
 * deployment PLAN — and never applies it. It is the pipeline half of the
 * Kubernetes target the way `deploy/cloudbuild.yaml` is the pipeline half of
 * Cloud Run: build the image, prove the bundle (`anvil certify`, `anvil
 * selftest`, `anvil conformance`), render the manifests, and publish the plan
 * as a workflow artifact for a human (or a separate, gated promotion job) to
 * review. No step holds a cluster or registry credential; the image built here
 * is not pushed by this workflow.
 *
 * Pure projection of AIR + the compile's own options, so it is compiler-owned
 * and drift-checked like every other `deploy/` file.
 */

export const GITHUB_ACTIONS_WORKFLOW_FILE = "deploy/ci/github-actions.yml";

/** The GitHub Actions expressions the workflow uses; `${{ … }}` is theirs, not JS. */
const gh = (expression: string) => `\${{ ${expression} }}`;

export function generateGithubActionsWorkflow(
  air: AirDocument,
  resourceOptions: Pick<ResourceOptions, "deploymentNamespace"> = {},
): Record<string, string> {
  const name = kubernetesWorkloadName(air, resourceOptions);
  const workflow = {
    name: `anvil release plan — ${air.service.id}`,
    on: {
      push: { branches: ["main"] },
      pull_request: {},
      workflow_dispatch: {},
    },
    // Read-only by construction: this workflow can neither push nor deploy.
    permissions: { contents: "read" },
    env: {
      // Pin the Anvil CLI with a repository variable (a package spec or a
      // vendored tarball path). The step below refuses to run unpinned.
      ANVIL_CLI_PACKAGE: gh("vars.ANVIL_CLI_PACKAGE"),
      // The image repository the plan is rendered for (no push happens here).
      ANVIL_IMAGE_REPOSITORY: gh("vars.ANVIL_IMAGE_REPOSITORY"),
      ANVIL_KUBERNETES_NAMESPACE: gh("vars.ANVIL_KUBERNETES_NAMESPACE || 'anvil'"),
    },
    jobs: {
      gates: {
        name: "Gates and plan (never applies)",
        "runs-on": "ubuntu-latest",
        steps: [
          { uses: "actions/checkout@v4" },
          { uses: "actions/setup-node@v4", with: { "node-version": "22" } },
          {
            name: "Install the pinned Anvil CLI",
            run:
              'test -n "$ANVIL_CLI_PACKAGE" || { echo "Set the ANVIL_CLI_PACKAGE repository variable to a reviewed Anvil CLI package spec."; exit 1; }\n' +
              'npm install --global "$ANVIL_CLI_PACKAGE"\n' +
              "anvil --version",
          },
          { name: "Static assurance (certify)", run: "anvil certify ." },
          { name: "Loopback self-test", run: "anvil selftest ." },
          { name: "Surface conformance", run: "anvil conformance ." },
          {
            name: "Build the runtime image (not pushed by this workflow)",
            run: `docker build -f deploy/Dockerfile -t "${name}:$GITHUB_SHA" .`,
          },
          {
            name: "Render the Kubernetes plan",
            run:
              'test -n "$ANVIL_IMAGE_REPOSITORY" || { echo "Set the ANVIL_IMAGE_REPOSITORY repository variable (registry/repo) the plan is rendered for."; exit 1; }\n' +
              "mkdir -p plan\n" +
              'anvil deploy kubernetes . --image "$ANVIL_IMAGE_REPOSITORY:$GITHUB_SHA" --namespace "$ANVIL_KUBERNETES_NAMESPACE" --out plan/kubernetes\n' +
              "kubectl kustomize plan/kubernetes > plan/kubernetes.rendered.yaml\n" +
              `if grep -q ${KUBERNETES_REPLACE_PREFIX} plan/kubernetes.rendered.yaml; then echo "Unfilled ${KUBERNETES_REPLACE_PREFIX} scaffold in the rendered manifest; supply the operator inputs."; exit 1; fi\n` +
              "anvil deploy kubernetes . > plan/kubernetes.plan.txt",
          },
          {
            name: "Record the Cloud Run plan",
            run: "anvil deploy cloud-run . > plan/cloud-run.plan.txt",
          },
          {
            name: "Publish the plan for review",
            uses: "actions/upload-artifact@v4",
            with: {
              name: `anvil-release-plan-${gh("github.sha")}`,
              path: "plan",
              "if-no-files-found": "error",
              "retention-days": 30,
            },
          },
        ],
      },
    },
  };
  return {
    [GITHUB_ACTIONS_WORKFLOW_FILE]:
      `# Generated by Anvil — release gates and deployment plan for "${air.service.id}".\n` +
      "# This workflow builds, proves, and PLANS. It never pushes an image, never\n" +
      "# applies a manifest, and holds no cluster or registry credential. Promote\n" +
      "# the reviewed plan artifact with a separate, gated job of your own.\n" +
      "# Copy to .github/workflows/ in the repository that holds this bundle.\n" +
      toYaml(workflow, { lineWidth: 0 }),
  };
}
