import type { AirDocument } from "@anvil/air";

/** Human-facing generated docs (spec §5.5). */
export function generateDocs(air: AirDocument): Record<string, string> {
  return {
    "docs/OPERATIONS.md": operationsDoc(air),
    "docs/README.md": readmeDoc(air),
  };
}

function operationsDoc(air: AirDocument): string {
  const header =
    "| Operation | Effect | Risk | Idempotency | Retry-safe | Confirm | State |\n| --- | --- | --- | --- | --- | --- | --- |";
  const rows = air.operations.map(
    (op) =>
      `| \`${op.cli.command}\` | ${op.effect.kind} | ${op.effect.kind === "mutation" ? op.effect.risk : "-"} | ${op.idempotency.mode} | ${op.retries.mode === "safe" ? "yes" : "no"} | ${op.confirmation.required ? "yes" : "no"} | ${op.state} |`,
  );
  return `# ${air.service.displayName ?? air.service.id} — Operations

Service \`${air.service.id}\` @ \`${air.service.version}\` — ${air.operations.length} operations.

${header}
${rows.join("\n")}

## Diagnostics
${air.diagnostics.length === 0 ? "_None._" : air.diagnostics.map((d) => `- **${d.level}** \`${d.code}\` ${d.operationId ? `(${d.operationId})` : ""}: ${d.message}`).join("\n")}
`;
}

function readmeDoc(air: AirDocument): string {
  const id = air.service.id;
  return `# ${air.service.displayName ?? id} — generated tool surface

Generated by Anvil from a \`${air.service.source.kind}\` spec. CLI, MCP server, and
skill are all projections of one AIR model.

## Layout
- \`air.yaml\` — the canonical model.
- \`catalog.json\` — the operation catalog.
- \`cli/\` — the type-safe CLI. Try \`node cli/${id}.mjs --help\`.
- \`mcp/\` — the MCP server. Boot with \`node mcp/server.js\`.
- \`skill/\` — the portable, progressive-disclosure skill package.
- \`schemas/\` — per-operation input JSON Schemas.
- \`runtime/\` — compiled manifests + the thin Cloud Run server.
- \`deploy/\` — Dockerfile + Cloud Run service + env/secret contracts.
- \`mock/\` — mock server + scenarios. \`evals/\` — behavior checks. \`tests/\` — conformance tests.

## Safety
Unsafe mutations refuse to run without confirmation and (where required) an
idempotency key. Non-idempotent writes are never retried automatically.
`;
}
