import type { AirDocument } from "@anvil/air";

/**
 * The generated per-service CLI entrypoint. It embeds AIR and dispatches through
 * the shared `runToolCli` engine in @anvil/cli, so the CLI, MCP, and skill never
 * drift: one engine, one model, three surfaces.
 */
export function generateCliSource(air: AirDocument): string {
  return `#!/usr/bin/env node
// Generated by Anvil — type-safe CLI for "${air.service.id}".
// The most important progressive-disclosure interface: --help, --schema,
// --examples, --explain, --dry-run, discover, inspect-risk (spec §7).
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { runToolCli } from "@anvil/cli";
import { loadAirDocument } from "@anvil/air";

const air = loadAirDocument(
  JSON.parse(readFileSync(fileURLToPath(new URL("./air.json", import.meta.url)), "utf8")),
);
// The sibling local MCP server, for \`--mcp stdio\` (skill → CLI → MCP). The CLI
// lives at cli/${air.service.id}.mjs, so its stdio server is ../mcp/server.js.
const mcpServerPath = fileURLToPath(new URL("../mcp/server.js", import.meta.url));
process.exitCode = await runToolCli(air, process.argv.slice(2), { mcpServerPath });
`;
}

/**
 * The thin, stateless Cloud Run server (spec: "Production serving path"). It
 * exposes /mcp, /healthz, /readyz, /metrics, and /openapi. Nothing on the hot
 * path parses specs or runs an LLM.
 */
export function generateRuntimeServer(air: AirDocument): string {
  return `#!/usr/bin/env node
// Generated by Anvil — thin runtime server for "${air.service.id}".
import { createServer } from "node:http";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import {
  buildMcpServer,
  loadInboundAuthConfig,
  protectedResourceMetadata,
  verifyInboundToken,
} from "@anvil/mcp-runtime";
import {
  allowedHostsFor,
  EnvCredentialResolver,
  FetchTransport,
  InMemoryObserver,
  loadRuntimeConfig,
  resolveLedger,
} from "@anvil/runtime";
import { loadAirDocument } from "@anvil/air";

const air = loadAirDocument(
  JSON.parse(readFileSync(fileURLToPath(new URL("./air.json", import.meta.url)), "utf8")),
);
const resources = JSON.parse(
  readFileSync(fileURLToPath(new URL("./resources.json", import.meta.url)), "utf8"),
);
const config = loadRuntimeConfig();
const catalog = JSON.parse(
  readFileSync(fileURLToPath(new URL("./operations.manifest.json", import.meta.url)), "utf8"),
);
const observer = new InMemoryObserver();
// Resolve the idempotency ledger once at boot. ANVIL_LEDGER selects a durable
// backend; without one, required-idempotency mutations fail closed outside dev
// (enforced in the executor) — a horizontally-scaled runtime never silently
// trusts a process-local ledger.
const deps = {
  transport: new FetchTransport(),
  credentials: new EnvCredentialResolver(),
  ledger: resolveLedger(config.ledger),
  observer,
};
// ANVIL_BASE_URL is a deliberate operator override (loopback self-test, staging
// smoke tests); when set without an explicit allowlist, egress pins to its host.
const baseUrl = process.env.ANVIL_BASE_URL ?? air.service.servers[0]?.url ?? "";
const allowedHosts = allowedHostsFor(
  config.allowedHosts,
  baseUrl,
  process.env.ANVIL_BASE_URL !== undefined,
);

function mcpContext() {
  return {
    ...deps,
    baseUrl,
    authProfile: config.authProfile,
    allowedHosts,
    env: config.env,
  };
}

// Inbound authentication: this server is an OAuth 2 resource server. When a
// platform (e.g. Gemini Enterprise) is configured to present a bearer token, we
// validate it on every protected route rather than trusting the network. Mode
// "none" (the default) admits everything, for local runs behind other controls.
const inboundAuth = loadInboundAuthConfig();

// The MCP Authorization discovery document, served unauthenticated so a client
// can find the authorization server before it has a token.
const resourceMetadata = protectedResourceMetadata(inboundAuth);

async function authorized(req, res) {
  const result = await verifyInboundToken(req.headers["authorization"], inboundAuth);
  if (result.ok) return true;
  res.writeHead(result.status, {
    "content-type": "application/json",
    "www-authenticate": result.wwwAuthenticate,
  });
  res.end(JSON.stringify({ error: { code: result.error, message: result.description } }));
  return false;
}

const server = createServer(async (req, res) => {
  const url = new URL(req.url ?? "/", "http://localhost");
  // Health/readiness are always open — probes have no token.
  if (url.pathname === "/healthz") return json(res, 200, { status: "ok" });
  if (url.pathname === "/readyz") return json(res, 200, { ready: true, service: config.serviceId });
  if (url.pathname === "/.well-known/oauth-protected-resource") {
    return resourceMetadata
      ? json(res, 200, resourceMetadata)
      : json(res, 404, { error: { code: "not_found", message: "Inbound auth is not configured." } });
  }
  // Everything below exposes the tool surface — gate it on the inbound token.
  if (url.pathname === "/metrics") {
    if (!(await authorized(req, res))) return;
    return json(res, 200, { records: observer.records.length });
  }
  if (url.pathname === "/openapi") {
    if (!(await authorized(req, res))) return;
    return json(res, 200, catalog);
  }
  if (url.pathname === "/mcp") {
    if (!(await authorized(req, res))) return;
    // Stateless StreamableHTTP: a fresh server+transport per request, closed on
    // response. Tool specs and resources are precomputed data, so per-request
    // construction is cheap and holds no cross-request state. sessionIdGenerator
    // MUST be undefined here — a session id would make the transport stateful and
    // expect the same instance across requests, but each request builds its own,
    // so the second call fails with "Server not initialized".
    const mcp = buildMcpServer(air, { resources, contextFor: () => mcpContext() });
    const transport = new StreamableHTTPServerTransport({ sessionIdGenerator: undefined });
    res.on("close", () => transport.close());
    await mcp.connect(transport);
    return transport.handleRequest(req, res);
  }
  return json(res, 404, { error: { code: "not_found", message: "No such route." } });
});

function json(res, status, body) {
  res.writeHead(status, { "content-type": "application/json" });
  res.end(JSON.stringify(body));
}

server.listen(process.env.PORT ?? 8080, () => console.error(config.serviceId, "listening"));
`;
}
