import type { AirDocument } from "@anvil/air";

/**
 * The generated per-service CLI entrypoint. It embeds AIR and dispatches through
 * the shared `runToolCli` engine in @anvil/cli, so the CLI, MCP, and skill never
 * drift: one engine, one model, three surfaces.
 */
export function generateCliSource(air: AirDocument): string {
  return `#!/usr/bin/env node
// Generated by Anvil — type-safe CLI for "${air.service.id}".
// The most important progressive-disclosure interface: --help, --schema,
// --examples, --explain, --dry-run, discover, inspect-risk (spec §7).
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { runToolCli } from "@anvil/cli";
import { loadAirDocument } from "@anvil/air";

const air = loadAirDocument(
  JSON.parse(readFileSync(fileURLToPath(new URL("./air.json", import.meta.url)), "utf8")),
);
process.exitCode = await runToolCli(air, process.argv.slice(2));
`;
}

/**
 * The thin, stateless Cloud Run server (spec: "Production serving path"). It
 * exposes /mcp, /healthz, /readyz, /metrics, and /openapi. Nothing on the hot
 * path parses specs or runs an LLM.
 */
export function generateRuntimeServer(air: AirDocument): string {
  return `#!/usr/bin/env node
// Generated by Anvil — thin runtime server for "${air.service.id}".
import { createServer } from "node:http";
import { randomUUID } from "node:crypto";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import { buildMcpServer } from "@anvil/mcp-runtime";
import {
  EnvCredentialResolver,
  FetchTransport,
  InMemoryObserver,
  loadRuntimeConfig,
  resolveLedger,
} from "@anvil/runtime";
import { loadAirDocument } from "@anvil/air";

const air = loadAirDocument(
  JSON.parse(readFileSync(fileURLToPath(new URL("./air.json", import.meta.url)), "utf8")),
);
const resources = JSON.parse(
  readFileSync(fileURLToPath(new URL("./resources.json", import.meta.url)), "utf8"),
);
const config = loadRuntimeConfig();
const catalog = JSON.parse(
  readFileSync(fileURLToPath(new URL("./operations.manifest.json", import.meta.url)), "utf8"),
);
const observer = new InMemoryObserver();
// Resolve the idempotency ledger once at boot. ANVIL_LEDGER selects a durable
// backend; without one, required-idempotency mutations fail closed outside dev
// (enforced in the executor) — a horizontally-scaled runtime never silently
// trusts a process-local ledger.
const deps = {
  transport: new FetchTransport(),
  credentials: new EnvCredentialResolver(),
  ledger: resolveLedger(config.ledger),
  observer,
};
const baseUrl = air.service.servers[0]?.url ?? "";

function mcpContext() {
  return {
    ...deps,
    baseUrl,
    authProfile: config.authProfile,
    allowedHosts: config.allowedHosts,
    env: config.env,
  };
}

const server = createServer(async (req, res) => {
  const url = new URL(req.url ?? "/", "http://localhost");
  if (url.pathname === "/healthz") return json(res, 200, { status: "ok" });
  if (url.pathname === "/readyz") return json(res, 200, { ready: true, service: config.serviceId });
  if (url.pathname === "/metrics") return json(res, 200, { records: observer.records.length });
  if (url.pathname === "/openapi") return json(res, 200, catalog);
  if (url.pathname === "/mcp") {
    // Stateless StreamableHTTP: a fresh server+transport per request, closed on
    // response. Tool specs and resources are precomputed data, so per-request
    // construction is cheap and holds no cross-request state.
    const mcp = buildMcpServer(air, { resources, contextFor: () => mcpContext() });
    const transport = new StreamableHTTPServerTransport({ sessionIdGenerator: () => randomUUID() });
    res.on("close", () => transport.close());
    await mcp.connect(transport);
    return transport.handleRequest(req, res);
  }
  return json(res, 404, { error: { code: "not_found", message: "No such route." } });
});

function json(res, status, body) {
  res.writeHead(status, { "content-type": "application/json" });
  res.end(JSON.stringify(body));
}

server.listen(process.env.PORT ?? 8080, () => console.error(config.serviceId, "listening"));
`;
}
