import type { AirDocument } from "@anvil/air";

/**
 * The generated per-service CLI entrypoint. It embeds AIR and dispatches through
 * the shared `runToolCli` engine in @anvil/cli, so the CLI, MCP, and skill never
 * drift: one engine, one model, three surfaces.
 */
export function generateCliSource(air: AirDocument): string {
  return `#!/usr/bin/env node
// Generated by Anvil — type-safe CLI for "${air.service.id}".
// The most important progressive-disclosure interface: --help, --schema,
// --examples, --explain, --dry-run, discover, inspect-risk (spec §7).
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { runToolCli } from "@anvil/cli";
import { loadAirDocument } from "@anvil/air";

const air = loadAirDocument(
  JSON.parse(readFileSync(fileURLToPath(new URL("./air.json", import.meta.url)), "utf8")),
);
// The sibling local MCP server, for \`--mcp stdio\` (skill → CLI → MCP). The CLI
// lives at cli/${air.service.id}.mjs, so its stdio server is ../mcp/server.js.
const mcpServerPath = fileURLToPath(new URL("../mcp/server.js", import.meta.url));
process.exitCode = await runToolCli(air, process.argv.slice(2), { mcpServerPath });
`;
}

/**
 * The thin, stateless Cloud Run server (spec: "Production serving path"). It
 * exposes /mcp, /healthz, /readyz, /metrics, and /openapi. Nothing on the hot
 * path parses specs or runs an LLM.
 */
export function generateRuntimeServer(air: AirDocument): string {
  const requiresDurableLedger = air.operations.some(
    (operation) =>
      operation.state === "approved" &&
      operation.effect.kind === "mutation" &&
      operation.idempotency.mode === "required",
  );
  return `#!/usr/bin/env node
// Generated by Anvil — thin runtime server for "${air.service.id}".
import { createServer } from "node:http";
import { lstatSync, readFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join as joinPath } from "node:path";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import { isInitializeRequest } from "@modelcontextprotocol/sdk/types.js";
import { createHash, randomUUID } from "node:crypto";
import {
  buildMcpServer,
  loadInboundAuthConfig,
  protectedResourceMetadata,
  verifyInboundToken,
} from "@anvil/mcp-runtime";
import {
  allowedHostsFor,
  currentInboundIdentity,
  FetchTransport,
  InMemoryObserver,
  loadRuntimeConfig,
  probeLedgerReadiness,
  resolveCredentials,
  resolveLedger,
  withInboundIdentity,
} from "@anvil/runtime";
import { loadAirDocument } from "@anvil/air";

const air = loadAirDocument(
  JSON.parse(readFileSync(fileURLToPath(new URL("./air.json", import.meta.url)), "utf8")),
);
const resources = JSON.parse(
  readFileSync(fileURLToPath(new URL("./resources.json", import.meta.url)), "utf8"),
);
const runtimeRoot = fileURLToPath(new URL(".", import.meta.url));

// Hash the exact /app/runtime payload copied into the production image. The
// local live-conformance harness independently computes the same digest from
// deploy/runtime; matching tool names alone can never attest a deployment.
function runtimeArtifactEntries(dir = runtimeRoot, prefix = "") {
  const entries = [];
  for (const name of readdirSync(dir).sort()) {
    const full = joinPath(dir, name);
    const relative = prefix ? prefix + "/" + name : name;
    const stat = lstatSync(full);
    if (stat.isSymbolicLink()) throw new Error("Runtime artifact contains a symbolic link.");
    if (stat.isDirectory()) entries.push(...runtimeArtifactEntries(full, relative));
    else if (stat.isFile()) entries.push([relative, readFileSync(full)]);
    else throw new Error("Runtime artifact contains an unsupported filesystem entry.");
  }
  return entries;
}

function computeRuntimeArtifactHash() {
  const hash = createHash("sha256");
  for (const [relative, bytes] of runtimeArtifactEntries()) {
    const contentHash = createHash("sha256").update(bytes).digest("hex");
    hash.update(relative + "\\0" + contentHash + "\\0");
  }
  return hash.digest("hex");
}

const artifactHash = computeRuntimeArtifactHash();
const config = loadRuntimeConfig();
const catalog = JSON.parse(
  readFileSync(fileURLToPath(new URL("./operations.manifest.json", import.meta.url)), "utf8"),
);
const observer = new InMemoryObserver();
// Resolve the idempotency ledger once at boot. ANVIL_LEDGER selects a durable
// backend; without one, required-idempotency mutations fail closed outside dev
// (enforced in the executor) — a horizontally-scaled runtime never silently
// trusts a process-local ledger.
const deps = {
  transport: new FetchTransport(),
  // ANVIL_CREDENTIALS / per-op AuthRequirement selects the resolver: static env
  // (default), Secret Manager references (sm://…), or RFC 8693 OBO token exchange
  // using the inbound caller token threaded below. Dev stays byte-identical.
  credentials: resolveCredentials(config),
  ledger: resolveLedger(config.ledger, {
    resultTtlMs: config.ledgerResultTtlSeconds * 1000,
  }),
  observer,
};
// ANVIL_BASE_URL is a deliberate operator override (loopback self-test, staging
// smoke tests); when set without an explicit allowlist, egress pins to its host.
const baseUrl = process.env.ANVIL_BASE_URL ?? air.service.servers[0]?.url ?? "";
const allowedHosts = allowedHostsFor(
  config.allowedHosts,
  baseUrl,
  process.env.ANVIL_BASE_URL !== undefined,
);

function mcpContext() {
  return {
    ...deps,
    serviceId: air.service.id,
    baseUrl,
    authProfile: config.authProfile,
    allowedHosts,
    env: config.env,
    timeoutMs: config.upstreamTimeoutMs,
    // The per-request caller identity (set by withInboundIdentity around dispatch);
    // the credential resolver uses it as the subject_token for OBO exchange.
    inbound: currentInboundIdentity(),
  };
}

// Inbound authentication: this server is an OAuth 2 resource server. When a
// platform (e.g. Gemini Enterprise) is configured to present a bearer token, we
// validate it on every protected route rather than trusting the network. Mode
// "none" (the default) admits everything, for local runs behind other controls.
const inboundAuth = loadInboundAuthConfig();

// The MCP Authorization discovery document, served unauthenticated so a client
// can find the authorization server before it has a token.
const resourceMetadata = protectedResourceMetadata(inboundAuth);

// Verify the inbound bearer and, on success, distill the validated caller into an
// InboundIdentity so an on-behalf-of upstream call can exchange it (RFC 8693). On
// failure the 401/403 is written here and { ok:false } signals the caller to stop.
async function authorized(req, res) {
  const header = req.headers["authorization"];
  const result = await verifyInboundToken(header, inboundAuth);
  if (!result.ok) {
    res.writeHead(result.status, {
      "content-type": "application/json",
      "www-authenticate": result.wwwAuthenticate,
    });
    res.end(JSON.stringify({ error: { code: result.error, message: result.description } }));
    return { ok: false };
  }
  const rawToken =
    typeof header === "string" ? header.replace(/^Bearer\\s+/i, "").trim() : undefined;
  if (inboundAuth.mode !== "none" && !rawToken) {
    res.writeHead(401, {
      "content-type": "application/json",
      "www-authenticate": 'Bearer error="invalid_token"',
    });
    res.end(
      JSON.stringify({
        error: { code: "invalid_token", message: "Verified bearer token is unavailable." },
      }),
    );
    return { ok: false };
  }
  const callerFingerprint =
    inboundAuth.mode === "none" ? "anonymous" : verifiedPrincipalFingerprint(result.claims);
  if (!callerFingerprint) {
    res.writeHead(401, {
      "content-type": "application/json",
      "www-authenticate": 'Bearer error="invalid_token"',
    });
    res.end(
      JSON.stringify({
        error: {
          code: "invalid_token",
          message: "Verified token does not identify a stable caller principal.",
        },
      }),
    );
    return { ok: false };
  }
  // Inbound mode "none" deliberately performs no token verification. Never promote a
  // caller-supplied bearer from that mode into a "validated" OBO subject.
  return {
    ok: true,
    identity: inboundAuth.mode === "none" ? undefined : inboundIdentityFrom(rawToken, result.claims),
    // Bind the session to the verified principal, not the bearer bytes. Access
    // tokens rotate during a long MCP session; the same issuer/subject may keep
    // using its session while a different principal cannot take it over.
    callerFingerprint,
  };
}

function verifiedPrincipalFingerprint(claims) {
  if (!claims || typeof claims !== "object" || Array.isArray(claims)) return undefined;
  const issuer = typeof claims.iss === "string" ? claims.iss : undefined;
  // sub is the standard principal. oid covers app-only Entra tokens, while
  // azp / client_id identify a verified machine caller when no subject claim
  // is issued. The verifier has already checked signature, issuer and audience.
  const textClaim = (value) =>
    typeof value === "string" && value.length > 0 ? value : undefined;
  const sub = textClaim(claims.sub);
  const oid = textClaim(claims.oid);
  const authorizedParty = textClaim(claims.azp) ?? textClaim(claims.client_id);
  if (!issuer || (!sub && !oid && !authorizedParty)) return undefined;
  const tenant =
    typeof claims.tid === "string"
      ? claims.tid
      : typeof claims.tenant === "string"
        ? claims.tenant
        : undefined;
  return createHash("sha256")
    .update(JSON.stringify({ issuer, sub, oid, authorizedParty, tenant }))
    .digest("base64url");
}

// The raw caller token + its verified claims → the OBO subject. The raw bearer is
// forwarded ONLY to the configured token endpoint for exchange; it is never sent
// to the upstream directly, recorded, or logged.
function inboundIdentityFrom(raw, claims) {
  if (!raw) return undefined;
  return {
    subjectToken: raw,
    subjectTokenType: raw.split(".").length === 3 ? "jwt" : "access_token",
    sub: claims.sub,
    email: claims.email,
    scope: claims.scope,
    claims,
  };
}

// Live MCP sessions keyed by the mcp-session-id minted at initialize. Gemini
// Enterprise (and any spec-compliant client) drives a real lifecycle —
// initialize, then tools/list and tool calls on that SAME session in separate
// HTTP requests — so the server must be stateful: a stateless transport builds a
// fresh, uninitialized server per request and the second call fails.
//
// The store is intentionally bounded. Idle sessions expire, capacity pressure
// evicts the least-recently-used inactive session, and active requests are never
// classified as idle. All transports are closed on eviction and process shutdown.
const MCP_REQUEST_MAX_BYTES = 1024 * 1024;
const MCP_SESSION_IDLE_TTL_MS = 15 * 60 * 1000;
const MCP_SESSION_SWEEP_MS = 60 * 1000;
const MCP_MAX_SESSIONS = 1000;
const sessions = new Map();
const liveSessionEntries = new Set();
let pendingSessionCount = 0;
let shuttingDown = false;

function forgetSession(entry) {
  liveSessionEntries.delete(entry);
  if (entry.sessionId && sessions.get(entry.sessionId) === entry) {
    sessions.delete(entry.sessionId);
  }
}

async function closeSession(entry) {
  if (entry.closePromise) return entry.closePromise;
  forgetSession(entry);
  entry.closePromise = entry.mcp.close().catch(() => {
    // Cleanup is best-effort after the session has already been made unreachable.
    console.error("Failed to close an MCP session cleanly.");
  });
  return entry.closePromise;
}

function pruneIdleSessions(now = Date.now()) {
  for (const entry of sessions.values()) {
    if (
      entry.activeRequests === 0 &&
      now - entry.lastUsedAt >= MCP_SESSION_IDLE_TTL_MS
    ) {
      void closeSession(entry);
    }
  }
}

function leastRecentlyUsedIdleSession() {
  let oldest;
  for (const entry of sessions.values()) {
    if (entry.activeRequests !== 0) continue;
    if (!oldest || entry.lastUsedAt < oldest.lastUsedAt) oldest = entry;
  }
  return oldest;
}

function reserveSessionSlot() {
  pruneIdleSessions();
  while (sessions.size + pendingSessionCount >= MCP_MAX_SESSIONS) {
    const oldest = leastRecentlyUsedIdleSession();
    if (!oldest) return false;
    // closeSession removes the entry synchronously before awaiting transport close.
    void closeSession(oldest);
  }
  pendingSessionCount += 1;
  return true;
}

function releaseSessionReservation() {
  pendingSessionCount = Math.max(0, pendingSessionCount - 1);
}

const sessionSweep = setInterval(() => pruneIdleSessions(), MCP_SESSION_SWEEP_MS);
sessionSweep.unref();

const server = createServer(async (req, res) => {
  const url = new URL(req.url ?? "/", "http://localhost");
  // Health/readiness are always open — probes have no token.
  if (url.pathname === "/healthz")
    return json(res, 200, {
      status: "ok",
      service: air.service.id,
      artifactHash,
    });
  if (url.pathname === "/readyz") {
    const ledger = await probeLedgerReadiness(
      deps.ledger,
      ${requiresDurableLedger} && config.env !== "dev",
    );
    return ledger.ready
      ? json(res, 200, { ready: true, service: air.service.id })
      : json(res, 503, {
          ready: false,
          service: air.service.id,
          code: "ledger_unavailable",
        });
  }
  if (url.pathname === "/.well-known/oauth-protected-resource") {
    return resourceMetadata
      ? json(res, 200, resourceMetadata)
      : json(res, 404, { error: { code: "not_found", message: "Inbound auth is not configured." } });
  }
  // Everything below exposes the tool surface — gate it on the inbound token.
  if (url.pathname === "/metrics") {
    if (!(await authorized(req, res)).ok) return;
    return json(res, 200, { records: observer.records.length });
  }
  if (url.pathname === "/openapi") {
    if (!(await authorized(req, res)).ok) return;
    return json(res, 200, catalog);
  }
  if (url.pathname === "/mcp") {
    if (shuttingDown) {
      return jsonRpcError(res, 503, -32000, "Server is shutting down.");
    }
    const auth = await authorized(req, res);
    if (!auth.ok) return;
    // Stateful StreamableHTTP sessions. Buffer the POST body so we can both route
    // by session and detect the initialize request; GET/DELETE carry no body.
    let body;
    if (req.method === "POST") {
      const mediaType = String(req.headers["content-type"] ?? "")
        .split(";", 1)[0]
        .trim()
        .toLowerCase();
      if (mediaType !== "application/json") {
        req.resume();
        return jsonRpcError(res, 415, -32600, "Content-Type must be application/json.");
      }
      const parsed = await readJsonBody(req, res);
      if (!parsed.ok) return;
      body = parsed.value;
    }
    const sidHeader = req.headers["mcp-session-id"];
    const sid = typeof sidHeader === "string" ? sidHeader : undefined;
    let entry = sid ? sessions.get(sid) : undefined;
    if (entry && entry.callerFingerprint !== auth.callerFingerprint) {
      return jsonRpcError(
        res,
        403,
        -32001,
        "This MCP session belongs to a different authenticated caller.",
      );
    }
    let reservationHeld = false;
    if (!entry) {
      if (req.method === "POST" && isInitializeRequest(body)) {
        if (!reserveSessionSlot()) {
          return jsonRpcError(
            res,
            503,
            -32000,
            "MCP session capacity is temporarily exhausted.",
          );
        }
        reservationHeld = true;
        // New session: build the server once and keep it for the session's life.
        const mcp = buildMcpServer(air, { resources, contextFor: () => mcpContext() });
        let initializedEntry;
        const transport = new StreamableHTTPServerTransport({
          sessionIdGenerator: () => randomUUID(),
          onsessioninitialized: (id) => {
            releaseSessionReservation();
            reservationHeld = false;
            initializedEntry.sessionId = id;
            sessions.set(id, initializedEntry);
          },
        });
        transport.onclose = () => {
          if (initializedEntry) forgetSession(initializedEntry);
        };
        initializedEntry = {
          mcp,
          transport,
          callerFingerprint: auth.callerFingerprint,
          lastUsedAt: Date.now(),
          activeRequests: 0,
          sessionId: undefined,
          closePromise: undefined,
        };
        entry = initializedEntry;
        liveSessionEntries.add(entry);
        try {
          await mcp.connect(transport);
        } catch {
          releaseSessionReservation();
          reservationHeld = false;
          await closeSession(entry);
          return jsonRpcError(res, 500, -32603, "MCP session initialization failed.");
        }
      } else {
        // A non-initialize request with no known session — reject per the spec.
        return jsonRpcError(res, 400, -32000, "No valid session; send initialize first.");
      }
    }
    // Dispatch inside the caller's identity so contextFor()/the resolver can use
    // it as the OBO subject_token. No identity (inbound auth "none") → plain call;
    // delegated ops then correctly fail auth_required rather than degrading.
    entry.activeRequests += 1;
    entry.lastUsedAt = Date.now();
    try {
      return await (auth.identity
        ? withInboundIdentity(auth.identity, () => entry.transport.handleRequest(req, res, body))
        : entry.transport.handleRequest(req, res, body));
    } catch {
      if (!res.headersSent) {
        return jsonRpcError(res, 500, -32603, "MCP request handling failed.");
      }
      res.destroy();
    } finally {
      entry.activeRequests = Math.max(0, entry.activeRequests - 1);
      entry.lastUsedAt = Date.now();
      if (reservationHeld) {
        releaseSessionReservation();
        await closeSession(entry);
      }
    }
  }
  return json(res, 404, { error: { code: "not_found", message: "No such route." } });
});

function readJsonBody(req, res) {
  const declaredLength = req.headers["content-length"];
  if (
    typeof declaredLength === "string" &&
    /^\\d+$/.test(declaredLength) &&
    Number(declaredLength) > MCP_REQUEST_MAX_BYTES
  ) {
    req.resume();
    jsonRpcError(res, 413, -32600, "MCP request body exceeds the size limit.");
    return Promise.resolve({ ok: false });
  }

  return new Promise((resolve) => {
    const chunks = [];
    let received = 0;
    let settled = false;

    const cleanup = () => {
      req.off("data", onData);
      req.off("end", onEnd);
      req.off("aborted", onAborted);
      req.off("error", onError);
    };
    const finish = (value) => {
      if (settled) return;
      settled = true;
      cleanup();
      resolve(value);
    };
    const rejectBody = (status, message) => {
      if (!res.headersSent) jsonRpcError(res, status, -32600, message);
      // Continue consuming the socket without retaining attacker-controlled bytes.
      req.once("error", () => {});
      req.resume();
      finish({ ok: false });
    };
    const onData = (chunk) => {
      const bytes = Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk);
      received += bytes.length;
      if (received > MCP_REQUEST_MAX_BYTES) {
        rejectBody(413, "MCP request body exceeds the size limit.");
        return;
      }
      chunks.push(bytes);
    };
    const onEnd = () => {
      const raw = Buffer.concat(chunks).toString("utf8");
      if (!raw.trim()) {
        rejectBody(400, "MCP request body must contain JSON.");
        return;
      }
      try {
        finish({ ok: true, value: JSON.parse(raw) });
      } catch {
        rejectBody(400, "MCP request body is malformed JSON.");
      }
    };
    const onAborted = () => rejectBody(400, "MCP request body was aborted.");
    const onError = () => rejectBody(400, "MCP request body could not be read.");

    req.on("data", onData);
    req.once("end", onEnd);
    req.once("aborted", onAborted);
    req.once("error", onError);
  });
}

function jsonRpcError(res, status, code, message) {
  return json(res, status, {
    jsonrpc: "2.0",
    error: { code, message },
    id: null,
  });
}

function json(res, status, body) {
  res.writeHead(status, {
    "content-type": "application/json",
    "cache-control": "no-store",
  });
  res.end(JSON.stringify(body));
}

async function shutdown() {
  if (shuttingDown) return;
  shuttingDown = true;
  clearInterval(sessionSweep);
  const serverClosed = new Promise((resolve) => {
    server.close((error) => {
      if (error) {
        console.error("HTTP server shutdown failed.");
        process.exitCode = 1;
      }
      resolve();
    });
  });
  // Bound graceful shutdown even if a client leaves an HTTP stream or transport
  // open. The timer starts before awaiting MCP close so cleanup cannot deadlock.
  const forceClose = setTimeout(() => server.closeAllConnections?.(), 5000);
  forceClose.unref();
  await Promise.allSettled([...liveSessionEntries].map((entry) => closeSession(entry)));
  server.closeIdleConnections?.();
  await serverClosed;
  clearTimeout(forceClose);
}

process.once("SIGTERM", () => void shutdown());
process.once("SIGINT", () => void shutdown());

server.listen(process.env.PORT ?? 8080, () => console.error(air.service.id, "listening"));
`;
}
