import type { AirDocument } from "@anvil/air";

// The live MCP server now lives in @anvil/mcp-runtime (the thin serving path).
// Re-exported here so build-time callers (tests, `anvil serve`) keep one import
// site, while the *generated* deployed server depends on @anvil/mcp-runtime
// directly and never pulls in this artifact foundry.
export {
  buildMcpServer,
  type DisclosureMode,
  decideLadder,
  type LadderDecision,
  type LadderDecisionReason,
  type LadderMeasuredAccuracy,
  MCP_RESERVED,
  type McpBuildOptions,
  MIN_LADDER_TOKEN_SAVINGS_FRACTION,
  MIN_LADDERED_ACCURACY_DELTA_PTS,
  operationZodShape,
  type ServedResource,
} from "@anvil/mcp-runtime";

/** The generated `mcp/server.js` entrypoint that boots the server over stdio. */
export function generateMcpServerSource(air: AirDocument): string {
  return `#!/usr/bin/env node
// Generated by Anvil for service "${air.service.id}". Do not edit by hand —
// regenerate from AIR (\`anvil compile\`). One tool per approved operation.
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { buildMcpServer } from "@anvil/mcp-runtime";
import { bootRuntimeFromEnv } from "@anvil/runtime";
import { loadAirDocument } from "@anvil/air";

const air = loadAirDocument(
  JSON.parse(readFileSync(fileURLToPath(new URL("./air.json", import.meta.url)), "utf8")),
);
const resources = JSON.parse(
  readFileSync(fileURLToPath(new URL("./resources.json", import.meta.url)), "utf8"),
);
// One composition root, shared with runtime/server.js and \`anvil serve mcp\`:
// runtime extensions (ANVIL_EXTENSIONS / ANVIL_POLICY_BUNDLE) load first and
// may contribute policy hooks, an observer, a transport wrapper, or ledger and
// credential backends; then the execution-record exporter (ANVIL_OTEL_EXPORTER,
// plus the ANVIL_RECORDS_DIR spool for anvil observe --from-records); then
// transport, credentials, and the idempotency ledger. A missing extension or an
// unknown exporter refuses to boot rather than serving without it. stdout is
// the MCP transport here, so the stdout exporter and boot diagnostics go to
// stderr.
const boot = await bootRuntimeFromEnv({
  serviceId: air.service.id,
  serviceVersion: air.service.version,
  recordWrite: (line) => process.stderr.write(\`\${line}\\n\`),
});
const config = boot.config;
// ANVIL_BASE_URL is a deliberate operator override (loopback self-test, staging
// smoke tests); when set without an explicit allowlist, egress pins to its host.
// ANVIL_PROTOCOL_FACADE is the operator's declaration that the base URL really
// serves a non-HTTP/JSON source's synthesized coordinates over HTTP+JSON.
const { baseUrl, allowedHosts, protocolFacade } = boot.baseUrlFor(air.service.servers[0]?.url);
const server = buildMcpServer(air, {
  resources,
  contextFor: () => ({
    ...boot.contextDeps,
    serviceId: air.service.id,
    remoteIdempotency: air.business !== undefined,
    baseUrl,
    authProfile: config.authProfile,
    allowedHosts,
    protocolFacade,
    env: config.env,
    timeoutMs: config.upstreamTimeoutMs,
    // One session, one principal: ANVIL_PRINCIPAL names this stdio caller in
    // the ANVIL_PRINCIPALS directory; rate and spend limits ride contextDeps.
    principal: boot.principalFor(),
  }),
});

await server.connect(new StdioServerTransport());
`;
}

/**
 * The generated `mcp/server-sse.js` entrypoint: the REMOTE MCP server, spoken
 * over HTTP + Server-Sent Events. This is the companion to the stdio server —
 * same tools, same safety runtime — for clients that connect to a URL instead of
 * spawning a local process. It exposes `GET /sse` (the event stream) and
 * `POST /messages?sessionId=…` (client → server), the MCP HTTP+SSE transport.
 *
 * Unlike `runtime/server.js` (stateless StreamableHTTP for Cloud Run), SSE is
 * stateful — one open stream per session — so a horizontally-scaled deployment
 * needs sticky routing by `sessionId`. The safety hot path is identical: one tool
 * per approved operation, egress pinned to the allowlist, secrets from the env.
 */
export function generateMcpSseServerSource(air: AirDocument): string {
  const requiresDurableLedger = air.operations.some(
    (operation) =>
      operation.state === "approved" &&
      operation.effect.kind === "mutation" &&
      operation.idempotency.mode === "required",
  );
  return `#!/usr/bin/env node
// Generated by Anvil for service "${air.service.id}" — REMOTE MCP server (HTTP + SSE).
// Do not edit by hand — regenerate from AIR (\`anvil compile\`).
// Transport: GET /sse (event stream) + POST /messages?sessionId=… (client→server).
import { createServer } from "node:http";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { SSEServerTransport } from "@modelcontextprotocol/sdk/server/sse.js";
import {
  buildMcpServer,
  loadInboundAuthConfig,
  protectedResourceMetadata,
  verifyInboundToken,
} from "@anvil/mcp-runtime";
import {
  bootRuntimeFromEnv,
  currentInboundIdentity,
  probeLedgerReadiness,
  withInboundIdentity,
} from "@anvil/runtime";
import { loadAirDocument } from "@anvil/air";

const air = loadAirDocument(
  JSON.parse(readFileSync(fileURLToPath(new URL("./air.json", import.meta.url)), "utf8")),
);
const resources = JSON.parse(
  readFileSync(fileURLToPath(new URL("./resources.json", import.meta.url)), "utf8"),
);
// Same composition root as mcp/server.js and runtime/server.js (see there):
// extensions, exporter, transport, credentials, ledger — in that order.
const boot = await bootRuntimeFromEnv({
  serviceId: air.service.id,
  serviceVersion: air.service.version,
});
const config = boot.config;
const deps = boot.contextDeps;
const { baseUrl, allowedHosts, protocolFacade } = boot.baseUrlFor(air.service.servers[0]?.url);
const mcpContext = () => {
  // The per-request caller identity (set by withInboundIdentity around
  // dispatch): the OBO subject token, and the key the principal directory
  // (ANVIL_PRINCIPALS) resolves this caller's scopes and limits by.
  const inbound = currentInboundIdentity();
  return {
    ...boot.contextDeps,
    serviceId: air.service.id,
    remoteIdempotency: air.business !== undefined,
    baseUrl,
    authProfile: config.authProfile,
    allowedHosts,
    protocolFacade,
    env: config.env,
    timeoutMs: config.upstreamTimeoutMs,
    inbound,
    principal: boot.principalFor(inbound),
  };
};

// Inbound authentication: this server is an OAuth 2 resource server, exactly
// like runtime/server.js. Mode "none" (the default) admits everything, for
// local runs behind other controls — but every deployed transport validates
// the same way, so a client cannot bypass ANVIL_INBOUND_AUTH by using SSE.
const inboundAuth = loadInboundAuthConfig();
const resourceMetadata = protectedResourceMetadata(inboundAuth);

async function authorized(req, res) {
  const header = req.headers["authorization"];
  const result = await verifyInboundToken(header, inboundAuth);
  if (!result.ok) {
    res.writeHead(result.status, {
      "content-type": "application/json",
      "www-authenticate": result.wwwAuthenticate,
    });
    res.end(JSON.stringify({ error: { code: result.error, message: result.description } }));
    return { ok: false };
  }
  const rawToken =
    typeof header === "string" ? header.replace(/^Bearer\\s+/i, "").trim() : undefined;
  if (inboundAuth.mode !== "none" && !rawToken) {
    res.writeHead(401, {
      "content-type": "application/json",
      "www-authenticate": 'Bearer error="invalid_token"',
    });
    res.end(
      JSON.stringify({
        error: { code: "invalid_token", message: "Verified bearer token is unavailable." },
      }),
    );
    return { ok: false };
  }
  // Inbound mode "none" deliberately performs no token verification. Never promote a
  // caller-supplied bearer from that mode into a "validated" OBO subject.
  return {
    ok: true,
    identity:
      inboundAuth.mode === "none" ? undefined : inboundIdentityFrom(rawToken, result.claims),
  };
}

// The raw caller token + its verified claims → the OBO subject. The raw bearer is
// forwarded ONLY to the configured token endpoint for exchange; it is never sent
// to the upstream directly, recorded, or logged.
function inboundIdentityFrom(raw, claims) {
  if (!raw) return undefined;
  return {
    subjectToken: raw,
    subjectTokenType: raw.split(".").length === 3 ? "jwt" : "access_token",
    sub: claims.sub,
    email: claims.email,
    scope: claims.scope,
    claims,
  };
}

// One live SSE transport per session, keyed by its sessionId. POST /messages
// carries ?sessionId=… back to the stream that owns the conversation.
const sessions = new Map();

function send(res, status, body) {
  res.writeHead(status, { "content-type": "application/json" });
  res.end(JSON.stringify(body));
}

const server = createServer(async (req, res) => {
  const url = new URL(req.url ?? "/", "http://localhost");
  if (url.pathname === "/healthz")
    return send(res, 200, {
      status: "ok",
      exporter: boot.exporter,
      extensions: boot.extensions.loaded,
    });
  if (url.pathname === "/readyz") {
    const ledger = await probeLedgerReadiness(
      deps.ledger,
      ${requiresDurableLedger} && config.env !== "dev",
    );
    return ledger.ready
      ? send(res, 200, { ready: true, service: air.service.id })
      : send(res, 503, {
          ready: false,
          service: air.service.id,
          code: "ledger_unavailable",
        });
  }
  if (url.pathname === "/.well-known/oauth-protected-resource") {
    return resourceMetadata
      ? send(res, 200, resourceMetadata)
      : send(res, 404, { error: { code: "not_found", message: "Inbound auth is not configured." } });
  }
  if (req.method === "GET" && url.pathname === "/sse") {
    const auth = await authorized(req, res);
    if (!auth.ok) return;
    const transport = new SSEServerTransport("/messages", res);
    sessions.set(transport.sessionId, { transport, identity: auth.identity });
    res.on("close", () => sessions.delete(transport.sessionId));
    const mcp = buildMcpServer(air, { resources, contextFor: () => mcpContext() });
    return auth.identity
      ? withInboundIdentity(auth.identity, () => mcp.connect(transport))
      : mcp.connect(transport);
  }
  if (req.method === "POST" && url.pathname === "/messages") {
    const auth = await authorized(req, res);
    if (!auth.ok) return;
    const sessionId = url.searchParams.get("sessionId");
    const entry = sessionId ? sessions.get(sessionId) : undefined;
    if (!entry)
      return send(res, 400, {
        error: { code: "no_session", message: "Unknown or missing sessionId. Open GET /sse first." },
      });
    return entry.identity
      ? withInboundIdentity(entry.identity, () => entry.transport.handlePostMessage(req, res))
      : entry.transport.handlePostMessage(req, res);
  }
  return send(res, 404, {
    error: { code: "not_found", message: "MCP over SSE: GET /sse, then POST /messages?sessionId=…" },
  });
});

server.listen(process.env.PORT ?? 8080, () =>
  console.error(air.service.id, "MCP SSE listening on /sse"),
);
`;
}
