import type { AirDocument } from "@anvil/air";

// The live MCP server now lives in @anvil/mcp-runtime (the thin serving path).
// Re-exported here so build-time callers (tests, `anvil serve`) keep one import
// site, while the *generated* deployed server depends on @anvil/mcp-runtime
// directly and never pulls in this artifact foundry.
export {
  buildMcpServer,
  type McpBuildOptions,
  operationZodShape,
  type ServedResource,
} from "@anvil/mcp-runtime";

/** The generated `mcp/server.js` entrypoint that boots the server over stdio. */
export function generateMcpServerSource(air: AirDocument): string {
  return `#!/usr/bin/env node
// Generated by Anvil for service "${air.service.id}". Do not edit by hand —
// regenerate from AIR (\`anvil compile\`). One tool per approved operation.
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { buildMcpServer } from "@anvil/mcp-runtime";
import {
  EnvCredentialResolver,
  FetchTransport,
  InMemoryObserver,
  loadRuntimeConfig,
  resolveLedger,
} from "@anvil/runtime";
import { loadAirDocument } from "@anvil/air";

const air = loadAirDocument(
  JSON.parse(readFileSync(fileURLToPath(new URL("./air.json", import.meta.url)), "utf8")),
);
const resources = JSON.parse(
  readFileSync(fileURLToPath(new URL("./resources.json", import.meta.url)), "utf8"),
);
const config = loadRuntimeConfig();
const transport = new FetchTransport();
const credentials = new EnvCredentialResolver();
const ledger = resolveLedger(config.ledger);
const observer = new InMemoryObserver();

const baseUrl = air.service.servers[0]?.url ?? "";
const server = buildMcpServer(air, {
  resources,
  contextFor: () => ({
    transport,
    credentials,
    ledger,
    observer,
    baseUrl,
    authProfile: config.authProfile,
    allowedHosts: config.allowedHosts,
    env: config.env,
  }),
});

await server.connect(new StdioServerTransport());
`;
}
