import { mkdirSync, readFileSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { operationInputSchema } from "@anvil/air";
import { certifyBundle, executableEvidenceStatuses, readBundleDir } from "@anvil/generators";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import {
  zArtifactsView,
  zArtifactView,
  zAssuranceView,
  zOperationView,
  zWorkspace,
} from "../contract.js";
import { loadAir, paymentsWorkspace, startServer } from "./fixture.js";

let workspace: Awaited<ReturnType<typeof paymentsWorkspace>>;
let running: Awaited<ReturnType<typeof startServer>>;
beforeAll(async () => {
  workspace = await paymentsWorkspace();
  running = await startServer(workspace.root);
});
afterAll(async () => {
  await running?.server.close();
  if (workspace) rmSync(workspace.root, { recursive: true, force: true });
});
const base = "/api/bundles/payments";

describe("workbench read APIs over real generated bundles", () => {
  it("projects the exact shared input schema without exposing an unapproved operation", async () => {
    const op = loadAir(workspace.bundleDir).operations.find((item) => item.state !== "approved");
    expect(op).toBeDefined();
    const reply = await running.client.get(`${base}/operations/${encodeURIComponent(op!.id)}`);
    expect(reply.status).toBe(200);
    const view = zOperationView.parse(reply.json);
    expect(view.inputSchema).toEqual(operationInputSchema(op!));
    expect(view.operation).toEqual(op);
    expect(view.served).toBe(false);
    expect((await running.client.get(`${base}/operations/not-an-operation`)).status).toBe(404);
  });

  it("runs the existing static checks and evidence readers without writing reports", async () => {
    const before = readBundleDir(workspace.bundleDir);
    const expected = certifyBundle(before, loadAir(workspace.bundleDir));
    const reply = await running.client.get(`${base}/assurance`);
    expect(reply.status).toBe(200);
    const report = zAssuranceView.parse(reply.json);
    expect(report.checks).toEqual(expected.checks);
    expect(report.status).toBe(expected.status);
    expect(report.bundleHash).toBe(expected.bundleHash);
    expect(report.evidence).toEqual(Object.values(executableEvidenceStatuses(before)));
    expect(report.certification.valid).toBe(false);
    expect(readBundleDir(workspace.bundleDir)).toEqual(before);
  });

  it("shows stale passing evidence as stale, and current failing evidence as failed", async () => {
    const path = join(workspace.bundleDir, "selftest.report.json");
    const files = readBundleDir(workspace.bundleDir);
    const hash = certifyBundle(files, loadAir(workspace.bundleDir)).bundleHash;
    try {
      writeFileSync(
        path,
        JSON.stringify({
          schemaVersion: 1,
          bundleHash: "0".repeat(64),
          summary: { pass: 1, fail: 0, skipped: 0 },
        }),
      );
      const stale = zAssuranceView.parse((await running.client.get(`${base}/assurance`)).json);
      expect(stale.evidence.find((lane) => lane.lane === "selftest")?.state).toBe("stale");
      writeFileSync(
        path,
        JSON.stringify({
          schemaVersion: 1,
          bundleHash: hash,
          summary: { pass: 0, fail: 1, skipped: 0 },
        }),
      );
      const failed = zAssuranceView.parse((await running.client.get(`${base}/assurance`)).json);
      expect(failed.evidence.find((lane) => lane.lane === "selftest")?.passed).toBe(false);
    } finally {
      rmSync(path, { force: true });
    }
  });

  it("lists and reads generated bytes, refusing arbitrary files and path traversal", async () => {
    writeFileSync(join(workspace.bundleDir, ".env"), "PRIVATE_SENTINEL=not-for-the-console");
    try {
      const listing = zArtifactsView.parse((await running.client.get(`${base}/artifacts`)).json);
      expect(listing.files.some((file) => file.path === ".env")).toBe(false);
      const path = listing.files.find((file) => file.path.startsWith("sdk/"))!.path;
      const reply = await running.client.get(`${base}/artifact?${new URLSearchParams({ path })}`);
      const artifact = zArtifactView.parse(reply.json);
      expect(artifact.content).toBe(readFileSync(join(workspace.bundleDir, path), "utf8"));
      expect(artifact.truncated).toBe(false);
      for (const outside of [".env", "../payments/.env", "/etc/passwd", "__proto__"]) {
        const denied = await running.client.get(
          `${base}/artifact?${new URLSearchParams({ path: outside })}`,
        );
        expect(denied.status).toBe(404);
        expect(denied.text).not.toContain("PRIVATE_SENTINEL");
      }
    } finally {
      rmSync(join(workspace.bundleDir, ".env"));
    }
  });

  it("bounds artifact responses and refuses symlink targets", async () => {
    const listing = zArtifactsView.parse((await running.client.get(`${base}/artifacts`)).json);
    const file = listing.files.find((item) => item.path.endsWith(".md"))!;
    const path = join(workspace.bundleDir, file.path);
    const original = readFileSync(path, "utf8");
    try {
      writeFileSync(path, "x".repeat(300 * 1024));
      const result = zArtifactView.parse(
        (await running.client.get(`${base}/artifact?${new URLSearchParams({ path: file.path })}`))
          .json,
      );
      expect(result.bytes).toBe(300 * 1024);
      expect(result.content.length).toBe(256 * 1024);
      expect(result.truncated).toBe(true);
      rmSync(path);
      symlinkSync("/etc/passwd", path);
      expect((await running.client.get(`${base}/artifacts`)).status).toBe(409);
    } finally {
      rmSync(path, { force: true });
      writeFileSync(path, original);
    }
  });

  it("keeps healthy bundles visible when a sibling has malformed AIR", async () => {
    const bad = join(workspace.root, "broken");
    mkdirSync(bad);
    writeFileSync(join(bad, "air.yaml"), "not: [valid");
    try {
      const reply = await running.client.get("/api/workspace");
      expect(reply.status).toBe(200);
      const view = zWorkspace.parse(reply.json);
      expect(view.bundles.map((bundle) => bundle.id)).toEqual(["payments"]);
      expect(view.issues).toEqual([expect.objectContaining({ id: "broken" })]);
    } finally {
      rmSync(bad, { recursive: true });
    }
  });
});
