import { type Operation, snakeCase } from "@anvil/air";
import { ACTION_VERB_WORDS } from "./classify.js";

/**
 * Whole-spec naming-dialect inference. Real specs name their operations in one
 * house style — Twilio is Verb+Resource, Slack is `namespace.method`, Stripe and
 * HubSpot autogenerate ids that embed the path, Zoom uses bare resource nouns.
 * Classifying that style ONCE over all operations jointly (instead of 300
 * independent per-op guesses) lets the compiler adjust how much it trusts every
 * declared operationId in the corpus, coherently.
 *
 * Deliberately conservative: the report tunes `name.quality` confidence only.
 * It never changes a derived name — names are validated against real reference
 * MCP surfaces and stay exactly as the per-op pass derived them.
 */

export type NamingDialect =
  | "verb_first"
  | "namespace_method"
  | "path_derived"
  | "resource_only"
  | "mixed";

export type NamingCasing = "camel" | "snake" | "pascal" | "kebab" | "mixed";

export interface DialectReport {
  dialect: NamingDialect;
  casing: NamingCasing;
  /** 0..1: the share of operations backing the classification. */
  confidence: number;
  /** How many operations were examined. */
  sampled: number;
  /** Human-readable evidence behind the classification. */
  signals: string[];
}

export interface DialectSample {
  operationId?: string;
  path?: string;
  method?: string;
}

/** Below this many operations the sample is too small to call a house style. */
export const MIN_SAMPLE = 5;

/** Majority threshold: a dialect must back more than half the operations. */
const MAJORITY = 0.5;

/**
 * Verbs that mark an id as verb-first. The classifier's action vocabulary
 * (`ACTION_VERB_WORDS` — imported, not duplicated) is the base, extended with
 * the plain REST/CRUD verbs the classifier expresses via HTTP methods rather
 * than keywords.
 */
const REST_VERBS = [
  "get",
  "list",
  "create",
  "update",
  "delete",
  "fetch",
  "retrieve",
  "read",
  "set",
  "add",
  "remove",
  "destroy",
  "purge",
  "drop",
  "put",
  "post",
  "patch",
  "head",
  "upsert",
  "insert",
  "modify",
  "replace",
  "enable",
  "disable",
  "archive",
  "restore",
  "upload",
  "close",
  "open",
  "assign",
  "attach",
  "detach",
  "copy",
  "move",
  "mark",
  "sync",
  "import",
  "count",
  "describe",
];

const KNOWN_VERBS: ReadonlySet<string> = new Set(
  [...Object.values(ACTION_VERB_WORDS).flat(), ...REST_VERBS]
    .map((v) => snakeCase(v).split("_")[0] ?? "")
    .filter((v) => v.length > 0),
);

/** Lowercase-alphanumeric normalization used for path-vs-id containment. */
const normalizeToken = (s: string): string => s.toLowerCase().replace(/[^a-z0-9]/g, "");

/** Dotted last path segments that are file extensions, not RPC namespaces (Twilio `.json`). */
const FILE_EXTENSIONS = new Set([
  "json",
  "xml",
  "html",
  "txt",
  "csv",
  "yaml",
  "yml",
  "atom",
  "rss",
]);

/** Slack-style `namespace.method` in the last path segment (`/chat.postMessage`). */
function isNamespacePath(path?: string): boolean {
  if (!path) return false;
  const segments = path.split("/").filter(Boolean);
  const last = segments[segments.length - 1];
  if (!last || last.startsWith("{")) return false;
  const dot = last.indexOf(".");
  if (dot <= 0 || dot === last.length - 1) return false;
  const ext = last.slice(last.lastIndexOf(".") + 1).toLowerCase();
  return !FILE_EXTENSIONS.has(ext);
}

/** Dot-namespaced RPC-style operationId (`admin.conversations.archive`). */
function isNamespaceId(operationId?: string): boolean {
  if (!operationId) return false;
  return /^[A-Za-z][\w-]*(\.[\w-]+)+$/.test(operationId);
}

/** Does the id start with a known action verb (`createRefund`, `list_users`)? */
function isVerbFirstId(operationId?: string): boolean {
  if (!operationId) return false;
  const first = snakeCase(operationId).split("_")[0];
  return first !== undefined && KNOWN_VERBS.has(first);
}

/**
 * How much of the operation's own path+method the operationId textually embeds
 * (both sides normalized to lowercase alphanumerics). Autogenerated ids score
 * high: Stripe `PostChargesChargeCapture` for `POST /v1/charges/{charge}/capture`,
 * HubSpot `get-/crm/v3/objects/0-3_getPage`. A human-authored `createRefund`
 * for `POST /payments/{id}/refunds` scores near zero.
 */
function pathDerivedCoverage(sample: DialectSample): number {
  if (!sample.operationId || !sample.path) return 0;
  const idNorm = normalizeToken(sample.operationId);
  if (!idNorm) return 0;
  const tokens = sample.path.split("/").map(normalizeToken).filter(Boolean);
  if (sample.method) tokens.push(normalizeToken(sample.method));
  if (tokens.length < 2) return 0;
  const hits = tokens.filter((t) => idNorm.includes(t)).length;
  return hits / tokens.length;
}

/** An id is "path-derived" when it embeds most of its own path+method tokens. */
const PATH_DERIVED_COVERAGE = 0.6;
const isPathDerivedId = (sample: DialectSample): boolean =>
  pathDerivedCoverage(sample) >= PATH_DERIVED_COVERAGE;

/** Bare resource noun ids (Zoom: `meetings`, `meeting`, `meetingCreate`). */
function isResourceOnlyId(operationId?: string): boolean {
  if (!operationId) return false;
  const words = snakeCase(operationId).split("_").filter(Boolean);
  if (words.length === 0 || words.length > 2) return false;
  return !KNOWN_VERBS.has(words[0] as string);
}

/** The casing of one id, or undefined when it carries no casing signal. */
function casingOf(operationId: string): Exclude<NamingCasing, "mixed"> | undefined {
  const hasUpper = /[A-Z]/.test(operationId);
  const hasUnderscore = operationId.includes("_");
  const hasHyphen = operationId.includes("-");
  if (hasUnderscore && !hasHyphen && !hasUpper) return "snake";
  if (hasHyphen && !hasUnderscore && !hasUpper) return "kebab";
  if (!hasUnderscore && !hasHyphen && hasUpper) {
    return /^[A-Z]/.test(operationId) ? "pascal" : "camel";
  }
  // A bare lowercase word (no signal) or a genuinely mixed style.
  return undefined;
}

/**
 * Classify the naming dialect of a whole operation set jointly. Fewer than
 * `MIN_SAMPLE` operations returns `mixed` with confidence 0 — too small a
 * corpus to call a house style, and no adjustment is applied downstream.
 */
export function detectNamingDialect(ops: DialectSample[]): DialectReport {
  const sampled = ops.length;
  if (sampled < MIN_SAMPLE) {
    return {
      dialect: "mixed",
      casing: "mixed",
      confidence: 0,
      sampled,
      signals: [`fewer than ${MIN_SAMPLE} operations — too small a sample to infer a house style`],
    };
  }

  let namespace = 0;
  let pathDerived = 0;
  let verbFirst = 0;
  let resourceOnly = 0;
  const casingVotes = new Map<Exclude<NamingCasing, "mixed">, number>();
  for (const op of ops) {
    if (isNamespacePath(op.path) || isNamespaceId(op.operationId)) namespace += 1;
    if (isPathDerivedId(op)) pathDerived += 1;
    if (isVerbFirstId(op.operationId)) verbFirst += 1;
    if (isResourceOnlyId(op.operationId)) resourceOnly += 1;
    const casing = op.operationId ? casingOf(op.operationId) : undefined;
    if (casing) casingVotes.set(casing, (casingVotes.get(casing) ?? 0) + 1);
  }

  // Precedence is specificity: a Slack-shaped spec also scores high on
  // path-derived containment (the id IS the dotted path), and a Stripe-shaped
  // autogen id also starts with an HTTP verb — the more specific signal wins.
  const counts: Array<[NamingDialect, number, string]> = [
    [
      "namespace_method",
      namespace,
      `${namespace}/${sampled} operations use dotted namespace.method naming`,
    ],
    [
      "path_derived",
      pathDerived,
      `${pathDerived}/${sampled} operationIds textually embed their own path+method (autogenerated)`,
    ],
    [
      "verb_first",
      verbFirst,
      `${verbFirst}/${sampled} operationIds start with a known action verb`,
    ],
    [
      "resource_only",
      resourceOnly,
      `${resourceOnly}/${sampled} operationIds are bare resource nouns`,
    ],
  ];

  const casingTotal = [...casingVotes.values()].reduce((a, b) => a + b, 0);
  let casing: NamingCasing = "mixed";
  for (const [name, votes] of casingVotes) {
    if (casingTotal > 0 && votes / casingTotal > MAJORITY) casing = name;
  }

  const signals = counts
    .filter(([, n]) => n > 0)
    .sort((a, b) => b[1] - a[1])
    .map(([, , signal]) => signal);

  const winner = counts.find(([, n]) => n / sampled > MAJORITY);
  if (winner) {
    const [dialect, n, signal] = winner;
    return {
      dialect,
      casing,
      confidence: Number((n / sampled).toFixed(2)),
      sampled,
      // Lead with the winning evidence.
      signals: [signal, ...signals.filter((s) => s !== signal)],
    };
  }

  const maxShare = Math.max(...counts.map(([, n]) => n)) / sampled;
  return {
    dialect: "mixed",
    casing,
    confidence: Number(Math.min(1, Math.max(0, 1 - maxShare)).toFixed(2)),
    sampled,
    signals: signals.length > 0 ? signals : ["no dominant naming style detected"],
  };
}

/** Path-derived autogen ids are semantically empty — distrust them corpus-wide. */
const PATH_DERIVED_PENALTY = 0.15;
/** A coherent human-authored dialect earns a small corpus-wide trust boost. */
const COHERENT_DIALECT_BOOST = 0.05;
const COHERENT_DIALECT_MIN_CONFIDENCE = 0.7;
const BOOST_CAP = 0.95;

/**
 * Fold the whole-spec dialect back into each operation's `name.quality`
 * evidence claim. This adjusts CONFIDENCE only, never a name:
 *   - `path_derived`: every declared operationId in the corpus is an autogen
 *     artifact of its own path — subtract 0.15 (generalizes the per-dialect
 *     "semantically-empty autogen id" fixes corpus-wide).
 *   - coherent `verb_first` / `namespace_method` (confidence >= 0.7): add 0.05,
 *     capped at 0.95 — a consistent house style is corroborating evidence.
 * Small samples (report confidence 0 via `detectNamingDialect`) adjust nothing.
 */
export function applyDialectAdjustment(operations: Operation[], report: DialectReport): void {
  if (report.sampled < MIN_SAMPLE) return;
  const penalize = report.dialect === "path_derived";
  const boost =
    (report.dialect === "verb_first" || report.dialect === "namespace_method") &&
    report.confidence >= COHERENT_DIALECT_MIN_CONFIDENCE;
  if (!penalize && !boost) return;

  for (const op of operations) {
    const claim = op.evidence.claims.find((c) => c.predicate === "name.quality");
    if (!claim || typeof claim.confidence !== "number") continue;
    if (penalize) {
      claim.confidence = Math.max(0, claim.confidence - PATH_DERIVED_PENALTY);
      claim.note = [claim.note, `whole-spec dialect "${report.dialect}": ids look autogenerated`]
        .filter(Boolean)
        .join("; ");
    } else {
      claim.confidence = Math.max(
        claim.confidence,
        Math.min(BOOST_CAP, claim.confidence + COHERENT_DIALECT_BOOST),
      );
      claim.note = [claim.note, `coherent whole-spec dialect "${report.dialect}"`]
        .filter(Boolean)
        .join("; ");
    }
  }
}
