// Bundle the deployable runtime ONCE, at Anvil's own build.
//
// `src/serve.ts` is the thin Cloud Run server every generated bundle ships as
// `runtime/server.js` and `deploy/runtime/server.js`. This script produces the
// self-contained file — Anvil's own packages, the MCP SDK, zod, everything but
// Node's built-ins inlined — that `anvil compile` then COPIES into each bundle.
//
// This is the exact esbuild configuration `@anvil/generators` used to run on
// every compile (`deployRuntime`), moved to the one place where it is sound:
// here, `node_modules` is real and `@anvil/runtime` resolves. Inside a
// single-file distribution of the CLI it did not, which is what made
// `anvil compile` impossible from a compiled binary. Moving the bundling here
// also takes esbuild — and its native platform binary — out of the CLI's
// shipped dependency closure entirely.
//
// Two files come out:
//   dist/serve.js          the runnable server (what a bundle ships)
//   dist/serve-bundle.js   the same bytes as an importable string, plus their
//                          sha256 and the package version, so the generator
//                          needs no filesystem read to find its own artifact —
//                          a plain import that survives any packer.
import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = join(here, "..");
const dist = join(pkgRoot, "dist");
const pkg = JSON.parse(readFileSync(join(pkgRoot, "package.json"), "utf8"));

mkdirSync(dist, { recursive: true });

const result = await build({
  entryPoints: [join(pkgRoot, "src", "serve.ts")],
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node22",
  treeShaking: true,
  minify: true,
  legalComments: "none",
  // A few transitive CommonJS modules use dynamic require for Node built-ins.
  // ESM has no ambient require, so provide a local createRequire seam while
  // keeping every third-party package bundled into this single file.
  banner: {
    js: 'import{createRequire as __anvilCreateRequire}from"node:module";const require=__anvilCreateRequire(import.meta.url);',
  },
  sourcemap: false,
  write: false,
  logLevel: "silent",
});

const serve = result.outputFiles[0]?.text;
if (!serve) throw new Error("build-serve: esbuild produced no output for src/serve.ts");
// The bundle must be self-contained: a bare `@anvil/*` or SDK import left in
// it would mean a bundle only runs where those packages are installed — the
// exact condition this build exists to remove.
const external = serve.match(/from\s*"(@anvil\/[^"]+|@modelcontextprotocol\/[^"]+)"/);
if (external) {
  throw new Error(`build-serve: bundle still imports ${external[1]}; it is not self-contained`);
}

const sha256 = createHash("sha256").update(serve).digest("hex");
const version = String(pkg.version);

writeFileSync(join(dist, "serve.js"), serve);
writeFileSync(
  join(dist, "serve-bundle.js"),
  [
    "// Generated by scripts/build-serve.mjs — the prebuilt runtime as an importable string.",
    `export const SERVE_BUNDLE = ${JSON.stringify(serve)};`,
    `export const SERVE_BUNDLE_SHA256 = ${JSON.stringify(sha256)};`,
    `export const SERVE_BUNDLE_VERSION = ${JSON.stringify(version)};`,
    "",
  ].join("\n"),
);
writeFileSync(
  join(dist, "serve-bundle.d.ts"),
  [
    "/** The self-contained deployable runtime (`dist/serve.js`), as text. */",
    "export declare const SERVE_BUNDLE: string;",
    "/** sha256 of SERVE_BUNDLE — the runtime's own content identity. */",
    "export declare const SERVE_BUNDLE_SHA256: string;",
    "/** The @anvil/mcp-runtime version that built it. */",
    "export declare const SERVE_BUNDLE_VERSION: string;",
    "",
  ].join("\n"),
);

console.log(
  `build-serve: dist/serve.js ${(serve.length / 1024).toFixed(0)} KB sha256 ${sha256.slice(0, 12)}…`,
);
