import {
  type AirDocument,
  agentPropKey,
  idempotencyModeUsesCarrier,
  type Operation,
  operationInputSchema,
  operationSafetyInputKeys,
} from "@anvil/air";
import { MCP_RESERVED } from "@anvil/generators";
import { businessInputCliFlag } from "./explain.js";
import { EXIT_CODES } from "./tool-cli.js";

/**
 * The `bin/<connector>` CLI `anvil package harness` writes (docs/branchyard.md):
 * one dependency-free Node script, in gateway mode only. It keeps the
 * generated CLI's grammar (`<connector> <resource> <verb> --flag value`,
 * `--help`, `--schema`, `--dry-run`, `--confirm`, `--idempotency-key`) and
 * exit codes, and sends every call to `ANVIL_GATEWAY_URL` over MCP Streamable
 * HTTP with the bearer read from `ANVIL_GATEWAY_TOKEN_FILE` on every call —
 * the same wire the generated CLI's `--mcp <url>` path speaks (ADR-0023).
 * It has no direct mode, so it never reads an upstream credential.
 *
 * Self-contained so a harness home can hold it without `@anvil/*` packages:
 * it needs Node.js 18 or later (global `fetch`) and nothing else.
 */

interface HarnessInput {
  flag: string;
  key: string;
  type: string;
  required: boolean;
  description?: string;
}

interface HarnessOperation {
  id: string;
  command: string[];
  tool: string;
  title: string;
  description: string;
  effect: string;
  risk: string;
  confirm: { required: boolean; key?: string; reason?: string };
  idempotency: { mode: string; key?: string };
  inputs: HarnessInput[];
  wholeBody: boolean;
  schema: unknown;
}

function inputsOf(op: Operation): HarnessInput[] {
  const out: HarnessInput[] = [];
  for (const param of op.input.params) {
    const flag = businessInputCliFlag(op, param.in, param.name);
    if (!flag) continue;
    out.push({
      flag,
      key: agentPropKey(param),
      type: String((param.schema as { type?: unknown }).type ?? "string"),
      required: param.required,
      ...(param.description ? { description: param.description } : {}),
    });
  }
  if (op.input.body?.projection === "fields") {
    for (const field of op.input.body.fields) {
      const flag = businessInputCliFlag(op, "body", field.name);
      if (!flag) continue;
      out.push({
        flag,
        key: agentPropKey(field),
        type: String((field.schema as { type?: unknown }).type ?? "string"),
        required: field.required,
        ...(field.description ? { description: field.description } : {}),
      });
    }
  }
  return out;
}

export function harnessOperations(air: AirDocument): HarnessOperation[] {
  return air.operations
    .filter((op) => op.state === "approved")
    .map((op) => {
      const safety = operationSafetyInputKeys(op);
      return {
        id: op.id,
        command: op.cli.command.split(" ").slice(1),
        tool: op.mcp.toolName,
        title: op.displayName,
        description: op.description || op.displayName,
        effect: op.effect.kind,
        risk: op.effect.risk,
        confirm: {
          required: op.confirmation.required,
          ...(op.confirmation.required ? { key: safety.confirm } : {}),
          ...(op.confirmation.reason ? { reason: op.confirmation.reason } : {}),
        },
        idempotency: {
          mode: op.idempotency.mode,
          ...(idempotencyModeUsesCarrier(op.idempotency.mode)
            ? { key: safety.idempotencyKey }
            : {}),
        },
        inputs: inputsOf(op),
        wholeBody: op.input.body !== undefined && op.input.body.projection !== "fields",
        schema: op.input.schema ?? operationInputSchema(op),
      };
    });
}

/** The full text of `bin/<connector>`. */
export function harnessCliSource(air: AirDocument, connector: string): string {
  const data = {
    connector,
    service: {
      id: air.service.id,
      title: air.service.displayName ?? air.service.id,
      version: air.service.version,
    },
    dryRunArg: MCP_RESERVED.dryRun,
    exitCodes: EXIT_CODES,
    operations: harnessOperations(air),
  };
  return `#!/usr/bin/env node
// Generated by Anvil (anvil package harness). Do not edit — regenerate from AIR.
// The ${connector} connector CLI, gateway mode only: every call goes to
// ANVIL_GATEWAY_URL over MCP Streamable HTTP, with the bearer read from the file
// ANVIL_GATEWAY_TOKEN_FILE names on every call. Requires Node.js 18+; no packages.
"use strict";

const SPEC = ${JSON.stringify(data, null, 2)};
${RUNTIME}`;
}

/** The CLI body, identical for every connector. Plain JavaScript (no build step). */
const RUNTIME = String.raw`
const { readFileSync } = require("node:fs");

const BOOLEAN_FLAGS = new Set(["help", "schema", "dry-run", "confirm", "json"]);
const PROTOCOL_VERSION = "2025-06-18";

function out(text) { process.stdout.write(text + "\n"); }
function err(text) { process.stderr.write(text + "\n"); }

function parseArgs(argv) {
  const positionals = [];
  const flags = {};
  for (let i = 0; i < argv.length; i++) {
    const token = argv[i];
    if (token.startsWith("--")) {
      const body = token.slice(2);
      const eq = body.indexOf("=");
      if (eq >= 0) flags[body.slice(0, eq)] = body.slice(eq + 1);
      else if (BOOLEAN_FLAGS.has(body) || i + 1 >= argv.length || argv[i + 1].startsWith("--")) flags[body] = true;
      else flags[body] = argv[++i];
    } else positionals.push(token);
  }
  return { positionals, flags };
}

function refusal(code, message, operation, extra) {
  err(JSON.stringify({ error: Object.assign({ code, message, retryable: false, safe_to_retry: false, operation: operation || SPEC.service.id, trace_id: "" }, extra || {}) }, null, 2));
  return SPEC.exitCodes[code] || 1;
}

function serviceHelp() {
  const lines = [SPEC.connector + " — " + SPEC.service.title + " through the Anvil gateway", "", "Commands:"];
  for (const op of SPEC.operations) {
    const flags = op.inputs.filter((i) => i.required).map((i) => i.flag + " <" + i.type + ">").join(" ");
    lines.push("  " + SPEC.connector + " " + op.command.join(" ") + (flags ? " " + flags : "") + "    " + op.effect + (op.confirm.required ? ", needs --confirm" : "") + " — " + op.title);
  }
  lines.push("", "Every command takes --help, --schema, --dry-run, and --input <file.json>.", "Gateway: ANVIL_GATEWAY_URL and ANVIL_GATEWAY_TOKEN_FILE (set by Branchyard).");
  return lines.join("\n");
}

function opHelp(op) {
  const lines = [SPEC.connector + " " + op.command.join(" ") + " — " + op.title, "", op.description, "", "Operation: " + op.id + " (" + op.effect + ", risk " + op.risk + ")"];
  if (op.confirm.required) lines.push("Needs --confirm" + (op.confirm.reason ? ": " + op.confirm.reason : "."));
  if (op.idempotency.key) lines.push("Takes --idempotency-key <key>; reuse it to retry the same intent.");
  lines.push("", "Flags:");
  for (const input of op.inputs) lines.push("  " + input.flag + " <" + input.type + ">" + (input.required ? " (required)" : "") + (input.description ? "  " + input.description : ""));
  if (op.wholeBody) lines.push("  --body <json>  the request body");
  lines.push("  --dry-run  preview the request; nothing is sent upstream", "  --schema   print the input JSON Schema");
  return lines.join("\n");
}

function matchOperation(positionals) {
  let best;
  for (const op of SPEC.operations) {
    if (op.command.length > positionals.length) continue;
    if (op.command.every((part, i) => positionals[i] === part) && (!best || op.command.length > best.command.length)) best = op;
  }
  return best;
}

function coerce(raw, type) {
  if (raw === true) return true;
  switch (type) {
    case "integer": return Number.parseInt(raw, 10);
    case "number": return Number(raw);
    case "boolean": return raw === "true";
    case "array":
    case "object": return JSON.parse(raw);
    default: return raw;
  }
}

function sseMessages(text) {
  const outMessages = [];
  let data = [];
  for (const line of text.split(/\r?\n/).concat([""])) {
    if (line.startsWith("data:")) data.push(line.slice(5).replace(/^ /, ""));
    else if (line === "" && data.length > 0) {
      try { outMessages.push(JSON.parse(data.join("\n"))); } catch (_e) { /* not JSON-RPC */ }
      data = [];
    }
  }
  return outMessages;
}

class GatewayError extends Error {
  constructor(code, message) { super(message); this.code = code; }
}

async function send(url, method, body, headers) {
  try {
    return await fetch(url, { method, headers, body: body === undefined ? undefined : JSON.stringify(body), signal: AbortSignal.timeout(60000) });
  } catch (_e) {
    throw new GatewayError("upstream_unavailable", "The Anvil gateway could not be reached.");
  }
}

async function rpc(url, id, method, params, headers) {
  const response = await send(url, "POST", { jsonrpc: "2.0", id, method, params }, headers);
  if (response.status === 401 || response.status === 403) {
    throw new GatewayError(response.status === 401 ? "auth_required" : "permission_denied", "The Anvil gateway refused this turn's token (HTTP " + response.status + ").");
  }
  if (response.status >= 400) throw new GatewayError("upstream_unavailable", "The Anvil gateway answered HTTP " + response.status + ".");
  const text = await response.text();
  let messages = [];
  try {
    messages = (response.headers.get("content-type") || "").startsWith("text/event-stream") ? sseMessages(text) : [].concat(text.trim() ? JSON.parse(text) : []);
  } catch (_e) { messages = []; }
  for (const message of messages) {
    if (message && message.id === id) {
      if (message.error) throw new GatewayError("unsupported_operation", "The Anvil gateway refused the request: " + String(message.error.message || "unknown error").slice(0, 300));
      return { result: message.result, response };
    }
  }
  throw new GatewayError("upstream_unavailable", "The Anvil gateway sent no response to " + method + ".");
}

async function callGateway(op, args) {
  const url = (process.env.ANVIL_GATEWAY_URL || "").trim();
  if (!url) throw new GatewayError("validation_error", "ANVIL_GATEWAY_URL is not set; this CLI only calls through the Anvil gateway.");
  const tokenFile = (process.env.ANVIL_GATEWAY_TOKEN_FILE || "").trim();
  let token = "";
  try { token = tokenFile ? readFileSync(tokenFile, "utf8").trim() : ""; } catch (_e) { token = ""; }
  if (!token) throw new GatewayError("auth_required", tokenFile ? "The gateway token file is missing, unreadable, or empty." : "ANVIL_GATEWAY_TOKEN_FILE is not set.");
  const connector = (process.env.ANVIL_GATEWAY_CONNECTOR || "").trim() || SPEC.connector;
  const headers = { "content-type": "application/json", accept: "application/json, text/event-stream", authorization: "Bearer " + token };
  const init = await rpc(url, 1, "initialize", { protocolVersion: PROTOCOL_VERSION, capabilities: {}, clientInfo: { name: "anvil-harness-cli/" + SPEC.connector, version: "1" } }, headers);
  const session = init.response.headers.get("mcp-session-id");
  if (session) headers["mcp-session-id"] = session;
  headers["mcp-protocol-version"] = (init.result && init.result.protocolVersion) || PROTOCOL_VERSION;
  try {
    await send(url, "POST", { jsonrpc: "2.0", method: "notifications/initialized" }, headers);
    const call = await rpc(url, 2, "tools/call", { name: connector + "__" + op.tool, arguments: args }, headers);
    return call.result;
  } finally {
    if (session) await send(url, "DELETE", undefined, headers).catch(() => undefined);
  }
}

async function main(argv) {
  const { positionals, flags } = parseArgs(argv);
  if (positionals.length === 0 || positionals[0] === "help") { out(serviceHelp()); return 0; }
  const op = matchOperation(positionals);
  if (!op) {
    err("Unknown command: " + positionals.join(" ") + "\nTry " + SPEC.connector + " --help.");
    return 1;
  }
  if (flags.help === true) { out(opHelp(op)); return 0; }
  if (flags.schema === true) { out(JSON.stringify(op.schema, null, 2)); return 0; }
  const known = new Set(["help", "schema", "dry-run", "confirm", "json", "input", "idempotency-key"].concat(op.inputs.map((i) => i.flag.slice(2))).concat(op.wholeBody ? ["body"] : []));
  const unknown = Object.keys(flags).filter((f) => !known.has(f));
  if (unknown.length > 0) return refusal("validation_error", "Unknown flag(s): " + unknown.map((f) => "--" + f).join(", ") + ". See " + SPEC.connector + " " + op.command.join(" ") + " --help.", op.id);
  let args = {};
  try {
    if (typeof flags.input === "string") args = JSON.parse(readFileSync(flags.input, "utf8"));
    for (const input of op.inputs) {
      const value = flags[input.flag.slice(2)];
      if (value !== undefined) args[input.key] = coerce(value, input.type);
    }
    if (op.wholeBody && typeof flags.body === "string") args.body = JSON.parse(flags.body);
  } catch (e) {
    return refusal("validation_error", "Invalid input: " + (e && e.message ? e.message : String(e)), op.id);
  }
  if (flags.confirm === true && op.confirm.key) args[op.confirm.key] = true;
  if (typeof flags["idempotency-key"] === "string") {
    if (!op.idempotency.key) return refusal("validation_error", "This operation takes no idempotency key.", op.id);
    args[op.idempotency.key] = flags["idempotency-key"];
  }
  if (flags["dry-run"] === true) args[SPEC.dryRunArg] = true;
  let result;
  try {
    result = await callGateway(op, args);
  } catch (e) {
    if (e instanceof GatewayError) return refusal(e.code, e.message, op.id);
    throw e;
  }
  const text = ((result && result.content) || []).filter((c) => c.type === "text").map((c) => c.text)[0] || JSON.stringify((result && result.structuredContent) || result, null, 2);
  if (result && result.isError) {
    err(text);
    try { return SPEC.exitCodes[JSON.parse(text).error.code] || 7; } catch (_e) { return 7; }
  }
  out(text);
  return 0;
}

main(process.argv.slice(2)).then((code) => { process.exitCode = code; }, (e) => {
  err(JSON.stringify({ error: { code: "unknown_upstream_error", message: String(e && e.message ? e.message : e) } }));
  process.exitCode = 7;
});
`;
