/**
 * The dry-run plan, specified once and emitted four times.
 *
 * `anvil run --dry-run` and the MCP server's reserved `anvil_dry_run` argument
 * both come back with the runtime's `DryRunPlan` (packages/runtime/src/executor.ts):
 * the request that WOULD have been sent, after every local gate has run and
 * before anything reaches the wire, with credential-bearing headers redacted.
 * The generated clients do not share the runtime's executor, so each carries
 * its own transcription of that plan here — the same fields, the same key
 * spelling, the same redaction set — and `sdk-compile.test.ts` proves the four
 * agree byte-for-byte on what they would have sent.
 *
 * Two rules every transcription keeps:
 *   - A dry run never resolves a credential. The runtime short-circuits before
 *     auth, so a plan can be read without a token, a refresh, or a token
 *     exchange ever happening — and the plan carries no bearer to redact.
 *   - Everything above it still runs: the wire gate, the confirmation gate,
 *     the idempotency gate. A dry run of a call the SDK would refuse is the
 *     same refusal, not a plan.
 */

/** The runtime's own redaction set, `REDACT` in executor.ts. */
export const DRY_RUN_REDACTED_HEADERS = [
  "authorization",
  "x-api-key",
  "proxy-authorization",
  "cookie",
] as const;

const j = (value: unknown): string => JSON.stringify(value);

/** `dry-run.ts` — the plan builder `invoke.ts` returns from instead of sending. */
export function typescriptDryRunModule(): string {
  return `// Generated by Anvil. Do not edit — regenerate from AIR.
// The dry-run plan: what a call WOULD send, after every local gate has run and
// before anything reaches the wire. The same shape \`anvil run --dry-run\`
// prints and the MCP server returns for \`anvil_dry_run\`, so a call can be
// previewed on any surface and read the same way.
import type { BuiltRequest } from "./invoke.js";
import type { OperationSpec } from "./spec.js";

export interface DryRunPlan {
  operation: string;
  method: string;
  url: string;
  /** Request headers, with credential-bearing values redacted to "***". */
  headers: Record<string, string>;
  /** The decoded body, or the raw text when it is not JSON. Absent when none. */
  body?: unknown;
  idempotencyKeyPresent: boolean;
  /** Whether the client would retry, and how many attempts it would spend. */
  retryPlan: { enabled: boolean; maxAttempts: number };
  confirmationRequired: boolean;
}

/** Header names whose values never leave a plan — the runtime's own set. */
const REDACTED_HEADERS = new Set(${j([...DRY_RUN_REDACTED_HEADERS])});

/** Build the plan for a request that will not be sent. */
export function dryRunPlan(
  spec: OperationSpec,
  request: BuiltRequest,
  idempotencyKeyPresent: boolean,
  safeToRetry: boolean,
): DryRunPlan {
  const headers: Record<string, string> = {};
  for (const [name, value] of Object.entries(request.headers)) {
    headers[name] = REDACTED_HEADERS.has(name.toLowerCase()) ? "***" : value;
  }
  let body: unknown;
  if (request.body !== undefined) {
    try {
      body = JSON.parse(request.body) as unknown;
    } catch {
      body = request.body;
    }
  }
  return {
    operation: spec.id,
    method: request.method,
    url: request.url,
    headers,
    ...(body !== undefined ? { body } : {}),
    idempotencyKeyPresent,
    retryPlan: { enabled: safeToRetry, maxAttempts: safeToRetry ? spec.retry.maxAttempts : 1 },
    confirmationRequired: spec.confirmation.required,
  };
}
`;
}

/** `_dry_run.py` — the plan builder `_invoke.py` returns from instead of sending. */
export function pythonDryRunModule(): string {
  return `"""Generated by Anvil. Do not edit — regenerate from AIR.

The dry-run plan: what a call WOULD send, after every local gate has run and
before anything reaches the wire. The same shape 'anvil run --dry-run' prints
and the MCP server returns for 'anvil_dry_run', so a call can be previewed on
any surface and read the same way.
"""

import json
from typing import Any, Dict

#: Header names whose values never leave a plan — the runtime's own set.
REDACTED_HEADERS = frozenset(${j([...DRY_RUN_REDACTED_HEADERS])
    .replace(/^\[/, "(")
    .replace(/\]$/, ")")})


def dry_run_plan(
    spec: Any, request: Dict[str, Any], idempotency_key_present: bool, safe_to_retry: bool
) -> Dict[str, Any]:
    """Build the plan for a request that will not be sent."""
    headers = {
        name: ("***" if name.lower() in REDACTED_HEADERS else value)
        for name, value in request["headers"].items()
    }
    plan: Dict[str, Any] = {
        "operation": spec.id,
        "method": request["method"],
        "url": request["url"],
        "headers": headers,
        "idempotencyKeyPresent": idempotency_key_present,
        "retryPlan": {
            "enabled": safe_to_retry,
            "maxAttempts": spec.retry["maxAttempts"] if safe_to_retry else 1,
        },
        "confirmationRequired": bool(spec.confirmation["required"]),
    }
    raw = request.get("body")
    if raw is not None:
        text = raw.decode("utf-8", "replace") if isinstance(raw, bytes) else str(raw)
        try:
            plan["body"] = json.loads(text)
        except ValueError:
            plan["body"] = text
    return plan
`;
}

/** `dryrun.go` — the plan builder `invoke.go` returns from instead of sending. */
export function goDryRunFile(pkg: string): string {
  return `// Generated by Anvil. Do not edit — regenerate from AIR.
//
// The dry-run plan: what a call WOULD send, after every local gate has run and
// before anything reaches the wire. The same shape \`anvil run --dry-run\`
// prints and the MCP server returns for \`anvil_dry_run\`, so a call can be
// previewed on any surface and read the same way.

package ${pkg}

import (
	"encoding/json"
	"strings"
)

// redactedHeaders are header names whose values never leave a plan — the
// runtime's own set.
var redactedHeaders = map[string]bool{
${[...DRY_RUN_REDACTED_HEADERS].map((name) => `\t${j(name)}: true,`).join("\n")}
}

// withoutCredential is the configuration a dry run builds its request under:
// a dry run never resolves a credential, exactly as the runtime's does not.
func (config clientConfig) withoutCredential() clientConfig {
	config.token = ""
	config.tokenProvider = nil
	return config
}

// dryRunPlan builds the plan for a request that will not be sent.
func dryRunPlan(spec OperationSpec, request builtRequest, idempotencyKeyPresent, safeToRetry bool) map[string]any {
	headers := map[string]any{}
	for name, value := range request.headers {
		if redactedHeaders[strings.ToLower(name)] {
			headers[name] = "***"
		} else {
			headers[name] = value
		}
	}
	maxAttempts := 1
	if safeToRetry {
		maxAttempts = spec.Retry.MaxAttempts
	}
	plan := map[string]any{
		"operation":             spec.ID,
		"method":                request.method,
		"url":                   request.url,
		"headers":               headers,
		"idempotencyKeyPresent": idempotencyKeyPresent,
		"retryPlan":             map[string]any{"enabled": safeToRetry, "maxAttempts": maxAttempts},
		"confirmationRequired":  spec.Confirmation.Required,
	}
	if len(request.body) > 0 {
		var body any
		if err := json.Unmarshal(request.body, &body); err == nil {
			plan["body"] = body
		} else {
			plan["body"] = string(request.body)
		}
	}
	return plan
}
`;
}

/** `DryRun.java` — the plan builder `Invoker` returns from instead of sending. */
export function javaDryRunFile(pkg: string): string {
  return `// Generated by Anvil. Do not edit — regenerate from AIR.
package ${pkg};

import java.util.Arrays;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * The dry-run plan: what a call WOULD send, after every local gate has run and
 * before anything reaches the wire. The same shape {@code anvil run --dry-run}
 * prints and the MCP server returns for {@code anvil_dry_run}, so a call can
 * be previewed on any surface and read the same way.
 */
final class DryRun {

  /** Header names whose values never leave a plan — the runtime's own set. */
  private static final Set<String> REDACTED_HEADERS =
      new HashSet<String>(
          Arrays.asList(${[...DRY_RUN_REDACTED_HEADERS].map((name) => j(name)).join(", ")}));

  private DryRun() {}

  /**
   * The configuration a dry run builds its request under: a dry run never
   * resolves a credential, exactly as the runtime's does not.
   */
  static Invoker.Config withoutCredential(Invoker.Config config) {
    return new Invoker.Config(
        config.baseUrl,
        config.protocolFacade,
        null,
        null,
        config.authIn,
        config.authName,
        config.authScheme,
        config.timeout,
        config.httpClient,
        config.userAgent,
        config.random);
  }

  /** Build the plan for a request that will not be sent. */
  static Map<String, Object> plan(
      OperationSpec spec, Invoker.Built built, boolean idempotencyKeyPresent, boolean safeToRetry) {
    Map<String, Object> headers = new LinkedHashMap<String, Object>();
    for (Map.Entry<String, List<String>> entry : built.request.headers().map().entrySet()) {
      headers.put(
          entry.getKey(),
          REDACTED_HEADERS.contains(entry.getKey().toLowerCase())
              ? "***"
              : String.join(", ", entry.getValue()));
    }
    Map<String, Object> retryPlan = new LinkedHashMap<String, Object>();
    retryPlan.put("enabled", safeToRetry);
    retryPlan.put("maxAttempts", safeToRetry ? spec.retry.maxAttempts : 1);
    Map<String, Object> plan = new LinkedHashMap<String, Object>();
    plan.put("operation", spec.id);
    plan.put("method", built.request.method());
    plan.put("url", built.request.uri().toString());
    plan.put("headers", headers);
    if (built.body != null) {
      Object body;
      try {
        body = Json.parse(built.body);
      } catch (RuntimeException notJson) {
        body = built.body;
      }
      plan.put("body", body);
    }
    plan.put("idempotencyKeyPresent", idempotencyKeyPresent);
    plan.put("retryPlan", retryPlan);
    plan.put("confirmationRequired", spec.confirmation.required);
    return plan;
  }
}
`;
}
