import type { SdkOperation, SdkPlan } from "./plan.js";

/**
 * Gateway mode for the generated SDKs (docs/branchyard.md, ADR-0029).
 *
 * With `ANVIL_GATEWAY_URL` set, a client sends every call to the Anvil
 * gateway over MCP Streamable HTTP instead of calling the upstream. The
 * bearer is read from the file `ANVIL_GATEWAY_TOKEN_FILE` names on every
 * call, so a token Branchyard replaces each turn is picked up without a new
 * client, and no upstream credential variable (`<SERVICE>_TOKEN` and the
 * rest) is ever read in that mode.
 *
 * The wire is the same one the CLI's `--mcp <url>` path speaks (ADR-0023):
 * `initialize`, `notifications/initialized`, one `tools/call`, then the
 * session is closed. The safety controls ride as the tool's own reserved
 * inputs (`confirm`, `idempotency_key`, `anvil_dry_run`), and the result is
 * decoded back into the same contract a direct call has: the response data,
 * the dry-run plan, or an `AnvilError` carrying the gateway's envelope.
 *
 * The tool name on the wire is `<connector>__<tool>`: a Branchyard gateway
 * mounts every bundle under its connector id, even when it serves only one.
 */

/** Wire names the gateway expects for one operation. */
interface GatewayToolRow {
  tool: string;
  /** The confirm input, present only when the operation takes one. */
  confirmKey?: string;
  /** The idempotency-key input, present only when the operation carries a key. */
  idempotencyKey?: string;
}

/** The MCP reserved argument that asks the server for a dry-run plan. */
const GATEWAY_DRY_RUN_ARG = "anvil_dry_run";
/** The MCP protocol revision a gateway client offers. The server may answer with another it supports. */
const GATEWAY_PROTOCOL_VERSION = "2025-06-18";

function gatewayToolRow(op: SdkOperation): GatewayToolRow {
  return {
    tool: op.mcpToolName,
    ...(op.confirmation.required ? { confirmKey: op.safetyKeys.confirm } : {}),
    ...(op.idempotency.carrier ? { idempotencyKey: op.safetyKeys.idempotencyKey } : {}),
  };
}

const j = (value: unknown): string => JSON.stringify(value);

function pyRow(row: GatewayToolRow): string {
  return `{"tool": ${j(row.tool)}, "confirmKey": ${row.confirmKey ? j(row.confirmKey) : "None"}, "idempotencyKey": ${row.idempotencyKey ? j(row.idempotencyKey) : "None"}}`;
}

/** `_gateway.py`: the transport plus this service's tool table. */
export function pythonGatewayModule(plan: SdkPlan): string {
  const rows = plan.operations
    .map((op) => `    ${j(op.id)}: ${pyRow(gatewayToolRow(op))},`)
    .join("\n");
  return `"""Generated by Anvil. Do not edit — regenerate from AIR.

Gateway mode. With ANVIL_GATEWAY_URL set, every call goes to the Anvil gateway
over MCP Streamable HTTP. The bearer is read from the file
ANVIL_GATEWAY_TOKEN_FILE names on every call (a token replaced each turn is
picked up), and no upstream credential variable is read.
"""

import json
import os
import urllib.error
import urllib.request
from typing import Any, Dict, List, Optional, Tuple

from .errors import ERROR_CODES, AnvilError

GATEWAY_URL_ENV_VAR = "ANVIL_GATEWAY_URL"
GATEWAY_TOKEN_FILE_ENV_VAR = "ANVIL_GATEWAY_TOKEN_FILE"
GATEWAY_CONNECTOR_ENV_VAR = "ANVIL_GATEWAY_CONNECTOR"
#: The connector id the gateway mounts this service under.
DEFAULT_CONNECTOR = ${j(plan.gateway.connector)}
PROTOCOL_VERSION = ${j(GATEWAY_PROTOCOL_VERSION)}
DRY_RUN_ARG = ${j(GATEWAY_DRY_RUN_ARG)}

#: Operation id -> the gateway tool and the safety inputs it takes.
TOOLS: Dict[str, Dict[str, Optional[str]]] = {
${rows}
}


def _flag_to_argument(flag: str) -> str:
    return flag[2:].replace("-", "_") if flag.startswith("--") else flag


class GatewayTransport(object):
    """One gateway, one caller. Holds no token: the file is read per call."""

    def __init__(
        self,
        url: str,
        token_file: Optional[str] = None,
        connector: Optional[str] = None,
        opener: Any = None,
        user_agent: str = "anvil-sdk (python)",
    ) -> None:
        self.url = url
        self._token_file = token_file
        self.connector = connector or os.environ.get(GATEWAY_CONNECTOR_ENV_VAR) or DEFAULT_CONNECTOR
        self._opener = opener
        self._user_agent = user_agent

    def _token(self, operation: str) -> str:
        path = self._token_file or os.environ.get(GATEWAY_TOKEN_FILE_ENV_VAR)
        if not path:
            raise AnvilError(
                code="auth_required",
                operation=operation,
                message="Gateway mode needs ANVIL_GATEWAY_TOKEN_FILE to name this turn's token file.",
            )
        try:
            with open(path, "r", encoding="utf-8") as handle:
                token = handle.read().strip()
        except OSError:
            raise AnvilError(
                code="auth_required",
                operation=operation,
                message="The gateway token file named by ANVIL_GATEWAY_TOKEN_FILE could not be read.",
            ) from None
        if not token:
            raise AnvilError(
                code="auth_required",
                operation=operation,
                message="The gateway token file is empty.",
            )
        return token

    def _send(
        self,
        method: str,
        body: Optional[Dict[str, Any]],
        headers: Dict[str, str],
        timeout: float,
        operation: str,
    ) -> Tuple[int, Dict[str, str], bytes]:
        data = json.dumps(body).encode("utf-8") if body is not None else None
        request = urllib.request.Request(self.url, data=data, method=method)
        for name, value in headers.items():
            request.add_header(name, value)
        send = self._opener or urllib.request.urlopen
        try:
            with send(request, timeout=timeout) as response:
                status = getattr(response, "status", None) or response.getcode()
                return status, {k.lower(): v for k, v in dict(response.headers).items()}, response.read()
        except urllib.error.HTTPError as error:
            return error.code, {k.lower(): v for k, v in dict(error.headers or {}).items()}, error.read() or b""
        except Exception:
            # Never surface the transport's own message: it can carry the URL.
            raise AnvilError(
                code="upstream_unavailable",
                operation=operation,
                message="The Anvil gateway could not be reached.",
                retryable=True,
            ) from None

    @staticmethod
    def _messages(headers: Dict[str, str], raw: bytes) -> List[Any]:
        text = raw.decode("utf-8", "replace")
        if headers.get("content-type", "").startswith("text/event-stream"):
            out: List[Any] = []
            data: List[str] = []
            for line in text.splitlines() + [""]:
                if line.startswith("data:"):
                    data.append(line[5:].lstrip(" "))
                elif line == "" and data:
                    try:
                        out.append(json.loads("\\n".join(data)))
                    except ValueError:
                        pass
                    data = []
            return out
        if not text.strip():
            return []
        parsed = json.loads(text)
        return parsed if isinstance(parsed, list) else [parsed]

    def _rpc(
        self,
        request_id: int,
        method: str,
        params: Dict[str, Any],
        headers: Dict[str, str],
        timeout: float,
        operation: str,
    ) -> Tuple[Any, Dict[str, str]]:
        status, response_headers, raw = self._send(
            "POST",
            {"jsonrpc": "2.0", "id": request_id, "method": method, "params": params},
            headers,
            timeout,
            operation,
        )
        if status in (401, 403):
            raise AnvilError(
                code="auth_required" if status == 401 else "permission_denied",
                operation=operation,
                message="The Anvil gateway refused this turn's token (HTTP %d)." % status,
            )
        if status >= 400:
            raise AnvilError(
                code="upstream_unavailable",
                operation=operation,
                message="The Anvil gateway answered HTTP %d." % status,
                retryable=status >= 500,
            )
        try:
            messages = self._messages(response_headers, raw)
        except ValueError:
            messages = []
        for message in messages:
            if isinstance(message, dict) and message.get("id") == request_id:
                if "error" in message:
                    error = message.get("error") or {}
                    raise AnvilError(
                        code="unsupported_operation",
                        operation=operation,
                        message="The Anvil gateway refused the request: %s"
                        % str(error.get("message", "unknown error"))[:300],
                    )
                return message.get("result"), response_headers
        raise AnvilError(
            code="upstream_unavailable",
            operation=operation,
            message="The Anvil gateway sent no response to %s." % method,
        )

    def call(
        self,
        spec: Any,
        payload: Dict[str, Any],
        confirm: bool,
        idempotency_key: Optional[str],
        dry_run: bool,
        timeout: float,
    ) -> Any:
        row = TOOLS.get(spec.id)
        if row is None:
            raise AnvilError(
                code="unsupported_operation",
                operation=spec.id,
                message="This operation has no gateway tool.",
            )
        arguments: Dict[str, Any] = {k: v for k, v in payload.items() if v is not None}
        if confirm and row.get("confirmKey"):
            arguments[row["confirmKey"]] = True
        if idempotency_key is not None and row.get("idempotencyKey"):
            arguments[row["idempotencyKey"]] = idempotency_key
        if dry_run:
            arguments[DRY_RUN_ARG] = True
        headers = {
            "Content-Type": "application/json",
            "Accept": "application/json, text/event-stream",
            "Authorization": "Bearer " + self._token(spec.id),
            "User-Agent": self._user_agent,
        }
        init, init_headers = self._rpc(
            1,
            "initialize",
            {
                "protocolVersion": PROTOCOL_VERSION,
                "capabilities": {},
                "clientInfo": {"name": self._user_agent, "version": "1"},
            },
            headers,
            timeout,
            spec.id,
        )
        session = init_headers.get("mcp-session-id")
        if session:
            headers["Mcp-Session-Id"] = session
        version = (init or {}).get("protocolVersion") if isinstance(init, dict) else None
        headers["Mcp-Protocol-Version"] = version or PROTOCOL_VERSION
        try:
            self._send(
                "POST",
                {"jsonrpc": "2.0", "method": "notifications/initialized"},
                headers,
                timeout,
                spec.id,
            )
            result, _ = self._rpc(
                2,
                "tools/call",
                {"name": self.connector + "__" + str(row["tool"]), "arguments": arguments},
                headers,
                timeout,
                spec.id,
            )
        finally:
            if session:
                try:
                    self._send("DELETE", None, headers, timeout, spec.id)
                except AnvilError:
                    pass
        return decode_tool_result(spec.id, result)


def decode_tool_result(operation: str, result: Any) -> Any:
    """Turn a gateway CallToolResult back into what a direct call returns or raises."""
    if not isinstance(result, dict):
        raise AnvilError(
            code="schema_mismatch", operation=operation, message="The gateway returned no tool result."
        )
    text = ""
    for item in result.get("content") or []:
        if isinstance(item, dict) and item.get("type") == "text":
            text = str(item.get("text", ""))
            break
    if result.get("isError"):
        try:
            envelope = json.loads(text).get("error") or {}
        except (ValueError, AttributeError):
            envelope = {}
        code = envelope.get("code")
        raise AnvilError(
            code=code if code in ERROR_CODES else "unknown_upstream_error",
            operation=str(envelope.get("operation") or operation),
            message=str(envelope.get("message") or text[:300] or "The gateway call failed."),
            trace_id=str(envelope.get("trace_id") or ""),
            retryable=bool(envelope.get("retryable", False)),
            safe_to_retry=bool(envelope.get("safe_to_retry", False)),
            upstream=envelope.get("upstream"),
            required_arguments=[_flag_to_argument(f) for f in envelope.get("required_flags") or []],
            details=envelope.get("details"),
        )
    structured = result.get("structuredContent")
    if isinstance(structured, dict):
        if DRY_RUN_ARG in structured:
            return structured[DRY_RUN_ARG]
        if "anvil_unvalidated" in structured:
            return structured["anvil_unvalidated"]
    try:
        return json.loads(text)
    except ValueError:
        pass
    if isinstance(structured, dict):
        return structured["result"] if list(structured.keys()) == ["result"] else structured
    return text
`;
}

/** `src/gateway.ts`: the transport plus this service's tool table. */
export function typescriptGatewayModule(plan: SdkPlan): string {
  const rows = plan.operations.map((op) => `  ${j(op.id)}: ${j(gatewayToolRow(op))},`).join("\n");
  return `// Generated by Anvil. Do not edit — regenerate from AIR.
//
// Gateway mode. With ANVIL_GATEWAY_URL set, every call goes to the Anvil
// gateway over MCP Streamable HTTP. The bearer is read from the file
// ANVIL_GATEWAY_TOKEN_FILE names on every call (a token replaced each turn is
// picked up), and no upstream credential variable is read.
import { AnvilError, type AnvilErrorCode } from "./errors.js";
import type { FetchLike } from "./invoke.js";
import type { CallOptions, OperationSpec } from "./spec.js";

export const GATEWAY_URL_ENV_VAR = "ANVIL_GATEWAY_URL";
export const GATEWAY_TOKEN_FILE_ENV_VAR = "ANVIL_GATEWAY_TOKEN_FILE";
export const GATEWAY_CONNECTOR_ENV_VAR = "ANVIL_GATEWAY_CONNECTOR";
/** The connector id the gateway mounts this service under. */
export const DEFAULT_CONNECTOR = ${j(plan.gateway.connector)};
const PROTOCOL_VERSION = ${j(GATEWAY_PROTOCOL_VERSION)};
const DRY_RUN_ARG = ${j(GATEWAY_DRY_RUN_ARG)};
const KNOWN_CODES: ReadonlySet<string> = new Set(${j(plan.errorCodes)});

/** Operation id -> the gateway tool and the safety inputs it takes. */
export const GATEWAY_TOOLS: Record<string, { tool: string; confirmKey?: string; idempotencyKey?: string }> = {
${rows}
};

export interface GatewayOptions {
  url: string;
  /** Overrides ANVIL_GATEWAY_TOKEN_FILE. */
  tokenFile?: string;
  /** Supplies the bearer per call instead of a file (runtimes without a filesystem). */
  tokenProvider?: () => Promise<string>;
  /** Overrides ANVIL_GATEWAY_CONNECTOR and the compiled default. */
  connector?: string;
  fetchImpl: FetchLike;
  timeoutMs: number;
  userAgent: string;
}

type Env = Record<string, string | undefined> | undefined;

function processEnv(): Env {
  return (globalThis as { process?: { env?: Record<string, string | undefined> } }).process?.env;
}

function refuse(code: AnvilErrorCode, operation: string, message: string, retryable = false): AnvilError {
  return new AnvilError({ code, operation, traceId: "", message, retryable });
}

async function readToken(options: GatewayOptions, operation: string): Promise<string> {
  if (options.tokenProvider) return options.tokenProvider();
  const path = options.tokenFile ?? processEnv()?.[GATEWAY_TOKEN_FILE_ENV_VAR];
  if (!path) {
    throw refuse(
      "auth_required",
      operation,
      "Gateway mode needs ANVIL_GATEWAY_TOKEN_FILE to name this turn's token file.",
    );
  }
  let text: string;
  try {
    const specifier = "node:fs/promises";
    const fs = (await import(specifier)) as { readFile(path: string, encoding: string): Promise<string> };
    text = await fs.readFile(path, "utf8");
  } catch {
    throw refuse(
      "auth_required",
      operation,
      "The gateway token file named by ANVIL_GATEWAY_TOKEN_FILE could not be read.",
    );
  }
  const token = text.trim();
  if (token.length === 0) throw refuse("auth_required", operation, "The gateway token file is empty.");
  return token;
}

async function messagesOf(response: Response): Promise<unknown[]> {
  const text = await response.text();
  if ((response.headers.get("content-type") ?? "").startsWith("text/event-stream")) {
    const out: unknown[] = [];
    let data: string[] = [];
    for (const line of [...text.split(/\\r?\\n/), ""]) {
      if (line.startsWith("data:")) data.push(line.slice(5).replace(/^ /, ""));
      else if (line === "" && data.length > 0) {
        try {
          out.push(JSON.parse(data.join("\\n")));
        } catch {
          // not a JSON-RPC message
        }
        data = [];
      }
    }
    return out;
  }
  if (text.trim().length === 0) return [];
  const parsed = JSON.parse(text) as unknown;
  return Array.isArray(parsed) ? parsed : [parsed];
}

async function send(
  options: GatewayOptions,
  method: "POST" | "DELETE",
  body: unknown,
  headers: Record<string, string>,
  operation: string,
): Promise<Response> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), options.timeoutMs);
  try {
    return await options.fetchImpl(options.url, {
      method,
      headers,
      ...(body === undefined ? {} : { body: JSON.stringify(body) }),
      signal: controller.signal,
    });
  } catch {
    // Never surface the transport's own message: it can carry the URL.
    throw refuse("upstream_unavailable", operation, "The Anvil gateway could not be reached.", true);
  } finally {
    clearTimeout(timer);
  }
}

async function rpc(
  options: GatewayOptions,
  id: number,
  method: string,
  params: unknown,
  headers: Record<string, string>,
  operation: string,
): Promise<{ result: unknown; response: Response }> {
  const response = await send(options, "POST", { jsonrpc: "2.0", id, method, params }, headers, operation);
  if (response.status === 401 || response.status === 403) {
    throw refuse(
      response.status === 401 ? "auth_required" : "permission_denied",
      operation,
      \`The Anvil gateway refused this turn's token (HTTP \${response.status}).\`,
    );
  }
  if (response.status >= 400) {
    throw refuse(
      "upstream_unavailable",
      operation,
      \`The Anvil gateway answered HTTP \${response.status}.\`,
      response.status >= 500,
    );
  }
  let messages: unknown[] = [];
  try {
    messages = await messagesOf(response);
  } catch {
    messages = [];
  }
  for (const message of messages) {
    const m = message as { id?: unknown; result?: unknown; error?: { message?: unknown } };
    if (m && m.id === id) {
      if (m.error) {
        throw refuse(
          "unsupported_operation",
          operation,
          \`The Anvil gateway refused the request: \${String(m.error.message ?? "unknown error").slice(0, 300)}\`,
        );
      }
      return { result: m.result, response };
    }
  }
  throw refuse("upstream_unavailable", operation, \`The Anvil gateway sent no response to \${method}.\`);
}

/** One call through the gateway: the same result or AnvilError a direct call gives. */
export async function gatewayCall(
  options: GatewayOptions,
  spec: OperationSpec,
  input: Record<string, unknown>,
  call: CallOptions,
): Promise<unknown> {
  const row = GATEWAY_TOOLS[spec.id];
  if (!row) throw refuse("unsupported_operation", spec.id, "This operation has no gateway tool.");
  const args: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(input)) if (value !== undefined) args[key] = value;
  if (call.confirm === true && row.confirmKey) args[row.confirmKey] = true;
  if (call.idempotencyKey !== undefined && row.idempotencyKey) args[row.idempotencyKey] = call.idempotencyKey;
  if (call.dryRun === true) args[DRY_RUN_ARG] = true;
  const connector = options.connector ?? processEnv()?.[GATEWAY_CONNECTOR_ENV_VAR] ?? DEFAULT_CONNECTOR;
  const headers: Record<string, string> = {
    "content-type": "application/json",
    accept: "application/json, text/event-stream",
    authorization: \`Bearer \${await readToken(options, spec.id)}\`,
    "user-agent": options.userAgent,
  };
  const init = await rpc(
    options,
    1,
    "initialize",
    { protocolVersion: PROTOCOL_VERSION, capabilities: {}, clientInfo: { name: options.userAgent, version: "1" } },
    headers,
    spec.id,
  );
  const session = init.response.headers.get("mcp-session-id");
  if (session) headers["mcp-session-id"] = session;
  const negotiated = (init.result as { protocolVersion?: unknown } | undefined)?.protocolVersion;
  headers["mcp-protocol-version"] = typeof negotiated === "string" ? negotiated : PROTOCOL_VERSION;
  try {
    await send(options, "POST", { jsonrpc: "2.0", method: "notifications/initialized" }, headers, spec.id);
    const { result } = await rpc(
      options,
      2,
      "tools/call",
      { name: \`\${connector}__\${row.tool}\`, arguments: args },
      headers,
      spec.id,
    );
    return decodeToolResult(spec.id, result);
  } finally {
    if (session) await send(options, "DELETE", undefined, headers, spec.id).catch(() => undefined);
  }
}

function flagToOption(flag: string): string {
  if (!flag.startsWith("--")) return flag;
  return flag.slice(2).replace(/-([a-z])/g, (_m, c: string) => c.toUpperCase());
}

/** Turn a gateway CallToolResult back into what a direct call returns or throws. */
export function decodeToolResult(operation: string, result: unknown): unknown {
  if (!result || typeof result !== "object") {
    throw refuse("schema_mismatch", operation, "The gateway returned no tool result.");
  }
  const r = result as {
    content?: Array<{ type?: string; text?: string }>;
    structuredContent?: Record<string, unknown>;
    isError?: boolean;
  };
  const text = r.content?.find((item) => item.type === "text")?.text ?? "";
  if (r.isError) {
    let envelope: Record<string, unknown> = {};
    try {
      envelope = ((JSON.parse(text) as { error?: Record<string, unknown> }).error ?? {}) as Record<string, unknown>;
    } catch {
      envelope = {};
    }
    const code = KNOWN_CODES.has(String(envelope.code))
      ? (envelope.code as AnvilErrorCode)
      : "unknown_upstream_error";
    const upstream = envelope.upstream as { status?: number; request_id?: string; code?: string } | undefined;
    throw new AnvilError({
      code,
      operation: typeof envelope.operation === "string" ? envelope.operation : operation,
      traceId: typeof envelope.trace_id === "string" ? envelope.trace_id : "",
      message: typeof envelope.message === "string" ? envelope.message : text.slice(0, 300) || "The gateway call failed.",
      retryable: envelope.retryable === true,
      safeToRetry: envelope.safe_to_retry === true,
      ...(upstream ? { upstream: { status: upstream.status, requestId: upstream.request_id, code: upstream.code } } : {}),
      ...(Array.isArray(envelope.required_flags)
        ? { requiredFlags: (envelope.required_flags as string[]).map(flagToOption) }
        : {}),
      ...(envelope.details !== undefined ? { details: envelope.details } : {}),
    });
  }
  const structured = r.structuredContent;
  if (structured && typeof structured === "object") {
    if (DRY_RUN_ARG in structured) return structured[DRY_RUN_ARG];
    if ("anvil_unvalidated" in structured) return structured.anvil_unvalidated;
  }
  try {
    return JSON.parse(text) as unknown;
  } catch {
    // fall through to the structured channel
  }
  if (structured && typeof structured === "object") {
    const keys = Object.keys(structured);
    return keys.length === 1 && keys[0] === "result" ? structured.result : structured;
  }
  return text;
}
`;
}
