import type { SdkPlan } from "./plan.js";

/**
 * The Go SDK's decision core — the files that are identical for every service
 * Anvil compiles, apart from the package clause.
 *
 * They live apart from the per-service projection on purpose: the code that
 * decides whether a call is allowed to happen is one reviewed implementation,
 * and generation only ever adds rows to the table it reads.
 */

const g = (value: unknown): string => JSON.stringify(value);

/** The Go package name: lowercase letters and digits only, as Go expects. */
export function goPackage(plan: SdkPlan): string {
  const sanitized = plan.service.id.replace(/[^a-z0-9]/g, "");
  return /^[a-z]/.test(sanitized) ? sanitized : `anvil${sanitized}`;
}

export function errorsFile(plan: SdkPlan): string {
  return `// Generated by Anvil. Do not edit — regenerate from AIR.

package ${goPackage(plan)}

import "fmt"

// ErrorCodes is the Anvil error taxonomy (spec section 10). Anvil never leaks
// raw upstream chaos as the primary interface: every failure arrives as *Error
// with one of these codes and the next action attached.
var ErrorCodes = []string{
${plan.errorCodes.map((code) => `\t${g(code)},`).join("\n")}
}

// Upstream carries the reviewed, non-secret detail of an upstream failure.
type Upstream struct {
	Status    int    \`json:"status,omitempty"\`
	RequestID string \`json:"request_id,omitempty"\`
	// Code is a declared, stable domain code — never an unreviewed raw body value.
	Code string \`json:"code,omitempty"\`
}

// Error is every failure this SDK returns.
type Error struct {
	Code        string    \`json:"code"\`
	Message     string    \`json:"message"\`
	Operation   string    \`json:"operation"\`
	TraceID     string    \`json:"trace_id"\`
	Retryable   bool      \`json:"retryable"\`
	SafeToRetry bool      \`json:"safe_to_retry"\`
	Upstream    *Upstream \`json:"upstream,omitempty"\`
	// RequiredArguments names what the caller must supply, for
	// confirmation_required / idempotency_required.
	RequiredArguments []string \`json:"required_arguments,omitempty"\`
	// RetryAfterMs is the upstream's own backpressure instruction, when it gave one.
	RetryAfterMs int64 \`json:"retry_after_ms,omitempty"\`
}

func (e *Error) Error() string {
	return fmt.Sprintf("%s: %s", e.Code, e.Message)
}

// HTTPStatusToErrorCode maps an upstream HTTP status onto the Anvil taxonomy.
func HTTPStatusToErrorCode(status int) string {
	switch status {
	case 400, 422:
		return "validation_error"
	case 401:
		return "auth_required"
	case 403:
		return "permission_denied"
	case 404, 410:
		return "not_found"
	case 408:
		return "upstream_timeout"
	case 409:
		return "conflict"
	case 429:
		return "rate_limited"
	case 502, 503:
		return "upstream_unavailable"
	case 504:
		return "upstream_timeout"
	}
	if status >= 500 {
		return "unknown_upstream_error"
	}
	if status >= 400 {
		return "validation_error"
	}
	return "unknown_upstream_error"
}

// IsRetryableCode reports whether a code is inherently retryable, before the
// idempotency gate applies.
func IsRetryableCode(code string) bool {
	return code == "rate_limited" || code == "upstream_timeout" || code == "upstream_unavailable"
}
`;
}

export function specFile(plan: SdkPlan): string {
  return `// Generated by Anvil. Do not edit — regenerate from AIR.
//
// The shape of one compiled operation. Generation only ever adds rows to this
// table; the code that reads it is the same reviewed implementation everywhere.

package ${goPackage(plan)}

import "time"

// ParamSpec is one non-body request parameter.
type ParamSpec struct {
	// WireName is the exact on-wire coordinate.
	WireName string
	// Key is the payload key the caller's input struct produces.
	Key      string
	In       string
	Required bool
}

// BodyFieldSpec is one projected top-level body field.
type BodyFieldSpec struct {
	WireName string
	Key      string
	Required bool
}

// BodySpec describes the request body as AIR preserved it.
type BodySpec struct {
	Required    bool
	ContentType string
	Projection  string
	Fields      []BodyFieldSpec
}

// CarrierSpec is the exact on-wire coordinate an idempotency key is placed at.
type CarrierSpec struct {
	Mechanism string
	Key       string
	// Path is the property path, for a body carrier.
	Path []string
}

// IdempotencySpec is the contract's idempotency posture.
type IdempotencySpec struct {
	Mode           string
	KeyDerivation  string
	// CallerKeyRequired is true when the SDK must refuse until a key is supplied.
	CallerKeyRequired bool
	Carrier           *CarrierSpec
}

// RetrySpec is the resolved retry policy.
type RetrySpec struct {
	Mode           string
	MaxAttempts    int
	Backoff        string
	BaseDelayMs    int64
	MaxDelayMs     int64
	RetryStatuses  []int
	RetryTransport bool
}

// ConfirmationSpec is the confirmation gate.
type ConfirmationSpec struct {
	Required      bool
	HumanApproval bool
	Reason        string
}

// GraphqlBinding is the compiled query document for a GraphQL operation.
type GraphqlBinding struct {
	Document      string
	OperationName string
	RootField     string
}

// OperationSpec is one approved operation, as data.
type OperationSpec struct {
	ID         string
	HTTPMethod string
	// WireProtocol is what a real call must speak. Anything but "http_json"
	// means Path below is a coordinate Anvil synthesized to hold operations
	// apart, not a wire address.
	WireProtocol string
	// Soap is what the envelope must carry, for a SOAP operation. Read from the
	// WSDL by the compiler; never inferred here.
	Soap *SoapBinding
	// Graphql is the document compiled from the SDL, for a GraphQL operation.
	// Posted as handed, so no caller value is ever interpolated into a query.
	Graphql *GraphqlBinding
	// Path is the path template with {wire_name} placeholders.
	Path         string
	Effect       string
	Params       []ParamSpec
	Body         *BodySpec
	Idempotency  IdempotencySpec
	Retry        RetrySpec
	Confirmation ConfirmationSpec
}

// CallOptions carries the per-call safety controls. These are never wire
// values — they decide whether the SDK sends anything at all.
type CallOptions struct {
	// Confirm is required by operations whose contract gates on confirmation.
	Confirm bool
	// IdempotencyKey is required when the contract needs a key it cannot derive.
	IdempotencyKey string
	// Headers are extra request headers; reserved names are ignored.
	Headers map[string]string
	// Timeout overrides the client deadline for this call.
	Timeout time.Duration
}

func firstCallOptions(options []CallOptions) CallOptions {
	if len(options) == 0 {
		return CallOptions{}
	}
	return options[0]
}
`;
}

/**
 * `mtls.go` — an `*http.Client` presenting a client certificate, emitted only
 * for a service whose auth scheme is `mtls`.
 *
 * `WithHTTPClient` already lets a caller inject any transport, so mTLS needs
 * nothing new in the call path — only something that builds the right
 * `*http.Client`. `tls.X509KeyPair` and `x509.CertPool.AppendCertsFromPEM`
 * take PEM bytes directly; a value that already names a readable file is read
 * first, mirroring the TypeScript and Python SDKs' file-or-literal-PEM rule.
 */
export function mtlsFile(plan: SdkPlan): string {
  return `// Generated by Anvil. Do not edit — regenerate from AIR.

package ${goPackage(plan)}

import (
	"crypto/tls"
	"crypto/x509"
	"fmt"
	"net/http"
	"os"
)

// resolvePem returns the bytes of the named file when value already names a
// readable file, or value itself as literal PEM bytes otherwise. The
// credential material is never logged, echoed, or included in an error.
func resolvePem(value string) ([]byte, error) {
	if info, err := os.Stat(value); err == nil && !info.IsDir() {
		return os.ReadFile(value)
	}
	return []byte(value), nil
}

// NewMtlsHTTPClient builds an *http.Client that presents the given client
// certificate on every HTTPS connection. When ca is non-empty, it — and only
// it — is trusted, mirroring how the TypeScript and Python SDKs treat an
// explicit CA; otherwise the platform's default trust store is used.
func NewMtlsHTTPClient(certPEM, keyPEM, caPEM string) (*http.Client, error) {
	certBytes, err := resolvePem(certPEM)
	if err != nil {
		return nil, fmt.Errorf("reading client certificate: %w", err)
	}
	keyBytes, err := resolvePem(keyPEM)
	if err != nil {
		return nil, fmt.Errorf("reading client key: %w", err)
	}
	cert, err := tls.X509KeyPair(certBytes, keyBytes)
	if err != nil {
		return nil, fmt.Errorf("parsing client certificate/key: %w", err)
	}
	tlsConfig := &tls.Config{Certificates: []tls.Certificate{cert}}
	if caPEM != "" {
		caBytes, err := resolvePem(caPEM)
		if err != nil {
			return nil, fmt.Errorf("reading CA certificate: %w", err)
		}
		pool := x509.NewCertPool()
		if !pool.AppendCertsFromPEM(caBytes) {
			return nil, fmt.Errorf("no certificates found in CA PEM")
		}
		tlsConfig.RootCAs = pool
	}
	return &http.Client{Transport: &http.Transport{TLSClientConfig: tlsConfig}}, nil
}
`;
}

/**
 * `oauth.go` — an optional refresh helper for \`oauth2_authorization_code\`,
 * emitted only when the contract names a token endpoint. Never performs the
 * interactive authorization step; only exchanges an already-obtained refresh
 * token for a fresh access token (RFC 6749 section 6).
 */
export function oauthFile(plan: SdkPlan): string {
  return `// Generated by Anvil. Do not edit — regenerate from AIR.

package ${goPackage(plan)}

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strconv"
	"strings"
	"sync"
	"time"
)

type refreshedToken struct {
	AccessToken string \`json:"access_token"\`
	ExpiresIn   *int64 \`json:"expires_in"\`
}

// NewRefreshingTokenProvider builds a TokenProvider that exchanges
// refreshToken at tokenEndpoint (RFC 6749 section 6) and caches the access
// token in memory until shortly before it expires. Never logs the refresh
// token, client secret, or minted access token.
func NewRefreshingTokenProvider(tokenEndpoint, refreshToken, clientID, clientSecret string) func(context.Context) (string, error) {
	var mu sync.Mutex
	var cachedToken string
	var expiresAt time.Time

	return func(ctx context.Context) (string, error) {
		mu.Lock()
		defer mu.Unlock()
		if cachedToken != "" && time.Now().Before(expiresAt) {
			return cachedToken, nil
		}
		form := url.Values{}
		form.Set("grant_type", "refresh_token")
		form.Set("refresh_token", refreshToken)
		form.Set("client_id", clientID)
		request, err := http.NewRequestWithContext(ctx, "POST", tokenEndpoint, strings.NewReader(form.Encode()))
		if err != nil {
			return "", err
		}
		request.Header.Set("content-type", "application/x-www-form-urlencoded")
		if clientSecret != "" {
			request.SetBasicAuth(clientID, clientSecret)
		}
		response, err := http.DefaultClient.Do(request)
		if err != nil {
			return "", fmt.Errorf("token refresh could not reach %s", tokenEndpoint)
		}
		defer response.Body.Close()
		raw, _ := io.ReadAll(response.Body)
		if response.StatusCode < 200 || response.StatusCode >= 300 {
			// Never surface the response body: a token endpoint's error payload
			// can echo back the refresh token or client secret it was sent.
			return "", fmt.Errorf("token refresh failed with HTTP %s from %s", strconv.Itoa(response.StatusCode), tokenEndpoint)
		}
		var payload refreshedToken
		if err := json.Unmarshal(raw, &payload); err != nil || payload.AccessToken == "" {
			return "", fmt.Errorf("token endpoint response carried no access_token")
		}
		expiresIn := int64(300)
		if payload.ExpiresIn != nil {
			expiresIn = *payload.ExpiresIn
		}
		cachedToken = payload.AccessToken
		expiresAt = time.Now().Add(time.Duration(expiresIn)*time.Second - 30*time.Second)
		return cachedToken, nil
	}
}
`;
}
