import type { SdkPlan } from "./plan.js";

/**
 * The Go SDK's decision core — the files that are identical for every service
 * Anvil compiles, apart from the package clause.
 *
 * They live apart from the per-service projection on purpose: the code that
 * decides whether a call is allowed to happen is one reviewed implementation,
 * and generation only ever adds rows to the table it reads.
 */

const g = (value: unknown): string => JSON.stringify(value);

/** The Go package name: lowercase letters and digits only, as Go expects. */
export function goPackage(plan: SdkPlan): string {
  const sanitized = plan.service.id.replace(/[^a-z0-9]/g, "");
  return /^[a-z]/.test(sanitized) ? sanitized : `anvil${sanitized}`;
}

export function errorsFile(plan: SdkPlan): string {
  return `// Generated by Anvil. Do not edit — regenerate from AIR.

package ${goPackage(plan)}

import "fmt"

// ErrorCodes is the Anvil error taxonomy (spec section 10). Anvil never leaks
// raw upstream chaos as the primary interface: every failure arrives as *Error
// with one of these codes and the next action attached.
var ErrorCodes = []string{
${plan.errorCodes.map((code) => `\t${g(code)},`).join("\n")}
}

// Upstream carries the reviewed, non-secret detail of an upstream failure.
type Upstream struct {
	Status    int    \`json:"status,omitempty"\`
	RequestID string \`json:"request_id,omitempty"\`
	// Code is a declared, stable domain code — never an unreviewed raw body value.
	Code string \`json:"code,omitempty"\`
}

// Error is every failure this SDK returns.
type Error struct {
	Code        string    \`json:"code"\`
	Message     string    \`json:"message"\`
	Operation   string    \`json:"operation"\`
	TraceID     string    \`json:"trace_id"\`
	Retryable   bool      \`json:"retryable"\`
	SafeToRetry bool      \`json:"safe_to_retry"\`
	Upstream    *Upstream \`json:"upstream,omitempty"\`
	// RequiredArguments names what the caller must supply, for
	// confirmation_required / idempotency_required.
	RequiredArguments []string \`json:"required_arguments,omitempty"\`
	// RetryAfterMs is the upstream's own backpressure instruction, when it gave one.
	RetryAfterMs int64 \`json:"retry_after_ms,omitempty"\`
}

func (e *Error) Error() string {
	return fmt.Sprintf("%s: %s", e.Code, e.Message)
}

// HTTPStatusToErrorCode maps an upstream HTTP status onto the Anvil taxonomy.
func HTTPStatusToErrorCode(status int) string {
	switch status {
	case 400, 422:
		return "validation_error"
	case 401:
		return "auth_required"
	case 403:
		return "permission_denied"
	case 404, 410:
		return "not_found"
	case 408:
		return "upstream_timeout"
	case 409:
		return "conflict"
	case 429:
		return "rate_limited"
	case 502, 503:
		return "upstream_unavailable"
	case 504:
		return "upstream_timeout"
	}
	if status >= 500 {
		return "unknown_upstream_error"
	}
	if status >= 400 {
		return "validation_error"
	}
	return "unknown_upstream_error"
}

// IsRetryableCode reports whether a code is inherently retryable, before the
// idempotency gate applies.
func IsRetryableCode(code string) bool {
	return code == "rate_limited" || code == "upstream_timeout" || code == "upstream_unavailable"
}
`;
}

export function specFile(plan: SdkPlan): string {
  return `// Generated by Anvil. Do not edit — regenerate from AIR.
//
// The shape of one compiled operation. Generation only ever adds rows to this
// table; the code that reads it is the same reviewed implementation everywhere.

package ${goPackage(plan)}

import "time"

// ParamSpec is one non-body request parameter.
type ParamSpec struct {
	// WireName is the exact on-wire coordinate.
	WireName string
	// Key is the payload key the caller's input struct produces.
	Key      string
	In       string
	Required bool
}

// BodyFieldSpec is one projected top-level body field.
type BodyFieldSpec struct {
	WireName string
	Key      string
	Required bool
}

// BodySpec describes the request body as AIR preserved it.
type BodySpec struct {
	Required    bool
	ContentType string
	Projection  string
	Fields      []BodyFieldSpec
}

// CarrierSpec is the exact on-wire coordinate an idempotency key is placed at.
type CarrierSpec struct {
	Mechanism string
	Key       string
	// Path is the property path, for a body carrier.
	Path []string
}

// IdempotencySpec is the contract's idempotency posture.
type IdempotencySpec struct {
	Mode           string
	KeyDerivation  string
	// CallerKeyRequired is true when the SDK must refuse until a key is supplied.
	CallerKeyRequired bool
	Carrier           *CarrierSpec
}

// RetrySpec is the resolved retry policy.
type RetrySpec struct {
	Mode           string
	MaxAttempts    int
	Backoff        string
	BaseDelayMs    int64
	MaxDelayMs     int64
	RetryStatuses  []int
	RetryTransport bool
}

// ConfirmationSpec is the confirmation gate.
type ConfirmationSpec struct {
	Required      bool
	HumanApproval bool
	Reason        string
}

// GraphqlBinding is the compiled query document for a GraphQL operation.
type GraphqlBinding struct {
	Document      string
	OperationName string
	RootField     string
}

// OperationSpec is one approved operation, as data.
type OperationSpec struct {
	ID         string
	HTTPMethod string
	// WireProtocol is what a real call must speak. Anything but "http_json"
	// means Path below is a coordinate Anvil synthesized to hold operations
	// apart, not a wire address.
	WireProtocol string
	// Soap is what the envelope must carry, for a SOAP operation. Read from the
	// WSDL by the compiler; never inferred here.
	Soap *SoapBinding
	// Graphql is the document compiled from the SDL, for a GraphQL operation.
	// Posted as handed, so no caller value is ever interpolated into a query.
	Graphql *GraphqlBinding
	// Path is the path template with {wire_name} placeholders.
	Path         string
	Effect       string
	Params       []ParamSpec
	Body         *BodySpec
	Idempotency  IdempotencySpec
	Retry        RetrySpec
	Confirmation ConfirmationSpec
}

// CallOptions carries the per-call safety controls. These are never wire
// values — they decide whether the SDK sends anything at all.
type CallOptions struct {
	// Confirm is required by operations whose contract gates on confirmation.
	Confirm bool
	// IdempotencyKey is required when the contract needs a key it cannot derive.
	IdempotencyKey string
	// Headers are extra request headers; reserved names are ignored.
	Headers map[string]string
	// Timeout overrides the client deadline for this call.
	Timeout time.Duration
}

func firstCallOptions(options []CallOptions) CallOptions {
	if len(options) == 0 {
		return CallOptions{}
	}
	return options[0]
}
`;
}
