import { goPackage } from "./go-core.js";
import type { SdkPlan } from "./plan.js";
import { wireFidelityCore } from "./wire-fidelity-core.js";

/**
 * The Go SDK's call path: the single `invoke` every generated method funnels
 * through (the retry gate and Retry-After arithmetic it reads live in
 * `go-safety.ts`). Identical for every service, so a method that skipped a
 * gate would have to be a change here rather than a quiet difference in one
 * emitted client.
 */

export function invokeFile(plan: SdkPlan): string {
  return (
    `// Generated by Anvil. Do not edit — regenerate from AIR.
//
// The one call path. Every generated method funnels through invoke, so the
// gates below cannot be bypassed by a method that forgot to check.

package ${goPackage(plan)}

import (
	"bytes"
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"reflect"
	"sort"
	"strings"
	"time"
)

// reservedHeaders are owned by the transport; a caller override would break the contract.
var reservedHeaders = map[string]bool{"authorization": true, "content-length": true, "content-type": true, "host": true, "transfer-encoding": true}
${wireFidelityCore.go}
func traceID() string {
	buffer := make([]byte, 16)
	if _, err := rand.Read(buffer); err != nil {
		return "trace-unavailable"
	}
	return hex.EncodeToString(buffer)
}

// assertWireExecutable is the transport gate. assertConfirmed asks whether the
// caller intends the effect; this asks whether this client can express the call
// at all. A SOAP, GraphQL, or gRPC operation arrives with a path Anvil
// invented, and sending JSON to it would be a well-formed lie. Mirrors the
// runtime's own gate so every surface refuses alike.
func assertWireExecutable(spec OperationSpec, config clientConfig) *Error {
	// A subscription is a bounded event-stream window with an array answer.
	// This client is request/response, and a protocol facade declares
	// coordinates, not framing — so the refusal holds with a facade declared.
	if spec.WireProtocol == "graphql_sse" {
		return &Error{
			Code:      "unsupported_operation",
			Operation: spec.ID,
			TraceID:   traceID(),
			Message: spec.ID + " is a GraphQL subscription, observed through a bounded Server-Sent " +
				"Events window. This client is request/response and cannot hold that window open, " +
				"and a protocol facade cannot change the framing of an event stream. Call it " +
				"through the generated MCP server or CLI, which share the runtime that reads this wire.",
		}
	}
	if spec.WireProtocol == "http_json" || config.protocolFacade != "" {
		return nil
	}
	// SOAP is speakable exactly when the compiler recovered a binding for it.
	if spec.WireProtocol == "soap" && spec.Soap != nil {
		return nil
	}
	if spec.WireProtocol == "graphql" && spec.Graphql != nil {
		return nil
	}
	return &Error{
		Code:      "unsupported_operation",
		Operation: spec.ID,
		TraceID:   traceID(),
		Message: spec.ID + " speaks " + spec.WireProtocol + ", which this client cannot put on the wire: " +
			spec.HTTPMethod + " " + spec.Path + " is a coordinate Anvil synthesized, not an address the " +
			"service serves. Point WithBaseURL at a facade that really does serve it over HTTP+JSON and " +
			"pass WithProtocolFacade with the reason, so the assumption is recorded.",
	}
}

// assertConfirmed is the confirmation gate. It refuses before anything reaches
// the wire.
func assertConfirmed(spec OperationSpec, options CallOptions) *Error {
	if !spec.Confirmation.Required || options.Confirm {
		return nil
	}
	audience := "Set CallOptions.Confirm once you intend the effect."
	if spec.Confirmation.HumanApproval {
		audience = "This effect needs explicit human approval, not a self-confirmation."
	}
	reason := ""
	if spec.Confirmation.Reason != "" {
		reason = ": " + spec.Confirmation.Reason
	}
	return &Error{
		Code:              "confirmation_required",
		Operation:         spec.ID,
		TraceID:           traceID(),
		Message:           fmt.Sprintf("%s requires confirmation%s. %s", spec.ID, reason, audience),
		RequiredArguments: []string{"Confirm"},
	}
}

// assertKeyed is the idempotency gate. A contract that demands a key gets one
// or a refusal.
func assertKeyed(spec OperationSpec, key string) *Error {
	if !spec.Idempotency.CallerKeyRequired || key != "" {
		return nil
	}
	return &Error{
		Code:      "idempotency_required",
		Operation: spec.ID,
		TraceID:   traceID(),
		Message: fmt.Sprintf(
			"%s requires an idempotency key that Anvil cannot derive for you. Set CallOptions.IdempotencyKey — reuse the same value to retry the same intent.",
			spec.ID,
		),
		RequiredArguments: []string{"IdempotencyKey"},
	}
}

func setBodyCarrier(body any, path []string, value string) any {
	root, ok := body.(map[string]any)
	if !ok || root == nil {
		root = map[string]any{}
	}
	cursor := root
	for _, segment := range path[:len(path)-1] {
		child, childOK := cursor[segment].(map[string]any)
		if !childOK || child == nil {
			child = map[string]any{}
		}
		cursor[segment] = child
		cursor = child
	}
	cursor[path[len(path)-1]] = value
	return root
}

func formatScalar(value any) string {
	switch typed := value.(type) {
	case string:
		return typed
	case fmt.Stringer:
		return typed.String()
	default:
		encoded, err := json.Marshal(typed)
		if err != nil {
			return fmt.Sprint(typed)
		}
		return strings.Trim(string(encoded), "\\"")
	}
}

type builtRequest struct {
	url     string
	method  string
	headers map[string]string
	body    []byte
}

// buildRequest builds the upstream request from the operation spec and the caller's payload.
func buildRequest(spec OperationSpec, payload map[string]any, config clientConfig, idempotencyKey string, extra map[string]string) builtRequest {
	path := spec.Path
	query := url.Values{}
	headers := map[string]string{"accept": "application/json", "user-agent": config.userAgent}
	for name, value := range extra {
		if !reservedHeaders[strings.ToLower(name)] {
			headers[strings.ToLower(name)] = value
		}
	}
	body := map[string]any{}
	hasBody := false
	cookie := ""

	for _, param := range spec.Params {
		value, present := payload[param.Key]
		if !present || value == nil {
			continue
		}
		switch param.In {
		case "path":
			path = strings.ReplaceAll(path, "{"+param.WireName+"}", simpleText(spec.ID, param, value, url.PathEscape))
		case "query":
			bindQuery(query, spec.ID, param, value)
		case "header":
			headers[param.WireName] = simpleText(spec.ID, param, value, identity)
		case "cookie":
			if cookie != "" {
				cookie += "; "
			}
			cookie += cookiePairs(spec.ID, param, value)
		case "body":
			body[param.WireName] = value
			hasBody = true
		}
	}

	var bodyValue any
	if hasBody {
		bodyValue = body
	}
	if spec.Body != nil {
		if spec.Body.Projection == "fields" {
			for _, field := range spec.Body.Fields {
				value, present := payload[field.Key]
				if !present || value == nil {
					continue
				}
				body[field.WireName] = value
				hasBody = true
			}
			if hasBody {
				bodyValue = body
			}
		} else if value, present := payload["body"]; present && value != nil {
			bodyValue = value
			hasBody = true
		}
	}

	if spec.Idempotency.Carrier != nil && idempotencyKey != "" {
		carrier := spec.Idempotency.Carrier
		switch carrier.Mechanism {
		case "header":
			// HTTP field names are case-insensitive; drop any modeled spelling
			// before injecting the one authoritative safety value.
			for name := range headers {
				if strings.EqualFold(name, carrier.Key) {
					delete(headers, name)
				}
			}
			headers[carrier.Key] = idempotencyKey
		case "query":
			query.Set(carrier.Key, idempotencyKey)
		case "path":
			path = strings.ReplaceAll(path, "{"+carrier.Key+"}", url.PathEscape(idempotencyKey))
		case "body":
			carrierPath := carrier.Path
			if len(carrierPath) == 0 {
				carrierPath = []string{carrier.Key}
			}
			bodyValue = setBodyCarrier(bodyValue, carrierPath, idempotencyKey)
			hasBody = true
		}
	}

	if config.token != "" && config.authCarrier != nil {
		if config.authCarrier.In == "header" {
			value := config.token
			if config.authCarrier.Scheme != "" {
				value = config.authCarrier.Scheme + " " + config.token
			}
			headers[strings.ToLower(config.authCarrier.Name)] = value
		} else {
			query.Set(config.authCarrier.Name, config.token)
		}
	}
	if cookie != "" {
		headers["cookie"] = cookie
	}

	// A GraphQL service serves one endpoint; the field name travels in the
	// document, never in the URL.
	if spec.WireProtocol == "graphql" && spec.Graphql != nil {
		variables := map[string]any{}
		if typed, ok := bodyValue.(map[string]any); ok {
			variables = typed
		}
		payload, _ := json.Marshal(map[string]any{
			"query":         spec.Graphql.Document,
			"operationName": spec.Graphql.OperationName,
			"variables":     variables,
		})
		headers["content-type"] = "application/json"
		headers["accept"] = "application/json"
		return builtRequest{
			url:     strings.TrimSuffix(config.baseURL, "/"),
			method:  "POST",
			headers: headers,
			body:    payload,
		}
	}

	// A SOAP service serves one endpoint. The path is a coordinate Anvil
	// synthesized to hold operations apart in a path-keyed model, so it is
	// deliberately dropped: the address is the base URL, from soap:address.
	if spec.WireProtocol == "soap" && spec.Soap != nil {
		// Go maps are unordered, so the field order comes from the contract
		// rather than from iteration — the four SDKs must emit one envelope.
		order := make([]string, 0)
		if spec.Body != nil {
			for _, field := range spec.Body.Fields {
				order = append(order, field.WireName)
			}
		}
		for key, value := range soapHeaders(*spec.Soap) {
			headers[key] = value
		}
		headers["accept"] = strings.Split(spec.Soap.ContentType, ";")[0]
		return builtRequest{
			url:     strings.TrimSuffix(config.baseURL, "/"),
			method:  "POST",
			headers: headers,
			body:    []byte(buildEnvelope(*spec.Soap, bodyValue, order)),
		}
	}

	target := strings.TrimSuffix(config.baseURL, "/") + path
	if encoded := query.Encode(); encoded != "" {
		target += "?" + encoded
	}
	request := builtRequest{url: target, method: spec.HTTPMethod, headers: headers}
	if hasBody {
		contentType := "application/json"
		if spec.Body != nil && spec.Body.ContentType != "" {
			contentType = spec.Body.ContentType
		}
		request.headers["content-type"] = contentType
		encoded, err := json.Marshal(bodyValue)
		if err == nil {
			request.body = encoded
		}
	}
	return request
}

func decode(raw []byte) any {
	if len(raw) == 0 {
		return nil
	}
	var value any
	if err := json.Unmarshal(raw, &value); err != nil {
		return string(raw)
	}
	return value
}

// invoke runs one operation end to end: gate, build, send, and retry only where
// the contract proves retrying is safe.
func invoke(ctx context.Context, config clientConfig, spec OperationSpec, payload map[string]any, options CallOptions) (any, error) {
	if refusal := assertWireExecutable(spec, config); refusal != nil {
		return nil, refusal
	}
	if refusal := assertEncodable(spec, payload); refusal != nil {
		return nil, refusal
	}
	if refusal := assertConfirmed(spec, options); refusal != nil {
		return nil, refusal
	}
	for key, value := range payload {
		if value == nil {
			delete(payload, key)
		}
	}
	idempotencyKey, err := ResolveIdempotencyKey(spec, options.IdempotencyKey, payload)
	if err != nil {
		return nil, &Error{Code: "validation_error", Operation: spec.ID, TraceID: traceID(), Message: err.Error()}
	}
	if refusal := assertKeyed(spec, idempotencyKey); refusal != nil {
		return nil, refusal
	}

	safeToRetry := RetryIsSafe(spec, idempotencyKey != "")
	if options.DryRun {
		// Every gate above has run; nothing below is sent. A dry run never
		// resolves a credential, exactly as the runtime's own dry run does not.
		preview := buildRequest(spec, payload, config.withoutCredential(), idempotencyKey, options.Headers)
		return dryRunPlan(spec, preview, idempotencyKey != "", safeToRetry), nil
	}
	// A delegated token source takes priority over a static token: it is how a
	// caller plugs in a refreshed authorization-code grant without the SDK
	// ever holding a long-lived secret of its own. Resolved once per call,
	// never cached here — a provider that wants caching does its own.
	if config.tokenProvider != nil {
		token, providerErr := config.tokenProvider(ctx)
		if providerErr != nil {
			return nil, &Error{
				Code:      "auth_required",
				Operation: spec.ID,
				TraceID:   traceID(),
				Message:   fmt.Sprintf("%s could not obtain a credential: %s", spec.ID, providerErr.Error()),
			}
		}
		config.token = token
	}
	maxAttempts := 1
	if safeToRetry {
		maxAttempts = spec.Retry.MaxAttempts
	}
	request := buildRequest(spec, payload, config, idempotencyKey, options.Headers)
	trace := traceID()
	timeout := config.timeout
	if options.Timeout > 0 {
		timeout = options.Timeout
	}

	for attempt := 1; ; attempt++ {
		attemptCtx, cancel := context.WithTimeout(ctx, timeout)
		httpRequest, buildErr := http.NewRequestWithContext(attemptCtx, request.method, request.url, bytes.NewReader(request.body))
		if buildErr != nil {
			cancel()
			return nil, &Error{Code: "validation_error", Operation: spec.ID, TraceID: trace, Message: fmt.Sprintf("%s could not be prepared for sending.", spec.ID)}
		}
		for name, value := range request.headers {
			httpRequest.Header.Set(name, value)
		}
		response, sendErr := config.httpClient.Do(httpRequest)
		if sendErr != nil {
			cancel()
			// Never surface the transport's own message: it can carry the URL,
			// and the URL can carry a query-carried credential.
			failure := &Error{
				Code:        "upstream_unavailable",
				Operation:   spec.ID,
				TraceID:     trace,
				Message:     fmt.Sprintf("%s failed: the request could not reach the upstream.", spec.ID),
				Retryable:   spec.Retry.RetryTransport,
				SafeToRetry: safeToRetry,
			}
			if !safeToRetry || !spec.Retry.RetryTransport || attempt >= maxAttempts {
				return nil, failure
			}
			decision := ResolveRetryDelay(attempt, spec.Retry, 0, false, config.random)
			if decision.Stop {
				return nil, failure
			}
			if err := sleepFor(ctx, decision.DelayMs, config.sleep); err != nil {
				return nil, failure
			}
			continue
		}

		raw, readErr := io.ReadAll(response.Body)
		response.Body.Close()
		cancel()
		if readErr != nil {
			raw = nil
		}

		// GraphQL reports failures inside a 200 with an errors array — the same
		// danger as a SOAP fault. A partial response counts as a failure.
		if spec.WireProtocol == "graphql" && spec.Graphql != nil {
			var envelope struct {
				Data   map[string]any ` +
    '`json:"data"`' +
    `
				Errors []struct {
					Message string ` +
    '`json:"message"`' +
    `
				} ` +
    '`json:"errors"`' +
    `
			}
			_ = json.Unmarshal(raw, &envelope)
			if len(envelope.Errors) > 0 {
				message := envelope.Errors[0].Message
				if message == "" {
					message = "the service returned a GraphQL error"
				}
				return nil, &Error{
					Code:        "unknown_upstream_error",
					Operation:   spec.ID,
					TraceID:     trace,
					Message:     spec.ID + " failed upstream: " + message,
					Retryable:   false,
					SafeToRetry: safeToRetry,
				}
			}
			if response.StatusCode >= 200 && response.StatusCode < 300 {
				if value, present := envelope.Data[spec.Graphql.RootField]; present {
					return value, nil
				}
				return envelope.Data, nil
			}
		}

		// A soap:Fault is a failure the transport delivered successfully, and
		// servers send it with 200 as readily as 500 — so the status is not the
		// answer here, the envelope is. Read before the status branch, or a
		// faulted 200 would be returned to the caller as a result.
		if spec.WireProtocol == "soap" && spec.Soap != nil {
			soapText := string(raw)
			if fault := soapFaultIn(soapText); fault != nil {
				// Only a Server fault is transient. A Client fault will fail
				// identically on retry, and retrying a mutation on one is
				// exactly what the safety contract forbids.
				if fault.Retryable && safeToRetry && attempt < maxAttempts {
					decision := ResolveRetryDelay(attempt, spec.Retry, 0, false, config.random)
					if !decision.Stop {
						config.sleep(time.Duration(decision.DelayMs) * time.Millisecond)
						continue
					}
				}
				return nil, &Error{
					Code:        "unknown_upstream_error",
					Operation:   spec.ID,
					TraceID:     trace,
					Message:     spec.ID + " failed upstream: " + fault.Message,
					Retryable:   fault.Retryable,
					SafeToRetry: safeToRetry,
				}
			}
			if response.StatusCode >= 200 && response.StatusCode < 300 {
				value, err := decodeEnvelope(*spec.Soap, soapText)
				if err != nil {
					return nil, &Error{
						Code:      "unknown_upstream_error",
						Operation: spec.ID,
						TraceID:   trace,
						Message:   spec.ID + " returned a SOAP response that could not be read.",
					}
				}
				return value, nil
			}
		}

		if response.StatusCode >= 200 && response.StatusCode < 300 {
			return decode(raw), nil
		}

		code := HTTPStatusToErrorCode(response.StatusCode)
		retryAfterMs, retryAfterErr := ParseRetryAfter(response.Header.Get("Retry-After"), time.Now())
		hasRetryAfter := retryAfterErr == nil
		failure := &Error{
			Code:        code,
			Operation:   spec.ID,
			TraceID:     trace,
			Message:     fmt.Sprintf("%s failed upstream with HTTP %d.", spec.ID, response.StatusCode),
			Retryable:   IsRetryableCode(code),
			SafeToRetry: safeToRetry,
			Upstream:    &Upstream{Status: response.StatusCode, RequestID: response.Header.Get("X-Request-Id")},
		}
		if hasRetryAfter {
			failure.RetryAfterMs = retryAfterMs
		}
		if !containsInt(spec.Retry.RetryStatuses, response.StatusCode) || attempt >= maxAttempts {
			return nil, failure
		}
		if !safeToRetry {
			// A transient failure we are not allowed to repeat. Say exactly
			// that, rather than retrying a write whose duplicate we cannot rule
			// out.
			return nil, &Error{
				Code:      "unsafe_retry_blocked",
				Operation: spec.ID,
				TraceID:   trace,
				Message: fmt.Sprintf(
					"%s failed transiently (HTTP %d) but is not provably idempotent, so it was not retried. Retry deliberately with an idempotency key if the effect is safe to repeat.",
					spec.ID, response.StatusCode,
				),
				Upstream:     &Upstream{Status: response.StatusCode},
				RetryAfterMs: failure.RetryAfterMs,
			}
		}
		decision := ResolveRetryDelay(attempt, spec.Retry, retryAfterMs, hasRetryAfter, config.random)
		if decision.Stop {
			return nil, &Error{
				Code:      code,
				Operation: spec.ID,
				TraceID:   trace,
				Message: fmt.Sprintf(
					"%s asked to be retried in %dms, longer than this client will wait inside one call. Retry deliberately after that delay.",
					spec.ID, decision.RetryAfterMs,
				),
				Retryable:    true,
				SafeToRetry:  safeToRetry,
				RetryAfterMs: decision.RetryAfterMs,
			}
		}
		if err := sleepFor(ctx, decision.DelayMs, config.sleep); err != nil {
			return nil, failure
		}
	}
}

func sleepFor(ctx context.Context, delayMs int64, sleep func(time.Duration)) error {
	if delayMs <= 0 {
		return nil
	}
	if sleep != nil {
		sleep(time.Duration(delayMs) * time.Millisecond)
		return nil
	}
	timer := time.NewTimer(time.Duration(delayMs) * time.Millisecond)
	defer timer.Stop()
	select {
	case <-ctx.Done():
		return ctx.Err()
	case <-timer.C:
		return nil
	}
}

func containsInt(values []int, target int) bool {
	for _, value := range values {
		if value == target {
			return true
		}
	}
	return false
}

func field(value any, name string) any {
	object, ok := value.(map[string]any)
	if !ok {
		return nil
	}
	return object[name]
}
`
  );
}
