import { goPackage } from "./go-core.js";
import type { SdkPlan } from "./plan.js";

/**
 * The Go SDK's call path: the retry gate and Retry-After arithmetic in
 * `safety.go`, and the single `invoke` every generated method funnels through.
 * Identical for every service, so a method that skipped a gate would have to be
 * a change here rather than a quiet difference in one emitted client.
 */

export function safetyFile(plan: SdkPlan): string {
  return `// Generated by Anvil. Do not edit — regenerate from AIR.
//
// The safety hot path, mirrored from @anvil/runtime. Identical decisions in
// every language Anvil emits: the same retry gate, the same Retry-After
// arithmetic, the same idempotency key derivation.

package ${goPackage(plan)}

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"math"
	"sort"
	"strconv"
	"strings"
	"time"
)

// MaxRetryDelayMs is the runtime-wide ceiling on a single pre-attempt sleep.
const MaxRetryDelayMs = 20000

// MaxIdempotencyKeyBytes bounds a caller-supplied key.
const MaxIdempotencyKeyBytes = 255

// RetryIsSafe reports whether automatic retry is safe for this operation.
//
// The guard behind the whole trust wedge: a mutation that is not provably
// idempotent is never retried, no matter what the policy says.
func RetryIsSafe(spec OperationSpec, hasIdempotencyKey bool) bool {
	if spec.Retry.Mode != "safe" {
		return false
	}
	if spec.Effect == "read" {
		return true
	}
	switch spec.Idempotency.Mode {
	case "natural", "client_id":
		return true
	case "required", "key_supported":
		return hasIdempotencyKey
	}
	return false
}

// ComputeBackoffMs is bounded exponential backoff with full jitter. attempt is
// 1-based: the delay applies before the (attempt+1)th try.
func ComputeBackoffMs(attempt int, retry RetrySpec, random func() float64) int64 {
	switch retry.Backoff {
	case "none":
		return 0
	case "fixed":
		if retry.BaseDelayMs < retry.MaxDelayMs {
			return retry.BaseDelayMs
		}
		return retry.MaxDelayMs
	}
	exp := float64(retry.BaseDelayMs) * math.Pow(2, float64(attempt-1))
	if exp > float64(retry.MaxDelayMs) {
		exp = float64(retry.MaxDelayMs)
	}
	if retry.Backoff == "exponential" {
		return int64(exp)
	}
	return int64(random() * exp)
}

var errNoRetryAfter = errors.New("no usable Retry-After")

// ParseRetryAfter is the upstream's own answer to "when should I come back?"
// (RFC 9110 section 10.2.3), in milliseconds from now. Both wire forms are
// accepted: delta-seconds and an HTTP-date. It reports errNoRetryAfter when the
// value is not a valid Retry-After at all, or names an instant already past —
// in both cases we have learned nothing.
func ParseRetryAfter(value string, now time.Time) (int64, error) {
	raw := strings.TrimSpace(value)
	if raw == "" {
		return 0, errNoRetryAfter
	}
	if seconds, err := strconv.ParseInt(raw, 10, 64); err == nil && seconds >= 0 {
		// Saturate rather than discard: an absurd delta is still an instruction
		// to stay away, and dropping it would let us hammer a service that just
		// asked us to stop.
		if seconds > math.MaxInt64/1000 {
			return math.MaxInt64, nil
		}
		return seconds * 1000, nil
	}
	at, err := time.Parse(time.RFC1123, raw)
	if err != nil {
		return 0, errNoRetryAfter
	}
	delta := at.Sub(now).Milliseconds()
	if delta < 0 {
		return 0, errNoRetryAfter
	}
	return delta, nil
}

// RetryDecision is what to do before the next attempt.
type RetryDecision struct {
	// Stop ends the attempt budget instead of sleeping.
	Stop         bool
	DelayMs      int64
	RetryAfterMs int64
}

// ResolveRetryDelay resolves the pre-attempt delay, honoring upstream
// backpressure over our own guess.
//
// An upstream asking for LONGER than the ceiling ends the attempt budget rather
// than clamping the sleep — clamping would mean knocking again early, which is
// how a rate limit becomes a ban. An upstream asking for LESS keeps our
// backoff: Retry-After is a floor on staying away, not permission to come back
// sooner and collapse jitter into a tight loop.
func ResolveRetryDelay(attempt int, retry RetrySpec, retryAfterMs int64, hasRetryAfter bool, random func() float64) RetryDecision {
	if hasRetryAfter && retryAfterMs > MaxRetryDelayMs {
		return RetryDecision{Stop: true, RetryAfterMs: retryAfterMs}
	}
	backoffMs := ComputeBackoffMs(attempt, retry, random)
	if !hasRetryAfter || retryAfterMs <= backoffMs {
		return RetryDecision{DelayMs: backoffMs}
	}
	return RetryDecision{DelayMs: retryAfterMs}
}

// CanonicalJSON is deterministic canonical JSON: object keys sorted, so equal
// inputs hash equal.
func CanonicalJSON(value any) string {
	var builder strings.Builder
	writeCanonical(&builder, value)
	return builder.String()
}

func writeCanonical(builder *strings.Builder, value any) {
	switch typed := value.(type) {
	case map[string]any:
		keys := make([]string, 0, len(typed))
		for key := range typed {
			keys = append(keys, key)
		}
		sort.Strings(keys)
		builder.WriteString("{")
		for index, key := range keys {
			if index > 0 {
				builder.WriteString(",")
			}
			encoded, _ := json.Marshal(key)
			builder.Write(encoded)
			builder.WriteString(":")
			writeCanonical(builder, typed[key])
		}
		builder.WriteString("}")
	case []any:
		builder.WriteString("[")
		for index, item := range typed {
			if index > 0 {
				builder.WriteString(",")
			}
			writeCanonical(builder, item)
		}
		builder.WriteString("]")
	default:
		encoded, err := json.Marshal(typed)
		if err != nil {
			builder.WriteString("null")
			return
		}
		builder.Write(encoded)
	}
}

// IdempotencyKeyIsTransportSafe is the portable caller-key contract: visible
// ASCII, at most 255 bytes.
func IdempotencyKeyIsTransportSafe(value string) bool {
	if value == "" || len(value) > MaxIdempotencyKeyBytes {
		return false
	}
	for _, r := range value {
		if r < 0x21 || r > 0x7e {
			return false
		}
	}
	return true
}

// RequestFingerprint is a stable fingerprint of a request: sha256 over the
// operation id and the canonicalized input.
func RequestFingerprint(operationID string, payload map[string]any) string {
	digest := sha256.New()
	digest.Write([]byte(operationID))
	digest.Write([]byte{0})
	digest.Write([]byte(CanonicalJSON(payload)))
	return hex.EncodeToString(digest.Sum(nil))
}

// ResolveIdempotencyKey applies caller-supplied, then fingerprint derivation,
// else none. An empty result means no key could be produced; the caller decides
// whether that is a refusal.
func ResolveIdempotencyKey(spec OperationSpec, provided string, payload map[string]any) (string, error) {
	if provided != "" {
		if !IdempotencyKeyIsTransportSafe(provided) {
			return "", fmt.Errorf("an idempotency key must be 1 to %d bytes of visible ASCII with no spaces or control characters", MaxIdempotencyKeyBytes)
		}
		return provided, nil
	}
	if spec.Idempotency.KeyDerivation == "request_fingerprint" {
		return "anvil-" + RequestFingerprint(spec.ID, payload)[:32], nil
	}
	return "", nil
}
`;
}

export function invokeFile(plan: SdkPlan): string {
  return `// Generated by Anvil. Do not edit — regenerate from AIR.
//
// The one call path. Every generated method funnels through invoke, so the
// gates below cannot be bypassed by a method that forgot to check.

package ${goPackage(plan)}

import (
	"bytes"
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
)

// reservedHeaders are owned by the transport; a caller override would break the
// contract.
var reservedHeaders = map[string]bool{
	"authorization":     true,
	"content-length":    true,
	"content-type":      true,
	"host":              true,
	"transfer-encoding": true,
}

func traceID() string {
	buffer := make([]byte, 16)
	if _, err := rand.Read(buffer); err != nil {
		return "trace-unavailable"
	}
	return hex.EncodeToString(buffer)
}

// assertWireExecutable is the transport gate. assertConfirmed asks whether the
// caller intends the effect; this asks whether this client can express the call
// at all. A SOAP, GraphQL, or gRPC operation arrives with a path Anvil
// invented, and sending JSON to it would be a well-formed lie. Mirrors the
// runtime's own gate so every surface refuses alike.
func assertWireExecutable(spec OperationSpec, config clientConfig) *Error {
	if spec.WireProtocol == "http_json" || config.protocolFacade != "" {
		return nil
	}
	// SOAP is speakable exactly when the compiler recovered a binding for it.
	if spec.WireProtocol == "soap" && spec.Soap != nil {
		return nil
	}
	return &Error{
		Code:      "unsupported_operation",
		Operation: spec.ID,
		TraceID:   traceID(),
		Message: spec.ID + " speaks " + spec.WireProtocol + ", which this client cannot put on the wire: " +
			spec.HTTPMethod + " " + spec.Path + " is a coordinate Anvil synthesized, not an address the " +
			"service serves. Point WithBaseURL at a facade that really does serve it over HTTP+JSON and " +
			"pass WithProtocolFacade with the reason, so the assumption is recorded.",
	}
}

// assertConfirmed is the confirmation gate. It refuses before anything reaches
// the wire.
func assertConfirmed(spec OperationSpec, options CallOptions) *Error {
	if !spec.Confirmation.Required || options.Confirm {
		return nil
	}
	audience := "Set CallOptions.Confirm once you intend the effect."
	if spec.Confirmation.HumanApproval {
		audience = "This effect needs explicit human approval, not a self-confirmation."
	}
	reason := ""
	if spec.Confirmation.Reason != "" {
		reason = ": " + spec.Confirmation.Reason
	}
	return &Error{
		Code:              "confirmation_required",
		Operation:         spec.ID,
		TraceID:           traceID(),
		Message:           fmt.Sprintf("%s requires confirmation%s. %s", spec.ID, reason, audience),
		RequiredArguments: []string{"Confirm"},
	}
}

// assertKeyed is the idempotency gate. A contract that demands a key gets one
// or a refusal.
func assertKeyed(spec OperationSpec, key string) *Error {
	if !spec.Idempotency.CallerKeyRequired || key != "" {
		return nil
	}
	return &Error{
		Code:      "idempotency_required",
		Operation: spec.ID,
		TraceID:   traceID(),
		Message: fmt.Sprintf(
			"%s requires an idempotency key that Anvil cannot derive for you. Set CallOptions.IdempotencyKey — reuse the same value to retry the same intent.",
			spec.ID,
		),
		RequiredArguments: []string{"IdempotencyKey"},
	}
}

func setBodyCarrier(body any, path []string, value string) any {
	root, ok := body.(map[string]any)
	if !ok || root == nil {
		root = map[string]any{}
	}
	cursor := root
	for _, segment := range path[:len(path)-1] {
		child, childOK := cursor[segment].(map[string]any)
		if !childOK || child == nil {
			child = map[string]any{}
		}
		cursor[segment] = child
		cursor = child
	}
	cursor[path[len(path)-1]] = value
	return root
}

func formatScalar(value any) string {
	switch typed := value.(type) {
	case string:
		return typed
	case fmt.Stringer:
		return typed.String()
	default:
		encoded, err := json.Marshal(typed)
		if err != nil {
			return fmt.Sprint(typed)
		}
		return strings.Trim(string(encoded), "\\"")
	}
}

type builtRequest struct {
	url     string
	method  string
	headers map[string]string
	body    []byte
}

// buildRequest builds the upstream request from the operation spec and the
// caller's payload.
func buildRequest(spec OperationSpec, payload map[string]any, config clientConfig, idempotencyKey string, extra map[string]string) builtRequest {
	path := spec.Path
	query := url.Values{}
	headers := map[string]string{"accept": "application/json", "user-agent": config.userAgent}
	for name, value := range extra {
		if !reservedHeaders[strings.ToLower(name)] {
			headers[strings.ToLower(name)] = value
		}
	}
	body := map[string]any{}
	hasBody := false
	cookie := ""

	for _, param := range spec.Params {
		value, present := payload[param.Key]
		if !present || value == nil {
			continue
		}
		switch param.In {
		case "path":
			path = strings.ReplaceAll(path, "{"+param.WireName+"}", url.PathEscape(formatScalar(value)))
		case "query":
			query.Set(param.WireName, formatScalar(value))
		case "header":
			headers[param.WireName] = formatScalar(value)
		case "cookie":
			if cookie != "" {
				cookie += "; "
			}
			cookie += param.WireName + "=" + formatScalar(value)
		case "body":
			body[param.WireName] = value
			hasBody = true
		}
	}

	var bodyValue any
	if hasBody {
		bodyValue = body
	}
	if spec.Body != nil {
		if spec.Body.Projection == "fields" {
			for _, field := range spec.Body.Fields {
				value, present := payload[field.Key]
				if !present || value == nil {
					continue
				}
				body[field.WireName] = value
				hasBody = true
			}
			if hasBody {
				bodyValue = body
			}
		} else if value, present := payload["body"]; present && value != nil {
			bodyValue = value
			hasBody = true
		}
	}

	if spec.Idempotency.Carrier != nil && idempotencyKey != "" {
		carrier := spec.Idempotency.Carrier
		switch carrier.Mechanism {
		case "header":
			// HTTP field names are case-insensitive; drop any modeled spelling
			// before injecting the one authoritative safety value.
			for name := range headers {
				if strings.EqualFold(name, carrier.Key) {
					delete(headers, name)
				}
			}
			headers[carrier.Key] = idempotencyKey
		case "query":
			query.Set(carrier.Key, idempotencyKey)
		case "path":
			path = strings.ReplaceAll(path, "{"+carrier.Key+"}", url.PathEscape(idempotencyKey))
		case "body":
			carrierPath := carrier.Path
			if len(carrierPath) == 0 {
				carrierPath = []string{carrier.Key}
			}
			bodyValue = setBodyCarrier(bodyValue, carrierPath, idempotencyKey)
			hasBody = true
		}
	}

	if config.token != "" && config.authCarrier != nil {
		if config.authCarrier.In == "header" {
			value := config.token
			if config.authCarrier.Scheme != "" {
				value = config.authCarrier.Scheme + " " + config.token
			}
			headers[strings.ToLower(config.authCarrier.Name)] = value
		} else {
			query.Set(config.authCarrier.Name, config.token)
		}
	}
	if cookie != "" {
		headers["cookie"] = cookie
	}

	// A SOAP service serves one endpoint. The path is a coordinate Anvil
	// synthesized to hold operations apart in a path-keyed model, so it is
	// deliberately dropped: the address is the base URL, from soap:address.
	if spec.WireProtocol == "soap" && spec.Soap != nil {
		// Go maps are unordered, so the field order comes from the contract
		// rather than from iteration — the four SDKs must emit one envelope.
		order := make([]string, 0)
		if spec.Body != nil {
			for _, field := range spec.Body.Fields {
				order = append(order, field.WireName)
			}
		}
		for key, value := range soapHeaders(*spec.Soap) {
			headers[key] = value
		}
		headers["accept"] = strings.Split(spec.Soap.ContentType, ";")[0]
		return builtRequest{
			url:     strings.TrimSuffix(config.baseURL, "/"),
			method:  "POST",
			headers: headers,
			body:    []byte(buildEnvelope(*spec.Soap, bodyValue, order)),
		}
	}

	target := strings.TrimSuffix(config.baseURL, "/") + path
	if encoded := query.Encode(); encoded != "" {
		target += "?" + encoded
	}
	request := builtRequest{url: target, method: spec.HTTPMethod, headers: headers}
	if hasBody {
		contentType := "application/json"
		if spec.Body != nil && spec.Body.ContentType != "" {
			contentType = spec.Body.ContentType
		}
		request.headers["content-type"] = contentType
		encoded, err := json.Marshal(bodyValue)
		if err == nil {
			request.body = encoded
		}
	}
	return request
}

func decode(raw []byte) any {
	if len(raw) == 0 {
		return nil
	}
	var value any
	if err := json.Unmarshal(raw, &value); err != nil {
		return string(raw)
	}
	return value
}

// invoke runs one operation end to end: gate, build, send, and retry only where
// the contract proves retrying is safe.
func invoke(ctx context.Context, config clientConfig, spec OperationSpec, payload map[string]any, options CallOptions) (any, error) {
	if refusal := assertWireExecutable(spec, config); refusal != nil {
		return nil, refusal
	}
	if refusal := assertConfirmed(spec, options); refusal != nil {
		return nil, refusal
	}
	for key, value := range payload {
		if value == nil {
			delete(payload, key)
		}
	}
	idempotencyKey, err := ResolveIdempotencyKey(spec, options.IdempotencyKey, payload)
	if err != nil {
		return nil, &Error{Code: "validation_error", Operation: spec.ID, TraceID: traceID(), Message: err.Error()}
	}
	if refusal := assertKeyed(spec, idempotencyKey); refusal != nil {
		return nil, refusal
	}

	safeToRetry := RetryIsSafe(spec, idempotencyKey != "")
	maxAttempts := 1
	if safeToRetry {
		maxAttempts = spec.Retry.MaxAttempts
	}
	request := buildRequest(spec, payload, config, idempotencyKey, options.Headers)
	trace := traceID()
	timeout := config.timeout
	if options.Timeout > 0 {
		timeout = options.Timeout
	}

	for attempt := 1; ; attempt++ {
		attemptCtx, cancel := context.WithTimeout(ctx, timeout)
		httpRequest, buildErr := http.NewRequestWithContext(attemptCtx, request.method, request.url, bytes.NewReader(request.body))
		if buildErr != nil {
			cancel()
			return nil, &Error{Code: "validation_error", Operation: spec.ID, TraceID: trace, Message: fmt.Sprintf("%s could not be prepared for sending.", spec.ID)}
		}
		for name, value := range request.headers {
			httpRequest.Header.Set(name, value)
		}
		response, sendErr := config.httpClient.Do(httpRequest)
		if sendErr != nil {
			cancel()
			// Never surface the transport's own message: it can carry the URL,
			// and the URL can carry a query-carried credential.
			failure := &Error{
				Code:        "upstream_unavailable",
				Operation:   spec.ID,
				TraceID:     trace,
				Message:     fmt.Sprintf("%s failed: the request could not reach the upstream.", spec.ID),
				Retryable:   spec.Retry.RetryTransport,
				SafeToRetry: safeToRetry,
			}
			if !safeToRetry || !spec.Retry.RetryTransport || attempt >= maxAttempts {
				return nil, failure
			}
			decision := ResolveRetryDelay(attempt, spec.Retry, 0, false, config.random)
			if decision.Stop {
				return nil, failure
			}
			if err := sleepFor(ctx, decision.DelayMs, config.sleep); err != nil {
				return nil, failure
			}
			continue
		}

		raw, readErr := io.ReadAll(response.Body)
		response.Body.Close()
		cancel()
		if readErr != nil {
			raw = nil
		}

		// A soap:Fault is a failure the transport delivered successfully, and
		// servers send it with 200 as readily as 500 — so the status is not the
		// answer here, the envelope is. Read before the status branch, or a
		// faulted 200 would be returned to the caller as a result.
		if spec.WireProtocol == "soap" && spec.Soap != nil {
			soapText := string(raw)
			if fault := soapFaultIn(soapText); fault != nil {
				// Only a Server fault is transient. A Client fault will fail
				// identically on retry, and retrying a mutation on one is
				// exactly what the safety contract forbids.
				if fault.Retryable && safeToRetry && attempt < maxAttempts {
					decision := ResolveRetryDelay(attempt, spec.Retry, 0, false, config.random)
					if !decision.Stop {
						config.sleep(time.Duration(decision.DelayMs) * time.Millisecond)
						continue
					}
				}
				return nil, &Error{
					Code:        "unknown_upstream_error",
					Operation:   spec.ID,
					TraceID:     trace,
					Message:     spec.ID + " failed upstream: " + fault.Message,
					Retryable:   fault.Retryable,
					SafeToRetry: safeToRetry,
				}
			}
			if response.StatusCode >= 200 && response.StatusCode < 300 {
				value, err := decodeEnvelope(*spec.Soap, soapText)
				if err != nil {
					return nil, &Error{
						Code:      "unknown_upstream_error",
						Operation: spec.ID,
						TraceID:   trace,
						Message:   spec.ID + " returned a SOAP response that could not be read.",
					}
				}
				return value, nil
			}
		}

		if response.StatusCode >= 200 && response.StatusCode < 300 {
			return decode(raw), nil
		}

		code := HTTPStatusToErrorCode(response.StatusCode)
		retryAfterMs, retryAfterErr := ParseRetryAfter(response.Header.Get("Retry-After"), time.Now())
		hasRetryAfter := retryAfterErr == nil
		failure := &Error{
			Code:        code,
			Operation:   spec.ID,
			TraceID:     trace,
			Message:     fmt.Sprintf("%s failed upstream with HTTP %d.", spec.ID, response.StatusCode),
			Retryable:   IsRetryableCode(code),
			SafeToRetry: safeToRetry,
			Upstream:    &Upstream{Status: response.StatusCode, RequestID: response.Header.Get("X-Request-Id")},
		}
		if hasRetryAfter {
			failure.RetryAfterMs = retryAfterMs
		}
		if !containsInt(spec.Retry.RetryStatuses, response.StatusCode) || attempt >= maxAttempts {
			return nil, failure
		}
		if !safeToRetry {
			// A transient failure we are not allowed to repeat. Say exactly
			// that, rather than retrying a write whose duplicate we cannot rule
			// out.
			return nil, &Error{
				Code:      "unsafe_retry_blocked",
				Operation: spec.ID,
				TraceID:   trace,
				Message: fmt.Sprintf(
					"%s failed transiently (HTTP %d) but is not provably idempotent, so it was not retried. Retry deliberately with an idempotency key if the effect is safe to repeat.",
					spec.ID, response.StatusCode,
				),
				Upstream:     &Upstream{Status: response.StatusCode},
				RetryAfterMs: failure.RetryAfterMs,
			}
		}
		decision := ResolveRetryDelay(attempt, spec.Retry, retryAfterMs, hasRetryAfter, config.random)
		if decision.Stop {
			return nil, &Error{
				Code:      code,
				Operation: spec.ID,
				TraceID:   trace,
				Message: fmt.Sprintf(
					"%s asked to be retried in %dms, longer than this client will wait inside one call. Retry deliberately after that delay.",
					spec.ID, decision.RetryAfterMs,
				),
				Retryable:    true,
				SafeToRetry:  safeToRetry,
				RetryAfterMs: decision.RetryAfterMs,
			}
		}
		if err := sleepFor(ctx, decision.DelayMs, config.sleep); err != nil {
			return nil, failure
		}
	}
}

func sleepFor(ctx context.Context, delayMs int64, sleep func(time.Duration)) error {
	if delayMs <= 0 {
		return nil
	}
	if sleep != nil {
		sleep(time.Duration(delayMs) * time.Millisecond)
		return nil
	}
	timer := time.NewTimer(time.Duration(delayMs) * time.Millisecond)
	defer timer.Stop()
	select {
	case <-ctx.Done():
		return ctx.Err()
	case <-timer.C:
		return nil
	}
}

func containsInt(values []int, target int) bool {
	for _, value := range values {
		if value == target {
			return true
		}
	}
	return false
}

func field(value any, name string) any {
	object, ok := value.(map[string]any)
	if !ok {
		return nil
	}
	return object[name]
}
`;
}
