import { goPackage } from "./go-core.js";
import type { SdkPlan } from "./plan.js";

/**
 * The Go SDK's `safety.go`: the retry gate, the Retry-After arithmetic, and
 * the idempotency key derivation, mirrored from @anvil/runtime. Identical for
 * every service, so the four SDKs and the runtime make one decision.
 */

export function safetyFile(plan: SdkPlan): string {
  return `// Generated by Anvil. Do not edit — regenerate from AIR.
//
// The safety hot path, mirrored from @anvil/runtime. Identical decisions in
// every language Anvil emits: the same retry gate, the same Retry-After
// arithmetic, the same idempotency key derivation.

package ${goPackage(plan)}

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"math"
	"sort"
	"strconv"
	"strings"
	"time"
)

// MaxRetryDelayMs is the runtime-wide ceiling on a single pre-attempt sleep.
const MaxRetryDelayMs = 20000

// MaxIdempotencyKeyBytes bounds a caller-supplied key.
const MaxIdempotencyKeyBytes = 255

// RetryIsSafe reports whether automatic retry is safe for this operation.
//
// The guard behind the whole trust wedge: a mutation that is not provably
// idempotent is never retried, no matter what the policy says.
func RetryIsSafe(spec OperationSpec, hasIdempotencyKey bool) bool {
	if spec.Retry.Mode != "safe" {
		return false
	}
	if spec.Effect == "read" {
		return true
	}
	switch spec.Idempotency.Mode {
	case "natural", "client_id":
		return true
	case "required", "key_supported":
		return hasIdempotencyKey
	}
	return false
}

// ComputeBackoffMs is bounded exponential backoff with full jitter. attempt is
// 1-based: the delay applies before the (attempt+1)th try.
func ComputeBackoffMs(attempt int, retry RetrySpec, random func() float64) int64 {
	switch retry.Backoff {
	case "none":
		return 0
	case "fixed":
		if retry.BaseDelayMs < retry.MaxDelayMs {
			return retry.BaseDelayMs
		}
		return retry.MaxDelayMs
	}
	exp := float64(retry.BaseDelayMs) * math.Pow(2, float64(attempt-1))
	if exp > float64(retry.MaxDelayMs) {
		exp = float64(retry.MaxDelayMs)
	}
	if retry.Backoff == "exponential" {
		return int64(exp)
	}
	return int64(random() * exp)
}

var errNoRetryAfter = errors.New("no usable Retry-After")

// ParseRetryAfter is the upstream's own answer to "when should I come back?"
// (RFC 9110 section 10.2.3), in milliseconds from now. Both wire forms are
// accepted: delta-seconds and an HTTP-date. It reports errNoRetryAfter when the
// value is not a valid Retry-After at all, or names an instant already past —
// in both cases we have learned nothing.
func ParseRetryAfter(value string, now time.Time) (int64, error) {
	raw := strings.TrimSpace(value)
	if raw == "" {
		return 0, errNoRetryAfter
	}
	if seconds, err := strconv.ParseInt(raw, 10, 64); err == nil && seconds >= 0 {
		// Saturate rather than discard: an absurd delta is still an instruction
		// to stay away, and dropping it would let us hammer a service that just
		// asked us to stop.
		if seconds > math.MaxInt64/1000 {
			return math.MaxInt64, nil
		}
		return seconds * 1000, nil
	}
	at, err := time.Parse(time.RFC1123, raw)
	if err != nil {
		return 0, errNoRetryAfter
	}
	delta := at.Sub(now).Milliseconds()
	if delta < 0 {
		return 0, errNoRetryAfter
	}
	return delta, nil
}

// RetryDecision is what to do before the next attempt.
type RetryDecision struct {
	// Stop ends the attempt budget instead of sleeping.
	Stop         bool
	DelayMs      int64
	RetryAfterMs int64
}

// ResolveRetryDelay resolves the pre-attempt delay, honoring upstream
// backpressure over our own guess.
//
// An upstream asking for LONGER than the ceiling ends the attempt budget rather
// than clamping the sleep — clamping would mean knocking again early, which is
// how a rate limit becomes a ban. An upstream asking for LESS keeps our
// backoff: Retry-After is a floor on staying away, not permission to come back
// sooner and collapse jitter into a tight loop.
func ResolveRetryDelay(attempt int, retry RetrySpec, retryAfterMs int64, hasRetryAfter bool, random func() float64) RetryDecision {
	if hasRetryAfter && retryAfterMs > MaxRetryDelayMs {
		return RetryDecision{Stop: true, RetryAfterMs: retryAfterMs}
	}
	backoffMs := ComputeBackoffMs(attempt, retry, random)
	if !hasRetryAfter || retryAfterMs <= backoffMs {
		return RetryDecision{DelayMs: backoffMs}
	}
	return RetryDecision{DelayMs: retryAfterMs}
}

// CanonicalJSON is deterministic canonical JSON: object keys sorted, so equal
// inputs hash equal.
func CanonicalJSON(value any) string {
	var builder strings.Builder
	writeCanonical(&builder, value)
	return builder.String()
}

func writeCanonical(builder *strings.Builder, value any) {
	switch typed := value.(type) {
	case map[string]any:
		keys := make([]string, 0, len(typed))
		for key := range typed {
			keys = append(keys, key)
		}
		sort.Strings(keys)
		builder.WriteString("{")
		for index, key := range keys {
			if index > 0 {
				builder.WriteString(",")
			}
			encoded, _ := json.Marshal(key)
			builder.Write(encoded)
			builder.WriteString(":")
			writeCanonical(builder, typed[key])
		}
		builder.WriteString("}")
	case []any:
		builder.WriteString("[")
		for index, item := range typed {
			if index > 0 {
				builder.WriteString(",")
			}
			writeCanonical(builder, item)
		}
		builder.WriteString("]")
	default:
		encoded, err := json.Marshal(typed)
		if err != nil {
			builder.WriteString("null")
			return
		}
		builder.Write(encoded)
	}
}

// IdempotencyKeyIsTransportSafe is the portable caller-key contract: visible
// ASCII, at most 255 bytes.
func IdempotencyKeyIsTransportSafe(value string) bool {
	if value == "" || len(value) > MaxIdempotencyKeyBytes {
		return false
	}
	for _, r := range value {
		if r < 0x21 || r > 0x7e {
			return false
		}
	}
	return true
}

// RequestFingerprint is a stable fingerprint of a request: sha256 over the
// operation id and the canonicalized input.
func RequestFingerprint(operationID string, payload map[string]any) string {
	digest := sha256.New()
	digest.Write([]byte(operationID))
	digest.Write([]byte{0})
	digest.Write([]byte(CanonicalJSON(payload)))
	return hex.EncodeToString(digest.Sum(nil))
}

// ResolveIdempotencyKey applies caller-supplied, then fingerprint derivation,
// else none. An empty result means no key could be produced; the caller decides
// whether that is a refusal.
func ResolveIdempotencyKey(spec OperationSpec, provided string, payload map[string]any) (string, error) {
	if provided != "" {
		if !IdempotencyKeyIsTransportSafe(provided) {
			return "", fmt.Errorf("an idempotency key must be 1 to %d bytes of visible ASCII with no spaces or control characters", MaxIdempotencyKeyBytes)
		}
		return provided, nil
	}
	if spec.Idempotency.KeyDerivation == "request_fingerprint" {
		return "anvil-" + RequestFingerprint(spec.ID, payload)[:32], nil
	}
	return "", nil
}
`;
}
