import { goDryRunFile } from "./dry-run.js";
import { goGrantConfigFields, goGrantConstants, goGrantOptions, goGrantWiring } from "./go-auth.js";
import { errorsFile, goPackage, mtlsFile, specFile } from "./go-core.js";
import { invokeFile } from "./go-invoke.js";
import { safetyFile } from "./go-safety.js";
import { needsOauth, oauthGrantsOf } from "./oauth-grants.js";
import { oauthFile } from "./oauth-grants-go.js";
import type { SdkField, SdkOperation, SdkPager, SdkPlan } from "./plan.js";
import { safetyNotes, wrap } from "./shared.js";
import { GO_SOAP } from "./soap.js";

/**
 * The Go SDK — a zero-dependency module over `net/http`.
 *
 * Same split as every other language Anvil emits: `safety.go` and `invoke.go`
 * are the reviewed decision core, identical for every service, and generation
 * only adds rows to the operation table they read.
 */
export function generateGoSdk(plan: SdkPlan): Record<string, string> {
  const root = "sdk/go";
  return {
    [`${root}/go.mod`]: goMod(plan),
    [`${root}/README.md`]: readme(plan),
    [`${root}/errors.go`]: errorsFile(plan),
    [`${root}/safety.go`]: safetyFile(plan),
    [`${root}/spec.go`]: specFile(plan),
    [`${root}/operations.go`]: operationsFile(plan),
    [`${root}/invoke.go`]: invokeFile(plan),
    [`${root}/dryrun.go`]: goDryRunFile(goPackage(plan)),
    // mTLS and the OAuth grants are emitted only for the service that
    // declared the scheme — a bearer/api-key service never carries
    // crypto/tls plumbing or dead token-endpoint code.
    ...(plan.auth.tls ? { [`${root}/mtls.go`]: mtlsFile(plan) } : {}),
    ...(needsOauth(plan)
      ? { [`${root}/oauth.go`]: oauthFile(goPackage(plan), oauthGrantsOf(plan)) }
      : {}),
    [`${root}/client.go`]: clientFile(plan),
    // Always emitted, unlike the TypeScript one: `OperationSpec.Soap` is a
    // typed field, so `SoapBinding` has to exist even in a REST service. Go
    // permits unused package-level functions, so the cost is a file nothing
    // calls rather than a compile error.
    [`${root}/soap.go`]: `// Generated by Anvil. Do not edit — regenerate from AIR.\npackage ${goPackage(plan)}\n\nimport (\n\t"encoding/xml"\n\t"errors"\n\t"fmt"\n\t"sort"\n\t"strings"\n)\n${GO_SOAP}`,
  };
}

const g = (value: unknown): string => JSON.stringify(value);

function goPascal(source: string): string {
  return source
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join("");
}

function goType(field: SdkField): string {
  const base = (() => {
    switch (field.type) {
      case "string":
        return "string";
      case "integer":
        return "int64";
      case "number":
        return "float64";
      case "boolean":
        return "bool";
      case "array":
        return "[]any";
      case "object":
        return "map[string]any";
      default:
        return "any";
    }
  })();
  if (field.required) return base;
  // Slices, maps, and `any` already carry a nil that means "absent"; scalars do
  // not, so an optional scalar is a pointer rather than a zero value the wire
  // could not distinguish from an omission.
  return base === "string" || base === "int64" || base === "float64" || base === "bool"
    ? `*${base}`
    : base;
}

function isPointer(field: SdkField): boolean {
  return goType(field).startsWith("*");
}

function goMod(plan: SdkPlan): string {
  return `// Generated by Anvil. Do not edit — regenerate from AIR.
module github.com/anvil-sdk/${plan.service.id}

go 1.21
`;
}

function readme(plan: SdkPlan): string {
  const pkg = goPackage(plan);
  const first = plan.operations[0];
  const required = first ? first.params.filter((param) => param.required) : [];
  const usage = first
    ? [
        "```go",
        `client, err := ${pkg}.New()`,
        "if err != nil {",
        "\tlog.Fatal(err)",
        "}",
        `result, err := client.${first.names.pascal}(ctx, ${pkg}.${first.names.pascal}Input{`,
        ...required.map((param) => `\t${goPascal(param.key)}: "…",`),
        `}${
          first.confirmation.required || first.idempotency.callerKeyRequired
            ? `, ${pkg}.CallOptions{${first.confirmation.required ? "Confirm: true" : ""}${
                first.confirmation.required && first.idempotency.callerKeyRequired ? ", " : ""
              }${first.idempotency.callerKeyRequired ? 'IdempotencyKey: "order-1234"' : ""}}`
            : ""
        })`,
        "```",
      ].join("\n")
    : "_This bundle has no approved operations yet._";
  return `# ${plan.service.displayName} — Go SDK

${plan.service.description}

Generated by Anvil from AIR. Zero dependencies — \`net/http\` and \`encoding/json\`
from the standard library, so \`sdk/go/\` can be vendored directly.

${usage}

The credential is read from \`${plan.auth.envVar}\` when \`New\` is called without
\`WithToken\`. It is never logged, echoed, or included in an error.

Safety is not advisory: an operation that requires confirmation returns
\`*Error\` with \`Code == "confirmation_required"\` before anything reaches the
network, and a transient failure on a mutation that cannot prove idempotence
returns \`"unsafe_retry_blocked"\` rather than being sent twice.

Every call can be previewed: set \`CallOptions{DryRun: true}\` and the same
gates run, then a redacted request plan (\`map[string]any\`) comes back
instead of a response — nothing is sent and no credential is resolved. It is
the plan \`anvil run --dry-run\` prints.

See \`../README.md\` for the full cross-language contract.
`;
}

function operationsFile(plan: SdkPlan): string {
  const rows = plan.operations.map((op) => {
    const params = op.params
      .map(
        (param) =>
          `\t\t\t{WireName: ${g(param.wireName)}, Key: ${g(param.key)}, In: ${g(param.in)}, Required: ${param.required}${param.style ? `, Style: ${g(param.style)}` : ""}${param.explode !== undefined ? `, Explode: ${param.explode}, ExplodeSet: true` : ""}},`,
      )
      .join("\n");
    const body = op.body
      ? `&BodySpec{Required: ${op.body.required}, ContentType: ${g(op.body.contentType)}, Projection: ${g(op.body.projection)}, Fields: []BodyFieldSpec{${op.body.fields
          .map(
            (field) =>
              `{WireName: ${g(field.wireName)}, Key: ${g(field.key)}, Required: ${field.required}}`,
          )
          .join(", ")}}}`
      : "nil";
    const carrier = op.idempotency.carrier
      ? `&CarrierSpec{Mechanism: ${g(op.idempotency.carrier.mechanism)}, Key: ${g(op.idempotency.carrier.key)}, Path: ${
          op.idempotency.carrier.mechanism === "body"
            ? `[]string{${op.idempotency.carrier.path.map((segment) => g(segment)).join(", ")}}`
            : "nil"
        }}`
      : "nil";
    return `\t${g(op.names.pascal)}: {
		ID:         ${g(op.id)},
		HTTPMethod: ${g(op.httpMethod)},
		WireProtocol: ${g(op.wireProtocol)},${
      op.wireBinding?.protocol === "graphql"
        ? `\n\t\tGraphql: &GraphqlBinding{Document: ${g(op.wireBinding.document)}, OperationName: ${g(op.wireBinding.operationName)}, RootField: ${g(op.wireBinding.rootField)}},`
        : op.wireBinding?.protocol === "soap"
          ? `\n\t\tSoap: &SoapBinding{SoapAction: ${g(op.wireBinding.soapAction ?? "")}, EnvelopeNamespace: ${g(op.wireBinding.envelopeNamespace)}, BodyNamespace: ${g(op.wireBinding.bodyNamespace)}, BodyElement: ${g(op.wireBinding.bodyElement)}, ResponseElement: ${g(op.wireBinding.responseElement ?? "")}, ContentType: ${g(op.wireBinding.contentType)}, SoapVersion: ${g(op.wireBinding.soapVersion)}},`
          : ""
    }
		Path:       ${g(op.path)},
		Effect:     ${g(op.effect)},
		Params: []ParamSpec{
${params}
		},
		Body: ${body},
		Idempotency: IdempotencySpec{Mode: ${g(op.idempotency.mode)}, KeyDerivation: ${g(op.idempotency.keyDerivation)}, CallerKeyRequired: ${op.idempotency.callerKeyRequired}, Carrier: ${carrier}},
		Retry: RetrySpec{Mode: ${g(op.retry.mode)}, MaxAttempts: ${op.retry.maxAttempts}, Backoff: ${g(op.retry.backoff)}, BaseDelayMs: ${op.retry.baseDelayMs}, MaxDelayMs: ${op.retry.maxDelayMs}, RetryStatuses: []int{${op.retry.retryStatuses.join(", ")}}, RetryTransport: ${op.retry.retryTransport}},
		Confirmation: ConfirmationSpec{Required: ${op.confirmation.required}, HumanApproval: ${op.confirmation.humanApproval}, Reason: ${g(op.confirmation.reason ?? "")}},
	},`;
  });
  return `// Generated by Anvil. Do not edit — regenerate from AIR.
//
// One row per approved operation. An operation still in review is absent here,
// which is why it cannot be called: the SDK has no way to name it.

package ${goPackage(plan)}

// Operations is every approved operation, keyed by its Go method name.
var Operations = map[string]OperationSpec{
${rows.join("\n")}
}
`;
}

/**
 * The paging helper: a pager whose `Next` returns whole pages until the
 * upstream stops handing back a continuation. Every style advances the same
 * way — see `SdkPager` in plan.ts — and every one stops on a repeated
 * continuation, so a server that echoes its own cursor cannot spin forever.
 */
function goPager(op: SdkOperation, pager: SdkPager): string {
  const name = op.names.pascal;
  const k = g(pager.cursorKey);
  const items = pager.itemsField
    ? `\titems, _ := field(result, ${g(pager.itemsField)}).([]any)`
    : "\tvar items []any";
  const short =
    pager.pageSizeKey && pager.itemsField
      ? `\tshort := false\n\tif size, ok := pagerNumber(payload[${g(pager.pageSizeKey)}]); ok && float64(len(items)) < size {\n\t\tshort = true\n\t}`
      : "\tshort := false";
  let advance = "";
  switch (pager.style) {
    case "cursor":
      advance = `\tif s, ok := field(result, ${g(pager.nextField ?? "")}).(string); ok && s != "" {\n\t\tnext = s\n\t}`;
      break;
    case "link":
      advance = `\t// Only the continuation value is read out of the link; the URL itself is\n\t// never fetched, so paging can never leave the compiled base URL.\n\tif s, ok := field(result, ${g(pager.nextField ?? "")}).(string); ok && s != "" {\n\t\tif v := pagerLinkParam(s, ${g(pager.cursorParam)}); v != "" {\n\t\t\tnext = v\n\t\t}\n\t}`;
      break;
    case "page":
    case "offset": {
      const step = pager.style === "page" ? "1" : "float64(len(items))";
      advance = pager.nextField
        ? `\tswitch v := field(result, ${g(pager.nextField)}).(type) {\n\tcase float64:\n\t\tnext = v\n\tcase string:\n\t\tif v != "" {\n\t\t\tnext = v\n\t\t}\n\t}`
        : `\tif n, ok := pagerNumber(p.cursor); ok && len(items) > 0 && !short {\n\t\tnext = n + ${step}\n\t}`;
      break;
    }
  }
  const startValue =
    pager.start !== undefined
      ? `\n\tif p.cursor == nil {\n\t\tp.cursor = float64(${pager.start})\n\t}`
      : "";
  const clamp =
    pager.pageSizeKey && pager.maxPageSize
      ? `\n\tif size, ok := pagerNumber(payload[${g(pager.pageSizeKey)}]); ok && size > ${pager.maxPageSize} {\n\t\tpayload[${g(pager.pageSizeKey)}] = float64(${pager.maxPageSize})\n\t}`
      : "";
  return `// ${name}Pager pages through ${op.canonicalName} (${pager.style} pagination) until the
// upstream stops handing back a continuation.
type ${name}Pager struct {
	client  *Client
	input   ${name}Input
	options CallOptions
	cursor  any
	done    bool
	seen    map[string]bool
}

// ${name}Paginated builds a pager over ${op.canonicalName}.
func (c *Client) ${name}Paginated(in ${name}Input, options ...CallOptions) *${name}Pager {
	p := &${name}Pager{client: c, input: in, options: firstCallOptions(options), seen: map[string]bool{}}
	p.cursor = in.payload()[${k}]${startValue}
	return p
}

// Next returns the next page. The second result is false once the upstream
// stops handing back a continuation.
func (p *${name}Pager) Next(ctx context.Context) (any, bool, error) {
	if p.done {
		return nil, false, nil
	}
	payload := p.input.payload()
	if p.cursor != nil {
		payload[${k}] = p.cursor
	}${clamp}
	result, err := invoke(ctx, p.client.config, Operations[${g(name)}], payload, p.options)
	if err != nil {
		return nil, false, err
	}
${items}
${short}
	var next any
${advance}
	// A server that echoes its own continuation would page the same page
	// forever; stop instead of paging until the process is killed.
	if next == nil {
		p.done = true
		return result, true, nil
	}
	key := fmt.Sprint(next)
	if p.seen[key] {
		p.done = true
		return result, true, nil
	}
	p.seen[key] = true
	p.cursor = next
	return result, true, nil
}`;
}

const GO_PAGER_HELPERS = `
// pagerNumber reads a page number, offset, or page size however the caller
// or the upstream typed it.
func pagerNumber(v any) (float64, bool) {
	switch n := v.(type) {
	case float64:
		return n, true
	case float32:
		return float64(n), true
	case int:
		return float64(n), true
	case int32:
		return float64(n), true
	case int64:
		return float64(n), true
	case string:
		if f, err := strconv.ParseFloat(n, 64); err == nil {
			return f, true
		}
	}
	return 0, false
}
`;

const GO_LINK_HELPER = `
// pagerLinkParam reads the continuation parameter out of a next-page link
// without ever fetching the link.
func pagerLinkParam(link, name string) string {
	u, err := url.Parse(link)
	if err != nil {
		return ""
	}
	return u.Query().Get(name)
}
`;

function clientFile(plan: SdkPlan): string {
  const pkg = goPackage(plan);
  const anyPager = plan.operations.some((op) => op.pager !== undefined);
  const anyLinkPager = plan.operations.some((op) => op.pager?.style === "link");
  const methods = [
    ...plan.operations.map((op) => goMethod(op)),
    ...(anyPager ? [GO_PAGER_HELPERS] : []),
    ...(anyLinkPager ? [GO_LINK_HELPER] : []),
  ].join("\n\n");
  const inputs = plan.operations.map((op) => goInputStruct(op)).join("\n\n");
  const tls = plan.auth.tls;
  const refresh = plan.auth.tokenRefresh;
  return `// Generated by Anvil. Do not edit — regenerate from AIR.

package ${pkg}

import (
	"context"${anyPager ? '\n\t"fmt"' : ""}
	"math/rand"
	"net/http"${anyLinkPager ? '\n\t"net/url"' : ""}
	"os"${anyPager ? '\n\t"strconv"' : ""}
	"time"
)

// DefaultBaseURL is the base URL recorded in AIR at compile time.
const DefaultBaseURL = ${g(plan.service.baseUrl)}

// TokenEnvVar is the environment variable read when no credential is
// supplied.${
    tls
      ? " Unused for this service — mtls carries no header or token; see\n// ClientCertEnvVar / ClientKeyEnvVar instead."
      : plan.auth.type === "custom_header"
        ? " Holds the raw header value — no scheme prefix is added."
        : ""
  }
const TokenEnvVar = ${g(plan.auth.envVar)}
${
  tls
    ? `
// Client-certificate material, by environment-variable NAME only — never PEM
// in generated code.
const ClientCertEnvVar = ${g(tls.certEnvVar)}
const ClientKeyEnvVar = ${g(tls.keyEnvVar)}
${tls.caEnvVar ? `const CaEnvVar = ${g(tls.caEnvVar)}\n` : ""}`
    : ""
}${
  refresh
    ? `
// Refresh-token wiring for the authorization-code grant (RFC 6749 section 6).
const TokenEndpoint = ${g(refresh.tokenEndpoint)}
const RefreshTokenEnvVar = ${g(refresh.refreshTokenEnvVar)}
const ClientIDEnvVar = ${g(refresh.clientIdEnvVar)}
const ClientSecretEnvVar = ${g(refresh.clientSecretEnvVar)}

// TokenClientAuth is how the refresh grant authenticates to the token
// endpoint — the same method the runtime uses for this contract.
const TokenClientAuth = ${g(refresh.clientAuth)}
`
    : ""
}${goGrantConstants(plan)}
const userAgent = ${g(`anvil-sdk-${plan.service.id}/${plan.service.version} (go)`)}

// AuthCarrier is where the credential travels on the wire.
type AuthCarrier struct {
	In     string
	Name   string
	Scheme string
}

var authCarrier = ${
    plan.auth.carrier
      ? `&AuthCarrier{In: ${g(plan.auth.carrier.in)}, Name: ${g(plan.auth.carrier.name)}, Scheme: ${g(plan.auth.carrier.scheme ?? "")}}`
      : "(*AuthCarrier)(nil)"
  }

type clientConfig struct {
	baseURL string
	// protocolFacade is the operator's stated reason that baseURL really does
	// serve the synthesized coordinates of a non-HTTP/JSON source over
	// HTTP+JSON. A declaration, never an inference.
	protocolFacade string
	token          string
	// tokenProvider, when set, is called once per call and takes priority
	// over a static token — the delegated-token source for
	// oauth2_authorization_code. Never logged or echoed; only its resolved
	// return value reaches the wire, and only as a header/query value.
	tokenProvider func(context.Context) (string, error)${goGrantConfigFields(plan)}
	authCarrier   *AuthCarrier
	timeout       time.Duration
	httpClient    *http.Client
	random        func() float64
	sleep         func(time.Duration)
	userAgent     string
}

// Client is ${plan.service.description}
//
// Every method is one approved operation. The safety gates live in invoke, so
// no method can skip them.
type Client struct {
	config clientConfig
}

// Option configures a Client.
type Option func(*clientConfig)

// WithBaseURL overrides the compiled-in upstream base URL.
func WithBaseURL(baseURL string) Option {
	return func(config *clientConfig) { config.baseURL = baseURL }
}

// WithProtocolFacade declares that the base URL really does serve the
// synthesized coordinates of a non-HTTP/JSON source (SOAP, GraphQL, gRPC) over
// HTTP+JSON. Without it those operations are refused rather than sent.
func WithProtocolFacade(reason string) Option {
	return func(config *clientConfig) { config.protocolFacade = reason }
}

// WithToken sets the credential this SDK carries. It is never logged, echoed,
// or included in an error.
func WithToken(token string) Option {
	return func(config *clientConfig) { config.token = token }
}

// WithTokenProvider sets a delegated-token source for oauth2_authorization_code:
// called once per call, taking priority over WithToken. It is never logged,
// echoed, or included in an error.
func WithTokenProvider(provider func(context.Context) (string, error)) Option {
	return func(config *clientConfig) { config.tokenProvider = provider }
}

${goGrantOptions(plan)}// WithHTTPClient injects a transport, for tests and embedders.
func WithHTTPClient(httpClient *http.Client) Option {
	return func(config *clientConfig) { config.httpClient = httpClient }
}

// WithTimeout sets the per-request deadline.
func WithTimeout(timeout time.Duration) Option {
	return func(config *clientConfig) { config.timeout = timeout }
}

// WithRandom injects the jitter source, so a retry schedule is deterministic
// under test.
func WithRandom(random func() float64) Option {
	return func(config *clientConfig) { config.random = random }
}

// WithSleep injects the backoff sleep, so a retry schedule is assertable.
func WithSleep(sleep func(time.Duration)) Option {
	return func(config *clientConfig) { config.sleep = sleep }
}

// New builds a client. Without WithToken it reads ${plan.auth.envVar}.
func New(options ...Option) (*Client, error) {
	config := clientConfig{
		baseURL:        DefaultBaseURL,
		protocolFacade: os.Getenv("ANVIL_PROTOCOL_FACADE"),
		token:          os.Getenv(TokenEnvVar),
		authCarrier: authCarrier,
		timeout:     30 * time.Second,
		random:      rand.Float64,
		userAgent:   userAgent,
	}
	for _, option := range options {
		option(&config)
	}
	if config.baseURL == "" {
		return nil, &Error{
			Code:              ${g("validation_error")},
			Operation:         ${g(plan.service.id)},
			Message:           "No base URL: the compiled model records no server, so one must be passed with WithBaseURL.",
			RequiredArguments: []string{"WithBaseURL"},
		}
	}
${
  tls
    ? `	// mTLS: an explicit WithHTTPClient always wins; otherwise a client is
	// built from the declared certificate/key (and CA, when named) once,
	// at construction.
	if config.httpClient == nil {
		cert, key := os.Getenv(ClientCertEnvVar), os.Getenv(ClientKeyEnvVar)
		if cert != "" && key != "" {
			mtlsClient, err := NewMtlsHTTPClient(cert, key, ${tls.caEnvVar ? "os.Getenv(CaEnvVar)" : `""`})
			if err != nil {
				return nil, &Error{
					Code:      ${g("validation_error")},
					Operation: ${g(plan.service.id)},
					Message:   "mTLS client certificate could not be loaded: " + err.Error(),
				}
			}
			config.httpClient = mtlsClient
		}
	}
`
    : ""
}${
  refresh
    ? `	// A caller-supplied WithToken or WithTokenProvider always wins. Only
	// when neither is set, and a refresh token is available, does the
	// client mint its own provider from the declared token endpoint.
	if config.tokenProvider == nil && config.token == "" {
		refreshToken, clientID := os.Getenv(RefreshTokenEnvVar), os.Getenv(ClientIDEnvVar)
		if refreshToken != "" && clientID != "" {
			config.tokenProvider = NewRefreshingTokenProvider(TokenEndpoint, refreshToken, clientID, os.Getenv(ClientSecretEnvVar), TokenClientAuth)
		}
	}
`
    : ""
}${goGrantWiring(plan)}	if config.httpClient == nil {
		config.httpClient = http.DefaultClient
	}
	if config.random == nil {
		config.random = rand.Float64
	}
	return &Client{config: config}, nil
}

${inputs}

${methods}
`;
}

function goInputStruct(op: SdkOperation): string {
  const fields: string[] = [];
  const assignments: string[] = [];
  const push = (field: SdkField, source: string) => {
    const name = goPascal(field.key);
    const doc = field.description ? `\t// ${field.description}\n` : "";
    fields.push(`${doc}\t${name} ${goType(field)} \`json:${g(`${field.key},omitempty`)}\``);
    if (field.required) {
      assignments.push(`\tpayload[${g(field.key)}] = in.${name}`);
    } else if (isPointer(field)) {
      assignments.push(`\tif in.${name} != nil {\n\t\tpayload[${g(field.key)}] = *in.${name}\n\t}`);
    } else {
      assignments.push(`\tif in.${name} != nil {\n\t\tpayload[${g(field.key)}] = in.${name}\n\t}`);
    }
    void source;
  };
  for (const param of op.params) push(param, param.in);
  if (op.body?.projection === "fields") {
    for (const field of op.body.fields) push(field, "body");
  } else if (op.body) {
    push(
      {
        wireName: "body",
        key: "body",
        required: op.body.required,
        type: "any",
        description: `The request body, sent verbatim (content type ${op.body.contentType}).`,
      },
      "body",
    );
  }
  return `// ${op.names.pascal}Input is the input for ${op.canonicalName}.
type ${op.names.pascal}Input struct {
${fields.length > 0 ? fields.join("\n") : "\t// This operation takes no input."}
}

func (in ${op.names.pascal}Input) payload() map[string]any {
	payload := map[string]any{}
${assignments.join("\n")}
	return payload
}`;
}

function goMethod(op: SdkOperation): string {
  const doc = [`// ${op.names.pascal} — ${op.description}`, "//"]
    .concat(safetyNotes(op).flatMap((note) => wrap(note, 72).map((line) => `// ${line}`)))
    .join("\n");
  const lines = [
    doc,
    `func (c *Client) ${op.names.pascal}(ctx context.Context, in ${op.names.pascal}Input, options ...CallOptions) (any, error) {`,
    `\treturn invoke(ctx, c.config, Operations[${g(op.names.pascal)}], in.payload(), firstCallOptions(options))`,
    "}",
  ];

  const pager = op.pager;
  if (pager) {
    lines.push("", goPager(op, pager));
  }

  const contract = op.async;
  if (contract?.statusMethodBase && contract.statusJobIdKey && contract.terminalStates.length > 0) {
    const statusPascal = goPascal(contract.statusMethodBase);
    const statusJobIdKey = contract.statusJobIdKey;
    lines.push(
      "",
      `// WaitFor${op.names.pascal} — ${contract.instruction}`,
      "//",
      "// It polls at the interval the contract declares and returns the first status",
      "// response in a terminal state. Every field name below is the one AIR",
      "// resolved — none is guessed.",
      `func (c *Client) WaitFor${op.names.pascal}(ctx context.Context, submitResult any, timeout time.Duration) (any, error) {
	handle, ok := field(submitResult, ${g(contract.jobIdField)}).(string)
	if !ok || handle == "" {
		return nil, &Error{Code: "schema_mismatch", Operation: ${g(op.id)}, Message: "The submit response carried no ${contract.jobIdField} to poll on."}
	}
	if timeout <= 0 {
		timeout = ${contract.pollIntervalSeconds * 60} * time.Second
	}
	deadline := time.Now().Add(timeout)
	terminal := map[string]bool{${contract.terminalStates.map((state) => `${g(state)}: true`).join(", ")}}
	for {
		status, err := c.${statusPascal}(ctx, ${statusPascal}Input{${goPascal(statusJobIdKey)}: handle})
		if err != nil {
			return nil, err
		}
		if state, isString := field(status, ${g(contract.stateField ?? "state")}).(string); isString && terminal[state] {
			return status, nil
		}
		if time.Now().After(deadline) {
			return nil, &Error{Code: "upstream_timeout", Operation: ${g(op.id)}, Message: "${op.canonicalName} did not reach a terminal state before the wait deadline.", Retryable: true}
		}
		if err := sleepFor(ctx, ${contract.pollIntervalSeconds * 1000}, c.config.sleep); err != nil {
			return nil, err
		}
	}
}`,
    );
  }
  return lines.join("\n");
}
