/**
 * The Java SDK's call path: the retry gate and Retry-After arithmetic in
 * `Safety`, and the single `Invoker.invoke` every generated method funnels
 * through. Identical for every service, so a method that skipped a gate would
 * have to be a change here rather than a quiet difference in one emitted client.
 */

export function safetyFile(pkg: string): string {
  return `// Generated by Anvil. Do not edit — regenerate from AIR.
package ${pkg};

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.time.Instant;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

/**
 * The safety hot path, mirrored from the Anvil runtime. Identical decisions in
 * every language Anvil emits: the same retry gate, the same Retry-After
 * arithmetic, the same idempotency key derivation.
 */
public final class Safety {

  /** The runtime-wide ceiling on a single pre-attempt sleep. */
  public static final long MAX_RETRY_DELAY_MS = 20000L;

  public static final int MAX_IDEMPOTENCY_KEY_BYTES = 255;

  private Safety() {}

  /**
   * Whether automatic retry is safe for this operation. The guard behind the
   * whole trust wedge: a mutation that is not provably idempotent is never
   * retried, no matter what the policy says.
   */
  public static boolean retryIsSafe(OperationSpec spec, boolean hasIdempotencyKey) {
    if (!"safe".equals(spec.retry.mode)) {
      return false;
    }
    if ("read".equals(spec.effect)) {
      return true;
    }
    String mode = spec.idempotency.mode;
    if ("natural".equals(mode) || "client_id".equals(mode)) {
      return true;
    }
    if ("required".equals(mode) || "key_supported".equals(mode)) {
      return hasIdempotencyKey;
    }
    return false;
  }

  /** Bounded exponential backoff with full jitter. {@code attempt} is 1-based. */
  public static long computeBackoffMs(int attempt, OperationSpec.Retry retry, double draw) {
    if ("none".equals(retry.backoff)) {
      return 0L;
    }
    if ("fixed".equals(retry.backoff)) {
      return Math.min(retry.baseDelayMs, retry.maxDelayMs);
    }
    double exp = Math.min((double) retry.maxDelayMs, retry.baseDelayMs * Math.pow(2, attempt - 1));
    if ("exponential".equals(retry.backoff)) {
      return (long) exp;
    }
    return (long) (draw * exp);
  }

  /**
   * The upstream's own answer to "when should I come back?" (RFC 9110 section
   * 10.2.3), in milliseconds from {@code now}. Both wire forms are accepted:
   * delta-seconds and an HTTP-date. Returns -1 when the value is not a valid
   * Retry-After at all, or names an instant already past — in both cases we
   * have learned nothing.
   */
  public static long parseRetryAfter(String value, Instant now) {
    if (value == null) {
      return -1L;
    }
    String raw = value.trim();
    if (raw.isEmpty()) {
      return -1L;
    }
    boolean digits = true;
    for (int index = 0; index < raw.length(); index++) {
      if (!Character.isDigit(raw.charAt(index))) {
        digits = false;
        break;
      }
    }
    if (digits) {
      try {
        // Saturate rather than discard: an absurd delta is still an instruction
        // to stay away, and dropping it would let us hammer a service that just
        // asked us to stop.
        return Math.multiplyExact(Long.parseLong(raw), 1000L);
      } catch (ArithmeticException overflow) {
        return Long.MAX_VALUE;
      } catch (NumberFormatException malformed) {
        return -1L;
      }
    }
    try {
      ZonedDateTime at = ZonedDateTime.parse(raw, DateTimeFormatter.RFC_1123_DATE_TIME);
      long delta = at.toInstant().toEpochMilli() - now.toEpochMilli();
      return delta < 0 ? -1L : delta;
    } catch (DateTimeParseException malformed) {
      return -1L;
    }
  }

  /** What to do before the next attempt. */
  public static final class RetryDecision {
    /** True when the attempt budget ends instead of sleeping. */
    public final boolean stop;

    public final long delayMs;

    RetryDecision(boolean stop, long delayMs) {
      this.stop = stop;
      this.delayMs = delayMs;
    }
  }

  /**
   * Resolve the pre-attempt delay, honoring upstream backpressure over our own
   * guess.
   *
   * <p>An upstream asking for LONGER than the ceiling ends the attempt budget
   * rather than clamping the sleep — clamping would mean knocking again early,
   * which is how a rate limit becomes a ban. An upstream asking for LESS keeps
   * our backoff: Retry-After is a floor on staying away, not permission to come
   * back sooner and collapse jitter into a tight loop.
   */
  public static RetryDecision resolveRetryDelay(
      int attempt, OperationSpec.Retry retry, long retryAfterMs, double draw) {
    if (retryAfterMs >= 0 && retryAfterMs > MAX_RETRY_DELAY_MS) {
      return new RetryDecision(true, retryAfterMs);
    }
    long backoffMs = computeBackoffMs(attempt, retry, draw);
    if (retryAfterMs < 0 || retryAfterMs <= backoffMs) {
      return new RetryDecision(false, backoffMs);
    }
    return new RetryDecision(false, retryAfterMs);
  }

  /** Deterministic canonical JSON: object keys sorted, so equal inputs hash equal. */
  public static String canonicalJson(Object value) {
    return Json.write(sortKeys(value));
  }

  @SuppressWarnings("unchecked")
  private static Object sortKeys(Object value) {
    if (value instanceof Map) {
      Map<String, Object> sorted = new TreeMap<String, Object>();
      for (Map.Entry<?, ?> entry : ((Map<?, ?>) value).entrySet()) {
        sorted.put(String.valueOf(entry.getKey()), sortKeys(entry.getValue()));
      }
      return sorted;
    }
    if (value instanceof Iterable) {
      List<Object> out = new ArrayList<Object>();
      for (Object item : (Iterable<Object>) value) {
        out.add(sortKeys(item));
      }
      return Collections.unmodifiableList(out);
    }
    return value;
  }

  /** Portable caller-key contract: visible ASCII, at most 255 bytes. */
  public static boolean idempotencyKeyIsTransportSafe(String value) {
    if (value == null || value.isEmpty()) {
      return false;
    }
    if (value.getBytes(StandardCharsets.UTF_8).length > MAX_IDEMPOTENCY_KEY_BYTES) {
      return false;
    }
    for (int index = 0; index < value.length(); index++) {
      char character = value.charAt(index);
      if (character < 0x21 || character > 0x7e) {
        return false;
      }
    }
    return true;
  }

  /** A stable fingerprint: sha256 over the operation id and canonical input. */
  public static String requestFingerprint(String operationId, Map<String, Object> payload) {
    try {
      MessageDigest digest = MessageDigest.getInstance("SHA-256");
      digest.update(operationId.getBytes(StandardCharsets.UTF_8));
      digest.update(new byte[] {0});
      digest.update(canonicalJson(payload).getBytes(StandardCharsets.UTF_8));
      byte[] bytes = digest.digest();
      StringBuilder out = new StringBuilder(bytes.length * 2);
      for (byte item : bytes) {
        out.append(Character.forDigit((item >> 4) & 0xf, 16));
        out.append(Character.forDigit(item & 0xf, 16));
      }
      return out.toString();
    } catch (NoSuchAlgorithmException impossible) {
      throw new IllegalStateException("SHA-256 is required by the Java platform", impossible);
    }
  }

  /**
   * Caller-supplied key, else fingerprint derivation, else none. Returns null
   * when no key can be produced; the caller decides whether that is a refusal.
   */
  public static String resolveIdempotencyKey(
      OperationSpec spec, String provided, Map<String, Object> payload) {
    if (provided != null && !provided.isEmpty()) {
      if (!idempotencyKeyIsTransportSafe(provided)) {
        throw AnvilException.builder("validation_error", spec.id,
                "An idempotency key must be 1 to 255 bytes of visible ASCII with no spaces or control characters.")
            .build();
      }
      return provided;
    }
    if ("request_fingerprint".equals(spec.idempotency.keyDerivation)) {
      return "anvil-" + requestFingerprint(spec.id, payload).substring(0, 32);
    }
    return null;
  }
}
`;
}

export function invokerFile(pkg: string): string {
  return `// Generated by Anvil. Do not edit — regenerate from AIR.
package ${pkg};

import java.io.IOException;
import java.net.URI;
import java.net.URLEncoder;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.UUID;

/**
 * The one call path. Every generated method funnels through {@link #invoke}, so
 * the gates below cannot be bypassed by a method that forgot to check.
 */
final class Invoker {

  /** Headers the transport owns; a caller override would break the contract. */
  private static final Set<String> RESERVED_HEADERS =
      new HashSet<String>(
          Arrays.asList(
              "authorization", "content-length", "content-type", "host", "transfer-encoding"));

  private Invoker() {}

  /** The resolved client configuration one call runs under. */
  static final class Config {
    final String baseUrl;
    /**
     * The operator's stated reason that baseUrl really does serve the
     * synthesized coordinates of a non-HTTP/JSON source over HTTP+JSON. A
     * declaration, never an inference.
     */
    final String protocolFacade;

    final String token;
    final String authIn;
    final String authName;
    final String authScheme;
    final Duration timeout;
    final HttpClient httpClient;
    final String userAgent;
    final java.util.function.DoubleSupplier random;

    Config(
        String baseUrl,
        String protocolFacade,
        String token,
        String authIn,
        String authName,
        String authScheme,
        Duration timeout,
        HttpClient httpClient,
        String userAgent,
        java.util.function.DoubleSupplier random) {
      this.baseUrl = baseUrl;
      this.protocolFacade = protocolFacade;
      this.token = token;
      this.authIn = authIn;
      this.authName = authName;
      this.authScheme = authScheme;
      this.timeout = timeout;
      this.httpClient = httpClient;
      this.userAgent = userAgent;
      this.random = random;
    }
  }

  private static String traceId() {
    return UUID.randomUUID().toString();
  }

  /**
   * The transport gate. The confirmation gate asks whether the caller intends
   * the effect; this asks whether this client can express the call at all. A
   * SOAP, GraphQL, or gRPC operation arrives with a path Anvil invented, and
   * sending JSON to it would be a well-formed lie. Mirrors the runtime's own
   * gate so every surface refuses alike.
   */
  static void assertWireExecutable(OperationSpec spec, Config config) {
    if ("http_json".equals(spec.wireProtocol) || config.protocolFacade != null) {
      return;
    }
    throw AnvilException.builder(
            "unsupported_operation",
            spec.id,
            spec.id
                + " speaks "
                + spec.wireProtocol
                + ", which this client cannot put on the wire: "
                + spec.httpMethod
                + " "
                + spec.path
                + " is a coordinate Anvil synthesized, not an address the service serves."
                + " Point builder().baseUrl(...) at a facade that really does serve it over"
                + " HTTP+JSON and pass protocolFacade(...) with the reason, so the assumption"
                + " is recorded.")
        .traceId(traceId())
        .build();
  }

  /** The confirmation gate. Refuses before anything reaches the wire. */
  static void assertConfirmed(OperationSpec spec, CallOptions options) {
    if (!spec.confirmation.required || options.confirmed()) {
      return;
    }
    String audience =
        spec.confirmation.humanApproval
            ? "This effect needs explicit human approval, not a self-confirmation."
            : "Call CallOptions.none().confirm(true) once you intend the effect.";
    String reason =
        spec.confirmation.reason == null || spec.confirmation.reason.isEmpty()
            ? ""
            : ": " + spec.confirmation.reason;
    throw AnvilException.builder(
            "confirmation_required",
            spec.id,
            spec.id + " requires confirmation" + reason + ". " + audience)
        .traceId(traceId())
        .requiredArguments("confirm")
        .build();
  }

  /** The idempotency gate. A contract that demands a key gets one or a refusal. */
  static void assertKeyed(OperationSpec spec, String key) {
    if (!spec.idempotency.callerKeyRequired || (key != null && !key.isEmpty())) {
      return;
    }
    throw AnvilException.builder(
            "idempotency_required",
            spec.id,
            spec.id
                + " requires an idempotency key that Anvil cannot derive for you. Set"
                + " CallOptions.idempotencyKey — reuse the same value to retry the same intent.")
        .traceId(traceId())
        .requiredArguments("idempotencyKey")
        .build();
  }

  @SuppressWarnings("unchecked")
  private static Object setBodyCarrier(Object body, List<String> path, String value) {
    Map<String, Object> root =
        body instanceof Map
            ? new LinkedHashMap<String, Object>((Map<String, Object>) body)
            : new LinkedHashMap<String, Object>();
    Map<String, Object> cursor = root;
    for (int index = 0; index < path.size() - 1; index++) {
      Object existing = cursor.get(path.get(index));
      Map<String, Object> child =
          existing instanceof Map
              ? new LinkedHashMap<String, Object>((Map<String, Object>) existing)
              : new LinkedHashMap<String, Object>();
      cursor.put(path.get(index), child);
      cursor = child;
    }
    cursor.put(path.get(path.size() - 1), value);
    return root;
  }

  private static String scalar(Object value) {
    if (value instanceof String) {
      return (String) value;
    }
    if (value instanceof Double || value instanceof Float) {
      double asDouble = ((Number) value).doubleValue();
      if (asDouble == Math.rint(asDouble) && !Double.isInfinite(asDouble)) {
        return Long.toString((long) asDouble);
      }
    }
    return String.valueOf(value);
  }

  /**
   * Percent-encode one path segment. {@link URLEncoder} implements
   * form encoding, where a space becomes {@code +} — which in a path means a
   * literal plus, not a space — so the one difference is undone here.
   */
  private static String encodePath(String value) {
    return URLEncoder.encode(value, StandardCharsets.UTF_8).replace("+", "%20");
  }

  /**
   * Encode one query name or value. Form encoding is exactly right here, and
   * the {@code +} for a space is deliberately kept: the TypeScript, Python, and
   * Go SDKs all emit {@code +} in a query string, and four clients built from
   * one contract should put the same bytes on the wire.
   */
  private static String encodeQuery(String value) {
    return URLEncoder.encode(value, StandardCharsets.UTF_8);
  }

  /** Build the upstream request from the operation spec and caller payload. */
  static HttpRequest buildRequest(
      OperationSpec spec,
      Map<String, Object> payload,
      Config config,
      String idempotencyKey,
      Map<String, String> extraHeaders,
      Duration timeout) {
    String path = spec.path;
    List<String[]> query = new ArrayList<String[]>();
    Map<String, String> headers = new LinkedHashMap<String, String>();
    headers.put("accept", "application/json");
    headers.put("user-agent", config.userAgent);
    for (Map.Entry<String, String> entry : extraHeaders.entrySet()) {
      if (!RESERVED_HEADERS.contains(entry.getKey().toLowerCase())) {
        headers.put(entry.getKey().toLowerCase(), entry.getValue());
      }
    }
    Map<String, Object> body = new LinkedHashMap<String, Object>();
    boolean hasBody = false;
    StringBuilder cookie = new StringBuilder();

    for (OperationSpec.Param param : spec.params) {
      Object value = payload.get(param.key);
      if (value == null) {
        continue;
      }
      if ("path".equals(param.in)) {
        path = path.replace("{" + param.wireName + "}", encodePath(scalar(value)));
      } else if ("query".equals(param.in)) {
        query.add(new String[] {param.wireName, scalar(value)});
      } else if ("header".equals(param.in)) {
        headers.put(param.wireName, scalar(value));
      } else if ("cookie".equals(param.in)) {
        if (cookie.length() > 0) {
          cookie.append("; ");
        }
        cookie.append(param.wireName).append('=').append(scalar(value));
      } else if ("body".equals(param.in)) {
        body.put(param.wireName, value);
        hasBody = true;
      }
    }

    Object bodyValue = hasBody ? body : null;
    if (spec.body != null) {
      if ("fields".equals(spec.body.projection)) {
        for (OperationSpec.BodyField field : spec.body.fields) {
          Object value = payload.get(field.key);
          if (value == null) {
            continue;
          }
          body.put(field.wireName, value);
          hasBody = true;
        }
        if (hasBody) {
          bodyValue = body;
        }
      } else if (payload.get("body") != null) {
        bodyValue = payload.get("body");
        hasBody = true;
      }
    }

    if (spec.idempotency.carrier != null && idempotencyKey != null && !idempotencyKey.isEmpty()) {
      OperationSpec.Carrier carrier = spec.idempotency.carrier;
      if ("header".equals(carrier.mechanism)) {
        // HTTP field names are case-insensitive; drop any modeled spelling
        // before injecting the one authoritative safety value.
        Iterator<String> names = headers.keySet().iterator();
        while (names.hasNext()) {
          if (names.next().equalsIgnoreCase(carrier.key)) {
            names.remove();
          }
        }
        headers.put(carrier.key, idempotencyKey);
      } else if ("query".equals(carrier.mechanism)) {
        query.removeIf(pair -> pair[0].equals(carrier.key));
        query.add(new String[] {carrier.key, idempotencyKey});
      } else if ("path".equals(carrier.mechanism)) {
        path = path.replace("{" + carrier.key + "}", encodePath(idempotencyKey));
      } else if ("body".equals(carrier.mechanism)) {
        List<String> carrierPath =
            carrier.path.isEmpty() ? Arrays.asList(carrier.key) : carrier.path;
        bodyValue = setBodyCarrier(bodyValue, carrierPath, idempotencyKey);
        hasBody = true;
      }
    }

    if (config.token != null && !config.token.isEmpty() && config.authName != null) {
      if ("header".equals(config.authIn)) {
        String value =
            config.authScheme == null || config.authScheme.isEmpty()
                ? config.token
                : config.authScheme + " " + config.token;
        headers.put(config.authName.toLowerCase(), value);
      } else {
        query.add(new String[] {config.authName, config.token});
      }
    }
    if (cookie.length() > 0) {
      headers.put("cookie", cookie.toString());
    }

    StringBuilder target = new StringBuilder();
    String base = config.baseUrl;
    while (base.endsWith("/")) {
      base = base.substring(0, base.length() - 1);
    }
    target.append(base).append(path);
    for (int index = 0; index < query.size(); index++) {
      target.append(index == 0 ? '?' : '&');
      target
          .append(encodeQuery(query.get(index)[0]))
          .append('=')
          .append(encodeQuery(query.get(index)[1]));
    }

    HttpRequest.BodyPublisher publisher = HttpRequest.BodyPublishers.noBody();
    if (hasBody) {
      headers.put(
          "content-type",
          spec.body == null || spec.body.contentType.isEmpty()
              ? "application/json"
              : spec.body.contentType);
      publisher = HttpRequest.BodyPublishers.ofString(Json.write(bodyValue));
    }
    HttpRequest.Builder builder =
        HttpRequest.newBuilder(URI.create(target.toString()))
            .timeout(timeout)
            .method(spec.httpMethod, publisher);
    for (Map.Entry<String, String> entry : headers.entrySet()) {
      builder.header(entry.getKey(), entry.getValue());
    }
    return builder.build();
  }

  /**
   * Run one operation end to end: gate, build, send, and retry only where the
   * contract proves retrying is safe.
   */
  static Object invoke(
      Config config, OperationSpec spec, Map<String, Object> rawPayload, CallOptions options) {
    assertWireExecutable(spec, config);
    assertConfirmed(spec, options);
    Map<String, Object> payload = new LinkedHashMap<String, Object>();
    for (Map.Entry<String, Object> entry : rawPayload.entrySet()) {
      if (entry.getValue() != null) {
        payload.put(entry.getKey(), entry.getValue());
      }
    }
    String idempotencyKey = Safety.resolveIdempotencyKey(spec, options.idempotencyKey(), payload);
    assertKeyed(spec, idempotencyKey);

    boolean safeToRetry = Safety.retryIsSafe(spec, idempotencyKey != null && !idempotencyKey.isEmpty());
    int maxAttempts = safeToRetry ? spec.retry.maxAttempts : 1;
    Duration timeout = options.timeout() == null ? config.timeout : options.timeout();
    HttpRequest request =
        buildRequest(spec, payload, config, idempotencyKey, options.headers(), timeout);
    String trace = traceId();

    for (int attempt = 1; ; attempt++) {
      HttpResponse<String> response = null;
      try {
        response = config.httpClient.send(request, HttpResponse.BodyHandlers.ofString());
      } catch (IOException | InterruptedException failure) {
        if (failure instanceof InterruptedException) {
          Thread.currentThread().interrupt();
        }
        // Never surface the transport's own message: it can carry the URL, and
        // the URL can carry a query-carried credential.
        AnvilException error =
            AnvilException.builder(
                    "upstream_unavailable",
                    spec.id,
                    spec.id + " failed: the request could not reach the upstream.")
                .traceId(trace)
                .retryable(spec.retry.retryTransport)
                .safeToRetry(safeToRetry)
                .build();
        if (!safeToRetry || !spec.retry.retryTransport || attempt >= maxAttempts) {
          throw error;
        }
        Safety.RetryDecision decision =
            Safety.resolveRetryDelay(attempt, spec.retry, -1L, config.random.getAsDouble());
        if (decision.stop || !sleep(decision.delayMs)) {
          throw error;
        }
        continue;
      }

      int status = response.statusCode();
      if (status >= 200 && status < 300) {
        return Json.parse(response.body());
      }

      String code = AnvilException.httpStatusToErrorCode(status);
      Optional<String> retryAfterHeader = response.headers().firstValue("retry-after");
      long retryAfterMs =
          retryAfterHeader.isPresent()
              ? Safety.parseRetryAfter(retryAfterHeader.get(), Instant.now())
              : -1L;
      AnvilException.Builder failure =
          AnvilException.builder(
                  code, spec.id, spec.id + " failed upstream with HTTP " + status + ".")
              .traceId(trace)
              .retryable(AnvilException.isRetryableCode(code))
              .safeToRetry(safeToRetry)
              .upstream(status, response.headers().firstValue("x-request-id").orElse(null));
      if (retryAfterMs >= 0) {
        failure.retryAfterMs(retryAfterMs);
      }
      if (!spec.retry.retries(status) || attempt >= maxAttempts) {
        throw failure.build();
      }
      if (!safeToRetry) {
        // A transient failure we are not allowed to repeat. Say exactly that,
        // rather than retrying a write whose duplicate we cannot rule out.
        AnvilException.Builder blocked =
            AnvilException.builder(
                    "unsafe_retry_blocked",
                    spec.id,
                    spec.id
                        + " failed transiently (HTTP "
                        + status
                        + ") but is not provably idempotent, so it was not retried. Retry"
                        + " deliberately with an idempotency key if the effect is safe to repeat.")
                .traceId(trace)
                .upstream(status, null);
        if (retryAfterMs >= 0) {
          blocked.retryAfterMs(retryAfterMs);
        }
        throw blocked.build();
      }
      Safety.RetryDecision decision =
          Safety.resolveRetryDelay(attempt, spec.retry, retryAfterMs, config.random.getAsDouble());
      if (decision.stop) {
        throw AnvilException.builder(
                code,
                spec.id,
                spec.id
                    + " asked to be retried in "
                    + decision.delayMs
                    + "ms, longer than this client will wait inside one call. Retry deliberately"
                    + " after that delay.")
            .traceId(trace)
            .retryable(true)
            .safeToRetry(safeToRetry)
            .retryAfterMs(decision.delayMs)
            .build();
      }
      if (!sleep(decision.delayMs)) {
        throw failure.build();
      }
    }
  }

  private static boolean sleep(long delayMs) {
    if (delayMs <= 0) {
      return true;
    }
    try {
      Thread.sleep(delayMs);
      return true;
    } catch (InterruptedException interrupted) {
      Thread.currentThread().interrupt();
      return false;
    }
  }

  /**
   * Read one named field off a decoded response. Async contracts name their
   * handle and state fields exactly; this reads that name and nothing else,
   * rather than guessing at a shape the contract never promised.
   */
  @SuppressWarnings("unchecked")
  static Object field(Object value, String name) {
    return value instanceof Map ? ((Map<String, Object>) value).get(name) : null;
  }
}
`;
}
