/**
 * `Json.java` — a small, strict JSON codec.
 *
 * Java has no JSON in its standard library, and an SDK that needs a dependency
 * resolver before it can say hello is not one you can drop into a repository.
 * One hand-written copy, shared by every service, rather than a dependency or a
 * per-service reimplementation.
 */

export function jsonFile(pkg: string): string {
  return `// Generated by Anvil. Do not edit — regenerate from AIR.
package ${pkg};

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * A small, strict JSON codec. Java has no JSON in its standard library, and an
 * SDK that needs a dependency resolver before it can say hello is not one you
 * can drop into a repository. Objects decode to {@link LinkedHashMap}, arrays
 * to {@link ArrayList}, numbers to {@link Double} or {@link Long}.
 */
public final class Json {

  private Json() {}

  /** Serialize a value. Maps, lists, strings, numbers, booleans, and null. */
  public static String write(Object value) {
    StringBuilder out = new StringBuilder();
    writeValue(out, value);
    return out.toString();
  }

  @SuppressWarnings("unchecked")
  private static void writeValue(StringBuilder out, Object value) {
    if (value == null) {
      out.append("null");
    } else if (value instanceof String) {
      writeString(out, (String) value);
    } else if (value instanceof Boolean) {
      out.append(value.toString());
    } else if (value instanceof Number) {
      out.append(writeNumber((Number) value));
    } else if (value instanceof Map) {
      out.append('{');
      boolean first = true;
      for (Map.Entry<?, ?> entry : ((Map<?, ?>) value).entrySet()) {
        if (!first) {
          out.append(',');
        }
        first = false;
        writeString(out, String.valueOf(entry.getKey()));
        out.append(':');
        writeValue(out, entry.getValue());
      }
      out.append('}');
    } else if (value instanceof Iterable) {
      out.append('[');
      boolean first = true;
      for (Object item : (Iterable<Object>) value) {
        if (!first) {
          out.append(',');
        }
        first = false;
        writeValue(out, item);
      }
      out.append(']');
    } else {
      writeString(out, String.valueOf(value));
    }
  }

  private static String writeNumber(Number number) {
    double asDouble = number.doubleValue();
    if (number instanceof Double || number instanceof Float) {
      if (asDouble == Math.rint(asDouble) && !Double.isInfinite(asDouble)) {
        return Long.toString((long) asDouble);
      }
      return Double.toString(asDouble);
    }
    return number.toString();
  }

  private static void writeString(StringBuilder out, String value) {
    out.append('"');
    for (int index = 0; index < value.length(); index++) {
      char character = value.charAt(index);
      switch (character) {
        case '"':
          out.append("\\\\\\"");
          break;
        case '\\\\':
          out.append("\\\\\\\\");
          break;
        case '\\n':
          out.append("\\\\n");
          break;
        case '\\r':
          out.append("\\\\r");
          break;
        case '\\t':
          out.append("\\\\t");
          break;
        default:
          if (character < 0x20) {
            out.append(String.format("\\\\u%04x", (int) character));
          } else {
            out.append(character);
          }
      }
    }
    out.append('"');
  }

  /** Parse JSON text. Returns null for empty input or unparseable text. */
  public static Object parse(String text) {
    if (text == null || text.trim().isEmpty()) {
      return null;
    }
    try {
      Parser parser = new Parser(text);
      Object value = parser.readValue();
      parser.skipWhitespace();
      return parser.atEnd() ? value : null;
    } catch (RuntimeException error) {
      return null;
    }
  }

  private static final class Parser {
    private final String text;
    private int index;

    Parser(String text) {
      this.text = text;
    }

    boolean atEnd() {
      return index >= text.length();
    }

    void skipWhitespace() {
      while (index < text.length() && Character.isWhitespace(text.charAt(index))) {
        index++;
      }
    }

    Object readValue() {
      skipWhitespace();
      if (atEnd()) {
        throw new IllegalStateException("unexpected end of input");
      }
      char character = text.charAt(index);
      if (character == '{') {
        return readObject();
      }
      if (character == '[') {
        return readArray();
      }
      if (character == '"') {
        return readString();
      }
      if (text.startsWith("true", index)) {
        index += 4;
        return Boolean.TRUE;
      }
      if (text.startsWith("false", index)) {
        index += 5;
        return Boolean.FALSE;
      }
      if (text.startsWith("null", index)) {
        index += 4;
        return null;
      }
      return readNumber();
    }

    private Map<String, Object> readObject() {
      Map<String, Object> out = new LinkedHashMap<String, Object>();
      index++;
      skipWhitespace();
      if (!atEnd() && text.charAt(index) == '}') {
        index++;
        return out;
      }
      while (true) {
        skipWhitespace();
        String key = readString();
        skipWhitespace();
        expect(':');
        out.put(key, readValue());
        skipWhitespace();
        char character = next();
        if (character == '}') {
          return out;
        }
        if (character != ',') {
          throw new IllegalStateException("expected , or }");
        }
      }
    }

    private List<Object> readArray() {
      List<Object> out = new ArrayList<Object>();
      index++;
      skipWhitespace();
      if (!atEnd() && text.charAt(index) == ']') {
        index++;
        return out;
      }
      while (true) {
        out.add(readValue());
        skipWhitespace();
        char character = next();
        if (character == ']') {
          return out;
        }
        if (character != ',') {
          throw new IllegalStateException("expected , or ]");
        }
      }
    }

    private String readString() {
      expect('"');
      StringBuilder out = new StringBuilder();
      while (true) {
        char character = next();
        if (character == '"') {
          return out.toString();
        }
        if (character != '\\\\') {
          out.append(character);
          continue;
        }
        char escape = next();
        switch (escape) {
          case '"':
            out.append('"');
            break;
          case '\\\\':
            out.append('\\\\');
            break;
          case '/':
            out.append('/');
            break;
          case 'b':
            out.append('\\b');
            break;
          case 'f':
            out.append('\\f');
            break;
          case 'n':
            out.append('\\n');
            break;
          case 'r':
            out.append('\\r');
            break;
          case 't':
            out.append('\\t');
            break;
          case 'u':
            out.append((char) Integer.parseInt(text.substring(index, index + 4), 16));
            index += 4;
            break;
          default:
            throw new IllegalStateException("bad escape");
        }
      }
    }

    private Object readNumber() {
      int start = index;
      while (index < text.length() && "+-0123456789.eE".indexOf(text.charAt(index)) >= 0) {
        index++;
      }
      String raw = text.substring(start, index);
      if (raw.isEmpty()) {
        throw new IllegalStateException("expected a number");
      }
      if (raw.indexOf('.') < 0 && raw.indexOf('e') < 0 && raw.indexOf('E') < 0) {
        try {
          return Long.valueOf(Long.parseLong(raw));
        } catch (NumberFormatException ignored) {
          // Falls through to the double parse below.
        }
      }
      return Double.valueOf(Double.parseDouble(raw));
    }

    private char next() {
      if (atEnd()) {
        throw new IllegalStateException("unexpected end of input");
      }
      return text.charAt(index++);
    }

    private void expect(char expected) {
      if (next() != expected) {
        throw new IllegalStateException("expected " + expected);
      }
    }
  }
}
`;
}
