import { callOptionsFile, exceptionFile, javaPackage, specFile } from "./java-core.js";
import { invokerFile, safetyFile } from "./java-invoke.js";
import { jsonFile } from "./java-json.js";
import type { SdkField, SdkOperation, SdkPlan } from "./plan.js";
import { safetyNotes, wrap } from "./shared.js";
import { JAVA_SOAP } from "./soap.js";

/**
 * The Java SDK — a zero-dependency library over `java.net.http`.
 *
 * Java has no JSON in its standard library, so the SDK ships a small, strict
 * codec rather than a dependency: an SDK you can drop into a repository and
 * compile is worth more than one that needs a resolver to say hello.
 */
export function generateJavaSdk(plan: SdkPlan): Record<string, string> {
  const pkg = javaPackage(plan);
  const dir = `sdk/java/src/main/java/${pkg.split(".").join("/")}`;
  const files: Record<string, string> = {
    "sdk/java/pom.xml": pom(plan),
    "sdk/java/README.md": readme(plan),
    [`${dir}/Json.java`]: jsonFile(pkg),
    [`${dir}/AnvilException.java`]: exceptionFile(pkg, plan),
    [`${dir}/OperationSpec.java`]: specFile(pkg),
    [`${dir}/CallOptions.java`]: callOptionsFile(pkg),
    [`${dir}/Safety.java`]: safetyFile(pkg),
    [`${dir}/Operations.java`]: operationsFile(pkg, plan),
    // Always appended, unlike the TypeScript module: `OperationSpec.soap` is a
    // typed field, so `Invoker.SoapBinding` has to exist even in a REST
    // service. Java permits unused static methods, so the cost is dead code
    // rather than a compile error.
    [`${dir}/Invoker.java`]: invokerFile(pkg).replace(/\n\}\n?$/, `\n${JAVA_SOAP}\n}\n`),
    [`${dir}/${clientName(plan)}.java`]: clientFile(pkg, plan),
  };
  for (const op of plan.operations) {
    files[`${dir}/${op.names.pascal}Input.java`] = inputFile(pkg, op);
  }
  return files;
}

function clientName(plan: SdkPlan): string {
  return `${plan.service.names.pascal}Client`;
}

const q = (value: unknown): string => JSON.stringify(value);

function javaCamel(source: string): string {
  const words = source.split(/[^a-zA-Z0-9]+/).filter(Boolean);
  return words
    .map((word, index) =>
      index === 0 ? word.toLowerCase() : word.charAt(0).toUpperCase() + word.slice(1),
    )
    .join("");
}

function javaType(field: SdkField, boxed: boolean): string {
  switch (field.type) {
    case "string":
      return "String";
    case "integer":
      return boxed ? "Long" : "long";
    case "number":
      return boxed ? "Double" : "double";
    case "boolean":
      return boxed ? "Boolean" : "boolean";
    case "array":
      return "java.util.List<Object>";
    case "object":
      return "java.util.Map<String, Object>";
    default:
      return "Object";
  }
}

function pom(plan: SdkPlan): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Anvil. Do not edit — regenerate from AIR. -->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.anvil.sdk</groupId>
  <artifactId>${plan.service.id}</artifactId>
  <version>${plan.service.version}</version>
  <name>${plan.service.displayName} Java SDK</name>
  <description>${plan.service.description} Generated by Anvil from AIR.</description>
  <properties>
    <maven.compiler.release>11</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
  <!-- No dependencies: java.net.http for transport, a bundled codec for JSON. -->
</project>
`;
}

function readme(plan: SdkPlan): string {
  const pkg = javaPackage(plan);
  const first = plan.operations[0];
  const required = first ? requiredFields(first) : [];
  const usage = first
    ? [
        "```java",
        `import ${pkg}.${clientName(plan)};`,
        `import ${pkg}.${first.names.pascal}Input;`,
        "",
        `${clientName(plan)} client = ${clientName(plan)}.create();`,
        `Object result = client.${first.names.camel}(`,
        `    new ${first.names.pascal}Input(${required.map(() => '"…"').join(", ")})${
          first.confirmation.required || first.idempotency.callerKeyRequired
            ? `,\n    CallOptions.none()${first.confirmation.required ? ".confirm(true)" : ""}${
                first.idempotency.callerKeyRequired ? '.idempotencyKey("order-1234")' : ""
              }`
            : ""
        });`,
        "```",
      ].join("\n")
    : "_This bundle has no approved operations yet._";
  return `# ${plan.service.displayName} — Java SDK

${plan.service.description}

Generated by Anvil from AIR. Java 11+, zero dependencies — \`java.net.http\` for
transport and a small bundled codec for JSON, so \`sdk/java/\` can be vendored
directly and compiled with \`javac\` alone.

${usage}

The credential is read from \`${plan.auth.envVar}\` when \`create()\` is called
without one. It is never logged, echoed, or included in an exception.

Safety is not advisory: an operation that requires confirmation throws
\`AnvilException\` with \`code() == "confirmation_required"\` before anything
reaches the network — and its convenience overload does not exist, so the gate
is visible at compile time.

See \`../README.md\` for the full cross-language contract.
`;
}

function requiredFields(op: SdkOperation): SdkField[] {
  const fields: SdkField[] = op.params.filter((param) => param.required);
  if (op.body?.projection === "fields") {
    fields.push(...op.body.fields.filter((field) => field.required));
  } else if (op.body?.required) {
    fields.push({
      wireName: "body",
      key: "body",
      required: true,
      type: "any",
      description: `The request body, sent verbatim (content type ${op.body.contentType}).`,
    });
  }
  return fields;
}

function optionalFields(op: SdkOperation): SdkField[] {
  const fields: SdkField[] = op.params.filter((param) => !param.required);
  if (op.body?.projection === "fields") {
    fields.push(...op.body.fields.filter((field) => !field.required));
  } else if (op.body && !op.body.required) {
    fields.push({
      wireName: "body",
      key: "body",
      required: false,
      type: "any",
      description: `The request body, sent verbatim (content type ${op.body.contentType}).`,
    });
  }
  return fields;
}

function operationsFile(pkg: string, plan: SdkPlan): string {
  const rows = plan.operations.map((op) => {
    const params = op.params
      .map(
        (param) =>
          `            new OperationSpec.Param(${q(param.wireName)}, ${q(param.key)}, ${q(param.in)}, ${param.required})`,
      )
      .join(",\n");
    const body = op.body
      ? `new OperationSpec.Body(${op.body.required}, ${q(op.body.contentType)}, ${q(op.body.projection)}${op.body.fields
          .map(
            (field) =>
              `,\n              new OperationSpec.BodyField(${q(field.wireName)}, ${q(field.key)}, ${field.required})`,
          )
          .join("")})`
      : "null";
    const carrier = op.idempotency.carrier
      ? `new OperationSpec.Carrier(${q(op.idempotency.carrier.mechanism)}, ${q(op.idempotency.carrier.key)}${
          op.idempotency.carrier.mechanism === "body"
            ? op.idempotency.carrier.path.map((segment) => `, ${q(segment)}`).join("")
            : ""
        })`
      : "null";
    return `    BY_NAME.put(
        ${q(op.names.camel)},
        new OperationSpec(
            ${q(op.id)},
            ${q(op.httpMethod)},
            ${q(op.wireProtocol)},
            ${
              op.wireBinding?.protocol === "graphql"
                ? `new Invoker.GraphqlBinding(${q(op.wireBinding.document)}, ${q(op.wireBinding.operationName)}, ${q(op.wireBinding.rootField)})`
                : "null"
            },
            ${
              op.wireBinding?.protocol === "soap"
                ? `new Invoker.SoapBinding(${q(op.wireBinding.soapAction ?? "")}, ${q(op.wireBinding.envelopeNamespace)}, ${q(op.wireBinding.bodyNamespace)}, ${q(op.wireBinding.bodyElement)}, ${q(op.wireBinding.responseElement ?? "")}, ${q(op.wireBinding.contentType)}, ${q(op.wireBinding.soapVersion)})`
                : "null"
            },
            ${q(op.path)},
            ${q(op.effect)},
            new OperationSpec.Param[] {
${params}
            },
            ${body},
            new OperationSpec.Idempotency(${q(op.idempotency.mode)}, ${q(op.idempotency.keyDerivation)}, ${op.idempotency.callerKeyRequired}, ${carrier}),
            new OperationSpec.Retry(${q(op.retry.mode)}, ${op.retry.maxAttempts}, ${q(op.retry.backoff)}, ${op.retry.baseDelayMs}L, ${op.retry.maxDelayMs}L, new int[] {${op.retry.retryStatuses.join(", ")}}, ${op.retry.retryTransport}),
            new OperationSpec.Confirmation(${op.confirmation.required}, ${op.confirmation.humanApproval}, ${q(op.confirmation.reason ?? "")})));`;
  });
  return `// Generated by Anvil. Do not edit — regenerate from AIR.
package ${pkg};

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * One row per approved operation. An operation still in review is absent here,
 * which is why it cannot be called: the SDK has no way to name it.
 */
public final class Operations {

  private static final Map<String, OperationSpec> BY_NAME =
      new LinkedHashMap<String, OperationSpec>();

  static {
${rows.join("\n")}
  }

  private Operations() {}

  /** Every approved operation, keyed by its Java method name. */
  public static Map<String, OperationSpec> all() {
    return Collections.unmodifiableMap(BY_NAME);
  }

  public static OperationSpec get(String name) {
    OperationSpec spec = BY_NAME.get(name);
    if (spec == null) {
      throw new IllegalArgumentException("no such approved operation: " + name);
    }
    return spec;
  }
}
`;
}

function inputFile(pkg: string, op: SdkOperation): string {
  const required = requiredFields(op);
  const optional = optionalFields(op);
  const constructorArgs = required
    .map((field) => `${javaType(field, false)} ${javaCamel(field.key)}`)
    .join(", ");
  const constructorBody = required
    .map((field) => `    this.values.put(${q(field.key)}, ${javaCamel(field.key)});`)
    .join("\n");
  const setters = optional
    .map(
      (
        field,
      ) => `  ${field.description ? `/** ${field.description} */\n  ` : ""}public ${op.names.pascal}Input ${javaCamel(field.key)}(${javaType(field, false)} value) {
    this.values.put(${q(field.key)}, value);
    return this;
  }`,
    )
    .join("\n\n");
  return `// Generated by Anvil. Do not edit — regenerate from AIR.
package ${pkg};

import java.util.LinkedHashMap;
import java.util.Map;

/** Input for {@code ${op.canonicalName}} — ${op.description} */
public final class ${op.names.pascal}Input {

  private final Map<String, Object> values = new LinkedHashMap<String, Object>();

  /** Required inputs are constructor arguments; optional ones are fluent setters. */
  public ${op.names.pascal}Input(${constructorArgs}) {
${constructorBody}
  }

${setters}

  /** The caller payload, keyed exactly as the operation spec expects. */
  public Map<String, Object> payload() {
    return new LinkedHashMap<String, Object>(values);
  }
}
`;
}

function clientFile(pkg: string, plan: SdkPlan): string {
  const name = clientName(plan);
  const methods = plan.operations.map((op) => javaMethod(op)).join("\n\n");
  return `// Generated by Anvil. Do not edit — regenerate from AIR.
package ${pkg};

import java.net.http.HttpClient;
import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.function.DoubleSupplier;

/**
 * ${plan.service.description}
 *
 * <p>Every method is one approved operation. The safety gates live in the
 * invoker, so no method can skip them.
 */
public final class ${name} {

  /** The base URL recorded in AIR at compile time. */
  public static final String DEFAULT_BASE_URL = ${q(plan.service.baseUrl)};

  /** The environment variable read when no token is supplied. */
  public static final String TOKEN_ENV_VAR = ${q(plan.auth.envVar)};

  private static final String USER_AGENT = ${q(`anvil-sdk-${plan.service.id}/${plan.service.version} (java)`)};

  private final Invoker.Config config;

  private ${name}(Invoker.Config config) {
    this.config = config;
  }

  /** A client on the compiled-in base URL, reading the credential from the environment. */
  public static ${name} create() {
    return builder().build();
  }

  public static Builder builder() {
    return new Builder();
  }

  /** Configures a client. The credential is never logged, echoed, or thrown. */
  public static final class Builder {
    private String baseUrl = DEFAULT_BASE_URL;
    private String protocolFacade = System.getenv("ANVIL_PROTOCOL_FACADE");
    private String token = System.getenv(TOKEN_ENV_VAR);
    private Duration timeout = Duration.ofSeconds(30);
    private HttpClient httpClient;
    private DoubleSupplier random = Math::random;

    /**
     * Declares that the base URL really does serve the synthesized coordinates
     * of a non-HTTP/JSON source (SOAP, GraphQL, gRPC) over HTTP+JSON. Without
     * it those operations are refused rather than sent.
     */
    public Builder protocolFacade(String reason) {
      this.protocolFacade = reason;
      return this;
    }

    public Builder baseUrl(String value) {
      this.baseUrl = value;
      return this;
    }

    public Builder token(String value) {
      this.token = value;
      return this;
    }

    public Builder timeout(Duration value) {
      this.timeout = value;
      return this;
    }

    /** Injects a transport, for tests and embedders. */
    public Builder httpClient(HttpClient value) {
      this.httpClient = value;
      return this;
    }

    /** Injects the jitter source, so a retry schedule is deterministic under test. */
    public Builder random(DoubleSupplier value) {
      this.random = value;
      return this;
    }

    public ${name} build() {
      if (baseUrl == null || baseUrl.isEmpty()) {
        throw AnvilException.builder(
                "validation_error",
                ${q(plan.service.id)},
                "No base URL: the compiled model records no server, so one must be passed to"
                    + " builder().baseUrl(...).")
            .requiredArguments("baseUrl")
            .build();
      }
      HttpClient client =
          httpClient != null
              ? httpClient
              : HttpClient.newBuilder().connectTimeout(timeout).build();
      return new ${name}(
          new Invoker.Config(
              baseUrl,
              protocolFacade,
              token,
              ${plan.auth.carrier ? q(plan.auth.carrier.in) : "null"},
              ${plan.auth.carrier ? q(plan.auth.carrier.name) : "null"},
              ${plan.auth.carrier?.scheme ? q(plan.auth.carrier.scheme) : "null"},
              timeout,
              client,
              USER_AGENT,
              random));
    }
  }

${methods.length > 0 ? methods : "  // This bundle has no approved operations yet."}
}
`;
}

function javaMethod(op: SdkOperation): string {
  const gated = op.confirmation.required || op.idempotency.callerKeyRequired;
  const doc = [
    "  /**",
    `   * ${op.description}`,
    "   *",
    ...safetyNotes(op).flatMap((note) => wrap(note, 72).map((line) => `   * <p>${line}`)),
    "   *",
    "   * @throws AnvilException a structured refusal or upstream failure.",
    "   */",
  ].join("\n");
  const lines = [
    doc,
    `  public Object ${op.names.camel}(${op.names.pascal}Input input, CallOptions options) {`,
    `    return Invoker.invoke(config, Operations.get(${q(op.names.camel)}), input.payload(), options);`,
    "  }",
  ];
  if (!gated) {
    // The convenience overload exists only where the contract has no gate to
    // satisfy. Where it does, its absence is the gate, visible at compile time.
    lines.push(
      "",
      `  /** ${op.description} */`,
      `  public Object ${op.names.camel}(${op.names.pascal}Input input) {`,
      `    return ${op.names.camel}(input, CallOptions.none());`,
      "  }",
    );
  }
  const page = op.pagination;
  if (page?.cursorKey && page.nextField) {
    lines.push(
      "",
      "  /**",
      `   * Page through ${op.canonicalName} until the upstream stops handing back a`,
      "   * continuation, collecting every page in order.",
      "   *",
      "   * @param maxPages a hard bound, so a misbehaving upstream cannot page forever.",
      "   */",
      `  public List<Object> ${op.names.camel}Pages(${op.names.pascal}Input input, CallOptions options, int maxPages) {`,
      "    List<Object> pages = new ArrayList<Object>();",
      "    List<String> seen = new ArrayList<String>();",
      `    Object cursor = input.payload().get(${q(page.cursorKey)});`,
      "    for (int index = 0; index < maxPages; index++) {",
      "      java.util.Map<String, Object> payload = input.payload();",
      "      if (cursor != null) {",
      `        payload.put(${q(page.cursorKey)}, cursor);`,
      "      }",
      `      Object page = Invoker.invoke(config, Operations.get(${q(op.names.camel)}), payload, options);`,
      "      pages.add(page);",
      `      Object next = Invoker.field(page, ${q(page.nextField)});`,
      "      if (!(next instanceof String) || ((String) next).isEmpty()) {",
      "        break;",
      "      }",
      // A server that echoes its own cursor would page the same page forever.
      "      if (seen.contains(next)) {",
      "        break;",
      "      }",
      "      seen.add((String) next);",
      "      cursor = next;",
      "    }",
      "    return pages;",
      "  }",
    );
  }
  const contract = op.async;
  if (contract?.statusMethodBase && contract.statusJobIdKey && contract.terminalStates.length > 0) {
    const statusCamel = javaCamel(contract.statusMethodBase);
    const statusPascal = contract.statusMethodBase
      .split("_")
      .filter(Boolean)
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join("");
    lines.push(
      "",
      "  /**",
      `   * ${contract.instruction}`,
      "   *",
      "   * <p>Polls at the interval the contract declares and returns the first status",
      "   * response in a terminal state. Every field name below is the one AIR resolved",
      "   * — none is guessed.",
      "   */",
      `  public Object waitFor${op.names.pascal}(Object submitResult, Duration timeout) {`,
      `    Object handle = Invoker.field(submitResult, ${q(contract.jobIdField)});`,
      "    if (!(handle instanceof String) || ((String) handle).isEmpty()) {",
      "      throw AnvilException.builder(",
      `              "schema_mismatch", ${q(op.id)},`,
      `              "The submit response carried no ${contract.jobIdField} to poll on.")`,
      "          .build();",
      "    }",
      `    Duration budget = timeout == null ? Duration.ofSeconds(${contract.pollIntervalSeconds * 60}) : timeout;`,
      "    Instant deadline = Instant.now().plus(budget);",
      `    List<String> terminal = Arrays.asList(${contract.terminalStates.map((state) => q(state)).join(", ")});`,
      "    while (true) {",
      `      Object status = ${statusCamel}(new ${statusPascal}Input((String) handle), CallOptions.none());`,
      `      Object state = Invoker.field(status, ${q(contract.stateField ?? "state")});`,
      "      if (state instanceof String && terminal.contains(state)) {",
      "        return status;",
      "      }",
      "      if (Instant.now().isAfter(deadline)) {",
      "        throw AnvilException.builder(",
      `                "upstream_timeout", ${q(op.id)},`,
      `                "${op.canonicalName} did not reach a terminal state before the wait deadline.")`,
      "            .retryable(true)",
      "            .build();",
      "      }",
      "      try {",
      `        Thread.sleep(${contract.pollIntervalSeconds * 1000}L);`,
      "      } catch (InterruptedException interrupted) {",
      "        Thread.currentThread().interrupt();",
      "        throw AnvilException.builder(",
      `                "upstream_timeout", ${q(op.id)}, "The wait was interrupted.")`,
      "            .build();",
      "      }",
      "    }",
      "  }",
    );
  }
  return lines.join("\n");
}
