import { javaDryRunFile } from "./dry-run.js";
import {
  javaGrantBuilderFields,
  javaGrantBuilderMethods,
  javaGrantConstants,
  javaGrantWiring,
} from "./java-auth.js";
import { callOptionsFile, exceptionFile, javaPackage, mtlsFile, specFile } from "./java-core.js";
import { invokerFile } from "./java-invoke.js";
import { jsonFile } from "./java-json.js";
import { safetyFile } from "./java-safety.js";
import { needsOauth, oauthGrantsOf } from "./oauth-grants.js";
import { oauthFile } from "./oauth-grants-java.js";
import type { SdkField, SdkOperation, SdkPager, SdkPlan } from "./plan.js";
import { safetyNotes, wrap } from "./shared.js";
import { JAVA_SOAP } from "./soap.js";

/**
 * The Java SDK — a zero-dependency library over `java.net.http`.
 *
 * Java has no JSON in its standard library, so the SDK ships a small, strict
 * codec rather than a dependency: an SDK you can drop into a repository and
 * compile is worth more than one that needs a resolver to say hello.
 */
export function generateJavaSdk(plan: SdkPlan): Record<string, string> {
  const pkg = javaPackage(plan);
  const dir = `sdk/java/src/main/java/${pkg.split(".").join("/")}`;
  const files: Record<string, string> = {
    "sdk/java/pom.xml": pom(plan),
    "sdk/java/README.md": readme(plan),
    [`${dir}/Json.java`]: jsonFile(pkg),
    [`${dir}/AnvilException.java`]: exceptionFile(pkg, plan),
    [`${dir}/OperationSpec.java`]: specFile(pkg),
    [`${dir}/CallOptions.java`]: callOptionsFile(pkg),
    [`${dir}/Safety.java`]: safetyFile(pkg),
    [`${dir}/Operations.java`]: operationsFile(pkg, plan),
    // Always appended, unlike the TypeScript module: `OperationSpec.soap` is a
    // typed field, so `Invoker.SoapBinding` has to exist even in a REST
    // service. Java permits unused static methods, so the cost is dead code
    // rather than a compile error.
    [`${dir}/Invoker.java`]: invokerFile(pkg).replace(/\n\}\n?$/, `\n${JAVA_SOAP}\n}\n`),
    [`${dir}/DryRun.java`]: javaDryRunFile(pkg),
    // mTLS and the OAuth grants are emitted only for the service that
    // declared the scheme — a bearer/api-key service never carries the
    // PEM-parsing plumbing or dead token-endpoint code.
    ...(plan.auth.tls ? { [`${dir}/Mtls.java`]: mtlsFile(pkg) } : {}),
    ...(needsOauth(plan) ? { [`${dir}/Oauth.java`]: oauthFile(pkg, oauthGrantsOf(plan)) } : {}),
    [`${dir}/${clientName(plan)}.java`]: clientFile(pkg, plan),
  };
  for (const op of plan.operations) {
    files[`${dir}/${op.names.pascal}Input.java`] = inputFile(pkg, op);
  }
  return files;
}

function clientName(plan: SdkPlan): string {
  return `${plan.service.names.pascal}Client`;
}

const q = (value: unknown): string => JSON.stringify(value);

function javaCamel(source: string): string {
  const words = source.split(/[^a-zA-Z0-9]+/).filter(Boolean);
  return words
    .map((word, index) =>
      index === 0 ? word.toLowerCase() : word.charAt(0).toUpperCase() + word.slice(1),
    )
    .join("");
}

function javaType(field: SdkField, boxed: boolean): string {
  switch (field.type) {
    case "string":
      return "String";
    case "integer":
      return boxed ? "Long" : "long";
    case "number":
      return boxed ? "Double" : "double";
    case "boolean":
      return boxed ? "Boolean" : "boolean";
    case "array":
      return "java.util.List<Object>";
    case "object":
      return "java.util.Map<String, Object>";
    default:
      return "Object";
  }
}

function pom(plan: SdkPlan): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Anvil. Do not edit — regenerate from AIR. -->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.anvil.sdk</groupId>
  <artifactId>${plan.service.id}</artifactId>
  <version>${plan.service.version}</version>
  <name>${plan.service.displayName} Java SDK</name>
  <description>${plan.service.description} Generated by Anvil from AIR.</description>
  <properties>
    <maven.compiler.release>11</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
  <!-- No dependencies: java.net.http for transport, a bundled codec for JSON. -->
</project>
`;
}

function readme(plan: SdkPlan): string {
  const pkg = javaPackage(plan);
  const first = plan.operations[0];
  const required = first ? requiredFields(first) : [];
  const usage = first
    ? [
        "```java",
        `import ${pkg}.${clientName(plan)};`,
        `import ${pkg}.${first.names.pascal}Input;`,
        "",
        `${clientName(plan)} client = ${clientName(plan)}.create();`,
        `Object result = client.${first.names.camel}(`,
        `    new ${first.names.pascal}Input(${required.map(() => '"…"').join(", ")})${
          first.confirmation.required || first.idempotency.callerKeyRequired
            ? `,\n    CallOptions.none()${first.confirmation.required ? ".confirm(true)" : ""}${
                first.idempotency.callerKeyRequired ? '.idempotencyKey("order-1234")' : ""
              }`
            : ""
        });`,
        "```",
      ].join("\n")
    : "_This bundle has no approved operations yet._";
  return `# ${plan.service.displayName} — Java SDK

${plan.service.description}

Generated by Anvil from AIR. Java 11+, zero dependencies — \`java.net.http\` for
transport and a small bundled codec for JSON, so \`sdk/java/\` can be vendored
directly and compiled with \`javac\` alone.

${usage}

The credential is read from \`${plan.auth.envVar}\` when \`create()\` is called
without one. It is never logged, echoed, or included in an exception.

Safety is not advisory: an operation that requires confirmation throws
\`AnvilException\` with \`code() == "confirmation_required"\` before anything
reaches the network — and its convenience overload does not exist, so the gate
is visible at compile time.

Every call can be previewed: pass \`CallOptions.none().dryRun(true)\` and the
same gates run, then a redacted request plan (a \`Map<String, Object>\`) comes
back instead of a response — nothing is sent and no credential is resolved. It
is the plan \`anvil run --dry-run\` prints.

See \`../README.md\` for the full cross-language contract.
`;
}

function requiredFields(op: SdkOperation): SdkField[] {
  const fields: SdkField[] = op.params.filter((param) => param.required);
  if (op.body?.projection === "fields") {
    fields.push(...op.body.fields.filter((field) => field.required));
  } else if (op.body?.required) {
    fields.push({
      wireName: "body",
      key: "body",
      required: true,
      type: "any",
      description: `The request body, sent verbatim (content type ${op.body.contentType}).`,
    });
  }
  return fields;
}

function optionalFields(op: SdkOperation): SdkField[] {
  const fields: SdkField[] = op.params.filter((param) => !param.required);
  if (op.body?.projection === "fields") {
    fields.push(...op.body.fields.filter((field) => !field.required));
  } else if (op.body && !op.body.required) {
    fields.push({
      wireName: "body",
      key: "body",
      required: false,
      type: "any",
      description: `The request body, sent verbatim (content type ${op.body.contentType}).`,
    });
  }
  return fields;
}

function operationsFile(pkg: string, plan: SdkPlan): string {
  const rows = plan.operations.map((op) => {
    const params = op.params
      .map(
        (param) =>
          `            new OperationSpec.Param(${q(param.wireName)}, ${q(param.key)}, ${q(param.in)}, ${param.required})`,
      )
      .join(",\n");
    const body = op.body
      ? `new OperationSpec.Body(${op.body.required}, ${q(op.body.contentType)}, ${q(op.body.projection)}${op.body.fields
          .map(
            (field) =>
              `,\n              new OperationSpec.BodyField(${q(field.wireName)}, ${q(field.key)}, ${field.required})`,
          )
          .join("")})`
      : "null";
    const carrier = op.idempotency.carrier
      ? `new OperationSpec.Carrier(${q(op.idempotency.carrier.mechanism)}, ${q(op.idempotency.carrier.key)}${
          op.idempotency.carrier.mechanism === "body"
            ? op.idempotency.carrier.path.map((segment) => `, ${q(segment)}`).join("")
            : ""
        })`
      : "null";
    return `    BY_NAME.put(
        ${q(op.names.camel)},
        new OperationSpec(
            ${q(op.id)},
            ${q(op.httpMethod)},
            ${q(op.wireProtocol)},
            ${
              op.wireBinding?.protocol === "graphql"
                ? `new Invoker.GraphqlBinding(${q(op.wireBinding.document)}, ${q(op.wireBinding.operationName)}, ${q(op.wireBinding.rootField)})`
                : "null"
            },
            ${
              op.wireBinding?.protocol === "soap"
                ? `new Invoker.SoapBinding(${q(op.wireBinding.soapAction ?? "")}, ${q(op.wireBinding.envelopeNamespace)}, ${q(op.wireBinding.bodyNamespace)}, ${q(op.wireBinding.bodyElement)}, ${q(op.wireBinding.responseElement ?? "")}, ${q(op.wireBinding.contentType)}, ${q(op.wireBinding.soapVersion)})`
                : "null"
            },
            ${q(op.path)},
            ${q(op.effect)},
            new OperationSpec.Param[] {
${params}
            },
            ${body},
            new OperationSpec.Idempotency(${q(op.idempotency.mode)}, ${q(op.idempotency.keyDerivation)}, ${op.idempotency.callerKeyRequired}, ${carrier}),
            new OperationSpec.Retry(${q(op.retry.mode)}, ${op.retry.maxAttempts}, ${q(op.retry.backoff)}, ${op.retry.baseDelayMs}L, ${op.retry.maxDelayMs}L, new int[] {${op.retry.retryStatuses.join(", ")}}, ${op.retry.retryTransport}),
            new OperationSpec.Confirmation(${op.confirmation.required}, ${op.confirmation.humanApproval}, ${q(op.confirmation.reason ?? "")})));`;
  });
  return `// Generated by Anvil. Do not edit — regenerate from AIR.
package ${pkg};

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * One row per approved operation. An operation still in review is absent here,
 * which is why it cannot be called: the SDK has no way to name it.
 */
public final class Operations {

  private static final Map<String, OperationSpec> BY_NAME =
      new LinkedHashMap<String, OperationSpec>();

  static {
${rows.join("\n")}
  }

  private Operations() {}

  /** Every approved operation, keyed by its Java method name. */
  public static Map<String, OperationSpec> all() {
    return Collections.unmodifiableMap(BY_NAME);
  }

  public static OperationSpec get(String name) {
    OperationSpec spec = BY_NAME.get(name);
    if (spec == null) {
      throw new IllegalArgumentException("no such approved operation: " + name);
    }
    return spec;
  }
}
`;
}

function inputFile(pkg: string, op: SdkOperation): string {
  const required = requiredFields(op);
  const optional = optionalFields(op);
  const constructorArgs = required
    .map((field) => `${javaType(field, false)} ${javaCamel(field.key)}`)
    .join(", ");
  const constructorBody = required
    .map((field) => `    this.values.put(${q(field.key)}, ${javaCamel(field.key)});`)
    .join("\n");
  const setters = optional
    .map(
      (
        field,
      ) => `  ${field.description ? `/** ${field.description} */\n  ` : ""}public ${op.names.pascal}Input ${javaCamel(field.key)}(${javaType(field, false)} value) {
    this.values.put(${q(field.key)}, value);
    return this;
  }`,
    )
    .join("\n\n");
  return `// Generated by Anvil. Do not edit — regenerate from AIR.
package ${pkg};

import java.util.LinkedHashMap;
import java.util.Map;

/** Input for {@code ${op.canonicalName}} — ${op.description} */
public final class ${op.names.pascal}Input {

  private final Map<String, Object> values = new LinkedHashMap<String, Object>();

  /** Required inputs are constructor arguments; optional ones are fluent setters. */
  public ${op.names.pascal}Input(${constructorArgs}) {
${constructorBody}
  }

${setters}

  /** The caller payload, keyed exactly as the operation spec expects. */
  public Map<String, Object> payload() {
    return new LinkedHashMap<String, Object>(values);
  }
}
`;
}

/**
 * The paging helper: collects pages in order under a caller-chosen bound.
 * Every style advances the same way — see `SdkPager` in plan.ts — and every
 * one stops on a repeated continuation.
 */
function javaPager(op: SdkOperation, pager: SdkPager): string[] {
  const k = q(pager.cursorKey);
  const items = pager.itemsField ? `Invoker.field(page, ${q(pager.itemsField)})` : "null";
  const short =
    pager.pageSizeKey && pager.itemsField
      ? `      Object requested = payload.get(${q(pager.pageSizeKey)});\n      boolean shortPage = requested instanceof Number && items instanceof List && ((List<?>) items).size() < ((Number) requested).longValue();`
      : "      boolean shortPage = false;";
  let advance = "";
  switch (pager.style) {
    case "cursor":
      advance = `      Object raw = Invoker.field(page, ${q(pager.nextField ?? "")});\n      if (raw instanceof String && !((String) raw).isEmpty()) {\n        next = raw;\n      }`;
      break;
    case "link":
      advance = `      Object raw = Invoker.field(page, ${q(pager.nextField ?? "")});\n      // Only the continuation value is read out of the link; the URL itself is\n      // never fetched, so paging can never leave the compiled base URL.\n      if (raw instanceof String && !((String) raw).isEmpty()) {\n        next = pagerLinkParam((String) raw, ${q(pager.cursorParam)});\n      }`;
      break;
    case "page":
    case "offset": {
      const step = pager.style === "page" ? "1L" : "(long) ((List<?>) items).size()";
      advance = pager.nextField
        ? `      Object raw = Invoker.field(page, ${q(pager.nextField)});\n      if (raw instanceof Number) {\n        next = raw;\n      } else if (raw instanceof String && !((String) raw).isEmpty()) {\n        next = raw;\n      }`
        : `      if (items instanceof List && !((List<?>) items).isEmpty() && !shortPage && cursor instanceof Number) {\n        next = Long.valueOf(((Number) cursor).longValue() + ${step});\n      }`;
      break;
    }
  }
  const startValue =
    pager.start !== undefined
      ? `\n    if (cursor == null) {\n      cursor = Long.valueOf(${pager.start}L);\n    }`
      : "";
  const clamp =
    pager.pageSizeKey && pager.maxPageSize
      ? `\n      Object size = payload.get(${q(pager.pageSizeKey)});\n      if (size instanceof Number && ((Number) size).longValue() > ${pager.maxPageSize}L) {\n        payload.put(${q(pager.pageSizeKey)}, Long.valueOf(${pager.maxPageSize}L));\n      }`
      : "";
  return [
    "  /**",
    `   * Page through ${op.canonicalName} (${pager.style} pagination) until the upstream stops`,
    "   * handing back a continuation, collecting every page in order.",
    "   *",
    "   * @param maxPages a hard bound, so a misbehaving upstream cannot page forever.",
    "   */",
    `  public List<Object> ${op.names.camel}Pages(${op.names.pascal}Input input, CallOptions options, int maxPages) {`,
    "    List<Object> pages = new ArrayList<Object>();",
    "    List<String> seen = new ArrayList<String>();",
    `    Object cursor = input.payload().get(${k});${startValue}`,
    "    for (int index = 0; index < maxPages; index++) {",
    "      java.util.Map<String, Object> payload = input.payload();",
    "      if (cursor != null) {",
    `        payload.put(${k}, cursor);`,
    `      }${clamp}`,
    `      Object page = Invoker.invoke(config, Operations.get(${q(op.names.camel)}), payload, options);`,
    "      pages.add(page);",
    `      Object items = ${items};`,
    short,
    "      Object next = null;",
    advance,
    "      // A server that echoes its own continuation would page the same page forever.",
    "      if (next == null) {",
    "        break;",
    "      }",
    "      String key = String.valueOf(next);",
    "      if (seen.contains(key)) {",
    "        break;",
    "      }",
    "      seen.add(key);",
    "      cursor = next;",
    "    }",
    "    return pages;",
    "  }",
  ];
}

const JAVA_LINK_HELPER = `
  /** The continuation parameter of a next-page link, read without ever fetching the link. */
  private static String pagerLinkParam(String link, String name) {
    try {
      String query = java.net.URI.create(link).getRawQuery();
      if (query == null) {
        return null;
      }
      for (String pair : query.split("&")) {
        int at = pair.indexOf('=');
        String key = at < 0 ? pair : pair.substring(0, at);
        if (java.net.URLDecoder.decode(key, java.nio.charset.StandardCharsets.UTF_8).equals(name)) {
          String value = at < 0 ? "" : pair.substring(at + 1);
          value = java.net.URLDecoder.decode(value, java.nio.charset.StandardCharsets.UTF_8);
          return value.isEmpty() ? null : value;
        }
      }
      return null;
    } catch (IllegalArgumentException e) {
      return null;
    }
  }
`;

function clientFile(pkg: string, plan: SdkPlan): string {
  const name = clientName(plan);
  const anyLinkPager = plan.operations.some((op) => op.pager?.style === "link");
  const methods = [
    ...plan.operations.map((op) => javaMethod(op)),
    ...(anyLinkPager ? [JAVA_LINK_HELPER] : []),
  ].join("\n\n");
  const tls = plan.auth.tls;
  const refresh = plan.auth.tokenRefresh;
  return `// Generated by Anvil. Do not edit — regenerate from AIR.
package ${pkg};

import java.net.http.HttpClient;
import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.function.DoubleSupplier;
import java.util.function.Supplier;

/**
 * ${plan.service.description}
 *
 * <p>Every method is one approved operation. The safety gates live in the
 * invoker, so no method can skip them.
 */
public final class ${name} {

  /** The base URL recorded in AIR at compile time. */
  public static final String DEFAULT_BASE_URL = ${q(plan.service.baseUrl)};

  /**
   * The environment variable read when no credential is supplied.${
     tls
       ? " Unused for\n   * this service — mtls carries no header or token; see CLIENT_CERT_ENV_VAR /\n   * CLIENT_KEY_ENV_VAR instead."
       : plan.auth.type === "custom_header"
         ? " Holds the raw\n   * header value — no scheme prefix is added."
         : ""
}
   */
  public static final String TOKEN_ENV_VAR = ${q(plan.auth.envVar)};
${
  tls
    ? `
  /** Client-certificate material, by environment-variable NAME only — never PEM in generated code. */
  public static final String CLIENT_CERT_ENV_VAR = ${q(tls.certEnvVar)};
  public static final String CLIENT_KEY_ENV_VAR = ${q(tls.keyEnvVar)};
  ${tls.caEnvVar ? `public static final String CA_ENV_VAR = ${q(tls.caEnvVar)};` : ""}
`
    : ""
}${
  refresh
    ? `
  /** Refresh-token wiring for the authorization-code grant (RFC 6749 section 6). */
  public static final String TOKEN_ENDPOINT = ${q(refresh.tokenEndpoint)};
  public static final String REFRESH_TOKEN_ENV_VAR = ${q(refresh.refreshTokenEnvVar)};
  public static final String CLIENT_ID_ENV_VAR = ${q(refresh.clientIdEnvVar)};
  public static final String CLIENT_SECRET_ENV_VAR = ${q(refresh.clientSecretEnvVar)};
  /** How the refresh grant authenticates to the token endpoint — the same method the runtime uses. */
  public static final String TOKEN_CLIENT_AUTH = ${q(refresh.clientAuth)};
`
    : ""
}${javaGrantConstants(plan)}
  private static final String USER_AGENT = ${q(`anvil-sdk-${plan.service.id}/${plan.service.version} (java)`)};

  private final Invoker.Config config;

  private ${name}(Invoker.Config config) {
    this.config = config;
  }

  /** A client on the compiled-in base URL, reading the credential from the environment. */
  public static ${name} create() {
    return builder().build();
  }

  public static Builder builder() {
    return new Builder();
  }

  /** Configures a client. The credential is never logged, echoed, or thrown. */
  public static final class Builder {
    private String baseUrl = DEFAULT_BASE_URL;
    private String protocolFacade = System.getenv("ANVIL_PROTOCOL_FACADE");
    private String token = System.getenv(TOKEN_ENV_VAR);
    private Supplier<String> tokenSupplier;${javaGrantBuilderFields(plan)}
    private Duration timeout = Duration.ofSeconds(30);
    private HttpClient httpClient;
    private DoubleSupplier random = Math::random;

    /**
     * Declares that the base URL really does serve the synthesized coordinates
     * of a non-HTTP/JSON source (SOAP, GraphQL, gRPC) over HTTP+JSON. Without
     * it those operations are refused rather than sent.
     */
    public Builder protocolFacade(String reason) {
      this.protocolFacade = reason;
      return this;
    }

    public Builder baseUrl(String value) {
      this.baseUrl = value;
      return this;
    }

    public Builder token(String value) {
      this.token = value;
      return this;
    }

    /**
     * Sets a delegated-token source for oauth2_authorization_code: called
     * once per call, taking priority over {@link #token}. Never logged,
     * echoed, or included in an exception.
     */
    public Builder tokenSupplier(Supplier<String> value) {
      this.tokenSupplier = value;
      return this;
    }

${javaGrantBuilderMethods(plan)}
    public Builder timeout(Duration value) {
      this.timeout = value;
      return this;
    }

    /** Injects a transport, for tests and embedders. */
    public Builder httpClient(HttpClient value) {
      this.httpClient = value;
      return this;
    }

    /** Injects the jitter source, so a retry schedule is deterministic under test. */
    public Builder random(DoubleSupplier value) {
      this.random = value;
      return this;
    }

    public ${name} build() {
      if (baseUrl == null || baseUrl.isEmpty()) {
        throw AnvilException.builder(
                "validation_error",
                ${q(plan.service.id)},
                "No base URL: the compiled model records no server, so one must be passed to"
                    + " builder().baseUrl(...).")
            .requiredArguments("baseUrl")
            .build();
      }
${
  tls
    ? `      // mTLS: an explicit httpClient(...) always wins; otherwise a client is
      // built from the declared certificate/key (and CA, when named) once,
      // at construction.
      if (httpClient == null) {
        String cert = System.getenv(CLIENT_CERT_ENV_VAR);
        String key = System.getenv(CLIENT_KEY_ENV_VAR);
        if (cert != null && !cert.isEmpty() && key != null && !key.isEmpty()) {
          javax.net.ssl.SSLContext sslContext =
              Mtls.buildContext(cert, key, ${tls.caEnvVar ? "System.getenv(CA_ENV_VAR)" : "null"});
          httpClient =
              HttpClient.newBuilder().connectTimeout(timeout).sslContext(sslContext).build();
        }
      }
`
    : ""
}${
  refresh
    ? `      // A caller-supplied token(...) or tokenSupplier(...) always wins. Only
      // when neither is set, and a refresh token is available, does the
      // client mint its own supplier from the declared token endpoint.
      if (tokenSupplier == null && (token == null || token.isEmpty())) {
        String refreshToken = System.getenv(REFRESH_TOKEN_ENV_VAR);
        String clientId = System.getenv(CLIENT_ID_ENV_VAR);
        if (refreshToken != null && !refreshToken.isEmpty() && clientId != null && !clientId.isEmpty()) {
          tokenSupplier =
              Oauth.refreshingTokenProvider(
                  TOKEN_ENDPOINT,
                  refreshToken,
                  clientId,
                  System.getenv(CLIENT_SECRET_ENV_VAR),
                  TOKEN_CLIENT_AUTH);
        }
      }
`
    : ""
}${javaGrantWiring(plan)}      HttpClient client =
          httpClient != null
              ? httpClient
              : HttpClient.newBuilder().connectTimeout(timeout).build();
      return new ${name}(
          new Invoker.Config(
              baseUrl,
              protocolFacade,
              token,
              tokenSupplier,
              ${plan.auth.carrier ? q(plan.auth.carrier.in) : "null"},
              ${plan.auth.carrier ? q(plan.auth.carrier.name) : "null"},
              ${plan.auth.carrier?.scheme ? q(plan.auth.carrier.scheme) : "null"},
              timeout,
              client,
              USER_AGENT,
              random));
    }
  }

${methods.length > 0 ? methods : "  // This bundle has no approved operations yet."}
}
`;
}

function javaMethod(op: SdkOperation): string {
  const gated = op.confirmation.required || op.idempotency.callerKeyRequired;
  const doc = [
    "  /**",
    `   * ${op.description}`,
    "   *",
    ...safetyNotes(op).flatMap((note) => wrap(note, 72).map((line) => `   * <p>${line}`)),
    "   *",
    "   * @throws AnvilException a structured refusal or upstream failure.",
    "   */",
  ].join("\n");
  const lines = [
    doc,
    `  public Object ${op.names.camel}(${op.names.pascal}Input input, CallOptions options) {`,
    `    return Invoker.invoke(config, Operations.get(${q(op.names.camel)}), input.payload(), options);`,
    "  }",
  ];
  if (!gated) {
    // The convenience overload exists only where the contract has no gate to
    // satisfy. Where it does, its absence is the gate, visible at compile time.
    lines.push(
      "",
      `  /** ${op.description} */`,
      `  public Object ${op.names.camel}(${op.names.pascal}Input input) {`,
      `    return ${op.names.camel}(input, CallOptions.none());`,
      "  }",
    );
  }
  const pager = op.pager;
  if (pager) {
    lines.push("", ...javaPager(op, pager));
  }
  const contract = op.async;
  if (contract?.statusMethodBase && contract.statusJobIdKey && contract.terminalStates.length > 0) {
    const statusCamel = javaCamel(contract.statusMethodBase);
    const statusPascal = contract.statusMethodBase
      .split("_")
      .filter(Boolean)
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join("");
    lines.push(
      "",
      "  /**",
      `   * ${contract.instruction}`,
      "   *",
      "   * <p>Polls at the interval the contract declares and returns the first status",
      "   * response in a terminal state. Every field name below is the one AIR resolved",
      "   * — none is guessed.",
      "   */",
      `  public Object waitFor${op.names.pascal}(Object submitResult, Duration timeout) {`,
      `    Object handle = Invoker.field(submitResult, ${q(contract.jobIdField)});`,
      "    if (!(handle instanceof String) || ((String) handle).isEmpty()) {",
      "      throw AnvilException.builder(",
      `              "schema_mismatch", ${q(op.id)},`,
      `              "The submit response carried no ${contract.jobIdField} to poll on.")`,
      "          .build();",
      "    }",
      `    Duration budget = timeout == null ? Duration.ofSeconds(${contract.pollIntervalSeconds * 60}) : timeout;`,
      "    Instant deadline = Instant.now().plus(budget);",
      `    List<String> terminal = Arrays.asList(${contract.terminalStates.map((state) => q(state)).join(", ")});`,
      "    while (true) {",
      `      Object status = ${statusCamel}(new ${statusPascal}Input((String) handle), CallOptions.none());`,
      `      Object state = Invoker.field(status, ${q(contract.stateField ?? "state")});`,
      "      if (state instanceof String && terminal.contains(state)) {",
      "        return status;",
      "      }",
      "      if (Instant.now().isAfter(deadline)) {",
      "        throw AnvilException.builder(",
      `                "upstream_timeout", ${q(op.id)},`,
      `                "${op.canonicalName} did not reach a terminal state before the wait deadline.")`,
      "            .retryable(true)",
      "            .build();",
      "      }",
      "      try {",
      `        Thread.sleep(${contract.pollIntervalSeconds * 1000}L);`,
      "      } catch (InterruptedException interrupted) {",
      "        Thread.currentThread().interrupt();",
      "        throw AnvilException.builder(",
      `                "upstream_timeout", ${q(op.id)}, "The wait was interrupted.")`,
      "            .build();",
      "      }",
      "    }",
      "  }",
    );
  }
  return lines.join("\n");
}
