import type { SdkPlan } from "./plan.js";

/**
 * The Java SDK's decision core — the classes that are identical for every
 * service Anvil compiles, apart from the package clause.
 *
 * They live apart from the per-service projection on purpose: the code that
 * decides whether a call is allowed to happen is one reviewed implementation,
 * and generation only ever adds rows to the table it reads. `Json` is here too:
 * Java has no JSON in its standard library, and a hand-written codec is exactly
 * the kind of thing that should have one copy, not one per service.
 */

const q = (value: unknown): string => JSON.stringify(value);

/** The Java package, e.g. `com.anvil.sdk.payments`. */
export function javaPackage(plan: SdkPlan): string {
  const sanitized = plan.service.id.replace(/[^a-z0-9]/g, "");
  return `com.anvil.sdk.${/^[a-z]/.test(sanitized) ? sanitized : `s${sanitized}`}`;
}

export function exceptionFile(pkg: string, plan: SdkPlan): string {
  return `// Generated by Anvil. Do not edit — regenerate from AIR.
package ${pkg};

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

/**
 * Every failure this SDK raises. Anvil never leaks raw upstream chaos as the
 * primary interface: a refusal always arrives as this, with a code from the
 * taxonomy and the next action attached.
 */
public final class AnvilException extends RuntimeException {

  private static final long serialVersionUID = 1L;

  /** The Anvil error taxonomy (spec section 10). */
  public static final List<String> ERROR_CODES =
      Collections.unmodifiableList(
          Arrays.asList(
${plan.errorCodes.map((code) => `              ${q(code)}`).join(",\n")}));

  private final String code;
  private final String operation;
  private final String traceId;
  private final boolean retryable;
  private final boolean safeToRetry;
  private final int upstreamStatus;
  private final String upstreamRequestId;
  private final List<String> requiredArguments;
  private final long retryAfterMs;

  AnvilException(Builder builder) {
    super(builder.message);
    this.code = builder.code;
    this.operation = builder.operation;
    this.traceId = builder.traceId;
    this.retryable = builder.retryable;
    this.safeToRetry = builder.safeToRetry;
    this.upstreamStatus = builder.upstreamStatus;
    this.upstreamRequestId = builder.upstreamRequestId;
    this.requiredArguments =
        Collections.unmodifiableList(Arrays.asList(builder.requiredArguments));
    this.retryAfterMs = builder.retryAfterMs;
  }

  /** One of {@link #ERROR_CODES}. */
  public String code() {
    return code;
  }

  public String operation() {
    return operation;
  }

  public String traceId() {
    return traceId;
  }

  public boolean retryable() {
    return retryable;
  }

  public boolean safeToRetry() {
    return safeToRetry;
  }

  /** The upstream HTTP status, or 0 when the failure never reached one. */
  public int upstreamStatus() {
    return upstreamStatus;
  }

  public String upstreamRequestId() {
    return upstreamRequestId;
  }

  /** What the caller must supply, for confirmation_required / idempotency_required. */
  public List<String> requiredArguments() {
    return requiredArguments;
  }

  /** The upstream's own backpressure instruction, or 0 when it gave none. */
  public long retryAfterMs() {
    return retryAfterMs;
  }

  /** Map an upstream HTTP status onto the Anvil error taxonomy. */
  public static String httpStatusToErrorCode(int status) {
    switch (status) {
      case 400:
      case 422:
        return "validation_error";
      case 401:
        return "auth_required";
      case 403:
        return "permission_denied";
      case 404:
      case 410:
        return "not_found";
      case 408:
        return "upstream_timeout";
      case 409:
        return "conflict";
      case 429:
        return "rate_limited";
      case 502:
      case 503:
        return "upstream_unavailable";
      case 504:
        return "upstream_timeout";
      default:
        break;
    }
    if (status >= 500) {
      return "unknown_upstream_error";
    }
    if (status >= 400) {
      return "validation_error";
    }
    return "unknown_upstream_error";
  }

  /** Whether a code is inherently retryable, before the idempotency gate. */
  public static boolean isRetryableCode(String code) {
    return "rate_limited".equals(code)
        || "upstream_timeout".equals(code)
        || "upstream_unavailable".equals(code);
  }

  static Builder builder(String code, String operation, String message) {
    return new Builder(code, operation, message);
  }

  static final class Builder {
    private final String code;
    private final String operation;
    private final String message;
    private String traceId = "";
    private boolean retryable;
    private boolean safeToRetry;
    private int upstreamStatus;
    private String upstreamRequestId;
    private String[] requiredArguments = new String[0];
    private long retryAfterMs;

    Builder(String code, String operation, String message) {
      this.code = code;
      this.operation = operation;
      this.message = message;
    }

    Builder traceId(String value) {
      this.traceId = value;
      return this;
    }

    Builder retryable(boolean value) {
      this.retryable = value;
      return this;
    }

    Builder safeToRetry(boolean value) {
      this.safeToRetry = value;
      return this;
    }

    Builder upstream(int status, String requestId) {
      this.upstreamStatus = status;
      this.upstreamRequestId = requestId;
      return this;
    }

    Builder requiredArguments(String... values) {
      this.requiredArguments = values;
      return this;
    }

    Builder retryAfterMs(long value) {
      this.retryAfterMs = value;
      return this;
    }

    AnvilException build() {
      return new AnvilException(this);
    }
  }
}
`;
}

export function specFile(pkg: string): string {
  return `// Generated by Anvil. Do not edit — regenerate from AIR.
package ${pkg};

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

/**
 * One approved operation, as data. Generation only ever adds rows to the table
 * in {@link Operations}; the code that reads it is the same reviewed
 * implementation everywhere.
 */
public final class OperationSpec {

  /** One non-body request parameter. */
  public static final class Param {
    /** The exact on-wire coordinate. */
    public final String wireName;
    /** The payload key the caller's input object produces. */
    public final String key;
    public final String in;
    public final boolean required;

    public Param(String wireName, String key, String in, boolean required) {
      this.wireName = wireName;
      this.key = key;
      this.in = in;
      this.required = required;
    }
  }

  /** One projected top-level body field. */
  public static final class BodyField {
    public final String wireName;
    public final String key;
    public final boolean required;

    public BodyField(String wireName, String key, boolean required) {
      this.wireName = wireName;
      this.key = key;
      this.required = required;
    }
  }

  /** The request body as AIR preserved it. */
  public static final class Body {
    public final boolean required;
    public final String contentType;
    public final String projection;
    public final List<BodyField> fields;

    public Body(boolean required, String contentType, String projection, BodyField... fields) {
      this.required = required;
      this.contentType = contentType;
      this.projection = projection;
      this.fields = Collections.unmodifiableList(Arrays.asList(fields));
    }
  }

  /** The exact on-wire coordinate an idempotency key is placed at. */
  public static final class Carrier {
    public final String mechanism;
    public final String key;
    /** The property path, for a body carrier. */
    public final List<String> path;

    public Carrier(String mechanism, String key, String... path) {
      this.mechanism = mechanism;
      this.key = key;
      this.path = Collections.unmodifiableList(Arrays.asList(path));
    }
  }

  /** The contract's idempotency posture. */
  public static final class Idempotency {
    public final String mode;
    public final String keyDerivation;
    /** True when the SDK must refuse until the caller supplies a key. */
    public final boolean callerKeyRequired;
    public final Carrier carrier;

    public Idempotency(
        String mode, String keyDerivation, boolean callerKeyRequired, Carrier carrier) {
      this.mode = mode;
      this.keyDerivation = keyDerivation;
      this.callerKeyRequired = callerKeyRequired;
      this.carrier = carrier;
    }
  }

  /** The resolved retry policy. */
  public static final class Retry {
    public final String mode;
    public final int maxAttempts;
    public final String backoff;
    public final long baseDelayMs;
    public final long maxDelayMs;
    public final int[] retryStatuses;
    public final boolean retryTransport;

    public Retry(
        String mode,
        int maxAttempts,
        String backoff,
        long baseDelayMs,
        long maxDelayMs,
        int[] retryStatuses,
        boolean retryTransport) {
      this.mode = mode;
      this.maxAttempts = maxAttempts;
      this.backoff = backoff;
      this.baseDelayMs = baseDelayMs;
      this.maxDelayMs = maxDelayMs;
      this.retryStatuses = retryStatuses;
      this.retryTransport = retryTransport;
    }

    public boolean retries(int status) {
      for (int candidate : retryStatuses) {
        if (candidate == status) {
          return true;
        }
      }
      return false;
    }
  }

  /** The confirmation gate. */
  public static final class Confirmation {
    public final boolean required;
    public final boolean humanApproval;
    public final String reason;

    public Confirmation(boolean required, boolean humanApproval, String reason) {
      this.required = required;
      this.humanApproval = humanApproval;
      this.reason = reason;
    }
  }

  public final String id;
  public final String httpMethod;
  /**
   * What a real call must speak. Anything but "http_json" means the path below
   * is a coordinate Anvil synthesized to hold operations apart, not a wire
   * address.
   */
  public final String wireProtocol;
  /** The path template with {wire_name} placeholders. */
  public final String path;
  public final String effect;
  public final List<Param> params;
  public final Body body;
  public final Idempotency idempotency;
  public final Retry retry;
  public final Confirmation confirmation;

  public OperationSpec(
      String id,
      String httpMethod,
      String wireProtocol,
      String path,
      String effect,
      Param[] params,
      Body body,
      Idempotency idempotency,
      Retry retry,
      Confirmation confirmation) {
    this.id = id;
    this.httpMethod = httpMethod;
    this.wireProtocol = wireProtocol;
    this.path = path;
    this.effect = effect;
    this.params = Collections.unmodifiableList(Arrays.asList(params));
    this.body = body;
    this.idempotency = idempotency;
    this.retry = retry;
    this.confirmation = confirmation;
  }
}
`;
}

export function callOptionsFile(pkg: string): string {
  return `// Generated by Anvil. Do not edit — regenerate from AIR.
package ${pkg};

import java.time.Duration;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * The per-call safety controls. These are never wire values — they decide
 * whether the SDK sends anything at all.
 */
public final class CallOptions {

  private boolean confirm;
  private String idempotencyKey;
  private Duration timeout;
  private final Map<String, String> headers = new LinkedHashMap<String, String>();

  private CallOptions() {}

  /** A fresh, empty set of options. */
  public static CallOptions none() {
    return new CallOptions();
  }

  /** Required by operations whose contract gates on confirmation. */
  public CallOptions confirm(boolean value) {
    this.confirm = value;
    return this;
  }

  /** Required when the contract needs a key Anvil cannot derive. */
  public CallOptions idempotencyKey(String value) {
    this.idempotencyKey = value;
    return this;
  }

  /** Overrides the client deadline for this call. */
  public CallOptions timeout(Duration value) {
    this.timeout = value;
    return this;
  }

  /** An extra request header. Reserved, transport-owned names are ignored. */
  public CallOptions header(String name, String value) {
    this.headers.put(name, value);
    return this;
  }

  boolean confirmed() {
    return confirm;
  }

  String idempotencyKey() {
    return idempotencyKey;
  }

  Duration timeout() {
    return timeout;
  }

  Map<String, String> headers() {
    return headers;
  }
}
`;
}
