import { GRANT_TOKEN_EXCHANGE, type SdkOauthGrants, TOKEN_TYPE_URN } from "./oauth-grants.js";

/**
 * `oauth.ts` — the TypeScript client's token grants, emitted only for a service
 * whose contract names a token endpoint (see `oauth-grants.ts` for which).
 *
 * One `postGrant` carries every grant to the endpoint, authenticating the way
 * the contract declares and the runtime already does (`provider.clientAuth`,
 * RFC 6749 §2.3.1): `client_secret_basic` sends HTTP Basic and keeps
 * `client_id` out of the form; `client_secret_post` carries both in the form;
 * `private_key_jwt` is refused, never downgraded. The interactive
 * authorization step never runs here, and nothing here logs a refresh token,
 * subject token, client secret, or minted access token.
 */
export function oauthModule(grants: SdkOauthGrants): string {
  return `// Generated by Anvil. Do not edit — regenerate from AIR.
// Token grants against the contract's declared token endpoint. Nothing here
// performs an interactive authorization step, and nothing here logs a refresh
// token, subject token, client secret, or minted access token.

export type TokenEndpointClientAuth =
  | "client_secret_basic"
  | "client_secret_post"
  | "private_key_jwt";

/** What every grant needs to authenticate the CLIENT to the token endpoint. */
export interface TokenGrantOptions {
  clientId: string;
  clientSecret?: string;
  /**
   * How to authenticate to the token endpoint (RFC 6749 §2.3.1). Defaults
   * to "client_secret_basic", the runtime's default for the same contract.
   */
  clientAuth?: TokenEndpointClientAuth;
  /** Injectable fetch, for tests. */
  fetch?: typeof fetch;
  /** Seconds of safety margin subtracted from a token's reported lifetime. */
  expirySkewSeconds?: number;
}

/** What a grant may narrow or address, when the contract or caller says so. */
export interface TokenGrantScope {
  scopes?: string[];
  audience?: string;
  resource?: string;
}

interface MintedToken {
  token: string;
  expiresAt: number;
}

/**
 * POST one grant to the token endpoint. Mirrors the runtime resolver exactly:
 * client_secret_basic sends the credentials as HTTP Basic and keeps client_id
 * out of the form; every other declared method carries client_id (and the
 * secret, when present) in the form body.
 */
async function postGrant(
  tokenEndpoint: string,
  form: URLSearchParams,
  options: TokenGrantOptions,
  kind: string,
): Promise<MintedToken> {
  const clientAuth = options.clientAuth ?? "client_secret_basic";
  if (clientAuth === "private_key_jwt") {
    // Nothing here mints an RFC 7523 assertion, so a private-key client is
    // refused rather than sent a client_secret it does not have.
    throw new Error("private_key_jwt client authentication is not supported by the " + kind + " helper");
  }
  const headers: Record<string, string> = {
    "content-type": "application/x-www-form-urlencoded",
  };
  if (options.clientSecret && clientAuth === "client_secret_basic") {
    headers.authorization = "Basic " + btoa(options.clientId + ":" + options.clientSecret);
  } else {
    form.set("client_id", options.clientId);
    if (options.clientSecret) form.set("client_secret", options.clientSecret);
  }
  const fetchImpl = options.fetch ?? ((url, init) => fetch(url, init));
  const response = await fetchImpl(tokenEndpoint, {
    method: "POST",
    headers,
    body: form.toString(),
  });
  if (!response.ok) {
    // Never surface the response body: a token endpoint's error payload can
    // echo back the credential it was sent.
    throw new Error(kind + " failed with HTTP " + response.status + " from " + tokenEndpoint);
  }
  const payload = (await response.json()) as { access_token?: string; expires_in?: number };
  if (!payload.access_token) {
    throw new Error("token endpoint response carried no access_token");
  }
  const skewMs = (options.expirySkewSeconds ?? 30) * 1000;
  return {
    token: payload.access_token,
    expiresAt: Date.now() + (payload.expires_in ?? 300) * 1000 - skewMs,
  };
}

function grantForm(fields: Record<string, string>, scope: TokenGrantScope): URLSearchParams {
  const form = new URLSearchParams(fields);
  if (scope.scopes && scope.scopes.length > 0) form.set("scope", scope.scopes.join(" "));
  if (scope.audience) form.set("audience", scope.audience);
  if (scope.resource) form.set("resource", scope.resource);
  return form;
}

/**
 * A provider that caches the minted token in memory until shortly before it
 * expires, and shares one in-flight mint between concurrent callers so a
 * burst of calls at startup is one round trip to the token endpoint.
 */
function cachedProvider(mint: () => Promise<MintedToken>): () => Promise<string> {
  let cached: MintedToken | undefined;
  let inFlight: Promise<MintedToken> | undefined;
  return async () => {
    if (cached && cached.expiresAt > Date.now()) return cached.token;
    if (!inFlight) {
      inFlight = mint().finally(() => {
        inFlight = undefined;
      });
    }
    cached = await inFlight;
    return cached.token;
  };
}
${
  grants.refresh
    ? `
export interface RefreshTokenProviderOptions extends TokenGrantOptions {
  refreshToken: string;
}

/**
 * Build a \`tokenProvider\` that exchanges a refresh token at \`tokenEndpoint\`
 * (RFC 6749 §6) and caches the access token in memory until shortly before it
 * expires. Pass the result as \`ClientOptions.tokenProvider\`. Never performs
 * the interactive authorization step — only refreshes a token that step
 * already produced.
 */
export function createRefreshingTokenProvider(
  tokenEndpoint: string,
  options: RefreshTokenProviderOptions,
): () => Promise<string> {
  return cachedProvider(() =>
    postGrant(
      tokenEndpoint,
      new URLSearchParams({ grant_type: "refresh_token", refresh_token: options.refreshToken }),
      options,
      "token refresh",
    ),
  );
}
`
    : ""
}${
  grants.clientCredentials
    ? `
export interface ClientCredentialsOptions extends TokenGrantOptions, TokenGrantScope {}

/**
 * Build a \`tokenProvider\` that mints the service's own bearer with the
 * client-credentials grant (RFC 6749 §4.4) and caches it in memory until
 * shortly before it expires — the same grant, to the same endpoint, with the
 * same client authentication the runtime uses for this contract.
 */
export function createClientCredentialsTokenProvider(
  tokenEndpoint: string,
  options: ClientCredentialsOptions,
): () => Promise<string> {
  return cachedProvider(() =>
    postGrant(
      tokenEndpoint,
      grantForm({ grant_type: "client_credentials" }, options),
      options,
      "client-credentials grant",
    ),
  );
}
`
    : ""
}${
  grants.tokenExchange
    ? `
/** RFC 8693 token-type URNs, the same table the runtime sends. */
const TOKEN_TYPE_URN = ${JSON.stringify(TOKEN_TYPE_URN, null, 2).split("\n").join("\n")} as const;

export type TokenType = keyof typeof TOKEN_TYPE_URN;

export interface TokenExchangeOptions extends TokenGrantOptions, TokenGrantScope {
  /** The type of the subject token being exchanged; the contract's, else access_token. */
  subjectTokenType?: TokenType;
  /** The type of token asked for; the contract's, else access_token. */
  requestedTokenType?: TokenType;
  /** Distinct subjects whose exchanged tokens are kept in memory at once. */
  maxCacheEntries?: number;
}

/**
 * A token exchange (RFC 8693) shared across subjects: one instance, one cache,
 * a \`tokenProvider\` per inbound caller. The subject token is exchanged, never
 * sent upstream as-is, and never logged.
 */
export interface TokenExchanger {
  tokenProvider(subjectToken: string, actorToken?: string): () => Promise<string>;
}

/**
 * Build a token exchanger against \`tokenEndpoint\`. Each subject's exchanged
 * token is cached until shortly before it expires; distinct subjects (and
 * distinct actors for one subject) never share a token.
 */
export function createTokenExchanger(
  tokenEndpoint: string,
  options: TokenExchangeOptions,
): TokenExchanger {
  const providers = new Map<string, () => Promise<string>>();
  const maxEntries = options.maxCacheEntries ?? 256;
  return {
    tokenProvider(subjectToken, actorToken) {
      const key = subjectToken + "\\u0000" + (actorToken ?? "");
      const existing = providers.get(key);
      if (existing) return existing;
      const provider = cachedProvider(() =>
        postGrant(
          tokenEndpoint,
          grantForm(
            {
              grant_type: ${JSON.stringify(GRANT_TOKEN_EXCHANGE)},
              subject_token: subjectToken,
              subject_token_type: TOKEN_TYPE_URN[options.subjectTokenType ?? "access_token"],
              requested_token_type: TOKEN_TYPE_URN[options.requestedTokenType ?? "access_token"],
              ...(actorToken ? { actor_token: actorToken, actor_token_type: TOKEN_TYPE_URN.jwt } : {}),
            },
            options,
          ),
          options,
          "token exchange",
        ),
      );
      if (providers.size >= maxEntries) {
        const oldest = providers.keys().next().value;
        if (oldest !== undefined) providers.delete(oldest);
      }
      providers.set(key, provider);
      return provider;
    },
  };
}
`
    : ""
}`;
}
