import { GRANT_TOKEN_EXCHANGE, type SdkOauthGrants, TOKEN_TYPE_URN } from "./oauth-grants.js";

const p = (value: unknown): string => JSON.stringify(value);

/**
 * `_oauth.py` — the Python client's token grants, emitted only for a service
 * whose contract names a token endpoint (see `oauth-grants.ts` for which).
 *
 * Same shape as the TypeScript module: one `_post_grant` carries every grant
 * to the endpoint with the declared client authentication, `private_key_jwt`
 * is refused rather than downgraded, and a `_Cached` provider holds the
 * minted token until shortly before it expires behind one lock, so
 * concurrent first calls are one round trip rather than several.
 *
 * `create_refreshing_token_provider` keeps its earlier signature exactly:
 * `client_auth` stays LAST so a caller of an earlier generation who passed
 * `expiry_skew_seconds` and `opener` positionally is not silently rebound.
 */
export function oauthModule(grants: SdkOauthGrants): string {
  return `"""Generated by Anvil. Do not edit — regenerate from AIR.

Token grants against the contract's declared token endpoint. Nothing here
performs an interactive authorization step, and nothing here logs a refresh
token, subject token, client secret, or minted access token.
"""

import base64
import json
import threading
import time
import urllib.error
import urllib.parse
import urllib.request
from typing import Any, Callable, Dict, List, Optional, Tuple


def _refuse_assertion_auth(client_auth: str, kind: str) -> None:
    if client_auth == "private_key_jwt":
        # Nothing here mints an RFC 7523 assertion, so a private-key client is
        # refused rather than sent a client_secret it does not have.
        raise RuntimeError(
            "private_key_jwt client authentication is not supported by the %s helper" % kind
        )


def _post_grant(
    token_endpoint: str,
    form: Dict[str, str],
    client_id: str,
    client_secret: Optional[str],
    client_auth: str,
    opener: Any,
    kind: str,
) -> Tuple[str, float]:
    """POST one grant and return (access_token, expires_in_seconds).

    Mirrors the runtime resolver exactly: client_secret_basic sends the
    credentials as HTTP Basic and keeps client_id out of the form; every other
    declared method carries client_id (and the secret, when present) in the
    form body.
    """
    _refuse_assertion_auth(client_auth, kind)
    headers = {"content-type": "application/x-www-form-urlencoded"}
    if client_secret and client_auth == "client_secret_basic":
        basic = base64.b64encode(("%s:%s" % (client_id, client_secret)).encode("utf-8"))
        headers["authorization"] = "Basic " + basic.decode("ascii")
    else:
        form["client_id"] = client_id
        if client_secret:
            form["client_secret"] = client_secret
    body = urllib.parse.urlencode(form).encode("utf-8")
    request = urllib.request.Request(token_endpoint, data=body, headers=headers, method="POST")
    send = opener or urllib.request.urlopen
    try:
        with send(request, timeout=30.0) as response:
            raw = response.read()
    except urllib.error.HTTPError as error:
        # Never surface the response body: a token endpoint's error payload
        # can echo back the credential it was sent.
        raise RuntimeError(
            "%s failed with HTTP %s from %s" % (kind, error.code, token_endpoint)
        ) from None
    payload = json.loads(raw.decode("utf-8"))
    access_token = payload.get("access_token")
    if not access_token:
        raise RuntimeError("token endpoint response carried no access_token")
    return access_token, float(payload.get("expires_in", 300))


def _grant_form(
    fields: Dict[str, str],
    scopes: Optional[List[str]],
    audience: Optional[str],
    resource: Optional[str],
) -> Dict[str, str]:
    form = dict(fields)
    if scopes:
        form["scope"] = " ".join(scopes)
    if audience:
        form["audience"] = audience
    if resource:
        form["resource"] = resource
    return form


class _Cached(object):
    """A provider that caches the minted token until shortly before it expires.

    One lock, so concurrent first calls share a single mint rather than each
    opening a round trip to the token endpoint.
    """

    def __init__(self, mint: Callable[[], Tuple[str, float]], expiry_skew_seconds: float) -> None:
        self._mint = mint
        self._skew = expiry_skew_seconds
        self._lock = threading.Lock()
        self._token: Optional[str] = None
        self._expires_at = 0.0

    def __call__(self) -> str:
        with self._lock:
            if self._token and self._expires_at > time.time():
                return self._token
            token, expires_in = self._mint()
            self._token = token
            self._expires_at = time.time() + expires_in - self._skew
            return token
${
  grants.refresh
    ? `

def create_refreshing_token_provider(
    token_endpoint: str,
    refresh_token: str,
    client_id: str,
    client_secret: Optional[str] = None,
    expiry_skew_seconds: float = 30.0,
    opener: Any = None,
    client_auth: str = "client_secret_basic",
) -> Callable[[], str]:
    """Build a token provider that exchanges 'refresh_token' at
    'token_endpoint' (RFC 6749 section 6) and caches the access token in
    memory until shortly before it expires. Never performs the interactive
    authorization step.

    'client_auth' is how the client authenticates to the token endpoint
    (RFC 6749 section 2.3.1), defaulting to 'client_secret_basic' exactly as
    the runtime resolver does for the same contract. It is LAST in the
    signature on purpose: callers of an earlier generation may pass
    'expiry_skew_seconds' and 'opener' positionally, and inserting a parameter
    before them would silently rebind those arguments on regeneration."""
    _refuse_assertion_auth(client_auth, "token refresh")
    return _Cached(
        lambda: _post_grant(
            token_endpoint,
            {"grant_type": "refresh_token", "refresh_token": refresh_token},
            client_id,
            client_secret,
            client_auth,
            opener,
            "token refresh",
        ),
        expiry_skew_seconds,
    )
`
    : ""
}${
  grants.clientCredentials
    ? `

def create_client_credentials_token_provider(
    token_endpoint: str,
    client_id: str,
    client_secret: Optional[str],
    scopes: Optional[List[str]] = None,
    audience: Optional[str] = None,
    resource: Optional[str] = None,
    client_auth: str = "client_secret_basic",
    expiry_skew_seconds: float = 30.0,
    opener: Any = None,
) -> Callable[[], str]:
    """Build a token provider that mints the service's own bearer with the
    client-credentials grant (RFC 6749 section 4.4) and caches it in memory
    until shortly before it expires — the same grant, to the same endpoint,
    with the same client authentication the runtime uses for this contract."""
    _refuse_assertion_auth(client_auth, "client-credentials grant")
    return _Cached(
        lambda: _post_grant(
            token_endpoint,
            _grant_form({"grant_type": "client_credentials"}, scopes, audience, resource),
            client_id,
            client_secret,
            client_auth,
            opener,
            "client-credentials grant",
        ),
        expiry_skew_seconds,
    )
`
    : ""
}${
  grants.tokenExchange
    ? `

#: RFC 8693 token-type URNs, the same table the runtime sends.
TOKEN_TYPE_URN = {
${Object.entries(TOKEN_TYPE_URN)
  .map(([name, urn]) => `    ${p(name)}: ${p(urn)},`)
  .join("\n")}
}


class TokenExchanger(object):
    """A token exchange (RFC 8693) shared across subjects: one instance, one
    cache, a token provider per inbound caller. The subject token is
    exchanged, never sent upstream as-is, and never logged. Each subject's
    exchanged token is cached until shortly before it expires; distinct
    subjects (and distinct actors for one subject) never share a token."""

    def __init__(
        self,
        token_endpoint: str,
        client_id: str,
        client_secret: Optional[str] = None,
        client_auth: str = "client_secret_basic",
        subject_token_type: str = "access_token",
        requested_token_type: str = "access_token",
        scopes: Optional[List[str]] = None,
        audience: Optional[str] = None,
        resource: Optional[str] = None,
        expiry_skew_seconds: float = 30.0,
        opener: Any = None,
        max_cache_entries: int = 256,
    ) -> None:
        _refuse_assertion_auth(client_auth, "token exchange")
        self._token_endpoint = token_endpoint
        self._client_id = client_id
        self._client_secret = client_secret
        self._client_auth = client_auth
        self._subject_token_type = TOKEN_TYPE_URN[subject_token_type]
        self._requested_token_type = TOKEN_TYPE_URN[requested_token_type]
        self._scopes = scopes
        self._audience = audience
        self._resource = resource
        self._skew = expiry_skew_seconds
        self._opener = opener
        self._max_cache_entries = max_cache_entries
        self._providers: Dict[str, Callable[[], str]] = {}
        self._lock = threading.Lock()

    def token_provider(self, subject_token: str, actor_token: Optional[str] = None) -> Callable[[], str]:
        """The provider for one inbound caller; pass it as 'token_provider'."""
        key = subject_token + "\\x00" + (actor_token or "")
        with self._lock:
            existing = self._providers.get(key)
            if existing is not None:
                return existing
            fields = {
                "grant_type": ${p(GRANT_TOKEN_EXCHANGE)},
                "subject_token": subject_token,
                "subject_token_type": self._subject_token_type,
                "requested_token_type": self._requested_token_type,
            }
            if actor_token:
                fields["actor_token"] = actor_token
                fields["actor_token_type"] = TOKEN_TYPE_URN["jwt"]
            form = _grant_form(fields, self._scopes, self._audience, self._resource)
            provider = _Cached(
                lambda: _post_grant(
                    self._token_endpoint,
                    dict(form),
                    self._client_id,
                    self._client_secret,
                    self._client_auth,
                    self._opener,
                    "token exchange",
                ),
                self._skew,
            )
            if len(self._providers) >= self._max_cache_entries:
                del self._providers[next(iter(self._providers))]
            self._providers[key] = provider
            return provider


def create_token_exchanger(token_endpoint: str, client_id: str, **options: Any) -> TokenExchanger:
    """Build a 'TokenExchanger' against 'token_endpoint'; keyword options are
    the constructor's ('client_secret', 'client_auth', 'subject_token_type',
    'requested_token_type', 'scopes', 'audience', 'resource', ...)."""
    return TokenExchanger(token_endpoint, client_id, **options)
`
    : ""
}`;
}
