import { GRANT_TOKEN_EXCHANGE, type SdkOauthGrants, TOKEN_TYPE_URN } from "./oauth-grants.js";

const g = (value: unknown): string => JSON.stringify(value);

/**
 * `oauth.go` — the Go client's token grants, emitted only for a service whose
 * contract names a token endpoint (see `oauth-grants.ts` for which).
 *
 * Same shape as the TypeScript module: one `postGrant` carries every grant to
 * the endpoint with the declared client authentication, `private_key_jwt` is
 * refused rather than downgraded, and `cachedProvider` holds the minted token
 * until shortly before it expires behind one mutex, so concurrent first calls
 * are one round trip rather than several.
 *
 * `NewRefreshingTokenProvider` keeps its earlier signature exactly: the
 * client-auth method is VARIADIC so the four-argument call an earlier
 * generation exported still compiles and still means `client_secret_basic`.
 */
export function oauthFile(pkg: string, grants: SdkOauthGrants): string {
  return `// Generated by Anvil. Do not edit — regenerate from AIR.
//
// Token grants against the contract's declared token endpoint. Nothing here
// performs an interactive authorization step, and nothing here logs a refresh
// token, subject token, client secret, or minted access token.

package ${pkg}

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strconv"
	"strings"
	"sync"
	"time"
)

type mintedToken struct {
	AccessToken string \`json:"access_token"\`
	ExpiresIn   *int64 \`json:"expires_in"\`
}

// postGrant POSTs one grant to the token endpoint. Mirrors the runtime
// resolver exactly: client_secret_basic sends the credentials as HTTP Basic and
// keeps client_id out of the form; every other declared method carries
// client_id (and the secret, when present) in the form body. private_key_jwt
// is refused: nothing here mints an RFC 7523 assertion, and substituting a
// client secret would hand a private-key client a credential it does not have.
func postGrant(ctx context.Context, httpClient *http.Client, tokenEndpoint string, form url.Values, clientID, clientSecret, clientAuth, kind string) (string, time.Time, error) {
	if clientAuth == "" {
		clientAuth = "client_secret_basic"
	}
	if clientAuth == "private_key_jwt" {
		return "", time.Time{}, fmt.Errorf("private_key_jwt client authentication is not supported by the %s helper", kind)
	}
	useBasic := clientSecret != "" && clientAuth == "client_secret_basic"
	if !useBasic {
		form.Set("client_id", clientID)
		if clientSecret != "" {
			form.Set("client_secret", clientSecret)
		}
	}
	request, err := http.NewRequestWithContext(ctx, "POST", tokenEndpoint, strings.NewReader(form.Encode()))
	if err != nil {
		return "", time.Time{}, err
	}
	request.Header.Set("content-type", "application/x-www-form-urlencoded")
	if useBasic {
		request.SetBasicAuth(clientID, clientSecret)
	}
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	response, err := httpClient.Do(request)
	if err != nil {
		return "", time.Time{}, fmt.Errorf("%s could not reach %s", kind, tokenEndpoint)
	}
	defer response.Body.Close()
	raw, _ := io.ReadAll(response.Body)
	if response.StatusCode < 200 || response.StatusCode >= 300 {
		// Never surface the response body: a token endpoint's error payload can
		// echo back the credential it was sent.
		return "", time.Time{}, fmt.Errorf("%s failed with HTTP %s from %s", kind, strconv.Itoa(response.StatusCode), tokenEndpoint)
	}
	var payload mintedToken
	if err := json.Unmarshal(raw, &payload); err != nil || payload.AccessToken == "" {
		return "", time.Time{}, fmt.Errorf("token endpoint response carried no access_token")
	}
	expiresIn := int64(300)
	if payload.ExpiresIn != nil {
		expiresIn = *payload.ExpiresIn
	}
	return payload.AccessToken, time.Now().Add(time.Duration(expiresIn) * time.Second), nil
}

func grantForm(fields map[string]string, scopes []string, audience, resource string) url.Values {
	form := url.Values{}
	for key, value := range fields {
		form.Set(key, value)
	}
	if len(scopes) > 0 {
		form.Set("scope", strings.Join(scopes, " "))
	}
	if audience != "" {
		form.Set("audience", audience)
	}
	if resource != "" {
		form.Set("resource", resource)
	}
	return form
}

// cachedProvider caches the minted token in memory until shortly before it
// expires. One mutex, so concurrent first calls share a single mint rather
// than each opening a round trip to the token endpoint.
func cachedProvider(skew time.Duration, mint func(context.Context) (string, time.Time, error)) func(context.Context) (string, error) {
	var mu sync.Mutex
	var cachedToken string
	var expiresAt time.Time
	if skew == 0 {
		skew = 30 * time.Second
	}
	return func(ctx context.Context) (string, error) {
		mu.Lock()
		defer mu.Unlock()
		if cachedToken != "" && time.Now().Before(expiresAt) {
			return cachedToken, nil
		}
		token, expiry, err := mint(ctx)
		if err != nil {
			return "", err
		}
		cachedToken = token
		expiresAt = expiry.Add(-skew)
		return cachedToken, nil
	}
}
${
  grants.refresh
    ? `
// NewRefreshingTokenProvider builds a TokenProvider that exchanges
// refreshToken at tokenEndpoint (RFC 6749 section 6) and caches the access
// token in memory until shortly before it expires. Never performs the
// interactive authorization step.
//
// clientAuth is how the client authenticates to the token endpoint (RFC 6749
// section 2.3.1); "client_secret_basic" is the runtime's default for the same
// contract. It is VARIADIC so the four-argument call an earlier generation
// exported still compiles.
func NewRefreshingTokenProvider(tokenEndpoint, refreshToken, clientID, clientSecret string, clientAuth ...string) func(context.Context) (string, error) {
	method := "client_secret_basic"
	if len(clientAuth) > 0 && clientAuth[0] != "" {
		method = clientAuth[0]
	}
	return cachedProvider(0, func(ctx context.Context) (string, time.Time, error) {
		form := url.Values{}
		form.Set("grant_type", "refresh_token")
		form.Set("refresh_token", refreshToken)
		return postGrant(ctx, nil, tokenEndpoint, form, clientID, clientSecret, method, "token refresh")
	})
}
`
    : ""
}${
  grants.clientCredentials
    ? `
// ClientCredentialsOptions narrows or addresses a client-credentials grant.
type ClientCredentialsOptions struct {
	// ClientAuth is how the client authenticates to the token endpoint;
	// "client_secret_basic" when empty, the runtime's default.
	ClientAuth string
	Scopes     []string
	Audience   string
	Resource   string
	// HTTPClient carries the grant; http.DefaultClient when nil.
	HTTPClient *http.Client
	// ExpirySkew is subtracted from a token's reported lifetime; 30s when zero.
	ExpirySkew time.Duration
}

// NewClientCredentialsTokenProvider builds a TokenProvider that mints the
// service's own bearer with the client-credentials grant (RFC 6749 section
// 4.4) and caches it in memory until shortly before it expires — the same
// grant, to the same endpoint, with the same client authentication the
// runtime uses for this contract.
func NewClientCredentialsTokenProvider(tokenEndpoint, clientID, clientSecret string, options ClientCredentialsOptions) func(context.Context) (string, error) {
	return cachedProvider(options.ExpirySkew, func(ctx context.Context) (string, time.Time, error) {
		form := grantForm(map[string]string{"grant_type": "client_credentials"}, options.Scopes, options.Audience, options.Resource)
		return postGrant(ctx, options.HTTPClient, tokenEndpoint, form, clientID, clientSecret, options.ClientAuth, "client-credentials grant")
	})
}
`
    : ""
}${
  grants.tokenExchange
    ? `
// tokenTypeURN is the RFC 8693 token-type table, the same one the runtime sends.
var tokenTypeURN = map[string]string{
${Object.entries(TOKEN_TYPE_URN)
  .map(([name, urn]) => `\t${g(name)}: ${g(urn)},`)
  .join("\n")}
}

// TokenExchangeOptions configures an RFC 8693 token exchange.
type TokenExchangeOptions struct {
	// ClientAuth is how the client authenticates to the token endpoint;
	// "client_secret_basic" when empty, the runtime's default.
	ClientAuth string
	// SubjectTokenType is the type of the subject token being exchanged;
	// "access_token" when empty.
	SubjectTokenType string
	// RequestedTokenType is the type of token asked for; "access_token" when empty.
	RequestedTokenType string
	Scopes             []string
	Audience           string
	Resource           string
	// HTTPClient carries the grant; http.DefaultClient when nil.
	HTTPClient *http.Client
	// ExpirySkew is subtracted from a token's reported lifetime; 30s when zero.
	ExpirySkew time.Duration
	// MaxCacheEntries bounds the distinct subjects kept in memory; 256 when zero.
	MaxCacheEntries int
}

// TokenExchanger is a token exchange (RFC 8693) shared across subjects: one
// instance, one cache, a TokenProvider per inbound caller. The subject token
// is exchanged, never sent upstream as-is, and never logged.
type TokenExchanger struct {
	tokenEndpoint string
	clientID      string
	clientSecret  string
	options       TokenExchangeOptions
	mu            sync.Mutex
	providers     map[string]func(context.Context) (string, error)
	order         []string
}

// NewTokenExchanger builds a token exchanger against tokenEndpoint.
func NewTokenExchanger(tokenEndpoint, clientID, clientSecret string, options TokenExchangeOptions) *TokenExchanger {
	return &TokenExchanger{
		tokenEndpoint: tokenEndpoint,
		clientID:      clientID,
		clientSecret:  clientSecret,
		options:       options,
		providers:     map[string]func(context.Context) (string, error){},
	}
}

// TokenProvider is the provider for one inbound caller; pass it to
// WithTokenProvider. Each subject's exchanged token is cached until shortly
// before it expires; distinct subjects (and distinct actors for one subject)
// never share a token. actorToken may be empty.
func (x *TokenExchanger) TokenProvider(subjectToken, actorToken string) func(context.Context) (string, error) {
	key := subjectToken + "\\x00" + actorToken
	x.mu.Lock()
	defer x.mu.Unlock()
	if existing, ok := x.providers[key]; ok {
		return existing
	}
	subjectType := tokenTypeURN[x.options.SubjectTokenType]
	if subjectType == "" {
		subjectType = tokenTypeURN["access_token"]
	}
	requestedType := tokenTypeURN[x.options.RequestedTokenType]
	if requestedType == "" {
		requestedType = tokenTypeURN["access_token"]
	}
	fields := map[string]string{
		"grant_type":           ${g(GRANT_TOKEN_EXCHANGE)},
		"subject_token":        subjectToken,
		"subject_token_type":   subjectType,
		"requested_token_type": requestedType,
	}
	if actorToken != "" {
		fields["actor_token"] = actorToken
		fields["actor_token_type"] = tokenTypeURN["jwt"]
	}
	provider := cachedProvider(x.options.ExpirySkew, func(ctx context.Context) (string, time.Time, error) {
		form := grantForm(fields, x.options.Scopes, x.options.Audience, x.options.Resource)
		return postGrant(ctx, x.options.HTTPClient, x.tokenEndpoint, form, x.clientID, x.clientSecret, x.options.ClientAuth, "token exchange")
	})
	maxEntries := x.options.MaxCacheEntries
	if maxEntries <= 0 {
		maxEntries = 256
	}
	if len(x.order) >= maxEntries {
		delete(x.providers, x.order[0])
		x.order = x.order[1:]
	}
	x.providers[key] = provider
	x.order = append(x.order, key)
	return provider
}
`
    : ""
}`;
}
