import type { SdkPlan } from "./plan.js";

/**
 * The Python SDK's decision core — the modules that are byte-identical for
 * every service Anvil compiles.
 *
 * They live apart from the per-service projection on purpose: the code that
 * decides whether a call is allowed to happen is one reviewed implementation,
 * and generation only ever adds rows to the table it reads.
 */

const p = (value: unknown): string => JSON.stringify(value);

export function errorsModule(plan: SdkPlan): string {
  return `"""Generated by Anvil. Do not edit — regenerate from AIR.

The Anvil error taxonomy (spec section 10). Anvil never leaks raw upstream
chaos as the primary interface: every failure arrives as 'AnvilError' with a
code from this list and the next action attached.
"""

from typing import Any, Dict, List, Optional

ERROR_CODES = (
${plan.errorCodes.map((code) => `    ${p(code)},`).join("\n")}
)


class AnvilError(Exception):
    """A structured refusal. 'code' is always one of 'ERROR_CODES'."""

    def __init__(
        self,
        code: str,
        message: str,
        operation: str,
        trace_id: str = "",
        retryable: bool = False,
        safe_to_retry: bool = False,
        upstream: Optional[Dict[str, Any]] = None,
        required_arguments: Optional[List[str]] = None,
        details: Any = None,
        retry_after_ms: Optional[int] = None,
    ) -> None:
        super().__init__(message)
        self.code = code
        self.message = message
        self.operation = operation
        self.trace_id = trace_id
        self.retryable = retryable
        self.safe_to_retry = safe_to_retry
        self.upstream = upstream
        #: What the caller must supply, for confirmation_required / idempotency_required.
        self.required_arguments = required_arguments or []
        self.details = details
        #: The upstream's own backpressure instruction, when it gave one.
        self.retry_after_ms = retry_after_ms

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return "AnvilError(code=%r, operation=%r, message=%r)" % (
            self.code,
            self.operation,
            self.message,
        )


def http_status_to_error_code(status: int) -> str:
    """Map an upstream HTTP status onto the Anvil error taxonomy."""
    if status in (400, 422):
        return "validation_error"
    if status == 401:
        return "auth_required"
    if status == 403:
        return "permission_denied"
    if status in (404, 410):
        return "not_found"
    if status == 408:
        return "upstream_timeout"
    if status == 409:
        return "conflict"
    if status == 429:
        return "rate_limited"
    if status in (502, 503):
        return "upstream_unavailable"
    if status == 504:
        return "upstream_timeout"
    if status >= 500:
        return "unknown_upstream_error"
    if status >= 400:
        return "validation_error"
    return "unknown_upstream_error"


def is_retryable_code(code: str) -> bool:
    """Whether a code is inherently retryable, before the idempotency gate."""
    return code in ("rate_limited", "upstream_timeout", "upstream_unavailable")
`;
}

export function safetyModule(): string {
  return `"""Generated by Anvil. Do not edit — regenerate from AIR.

The safety hot path, mirrored from '@anvil/runtime'. Identical decisions in
every language Anvil emits: the same retry gate, the same Retry-After
arithmetic, the same idempotency key derivation.
"""

import calendar
import hashlib
import json
import random as _random
import re
from typing import Any, Optional, Tuple

#: The runtime-wide ceiling on a single pre-attempt sleep.
MAX_RETRY_DELAY_MS = 20000
MAX_IDEMPOTENCY_KEY_BYTES = 255

_MONTHS = (
    "jan", "feb", "mar", "apr", "may", "jun",
    "jul", "aug", "sep", "oct", "nov", "dec",
)
_IMF_FIXDATE = re.compile(
    r"^[A-Za-z]{3}, ([0-9]{2}) ([A-Za-z]{3}) ([0-9]{4}) "
    r"([0-9]{2}):([0-9]{2}):([0-9]{2}) GMT$"
)
_VISIBLE_ASCII = re.compile(r"^[\\x21-\\x7e]+$")


def retry_is_safe(spec: Any, has_idempotency_key: bool) -> bool:
    """Whether automatic retry is safe for this operation.

    The guard behind the whole trust wedge: a mutation that is not provably
    idempotent is never retried, no matter what the policy says.
    """
    if spec.retry["mode"] != "safe":
        return False
    if spec.effect == "read":
        return True
    mode = spec.idempotency["mode"]
    if mode in ("natural", "client_id"):
        return True
    if mode in ("required", "key_supported"):
        return has_idempotency_key
    return False


def compute_backoff_ms(attempt: int, retry: Any, rng: Any = None) -> int:
    """Bounded exponential backoff with full jitter. 'attempt' is 1-based."""
    backoff = retry["backoff"]
    base = retry["baseDelayMs"]
    ceiling = retry["maxDelayMs"]
    if backoff == "none":
        return 0
    if backoff == "fixed":
        return min(base, ceiling)
    exp = min(ceiling, base * (2 ** (attempt - 1)))
    if backoff == "exponential":
        return int(exp)
    draw = (rng or _random.random)()
    return int(draw * exp)


def parse_retry_after(value: str, now_ms: int) -> Optional[int]:
    """The upstream's own answer to "when should I come back?" in milliseconds.

    Both wire forms are accepted: delta-seconds and an HTTP-date. Returns None
    when the value is not a valid Retry-After at all, or names an instant
    already past — in both cases we have learned nothing.
    """
    raw = value.strip()
    if not raw:
        return None
    if raw.isdigit():
        # Saturate rather than discard: an absurd delta is still an instruction
        # to stay away, and dropping it would let us hammer a service that just
        # asked us to stop.
        return int(raw) * 1000
    match = _IMF_FIXDATE.match(raw)
    if not match:
        return None
    day = int(match.group(1))
    try:
        month = _MONTHS.index(match.group(2).lower()) + 1
    except ValueError:
        return None
    year = int(match.group(3))
    hour, minute, second = int(match.group(4)), int(match.group(5)), int(match.group(6))
    if day < 1 or day > 31 or hour > 23 or minute > 59 or second > 59:
        return None
    try:
        at_ms = calendar.timegm((year, month, day, hour, minute, second, 0, 0, 0)) * 1000
    except (ValueError, OverflowError):
        return None
    delta = at_ms - now_ms
    return None if delta < 0 else int(delta)


def resolve_retry_delay(
    attempt: int, retry: Any, retry_after_ms: Optional[int], rng: Any = None
) -> Tuple[str, int]:
    """Resolve the pre-attempt delay, honoring upstream backpressure.

    Returns '("wait", delay_ms)' or '("stop", retry_after_ms)'.

    An upstream asking for LONGER than the ceiling ends the attempt budget
    rather than clamping the sleep — clamping would mean knocking again early,
    which is how a rate limit becomes a ban. An upstream asking for LESS keeps
    our backoff: Retry-After is a floor on staying away, not permission to come
    back sooner and collapse jitter into a tight loop.
    """
    if retry_after_ms is not None and retry_after_ms > MAX_RETRY_DELAY_MS:
        return ("stop", retry_after_ms)
    backoff_ms = compute_backoff_ms(attempt, retry, rng)
    if retry_after_ms is None or retry_after_ms <= backoff_ms:
        return ("wait", backoff_ms)
    return ("wait", retry_after_ms)


def canonical_json(value: Any) -> str:
    """Deterministic canonical JSON: keys sorted, so equal inputs hash equal."""
    return json.dumps(value, sort_keys=True, separators=(",", ":"))


def idempotency_key_is_transport_safe(value: str) -> bool:
    """Portable caller-key contract: visible ASCII, at most 255 bytes."""
    return bool(value) and len(value.encode("utf-8")) <= MAX_IDEMPOTENCY_KEY_BYTES and bool(
        _VISIBLE_ASCII.match(value)
    )


def request_fingerprint(operation_id: str, payload: Any) -> str:
    """A stable fingerprint: sha256 over the operation id and canonical input."""
    digest = hashlib.sha256()
    digest.update(operation_id.encode("utf-8"))
    digest.update(b"\\x00")
    digest.update(canonical_json(payload).encode("utf-8"))
    return digest.hexdigest()


def resolve_idempotency_key(spec: Any, provided: Optional[str], payload: Any) -> Optional[str]:
    """Caller-supplied key, else fingerprint derivation, else none.

    Returns None when no key can be produced; the caller decides whether that
    is a refusal.
    """
    if provided:
        if not idempotency_key_is_transport_safe(provided):
            raise ValueError(
                "An idempotency key must be 1 to 255 bytes of visible ASCII "
                "with no spaces or control characters."
            )
        return provided
    if spec.idempotency["keyDerivation"] == "request_fingerprint":
        return "anvil-" + request_fingerprint(spec.id, payload)[:32]
    return None
`;
}

export function specModule(): string {
  return `"""Generated by Anvil. Do not edit — regenerate from AIR.

The shape of one compiled operation. Generation only ever adds rows to this
table; the code that reads it is the same reviewed implementation everywhere.
"""

from typing import Any, Dict, List, Optional


class OperationSpec(object):
    """One approved operation, as data."""

    __slots__ = (
        "id",
        "http_method",
        "wire_protocol",
        "soap",
        "graphql",
        "path",
        "effect",
        "params",
        "body",
        "idempotency",
        "retry",
        "confirmation",
    )

    def __init__(
        self,
        id: str,
        http_method: str,
        wire_protocol: str,
        soap: Optional[Dict[str, str]],
        graphql: Optional[Dict[str, str]],
        path: str,
        effect: str,
        params: List[Dict[str, Any]],
        body: Optional[Dict[str, Any]],
        idempotency: Dict[str, Any],
        retry: Dict[str, Any],
        confirmation: Dict[str, Any],
    ) -> None:
        self.id = id
        self.http_method = http_method
        #: What a real call must speak. Anything but "http_json" means the path
        #: below is a coordinate Anvil synthesized, not a wire address.
        self.wire_protocol = wire_protocol
        #: For a SOAP operation: what the envelope must carry, read from the
        #: WSDL by the compiler. Never inferred here.
        self.soap = soap
        #: For a GraphQL operation: the document compiled from the SDL. Posted
        #: as handed, so no caller value is ever interpolated into a query.
        self.graphql = graphql
        #: Path template with {wire_name} placeholders.
        self.path = path
        self.effect = effect
        self.params = params
        self.body = body
        self.idempotency = idempotency
        self.retry = retry
        self.confirmation = confirmation
`;
}

export function invokeModule(): string {
  return `"""Generated by Anvil. Do not edit — regenerate from AIR.

The one call path. Every generated method funnels through 'invoke', so the
gates below cannot be bypassed by a method that forgot to check.
"""

import json
import time
import urllib.error
import urllib.parse
import urllib.request
import uuid
from typing import Any, Dict, Optional

from ._safety import (
    parse_retry_after,
    resolve_idempotency_key,
    resolve_retry_delay,
    retry_is_safe,
)
from .errors import AnvilError, http_status_to_error_code, is_retryable_code
from .spec import OperationSpec

#: Headers the transport owns; a caller override would break the contract.
RESERVED_HEADERS = frozenset(
    ("authorization", "content-length", "content-type", "host", "transfer-encoding")
)


def _trace_id() -> str:
    return str(uuid.uuid4())


def assert_wire_executable(spec: OperationSpec, protocol_facade: Optional[str]) -> None:
    """The transport gate. The confirmation gate asks whether the caller intends
    the effect; this asks whether this client can express the call at all. A
    SOAP, GraphQL, or gRPC operation arrives with a path Anvil invented, and
    sending JSON to it would be a well-formed lie. Mirrors the runtime's own
    gate so every surface refuses alike."""
    # A subscription is a bounded event-stream window with an array answer.
    # This client is request/response, and a protocol facade declares
    # coordinates, not framing -- so the refusal holds with a facade declared.
    if spec.wire_protocol == "graphql_sse":
        raise AnvilError(
            code="unsupported_operation",
            operation=spec.id,
            trace_id=_trace_id(),
            message="%s is a GraphQL subscription, observed through a bounded "
            "Server-Sent Events window. This client is request/response and cannot "
            "hold that window open, and a protocol facade cannot change the framing "
            "of an event stream. Call it through the generated MCP server or CLI, "
            "which share the runtime that reads this wire." % spec.id,
        )
    if spec.wire_protocol == "http_json" or protocol_facade is not None:
        return
    # SOAP is speakable exactly when the compiler recovered a binding for it.
    if spec.wire_protocol == "soap" and spec.soap:
        return
    if spec.wire_protocol == "graphql" and spec.graphql:
        return
    raise AnvilError(
        code="unsupported_operation",
        operation=spec.id,
        trace_id=_trace_id(),
        message="%s speaks %s, which this client cannot put on the wire: %s %s is a "
        "coordinate Anvil synthesized, not an address the service serves. Point "
        "base_url at a facade that really does serve it over HTTP+JSON and pass "
        "protocol_facade with the reason, so the assumption is recorded."
        % (spec.id, spec.wire_protocol, spec.http_method, spec.path),
    )


def assert_confirmed(spec: OperationSpec, confirm: bool) -> None:
    """The confirmation gate. Refuses before anything reaches the wire."""
    if not spec.confirmation["required"] or confirm is True:
        return
    audience = (
        "This effect needs explicit human approval, not a self-confirmation."
        if spec.confirmation.get("humanApproval")
        else "Pass confirm=True once you intend the effect."
    )
    reason = spec.confirmation.get("reason")
    raise AnvilError(
        code="confirmation_required",
        operation=spec.id,
        trace_id=_trace_id(),
        message="%s requires confirmation%s. %s"
        % (spec.id, (": " + reason) if reason else "", audience),
        required_arguments=["confirm"],
    )


def assert_keyed(spec: OperationSpec, key: Optional[str]) -> None:
    """The idempotency gate. A contract that demands a key gets one or a refusal."""
    if not spec.idempotency["callerKeyRequired"] or key is not None:
        return
    raise AnvilError(
        code="idempotency_required",
        operation=spec.id,
        trace_id=_trace_id(),
        message=(
            "%s requires an idempotency key that Anvil cannot derive for you. "
            "Pass idempotency_key — reuse the same value to retry the same intent."
        )
        % spec.id,
        required_arguments=["idempotency_key"],
    )


def _set_body_carrier(body: Any, path: Any, value: str) -> Any:
    root = dict(body) if isinstance(body, dict) else {}
    cursor = root
    for segment in path[:-1]:
        child = cursor.get(segment)
        child = dict(child) if isinstance(child, dict) else {}
        cursor[segment] = child
        cursor = child
    cursor[path[-1]] = value
    return root


def build_request(
    spec: OperationSpec,
    payload: Dict[str, Any],
    base_url: str,
    auth: Optional[Dict[str, Any]],
    token: Optional[str],
    idempotency_key: Optional[str],
    extra_headers: Dict[str, str],
    user_agent: str,
) -> Dict[str, Any]:
    """Build the upstream request from the operation spec and caller input."""
    path = spec.path
    query = []
    headers = {"accept": "application/json", "user-agent": user_agent}
    for name, value in extra_headers.items():
        if name.lower() not in RESERVED_HEADERS:
            headers[name.lower()] = value
    body: Dict[str, Any] = {}
    has_body = False
    cookie = ""

    for param in spec.params:
        value = payload.get(param["key"])
        if value is None:
            continue
        where = param["in"]
        if where == "path":
            path = path.replace(
                "{" + param["wireName"] + "}", urllib.parse.quote(str(value), safe="")
            )
        elif where == "query":
            query.append((param["wireName"], str(value)))
        elif where == "header":
            headers[param["wireName"]] = str(value)
        elif where == "cookie":
            cookie = (cookie + "; " if cookie else "") + param["wireName"] + "=" + str(value)
        elif where == "body":
            body[param["wireName"]] = value
            has_body = True

    body_value: Any = body if has_body else None
    if spec.body is not None:
        if spec.body["projection"] == "fields":
            for field in spec.body["fields"]:
                value = payload.get(field["key"])
                if value is None:
                    continue
                body[field["wireName"]] = value
                has_body = True
            if has_body:
                body_value = body
        elif payload.get("body") is not None:
            body_value = payload["body"]
            has_body = True

    carrier = spec.idempotency.get("carrier")
    if carrier and idempotency_key:
        mechanism = carrier["mechanism"]
        if mechanism == "header":
            # HTTP field names are case-insensitive; drop any modeled spelling
            # before injecting the one authoritative safety value.
            for name in [n for n in headers if n.lower() == carrier["key"].lower()]:
                del headers[name]
            headers[carrier["key"]] = idempotency_key
        elif mechanism == "query":
            query = [(k, v) for (k, v) in query if k != carrier["key"]]
            query.append((carrier["key"], idempotency_key))
        elif mechanism == "path":
            path = path.replace(
                "{" + carrier["key"] + "}", urllib.parse.quote(idempotency_key, safe="")
            )
        elif mechanism == "body":
            body_value = _set_body_carrier(
                body_value, carrier.get("path") or [carrier["key"]], idempotency_key
            )
            has_body = True

    if token and auth:
        if auth["in"] == "header":
            scheme = auth.get("scheme")
            headers[auth["name"].lower()] = (scheme + " " + token) if scheme else token
        else:
            query.append((auth["name"], token))
    if cookie:
        headers["cookie"] = cookie

    # A SOAP service serves one endpoint. The path is a coordinate Anvil
    # synthesized to hold operations apart in a path-keyed model, so it is
    # deliberately dropped: the address is the base URL, from soap:address.
    if spec.wire_protocol == "soap" and spec.soap:
        headers.update(soap_headers(spec.soap))
        headers["accept"] = spec.soap["contentType"].split(";")[0]
        return {
            "url": base_url.rstrip("/") or "/",
            "method": "POST",
            "headers": headers,
            "body": build_envelope(spec.soap, body_value).encode("utf-8"),
        }

    # A GraphQL service serves one endpoint; the field name travels in the
    # document, never in the URL.
    if spec.wire_protocol == "graphql" and spec.graphql:
        headers["content-type"] = "application/json"
        headers["accept"] = "application/json"
        payload = {
            "query": spec.graphql["document"],
            "operationName": spec.graphql["operationName"],
            "variables": body_value if isinstance(body_value, dict) else {},
        }
        return {
            "url": base_url.rstrip("/") or "/",
            "method": "POST",
            "headers": headers,
            "body": json.dumps(payload, separators=(",", ":")).encode("utf-8"),
        }

    url = base_url.rstrip("/") + path
    if query:
        url = url + "?" + urllib.parse.urlencode(query)
    request: Dict[str, Any] = {"url": url, "method": spec.http_method, "headers": headers}
    if has_body:
        content_type = (spec.body or {}).get("contentType") or "application/json"
        headers["content-type"] = content_type
        # Compact separators so the body bytes match what the other generated
        # SDKs send for the same input — one contract, one request.
        request["body"] = json.dumps(body_value, separators=(",", ":")).encode("utf-8")
    return request


def _decode(raw: bytes) -> Any:
    if not raw:
        return None
    text = raw.decode("utf-8", "replace")
    try:
        return json.loads(text)
    except ValueError:
        return text


def invoke(
    spec: OperationSpec,
    payload: Dict[str, Any],
    *,
    base_url: str,
    protocol_facade: Optional[str] = None,
    auth: Optional[Dict[str, Any]],
    token: Optional[str],
    token_provider: Any = None,
    user_agent: str,
    timeout: float,
    confirm: bool = False,
    idempotency_key: Optional[str] = None,
    headers: Optional[Dict[str, str]] = None,
    opener: Any = None,
    sleep: Any = None,
    rng: Any = None,
) -> Any:
    """Run one operation end to end: gate, build, send, and retry only where
    the contract proves retrying is safe.

    'token_provider', when given, is called with no arguments once per call
    and takes priority over a static 'token' — the delegated-token source for
    'oauth2_authorization_code'. Never cached here; a provider that wants
    caching does its own.
    """
    assert_wire_executable(spec, protocol_facade)
    assert_confirmed(spec, confirm)
    if token_provider is not None:
        token = token_provider()
    payload = {key: value for key, value in payload.items() if value is not None}
    resolved_key = resolve_idempotency_key(spec, idempotency_key, payload)
    assert_keyed(spec, resolved_key)

    safe_to_retry = retry_is_safe(spec, resolved_key is not None)
    max_attempts = spec.retry["maxAttempts"] if safe_to_retry else 1
    request = build_request(
        spec, payload, base_url, auth, token, resolved_key, headers or {}, user_agent
    )
    trace = _trace_id()
    sleep = sleep or time.sleep
    send = opener or urllib.request.urlopen

    attempt = 1
    while True:
        status = None
        response_headers: Dict[str, str] = {}
        raw = b""
        transport_message = None
        http_request = urllib.request.Request(
            request["url"], data=request.get("body"), method=request["method"]
        )
        for name, value in request["headers"].items():
            http_request.add_header(name, value)
        try:
            with send(http_request, timeout=timeout) as response:
                status = getattr(response, "status", None) or response.getcode()
                response_headers = {k.lower(): v for k, v in dict(response.headers).items()}
                raw = response.read()
        except urllib.error.HTTPError as error:
            status = error.code
            response_headers = {k.lower(): v for k, v in dict(error.headers or {}).items()}
            raw = error.read() or b""
        except Exception:
            # Never surface the transport's own message: it can carry the URL,
            # and the URL can carry a query-carried credential.
            transport_message = "the request could not reach the upstream"

        if transport_message is not None:
            error = AnvilError(
                code="upstream_unavailable",
                operation=spec.id,
                trace_id=trace,
                message="%s failed: %s." % (spec.id, transport_message),
                retryable=bool(spec.retry["retryTransport"]),
                safe_to_retry=safe_to_retry,
            )
            if not safe_to_retry or not spec.retry["retryTransport"] or attempt >= max_attempts:
                raise error
            action, delay_ms = resolve_retry_delay(attempt, spec.retry, None, rng)
            if action == "stop":
                raise error
            sleep(delay_ms / 1000.0)
            attempt += 1
            continue

        # A soap:Fault is a failure the transport delivered successfully, and
        # servers send it with 200 as readily as 500 — so the status is not the
        # answer here, the envelope is. Read before the status branch, or a
        # faulted 200 would be returned to the caller as a result.
        if spec.wire_protocol == "soap" and spec.soap:
            soap_text = raw.decode("utf-8", "replace") if raw else ""
            fault = soap_fault(soap_text)
            if fault is not None:
                # Only a Server fault is transient. A Client fault will fail
                # identically on retry, and retrying a mutation on one is
                # exactly what the safety contract forbids.
                if fault["retryable"] and safe_to_retry and attempt < max_attempts:
                    action, delay_ms = resolve_retry_delay(attempt, spec.retry, None, rng)
                    if action != "stop":
                        sleep(delay_ms / 1000.0)
                        attempt += 1
                        continue
                raise AnvilError(
                    code="unknown_upstream_error",
                    operation=spec.id,
                    trace_id=trace,
                    message="%s failed upstream: %s" % (spec.id, fault["message"]),
                    retryable=bool(fault["retryable"]),
                    safe_to_retry=safe_to_retry,
                )
            if status is not None and 200 <= status < 300:
                return decode_envelope(spec.soap, soap_text)

        # GraphQL reports failures inside a 200 with an errors array — the same
        # danger as a SOAP fault. A partial response counts as a failure.
        if spec.wire_protocol == "graphql" and spec.graphql:
            try:
                envelope = json.loads(raw.decode("utf-8", "replace")) if raw else {}
            except Exception:
                envelope = {}
            gql_errors = envelope.get("errors") if isinstance(envelope, dict) else None
            if isinstance(gql_errors, list) and gql_errors:
                first = gql_errors[0] if isinstance(gql_errors[0], dict) else {}
                raise AnvilError(
                    code="unknown_upstream_error",
                    operation=spec.id,
                    trace_id=trace,
                    message="%s failed upstream: %s"
                    % (spec.id, first.get("message") or "the service returned a GraphQL error"),
                    retryable=False,
                    safe_to_retry=safe_to_retry,
                )
            if status is not None and 200 <= status < 300:
                data = envelope.get("data") if isinstance(envelope, dict) else None
                root = spec.graphql.get("rootField") or ""
                if isinstance(data, dict) and root in data:
                    return data[root]
                return data

        if status is not None and 200 <= status < 300:
            return _decode(raw)

        code = http_status_to_error_code(int(status or 0))
        retry_after_raw = response_headers.get("retry-after")
        retry_after_ms = (
            parse_retry_after(retry_after_raw, int(time.time() * 1000))
            if retry_after_raw
            else None
        )
        failure = AnvilError(
            code=code,
            operation=spec.id,
            trace_id=trace,
            message="%s failed upstream with HTTP %s." % (spec.id, status),
            retryable=is_retryable_code(code),
            safe_to_retry=safe_to_retry,
            upstream={"status": status, "request_id": response_headers.get("x-request-id")},
            retry_after_ms=retry_after_ms,
        )
        if status not in spec.retry["retryStatuses"] or attempt >= max_attempts:
            raise failure
        if not safe_to_retry:
            # A transient failure we are not allowed to repeat. Say exactly
            # that, rather than retrying a write whose duplicate we cannot rule
            # out.
            raise AnvilError(
                code="unsafe_retry_blocked",
                operation=spec.id,
                trace_id=trace,
                message=(
                    "%s failed transiently (HTTP %s) but is not provably idempotent, "
                    "so it was not retried. Retry deliberately with an idempotency key "
                    "if the effect is safe to repeat."
                )
                % (spec.id, status),
                upstream={"status": status},
                retry_after_ms=retry_after_ms,
            )
        action, delay_ms = resolve_retry_delay(attempt, spec.retry, retry_after_ms, rng)
        if action == "stop":
            raise AnvilError(
                code=code,
                operation=spec.id,
                trace_id=trace,
                message=(
                    "%s asked to be retried in %sms, longer than this client will wait "
                    "inside one call. Retry deliberately after that delay."
                )
                % (spec.id, delay_ms),
                retryable=True,
                safe_to_retry=safe_to_retry,
                retry_after_ms=delay_ms,
            )
        sleep(delay_ms / 1000.0)
        attempt += 1
`;
}

/**
 * `_mtls.py` — a urllib opener that presents a client certificate, emitted
 * only for a service whose auth scheme is `mtls`.
 *
 * `invoke()` already accepts an injectable `opener` (for tests), so mTLS
 * needs nothing new in the call path — only something that builds the right
 * opener. `ssl.SSLContext.load_cert_chain` accepts file paths only, so a raw
 * PEM value read from the environment is written to a private (0600) temp
 * file once; a value that already names a file is used as-is.
 */
export function mtlsModule(): string {
  return `"""Generated by Anvil. Do not edit — regenerate from AIR.

Mutual-TLS transport: an SSL context presenting this service's client
certificate, and a urllib opener built from it. The credential material is
never logged, echoed, or included in an error.
"""

import atexit
import os
import ssl
import tempfile
import urllib.request
from typing import Optional


def _is_pem_text(value: str) -> bool:
    return value.lstrip().startswith("-----BEGIN")


def _materialize(value: str) -> str:
    """Return a file path holding 'value'.

    A value that already names a readable file is used as-is. Literal PEM
    text is written once to a private temp file (mode 0600) and removed when
    the process exits, since 'ssl.SSLContext.load_cert_chain' takes only file
    paths, never PEM bytes directly.
    """
    if not _is_pem_text(value) and os.path.isfile(value):
        return value
    fd, path = tempfile.mkstemp(prefix="anvil-sdk-tls-")
    try:
        os.chmod(path, 0o600)
        with os.fdopen(fd, "w") as handle:
            handle.write(value)
    except BaseException:
        os.close(fd)
        raise
    atexit.register(lambda: os.path.exists(path) and os.remove(path))
    return path


def build_mtls_opener(cert: str, key: str, ca: Optional[str] = None):
    """Build a urllib opener callable — 'invoke()' calls it exactly like
    'urllib.request.urlopen(request, timeout=...)' — that presents
    'cert'/'key' on every HTTPS connection. When 'ca' is given, it — and only
    it — is trusted, mirroring how the TypeScript and Go SDKs treat an
    explicit CA. Otherwise the platform's default trust store is used."""
    context = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
    context.load_cert_chain(certfile=_materialize(cert), keyfile=_materialize(key))
    if ca:
        if not _is_pem_text(ca) and os.path.isfile(ca):
            context.load_verify_locations(cafile=ca)
        else:
            context.load_verify_locations(cadata=ca)
    else:
        context.load_default_certs()
    opener = urllib.request.build_opener(urllib.request.HTTPSHandler(context=context))
    return opener.open
`;
}

/**
 * `_oauth.py` — an optional refresh helper for `oauth2_authorization_code`,
 * emitted only when the contract names a token endpoint. Never performs the
 * interactive authorization step; only exchanges an already-obtained refresh
 * token for a fresh access token (RFC 6749 §6).
 */
export function oauthModule(): string {
  return `"""Generated by Anvil. Do not edit — regenerate from AIR.

Optional refresh helper for the authorization-code grant (RFC 6749 section 6).
Never performs the interactive authorization step, and never logs the refresh
token, client secret, or minted access token.
"""

import base64
import json
import time
import urllib.error
import urllib.parse
import urllib.request
from typing import Any, Callable, Dict, Optional


def create_refreshing_token_provider(
    token_endpoint: str,
    refresh_token: str,
    client_id: str,
    client_secret: Optional[str] = None,
    expiry_skew_seconds: float = 30.0,
    opener: Any = None,
    client_auth: str = "client_secret_basic",
) -> Callable[[], str]:
    """Build a token provider that exchanges 'refresh_token' at
    'token_endpoint' and caches the access token in memory until shortly
    before it expires.

    'client_auth' is how the client authenticates to the token endpoint
    (RFC 6749 section 2.3.1), defaulting to 'client_secret_basic' exactly as
    the runtime resolver does for the same contract. It is LAST in the
    signature on purpose: callers of an earlier generation may pass
    'expiry_skew_seconds' and 'opener' positionally, and inserting a parameter
    before them would silently rebind those arguments on regeneration."""
    if client_auth == "private_key_jwt":
        # Nothing here mints an RFC 7523 assertion, so a private-key client is
        # refused rather than sent a client_secret it does not have.
        raise RuntimeError(
            "private_key_jwt client authentication is not supported by the refresh helper"
        )
    send = opener or urllib.request.urlopen
    cache: Dict[str, Any] = {}

    def provider() -> str:
        cached_token = cache.get("token")
        expires_at = cache.get("expires_at", 0.0)
        if cached_token and expires_at > time.time():
            return cached_token
        form: Dict[str, str] = {"grant_type": "refresh_token", "refresh_token": refresh_token}
        headers = {"content-type": "application/x-www-form-urlencoded"}
        # Mirrors the runtime resolver exactly: client_secret_basic sends the
        # credentials as HTTP Basic and keeps client_id out of the form; every
        # other declared method carries client_id (and the secret, when
        # present) in the form body.
        if client_secret and client_auth == "client_secret_basic":
            basic = base64.b64encode(("%s:%s" % (client_id, client_secret)).encode("utf-8"))
            headers["authorization"] = "Basic " + basic.decode("ascii")
        else:
            form["client_id"] = client_id
            if client_secret:
                form["client_secret"] = client_secret
        body = urllib.parse.urlencode(form).encode("utf-8")
        request = urllib.request.Request(token_endpoint, data=body, headers=headers, method="POST")
        try:
            with send(request, timeout=30.0) as response:
                raw = response.read()
        except urllib.error.HTTPError as error:
            # Never surface the response body: a token endpoint's error
            # payload can echo back the refresh token or client secret.
            raise RuntimeError(
                "token refresh failed with HTTP %s from %s" % (error.code, token_endpoint)
            ) from None
        payload = json.loads(raw.decode("utf-8"))
        access_token = payload.get("access_token")
        if not access_token:
            raise RuntimeError("token endpoint response carried no access_token")
        cache["token"] = access_token
        cache["expires_at"] = time.time() + float(payload.get("expires_in", 300)) - expiry_skew_seconds
        return access_token

    return provider
`;
}
