import type { SdkOperation, SdkPlan } from "./plan.js";
import { errorsModule, invokeModule, safetyModule, specModule } from "./python-core.js";
import { safetyNotes, wrap } from "./shared.js";

/**
 * The Python SDK — a zero-dependency package over `urllib.request`.
 *
 * Same split as every other language Anvil emits: `_safety.py` and `_invoke.py`
 * are the reviewed decision core, identical for every service, and generation
 * only adds rows to the operation table they read.
 */
export function generatePythonSdk(plan: SdkPlan): Record<string, string> {
  const pkg = pythonPackage(plan);
  const root = "sdk/python";
  return {
    [`${root}/pyproject.toml`]: pyproject(plan, pkg),
    [`${root}/README.md`]: readme(plan, pkg),
    [`${root}/${pkg}/__init__.py`]: initModule(plan, pkg),
    [`${root}/${pkg}/errors.py`]: errorsModule(plan),
    [`${root}/${pkg}/_safety.py`]: safetyModule(),
    [`${root}/${pkg}/spec.py`]: specModule(),
    [`${root}/${pkg}/operations.py`]: operationsModule(plan),
    [`${root}/${pkg}/_invoke.py`]: invokeModule(),
    [`${root}/${pkg}/client.py`]: clientModule(plan),
  };
}

/** The importable package name, e.g. `anvil_payments`. */
function pythonPackage(plan: SdkPlan): string {
  return `anvil_${plan.service.names.snake}`;
}

const p = (value: unknown): string => JSON.stringify(value);

function pyLiteral(value: unknown): string {
  if (value === null || value === undefined) return "None";
  if (typeof value === "boolean") return value ? "True" : "False";
  if (typeof value === "number") return String(value);
  if (typeof value === "string") return p(value);
  if (Array.isArray(value)) return `[${value.map(pyLiteral).join(", ")}]`;
  return `{${Object.entries(value as Record<string, unknown>)
    .map(([key, item]) => `${p(key)}: ${pyLiteral(item)}`)
    .join(", ")}}`;
}

function pyType(kind: string): string {
  switch (kind) {
    case "string":
      return "str";
    case "integer":
      return "int";
    case "number":
      return "float";
    case "boolean":
      return "bool";
    case "array":
      return "List[Any]";
    case "object":
      return "Dict[str, Any]";
    default:
      return "Any";
  }
}

function pyproject(plan: SdkPlan, pkg: string): string {
  return `# Generated by Anvil. Do not edit — regenerate from AIR.
[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = ${p(`anvil-sdk-${plan.service.id}`)}
version = ${p(plan.service.version)}
description = ${p(`${plan.service.description} Generated by Anvil from AIR — same operations and safety contract as the CLI and MCP server.`)}
requires-python = ">=3.9"
dependencies = []

[tool.setuptools]
packages = [${p(pkg)}]
`;
}

function readme(plan: SdkPlan, pkg: string): string {
  const first = plan.operations[0];
  const args = first
    ? first.params
        .filter((param) => param.required)
        .map((param) => `${param.key}="…"`)
        .concat(first.confirmation.required ? [`${first.safetyKeys.confirm}=True`] : [])
        .concat(
          first.idempotency.callerKeyRequired
            ? [`${first.safetyKeys.idempotencyKey}="order-1234"`]
            : [],
        )
        .join(", ")
    : "";
  return `# ${plan.service.displayName} — Python SDK

${plan.service.description}

Generated by Anvil from AIR. Zero dependencies — it uses \`urllib\` from the
standard library, so \`sdk/python/\` can be vendored directly.

\`\`\`python
from ${pkg} import ${plan.service.names.pascal}Client

client = ${plan.service.names.pascal}Client()  # reads ${plan.auth.envVar}
${first ? `result = client.${first.names.snake}(${args})` : "# no approved operations yet"}
\`\`\`

Safety is not advisory here: an operation that requires confirmation raises
\`AnvilError(code="confirmation_required")\` before anything reaches the network,
a contract that needs an idempotency key it cannot derive raises
\`idempotency_required\`, and a transient failure on a mutation that cannot prove
idempotence raises \`unsafe_retry_blocked\` rather than being sent twice.

See \`../README.md\` for the full cross-language contract.
`;
}

function operationsModule(plan: SdkPlan): string {
  const rows = plan.operations.map((op) => {
    const params = op.params.map(
      (param) =>
        `{"wireName": ${p(param.wireName)}, "key": ${p(param.key)}, "in": ${p(param.in)}, "required": ${param.required ? "True" : "False"}}`,
    );
    const body = op.body
      ? `{"required": ${op.body.required ? "True" : "False"}, "contentType": ${p(op.body.contentType)}, "projection": ${p(op.body.projection)}, "fields": [${op.body.fields
          .map(
            (field) =>
              `{"wireName": ${p(field.wireName)}, "key": ${p(field.key)}, "required": ${field.required ? "True" : "False"}}`,
          )
          .join(", ")}]}`
      : "None";
    return `    ${p(op.names.snake)}: OperationSpec(
        id=${p(op.id)},
        http_method=${p(op.httpMethod)},
        path=${p(op.path)},
        effect=${p(op.effect)},
        params=[
${params.map((row) => `            ${row},`).join("\n")}
        ],
        body=${body},
        idempotency=${pyLiteral(op.idempotency)},
        retry=${pyLiteral(op.retry)},
        confirmation=${pyLiteral(op.confirmation)},
    ),`;
  });
  return `"""Generated by Anvil. Do not edit — regenerate from AIR.

One row per approved operation. An operation still in review is absent here,
which is why it cannot be called: the SDK has no way to name it.
"""

from typing import Dict

from .spec import OperationSpec

OPERATIONS: Dict[str, OperationSpec] = {
${rows.join("\n")}
}
`;
}

function clientModule(plan: SdkPlan): string {
  const className = `${plan.service.names.pascal}Client`;
  const methods = plan.operations.map((op) => pythonMethod(op)).join("\n\n");
  return `"""Generated by Anvil. Do not edit — regenerate from AIR.

${plan.service.description}
"""

import os
from typing import Any, Dict, Iterator, List, Optional

from ._invoke import invoke
from .errors import AnvilError
from .operations import OPERATIONS

#: The base URL recorded in AIR at compile time.
DEFAULT_BASE_URL = ${p(plan.service.baseUrl)}
#: The environment variable read when no token is passed.
TOKEN_ENV_VAR = ${p(plan.auth.envVar)}
_AUTH_CARRIER: Optional[Dict[str, Any]] = ${plan.auth.carrier ? pyLiteral(plan.auth.carrier) : "None"}
_USER_AGENT = ${p(`anvil-sdk-${plan.service.id}/${plan.service.version} (python)`)}


def _field(value: Any, name: str) -> Any:
    """Read one named field off a decoded response.

    Async contracts name their handle and state fields exactly; this reads that
    name and nothing else, rather than guessing at a shape never promised.
    """
    return value.get(name) if isinstance(value, dict) else None


class ${className}(object):
    """${plan.service.description}

    Every method is one approved operation. The safety gates live in
    '_invoke', so no method can skip them.
    """

    def __init__(
        self,
        base_url: Optional[str] = None,
        token: Optional[str] = None,
        timeout: float = 30.0,
        opener: Any = None,
        sleep: Any = None,
        rng: Any = None,
        user_agent: Optional[str] = None,
    ) -> None:
        self.base_url = base_url or DEFAULT_BASE_URL
        #: The credential this SDK carries on the wire. Never logged or echoed.
        self._token = token if token is not None else os.environ.get(TOKEN_ENV_VAR)
        self.timeout = timeout
        self._opener = opener
        self._sleep = sleep
        self._rng = rng
        self._user_agent = user_agent or _USER_AGENT
        if not self.base_url:
            raise AnvilError(
                code="validation_error",
                operation=${p(plan.service.id)},
                message=(
                    "No base URL: the compiled model records no server, so one must be "
                    "passed as base_url."
                ),
                required_arguments=["base_url"],
            )

    def _call(
        self,
        name: str,
        payload: Dict[str, Any],
        confirm: bool,
        idempotency_key: Optional[str],
        headers: Optional[Dict[str, str]],
        timeout: Optional[float],
    ) -> Any:
        return invoke(
            OPERATIONS[name],
            payload,
            base_url=self.base_url,
            auth=_AUTH_CARRIER,
            token=self._token,
            user_agent=self._user_agent,
            timeout=timeout if timeout is not None else self.timeout,
            confirm=confirm,
            idempotency_key=idempotency_key,
            headers=headers,
            opener=self._opener,
            sleep=self._sleep,
            rng=self._rng,
        )

${methods.length > 0 ? methods : "    pass"}
`;
}

interface PythonArgument {
  name: string;
  annotation: string;
  default?: string;
  doc?: string;
}

function businessArguments(op: SdkOperation): PythonArgument[] {
  const args: PythonArgument[] = [];
  for (const param of op.params) {
    args.push({
      name: param.key,
      annotation: param.required ? pyType(param.type) : `Optional[${pyType(param.type)}]`,
      ...(param.required ? {} : { default: "None" }),
      doc: param.description,
    });
  }
  if (op.body?.projection === "fields") {
    for (const field of op.body.fields) {
      args.push({
        name: field.key,
        annotation: field.required ? pyType(field.type) : `Optional[${pyType(field.type)}]`,
        ...(field.required ? {} : { default: "None" }),
        doc: field.description,
      });
    }
  } else if (op.body) {
    args.push({
      name: "body",
      annotation: op.body.required ? "Any" : "Optional[Any]",
      ...(op.body.required ? {} : { default: "None" }),
      doc: `The request body, sent verbatim (content type ${op.body.contentType}).`,
    });
  }
  // Required first: Python allows any order after `*`, but a signature that
  // reads required-then-optional is the one a caller can skim.
  return [
    ...args.filter((arg) => arg.default === undefined),
    ...args.filter((arg) => arg.default !== undefined),
  ];
}

function pythonMethod(op: SdkOperation): string {
  const args = businessArguments(op);
  const safety = [
    `        ${op.safetyKeys.confirm}: bool = False,`,
    `        ${op.safetyKeys.idempotencyKey}: Optional[str] = None,`,
    "        headers: Optional[Dict[str, str]] = None,",
    "        timeout: Optional[float] = None,",
  ];
  const signature = [
    `    def ${op.names.snake}(`,
    "        self,",
    "        *,",
    ...args.map(
      (arg) => `        ${arg.name}: ${arg.annotation}${arg.default ? ` = ${arg.default}` : ""},`,
    ),
    ...safety,
    "    ) -> Any:",
  ];
  const payload = `{${args.map((arg) => `${p(arg.name)}: ${arg.name}`).join(", ")}}`;
  const call = [
    "        return self._call(",
    `            ${p(op.names.snake)},`,
    `            ${payload},`,
    `            ${op.safetyKeys.confirm},`,
    `            ${op.safetyKeys.idempotencyKey},`,
    "            headers,",
    "            timeout,",
    "        )",
  ];
  const lines = [...signature, docstring(op, args, 8), ...call];

  const page = op.pagination;
  if (page?.cursorKey && page.nextField) {
    lines.push(
      "",
      `    def ${op.names.snake}_paginated(`,
      "        self,",
      "        *,",
      ...args.map(
        (arg) => `        ${arg.name}: ${arg.annotation}${arg.default ? ` = ${arg.default}` : ""},`,
      ),
      ...safety,
      "    ) -> Iterator[Any]:",
      `        """Page through ${op.canonicalName} until the upstream stops handing back a`,
      `        continuation. Yields one ${page.itemsField ? `item from '${page.itemsField}'` : "page"} at a time."""`,
      `        payload = ${payload}`,
      "        seen: List[str] = []",
      `        cursor = payload.get(${p(page.cursorKey)})`,
      "        while True:",
      `            page = self._call(${p(op.names.snake)}, dict(payload, **({} if cursor is None else {${p(page.cursorKey)}: cursor})), ${op.safetyKeys.confirm}, ${op.safetyKeys.idempotencyKey}, headers, timeout)`,
      "            if not isinstance(page, dict):",
      "                return",
      page.itemsField
        ? `            items = page.get(${p(page.itemsField)})\n            if isinstance(items, list):\n                for item in items:\n                    yield item\n            elif items is not None:\n                yield items`
        : "            yield page",
      `            nxt = page.get(${p(page.nextField)})`,
      "            if not isinstance(nxt, str) or not nxt:",
      "                return",
      // A server that echoes its own cursor would spin this loop forever.
      "            if nxt in seen:",
      "                return",
      "            seen.append(nxt)",
      "            cursor = nxt",
    );
  }

  const contract = op.async;
  if (contract?.statusMethodBase && contract.statusJobIdKey && contract.terminalStates.length > 0) {
    lines.push(
      "",
      `    def wait_for_${op.names.snake}(`,
      "        self,",
      "        submit_result: Any,",
      "        *,",
      `        timeout_seconds: float = ${contract.pollIntervalSeconds * 60},`,
      "    ) -> Any:",
      `        """${contract.instruction}`,
      "",
      "        Polls at the interval the contract declares and returns the first status",
      "        response in a terminal state. Every field name below is the one AIR",
      '        resolved — none is guessed."""',
      `        handle = _field(submit_result, ${p(contract.jobIdField)})`,
      "        if not isinstance(handle, str) or not handle:",
      "            raise AnvilError(",
      '                code="schema_mismatch",',
      `                operation=${p(op.id)},`,
      `                message="The submit response carried no ${contract.jobIdField} to poll on.",`,
      "            )",
      "        import time as _time",
      "",
      "        deadline = _time.time() + timeout_seconds",
      `        terminal = ${pyLiteral(contract.terminalStates)}`,
      "        while True:",
      `            status = self.${contract.statusMethodBase}(**{${p(contract.statusJobIdKey)}: handle})`,
      `            state = _field(status, ${p(contract.stateField ?? "state")})`,
      "            if isinstance(state, str) and state in terminal:",
      "                return status",
      "            if _time.time() >= deadline:",
      "                raise AnvilError(",
      '                    code="upstream_timeout",',
      `                    operation=${p(op.id)},`,
      `                    message="${op.canonicalName} did not reach a terminal state before the wait deadline.",`,
      "                    retryable=True,",
      "                )",
      `            (self._sleep or _time.sleep)(${contract.pollIntervalSeconds})`,
    );
  }
  return lines.join("\n");
}

function docstring(op: SdkOperation, args: PythonArgument[], indent: number): string {
  const pad = " ".repeat(indent);
  const lines = [`${pad}"""${op.description}`, ""];
  for (const note of safetyNotes(op)) {
    for (const wrapped of wrap(note, 72)) lines.push(`${pad}${wrapped}`);
  }
  const documented = args.filter((arg) => arg.doc);
  if (documented.length > 0) {
    lines.push("", `${pad}Args:`);
    for (const arg of documented) {
      const wrapped = wrap(`${arg.name}: ${arg.doc}`, 68);
      lines.push(`${pad}    ${wrapped[0]}`);
      for (const rest of wrapped.slice(1)) lines.push(`${pad}        ${rest}`);
    }
  }
  lines.push(
    "",
    `${pad}Raises:`,
    `${pad}    AnvilError: a structured refusal or upstream failure.`,
  );
  lines.push(`${pad}"""`);
  return lines.join("\n");
}

function initModule(plan: SdkPlan, pkg: string): string {
  return `"""${plan.service.displayName} — generated Python SDK.

Generated by Anvil from AIR. The CLI, the MCP server, and this SDK are three
projections of one model: same operations, same wire coordinates, same safety
contract.
"""

from ._safety import MAX_RETRY_DELAY_MS
from .client import DEFAULT_BASE_URL, TOKEN_ENV_VAR, ${plan.service.names.pascal}Client
from .errors import ERROR_CODES, AnvilError
from .operations import OPERATIONS
from .spec import OperationSpec

__all__ = [
    "AnvilError",
    "ERROR_CODES",
    "MAX_RETRY_DELAY_MS",
    "OPERATIONS",
    "OperationSpec",
    "DEFAULT_BASE_URL",
    "TOKEN_ENV_VAR",
    ${p(`${plan.service.names.pascal}Client`)},
]
__version__ = ${p(plan.service.version)}
# Package: ${pkg}
`;
}
