import type { SdkOperation, SdkPlan } from "./plan.js";
import { docLines, inputTypeName, requiredCallOptions } from "./shared.js";
import { needsSoap, TYPESCRIPT_SOAP } from "./soap.js";
import { errorsModule, invokeModule, safetyModule, specModule } from "./typescript-core.js";

/**
 * The TypeScript SDK — a zero-dependency ESM package over the platform `fetch`.
 *
 * The safety core (`errors.ts`, `safety.ts`, `spec.ts`, `invoke.ts`) comes from
 * `typescript-core.ts` and is byte-identical for every service; only
 * `operations.ts` and `client.ts` are per-service. That split is deliberate:
 * the parts that decide whether a call is allowed to happen are one reviewed
 * implementation, and generation only ever adds rows to the table it reads.
 */
export function generateTypeScriptSdk(plan: SdkPlan): Record<string, string> {
  return {
    "sdk/typescript/package.json": packageJson(plan),
    "sdk/typescript/tsconfig.json": tsconfig(),
    "sdk/typescript/README.md": readme(plan),
    "sdk/typescript/src/errors.ts": errorsModule(),
    "sdk/typescript/src/safety.ts": safetyModule(),
    "sdk/typescript/src/spec.ts": specModule(),
    "sdk/typescript/src/invoke.ts": invokeModule(needsSoap(plan.operations)),
    // Emitted only for a service that has a SOAP operation. A REST client must
    // not ship an XML reader it never calls.
    ...(needsSoap(plan.operations)
      ? {
          "sdk/typescript/src/soap.ts": `// Generated by Anvil. Do not edit — regenerate from AIR.${TYPESCRIPT_SOAP}`,
        }
      : {}),
    "sdk/typescript/src/operations.ts": operationsModule(plan),
    "sdk/typescript/src/client.ts": clientModule(plan),
    "sdk/typescript/src/index.ts": indexModule(),
  };
}

const j = (value: unknown): string => JSON.stringify(value);

function packageJson(plan: SdkPlan): string {
  return `${JSON.stringify(
    {
      name: `@anvil-sdk/${plan.service.id}`,
      version: plan.service.version,
      description: `${plan.service.description} Generated by Anvil from AIR — same operations, same safety contract, as the CLI and MCP server.`,
      private: true,
      type: "module",
      main: "./dist/index.js",
      types: "./dist/index.d.ts",
      exports: { ".": { types: "./dist/index.d.ts", import: "./dist/index.js" } },
      files: ["dist"],
      engines: { node: ">=20" },
      scripts: { build: "tsc -p tsconfig.json", typecheck: "tsc -p tsconfig.json --noEmit" },
      devDependencies: { typescript: "^5.9.3" },
    },
    null,
    2,
  )}\n`;
}

function tsconfig(): string {
  return `${JSON.stringify(
    {
      compilerOptions: {
        target: "ES2022",
        module: "NodeNext",
        moduleResolution: "NodeNext",
        lib: ["ES2022", "DOM"],
        strict: true,
        exactOptionalPropertyTypes: false,
        declaration: true,
        outDir: "dist",
        rootDir: "src",
        skipLibCheck: true,
        types: [],
      },
      include: ["src"],
    },
    null,
    2,
  )}\n`;
}

function readme(plan: SdkPlan): string {
  const first = plan.operations[0];
  const usage = first
    ? [
        "```ts",
        `import { ${plan.service.names.pascal}Client } from "@anvil-sdk/${plan.service.id}";`,
        "",
        `const client = new ${plan.service.names.pascal}Client({ token: process.env.${plan.auth.envVar} });`,
        `const result = await client.${first.names.camel}({${first.params
          .filter((p) => p.required)
          .map((p) => ` ${p.key}: "…"`)
          .join(",")}${first.params.some((p) => p.required) ? " " : ""}}${
          requiredCallOptions(first).length > 0
            ? `, { ${requiredCallOptions(first).join(", ")} }`
            : ""
        });`,
        "```",
      ].join("\n")
    : "_This bundle has no approved operations yet._";
  return `# ${plan.service.displayName} — TypeScript SDK

${plan.service.description}

Generated by Anvil from AIR. The CLI, the MCP server, and this SDK are three
projections of one model: same operations, same wire coordinates, same safety
contract.

## Install

Zero runtime dependencies — it uses the platform \`fetch\`. Node 20+ or any
runtime with WHATWG fetch and Web Crypto.

## Usage

${usage}

## Safety contract

- **Only approved operations exist.** An operation still in review has no method.
- **Confirmation gates are compile-visible.** An operation with
  \`confirmation.required\` refuses without \`{ confirm: true }\`; one that needs
  human approval says so in the refusal.
- **Idempotency is not optional where the contract requires it.** A key is
  derived (\`anvil-<fingerprint>\`) when the contract allows derivation, and
  demanded from you when it does not.
- **Non-idempotent mutations are never retried.** The retry gate is the same
  predicate the Anvil runtime uses; a mutation that cannot prove idempotence is
  surfaced as \`unsafe_retry_blocked\` rather than sent twice.
- **\`Retry-After\` wins.** An upstream asking for longer than the ceiling ends
  the attempt budget and returns the number it gave you, instead of coming back
  early.
- **Errors are structured.** Every failure is an \`AnvilError\` carrying a code
  from the Anvil taxonomy, never raw upstream chaos.
- **Credentials never appear in errors or logs.**

## Paging and long-running work

Operations that declare pagination get an \`AsyncIterable\` variant
(\`…Paginated\`). Operations that declare a resolvable async contract get a
\`waitFor…\` helper that polls the declared status operation until a declared
terminal state.
`;
}

function operationsModule(plan: SdkPlan): string {
  const rows = plan.operations.map((op) => {
    const spec = {
      id: op.id,
      httpMethod: op.httpMethod,
      wireProtocol: op.wireProtocol,
      ...(op.wireBinding
        ? {
            soap: {
              soapAction: op.wireBinding.soapAction ?? "",
              envelopeNamespace: op.wireBinding.envelopeNamespace,
              bodyNamespace: op.wireBinding.bodyNamespace,
              bodyElement: op.wireBinding.bodyElement,
              responseElement: op.wireBinding.responseElement ?? "",
              contentType: op.wireBinding.contentType,
              soapVersion: op.wireBinding.soapVersion,
            },
          }
        : {}),
      path: op.path,
      effect: op.effect,
      params: op.params.map((p) => ({
        wireName: p.wireName,
        key: p.key,
        in: p.in,
        required: p.required,
      })),
      ...(op.body
        ? {
            body: {
              required: op.body.required,
              contentType: op.body.contentType,
              projection: op.body.projection,
              fields: op.body.fields.map((f) => ({
                wireName: f.wireName,
                key: f.key,
                required: f.required,
              })),
            },
          }
        : {}),
      idempotency: op.idempotency,
      retry: op.retry,
      confirmation: op.confirmation,
    };
    return `  ${JSON.stringify(op.names.camel)}: ${JSON.stringify(spec, null, 2)
      .split("\n")
      .join("\n  ")},`;
  });
  const interfaces = plan.operations.map((op) => inputInterface(op)).join("\n\n");
  return `// Generated by Anvil. Do not edit — regenerate from AIR.
// One row per approved operation. An operation still in review is absent here,
// which is why it cannot be called: the SDK has no way to name it.
import type { OperationSpec } from "./spec.js";

export const OPERATIONS = {
${rows.join("\n")}
} satisfies Record<string, OperationSpec>;

export type OperationName = keyof typeof OPERATIONS;

${interfaces}
`;
}

function tsType(kind: string): string {
  switch (kind) {
    case "string":
      return "string";
    case "integer":
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "array":
      return "unknown[]";
    case "object":
      return "Record<string, unknown>";
    default:
      return "unknown";
  }
}

function inputInterface(op: SdkOperation): string {
  const fields: string[] = [];
  for (const param of op.params) {
    const type = param.enumValues
      ? param.enumValues.map((value) => j(value)).join(" | ")
      : tsType(param.type);
    fields.push(
      `${docLines(param.description ?? `${param.in} parameter \`${param.wireName}\``, "  ")}  ${param.key}${param.required ? "" : "?"}: ${type};`,
    );
  }
  if (op.body?.projection === "fields") {
    for (const field of op.body.fields) {
      const type = field.enumValues
        ? field.enumValues.map((value) => j(value)).join(" | ")
        : tsType(field.type);
      fields.push(
        `${docLines(field.description ?? `body field \`${field.wireName}\``, "  ")}  ${field.key}${field.required ? "" : "?"}: ${type};`,
      );
    }
  } else if (op.body) {
    fields.push(
      `${docLines(`The request body, sent verbatim (content type \`${op.body.contentType}\`).`, "  ")}  body${op.body.required ? "" : "?"}: unknown;`,
    );
  }
  const body = fields.length > 0 ? `\n${fields.join("\n")}\n` : "\n  [key: string]: never;\n";
  return `${docLines(`Input for \`${op.canonicalName}\` — ${op.description}`, "")}export interface ${inputTypeName(op)} {${body}}`;
}

function clientModule(plan: SdkPlan): string {
  const className = `${plan.service.names.pascal}Client`;
  const methods = plan.operations.map((op) => clientMethod(op)).join("\n\n");
  return `// Generated by Anvil. Do not edit — regenerate from AIR.
import { AnvilError } from "./errors.js";
import { invoke, type ClientOptions, type FetchLike, type InvokeContext } from "./invoke.js";
import { OPERATIONS } from "./operations.js";
import type * as Inputs from "./operations.js";
import type { CallOptions } from "./spec.js";

/**
 * Read one top-level field off a decoded response. Async contracts name their
 * handle and state fields exactly; this reads that name and nothing else,
 * rather than guessing at a shape the contract never promised.
 */
function readField(value: unknown, field: string): unknown {
  return value && typeof value === "object" && !Array.isArray(value)
    ? (value as Record<string, unknown>)[field]
    : undefined;
}

/** The base URL recorded in AIR at compile time. */
export const DEFAULT_BASE_URL = ${j(plan.service.baseUrl)};
/** The environment variable read when no token is passed. */
export const TOKEN_ENV_VAR = ${j(plan.auth.envVar)};

const AUTH_CARRIER = ${plan.auth.carrier ? JSON.stringify(plan.auth.carrier) : "undefined"} as
  | { in: "header" | "query"; name: string; scheme?: string }
  | undefined;

/**
 * ${plan.service.description}
 *
 * Every method is one approved operation. The safety gates live in \`invoke\`,
 * so no method can skip them.
 */
export class ${className} {
  private readonly context: InvokeContext;

  constructor(options: ClientOptions = {}) {
    const env = (globalThis as { process?: { env?: Record<string, string | undefined> } }).process
      ?.env;
    const token = options.token ?? env?.[TOKEN_ENV_VAR];
    const fetchImpl: FetchLike =
      options.fetch ?? ((url, init) => fetch(url, init));
    this.context = {
      baseUrl: options.baseUrl ?? DEFAULT_BASE_URL,
      protocolFacade: options.protocolFacade ?? env?.["ANVIL_PROTOCOL_FACADE"],
      token,
      authCarrier: AUTH_CARRIER,
      timeoutMs: options.timeoutMs ?? 30000,
      fetchImpl,
      sleep: options.sleep ?? ((ms) => new Promise((resolve) => setTimeout(resolve, ms))),
      random: options.random ?? Math.random,
      userAgent: options.userAgent ?? ${j(`anvil-sdk-${plan.service.id}/${plan.service.version} (typescript)`)},
    };
    if (this.context.baseUrl.length === 0) {
      throw new AnvilError({
        code: "validation_error",
        operation: ${j(plan.service.id)},
        traceId: "",
        message:
          "No base URL: the compiled model records no server, so one must be passed as { baseUrl }.",
        requiredFlags: ["baseUrl"],
      });
    }
  }

${methods}
}
`;
}

function clientMethod(op: SdkOperation): string {
  const inputType = `Inputs.${inputTypeName(op)}`;
  const lines = [
    methodDoc(op),
    `  async ${op.names.camel}(input: ${inputType}, options: CallOptions = {}): Promise<unknown> {`,
    `    return invoke(OPERATIONS.${op.names.camel}, input as unknown as Record<string, unknown>, options, this.context);`,
    "  }",
  ];
  const page = op.pagination;
  if (page?.cursorKey && page.nextField) {
    const itemsField = page.itemsField;
    lines.push(
      "",
      `  /**
   * Page through \`${op.canonicalName}\` until the upstream stops handing back a
   * continuation. Each yielded value is one ${itemsField ? `item from \`${itemsField}\`` : "page"}.
   */`,
      `  async *${op.names.camel}Paginated(input: ${inputType}, options: CallOptions = {}): AsyncGenerator<unknown, void, undefined> {`,
      "    const seen = new Set<string>();",
      `    let cursor: string | undefined = (input as Record<string, unknown>)[${j(page.cursorKey)}] as string | undefined;`,
      "    for (;;) {",
      `      const page = (await this.${op.names.camel}(`,
      `        { ...input, ...(cursor === undefined ? {} : { ${page.cursorKey}: cursor }) } as ${inputType},`,
      "        options,",
      "      )) as Record<string, unknown> | null;",
      '      if (page === null || typeof page !== "object") return;',
      itemsField
        ? `      const items = page[${j(itemsField)}];\n      if (Array.isArray(items)) { for (const item of items) yield item; } else if (items !== undefined) { yield items; }`
        : "      yield page;",
      `      const next = page[${j(page.nextField)}];`,
      '      if (typeof next !== "string" || next.length === 0) return;',
      // A server that echoes its own cursor would spin this loop forever; stop
      // instead of paging the same page until the process is killed.
      "      if (seen.has(next)) return;",
      "      seen.add(next);",
      "      cursor = next;",
      "    }",
      "  }",
    );
  }
  const async = op.async;
  if (async?.statusMethodBase && async.statusJobIdKey && async.terminalStates.length > 0) {
    lines.push(
      "",
      `  /**
   * ${async.instruction}
   *
   * Polls at the interval the contract declares and returns the first status
   * response in a terminal state. Never invents a coordinate: every field name
   * below is the one AIR resolved.
   */`,
      `  async waitFor${op.names.pascal}(submitResult: unknown, options: { timeoutMs?: number; call?: CallOptions } = {}): Promise<unknown> {`,
      `    const handle = readField(submitResult, ${j(async.jobIdField)});`,
      '    if (typeof handle !== "string" || handle.length === 0) {',
      "      throw new AnvilError({",
      '        code: "schema_mismatch",',
      `        operation: ${j(op.id)},`,
      '        traceId: "",',
      `        message: "The submit response carried no ${async.jobIdField} to poll on.",`,
      "      });",
      "    }",
      `    const deadline = Date.now() + (options.timeoutMs ?? ${async.pollIntervalSeconds * 1000 * 60});`,
      `    const terminal = new Set(${j(async.terminalStates)});`,
      "    for (;;) {",
      `      const status = await this.${camelOf(async.statusMethodBase)}({ ${async.statusJobIdKey}: handle } as never, options.call ?? {});`,
      `      const state = readField(status, ${j(async.stateField ?? "state")});`,
      '      if (typeof state === "string" && terminal.has(state)) return status;',
      "      if (Date.now() >= deadline) {",
      "        throw new AnvilError({",
      '          code: "upstream_timeout",',
      `          operation: ${j(op.id)},`,
      '          traceId: "",',
      `          message: "${op.canonicalName} did not reach a terminal state before the wait deadline.",`,
      "          retryable: true,",
      "        });",
      "      }",
      `      await this.context.sleep(${async.pollIntervalSeconds * 1000});`,
      "    }",
      "  }",
    );
  }
  return lines.join("\n");
}

function camelOf(canonicalName: string): string {
  return canonicalName
    .split("_")
    .filter(Boolean)
    .map((word, index) => (index === 0 ? word : word.charAt(0).toUpperCase() + word.slice(1)))
    .join("");
}

function methodDoc(op: SdkOperation): string {
  const lines = [
    op.description,
    "",
    `\`${op.httpMethod} ${op.path}\` · operation \`${op.id}\``,
    `Aligned surfaces: CLI \`${op.cliCommand}\` · MCP tool \`${op.mcpToolName}\``,
    `Effect: ${op.effect}${op.effect === "mutation" ? ` (risk ${op.risk}, ${op.reversible ? "reversible" : "IRREVERSIBLE"})` : ""}`,
    `Idempotency: ${op.idempotency.mode} · retry: ${op.retry.mode}`,
  ];
  if (op.confirmation.required) {
    lines.push(
      `Requires \`{ confirm: true }\`${op.confirmation.humanApproval ? " and explicit HUMAN approval" : ""}${op.confirmation.reason ? ` — ${op.confirmation.reason}` : ""}.`,
    );
  }
  if (op.idempotency.callerKeyRequired) {
    lines.push("Requires `{ idempotencyKey }` — Anvil cannot derive one for this contract.");
  }
  if (op.deprecated) lines.push("@deprecated This operation is marked deprecated upstream.");
  return `  /**\n${lines.map((line) => `   * ${line}`.trimEnd()).join("\n")}\n   */`;
}

function indexModule(): string {
  return `// Generated by Anvil. Do not edit — regenerate from AIR.
export * from "./client.js";
export * from "./errors.js";
export * from "./operations.js";
export * from "./safety.js";
export * from "./spec.js";
export type { ClientOptions, FetchLike } from "./invoke.js";
`;
}
