import type { ComposeCatalog } from "./catalog.js";
import { TYPESCRIPT_FLOW } from "./typescript-flow.js";

/**
 * The TypeScript composite SDK: the same `Composite` and `Flow` as the
 * Python one, with the same flow, plan and run documents. Connector clients
 * are imported from their own generated SDK sources (`clients.ts`), so every
 * call still runs that SDK's gates.
 */

const RUNTIME = String.raw`// Generated by Anvil. Do not edit — regenerate with 'anvil connectors compose'.
//
// The composite SDK: every composed connector behind one object, and Flow, a
// DAG of calls across them. Each step is one ordinary call to a connector
// SDK method, so approval, confirmation, idempotency and (in gateway mode)
// the branch's grant apply exactly as they do to a direct call. Nothing here
// undoes anything on its own: compensate() runs only when called.
import { CATALOG } from "./catalog.js";
import { CLIENTS } from "./clients.js";

export const FLOW_SCHEMA = "anvil.compose-flow/v1";
export const PLAN_SCHEMA = "anvil.compose-plan/v1";
export const RUN_SCHEMA = "anvil.compose-run/v1";

type Json = unknown;
type Op = {
  id: string;
  title: string;
  method: { python: string; typescript: string };
  safety: { confirm: string; idempotencyKey: string; dryRun: string };
  effect: string;
  effectClass: string;
  confirm: boolean;
  idempotencyKeyRequired: boolean;
  inputs: Array<{ key: string; wire: string; required: boolean }>;
  undo?: { kind: string; operation: string; arguments: Record<string, unknown> };
};
type ConnectorRow = { id: string; title: string; operations: Op[] };

const CONNECTORS: Map<string, ConnectorRow> = new Map(
  (CATALOG.connectors as unknown as ConnectorRow[]).map((c) => [c.id, c]),
);

export class ComposeError extends Error {
  constructor(
    readonly code: string,
    message: string,
    readonly details: Record<string, unknown> = {},
  ) {
    super(message);
    this.name = "ComposeError";
  }
  toJSON(): Record<string, unknown> {
    return { code: this.code, message: this.message, details: this.details };
  }
}

// -- paths and references ------------------------------------------------------

const NAME = /^[A-Za-z_$][A-Za-z0-9_$-]*/;
const INDEX = /^\[(\d+)\]/;

function segments(path: string): Array<string | number> {
  const out: Array<string | number> = [];
  let rest = path ?? "";
  if (rest && !rest.startsWith(".") && !rest.startsWith("[")) rest = "." + rest;
  while (rest) {
    if (rest.startsWith(".")) {
      const m = NAME.exec(rest.slice(1));
      if (!m) throw new ComposeError("invalid_path", "expected a name after '.' in '" + path + "'");
      out.push(m[0]);
      rest = rest.slice(1 + m[0].length);
      continue;
    }
    const m = INDEX.exec(rest);
    if (!m) throw new ComposeError("invalid_path", "unexpected '" + rest[0] + "' in '" + path + "'");
    out.push(Number(m[1]));
    rest = rest.slice(m[0].length);
  }
  return out;
}

const MISSING: unique symbol = Symbol("missing");
type Found = unknown | typeof MISSING;

function walk(value: unknown, path: string): Found {
  let current: unknown = value;
  for (const segment of segments(path)) {
    if (typeof segment === "number") {
      if (Array.isArray(current) && segment < current.length) {
        current = current[segment];
        continue;
      }
      return MISSING;
    }
    if (current && typeof current === "object" && !Array.isArray(current) && segment in (current as object)) {
      current = (current as Record<string, unknown>)[segment];
      continue;
    }
    return MISSING;
  }
  return current;
}

export class Ref {
  constructor(
    readonly step: string | null,
    readonly path = "",
  ) {
    if (path) segments(path);
  }
  toJSON(): Record<string, unknown> {
    if (this.step === null) return { $item: this.path };
    return this.path ? { $ref: this.step, path: this.path } : { $ref: this.step };
  }
  equals(value: unknown): Record<string, unknown> {
    return { ...this.toJSON(), equals: value };
  }
  exists(): Record<string, unknown> {
    return { ...this.toJSON(), exists: true };
  }
  truthy(): Record<string, unknown> {
    return { ...this.toJSON(), truthy: true };
  }
}

export class StepHandle {
  constructor(readonly id: string) {}
  ref(path = ""): Ref {
    return new Ref(this.id, path);
  }
  at(index: number): Ref {
    return new Ref(this.id, "[" + index + "]");
  }
}

/** A reference to a step's result at path ("" is the whole result). */
export function ref(step: string | StepHandle, path = ""): Ref {
  return new Ref(step instanceof StepHandle ? step.id : step, path);
}

/** Inside Flow.map: the current element of the list being mapped over. */
export function item(path = ""): Ref {
  return new Ref(null, path);
}

function encode(value: unknown): Json {
  if (value instanceof Ref) return value.toJSON();
  if (value instanceof StepHandle) return { $ref: value.id };
  if (Array.isArray(value)) return value.map(encode);
  if (value && typeof value === "object") {
    return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, encode(v)]));
  }
  return value;
}

function isObject(value: unknown): value is Record<string, unknown> {
  return !!value && typeof value === "object" && !Array.isArray(value);
}

function refsIn(value: unknown, out: string[] = []): string[] {
  if (Array.isArray(value)) value.forEach((v) => refsIn(v, out));
  else if (isObject(value)) {
    if ("$ref" in value) out.push(String(value.$ref));
    else Object.values(value).forEach((v) => refsIn(v, out));
  }
  return out;
}

function usesItem(value: unknown): boolean {
  if (Array.isArray(value)) return value.some(usesItem);
  if (isObject(value)) return "$item" in value || Object.values(value).some(usesItem);
  return false;
}

function placeholder(step: string, path: string): string {
  return "<" + step + (path && !path.startsWith("[") ? "." + path : path) + ">";
}

function resolve(value: unknown, results: Map<string, unknown>, current: Found, placeholders: boolean): unknown {
  if (Array.isArray(value)) return value.map((v) => resolve(v, results, current, placeholders));
  if (!isObject(value)) return value;
  if ("$ref" in value) {
    const step = String(value.$ref);
    const path = String(value.path ?? "");
    const found = results.has(step) ? walk(results.get(step), path) : MISSING;
    if (found === MISSING) {
      if (placeholders) return placeholder(step, path);
      throw new ComposeError("unresolved_ref", "step '" + step + "' has nothing at '" + path + "'", { step, path });
    }
    return found;
  }
  if ("$item" in value) {
    const path = String(value.$item ?? "");
    if (current === MISSING) {
      if (placeholders) return placeholder("item", path);
      throw new ComposeError("unresolved_ref", "$item is only meaningful inside map");
    }
    const found = walk(current, path);
    if (found === MISSING) throw new ComposeError("unresolved_ref", "the mapped item has nothing at '" + path + "'");
    return found;
  }
  return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, resolve(v, results, current, placeholders)]));
}

function conditionHolds(when: Record<string, unknown>, results: Map<string, unknown>): boolean {
  const step = String(when.$ref);
  const found = results.has(step) ? walk(results.get(step), String(when.path ?? "")) : MISSING;
  if ("equals" in when) return found !== MISSING && JSON.stringify(found) === JSON.stringify(when.equals);
  if (when.exists) return found !== MISSING && found !== null && found !== undefined;
  return found !== MISSING && !!found;
}

// -- the composite ---------------------------------------------------------------

export interface FlowStep {
  id: string;
  operation: string;
  connector?: string;
  args?: Record<string, Json>;
  after?: string[];
  when?: Record<string, Json>;
  for_each?: Record<string, Json>;
  confirm?: boolean;
  idempotency_key?: string;
}

export interface FlowDocument {
  schema?: string;
  name?: string;
  steps: FlowStep[];
}

export interface Finding {
  level: "error" | "warning";
  code: string;
  step: string | null;
  message: string;
}

export interface CallOptions {
  connector?: string;
  confirm?: boolean;
  idempotencyKey?: string;
  dryRun?: boolean;
}

function envName(connector: string): string {
  return connector.replace(/[^A-Za-z0-9]+/g, "_").toUpperCase();
}

function normalise(op: Op, args: Record<string, unknown>): Record<string, unknown> {
  const keys = new Set(op.inputs.map((i) => i.key));
  const byWire = new Map(op.inputs.map((i) => [i.wire, i.key]));
  const out: Record<string, unknown> = {};
  for (const [name, value] of Object.entries(args)) {
    const key = keys.has(name) ? name : byWire.get(name);
    if (key === undefined) {
      throw new ComposeError("unknown_input", "operation " + op.id + " takes no input '" + name + "'", {
        operation: op.id,
        input: name,
      });
    }
    out[key] = value;
  }
  return out;
}

/**
 * Every composed connector's client, and the flows that span them. Options
 * go to every connector client; perConnector adds options for one. In
 * gateway mode (ANVIL_GATEWAY_URL) each client calls the gateway under its
 * own connector id; outside it, ANVIL_<CONNECTOR>_BASE_URL may set a base URL.
 */
export class Composite {
  private readonly clients = new Map<string, any>();
  constructor(
    private readonly options: Record<string, unknown> = {},
    private readonly perConnector: Record<string, Record<string, unknown>> = {},
  ) {
    for (const id of Object.keys(perConnector)) this.connector(id);
  }

  connectors(): string[] {
    return [...CONNECTORS.keys()].sort();
  }

  operations(connector?: string): Array<Op & { connector: string }> {
    const ids = connector ? [connector] : this.connectors();
    return ids.flatMap((id) => this.connector(id).operations.map((op) => ({ ...op, connector: id })));
  }

  describe(operation: string, connector?: string): Op & { connector: string } {
    const [id, op] = this.resolve(operation, connector);
    return { ...op, connector: id };
  }

  resolve(operation: string, connector?: string): [string, Op] {
    if (connector === undefined && operation.includes(":")) {
      const at = operation.indexOf(":");
      connector = operation.slice(0, at);
      operation = operation.slice(at + 1);
    }
    const ids = connector ? [connector] : this.connectors();
    const found: Array<[string, Op]> = [];
    for (const id of ids) {
      for (const op of this.connector(id).operations) if (op.id === operation) found.push([id, op]);
    }
    if (found.length === 0) {
      throw new ComposeError("unknown_operation", "no composed connector has operation '" + operation + "'", {
        operation,
        connector,
      });
    }
    if (found.length > 1) {
      throw new ComposeError(
        "ambiguous_operation",
        "operation '" + operation + "' is in " + found.map(([c]) => c).join(", ") + "; name the connector",
        { operation, connectors: found.map(([c]) => c) },
      );
    }
    return found[0] as [string, Op];
  }

  private connector(id: string): ConnectorRow {
    const row = CONNECTORS.get(id);
    if (!row) {
      throw new ComposeError(
        "unknown_connector",
        "connector '" + id + "' is not composed (composed: " + this.connectors().join(", ") + ")",
        { connector: id },
      );
    }
    return row;
  }

  /** The connector's own generated client, built on first use. */
  client(connector: string): any {
    this.connector(connector);
    if (!this.clients.has(connector)) {
      const options: Record<string, unknown> = { ...this.options, ...(this.perConnector[connector] ?? {}) };
      if (options.gatewayConnector === undefined) options.gatewayConnector = connector;
      const env = (globalThis as { process?: { env?: Record<string, string | undefined> } }).process?.env;
      const baseUrl = env?.["ANVIL_" + envName(connector) + "_BASE_URL"];
      if (baseUrl && options.baseUrl === undefined) options.baseUrl = baseUrl;
      const make = (CLIENTS as Record<string, (o: Record<string, unknown>) => unknown>)[connector];
      if (!make) throw new ComposeError("connector_missing", "connector '" + connector + "' has no client");
      this.clients.set(connector, make(options));
    }
    return this.clients.get(connector);
  }

  /** One call by operation id, through the connector SDK's own method. */
  async call(operation: string, args: Record<string, unknown> = {}, options: CallOptions = {}): Promise<unknown> {
    const [id, op] = this.resolve(operation, options.connector);
    const client = this.client(id);
    const method = client[op.method.typescript] as (i: unknown, o: unknown) => Promise<unknown>;
    return method.call(client, normalise(op, args), {
      confirm: options.confirm ?? false,
      ...(options.idempotencyKey !== undefined ? { idempotencyKey: options.idempotencyKey } : {}),
      dryRun: options.dryRun ?? false,
    });
  }

  flow(name = "flow"): Flow {
    return new Flow(this, name);
  }

  /** A Flow from an anvil.compose-flow/v1 document. */
  load(document: FlowDocument | string): Flow {
    const doc = (typeof document === "string" ? JSON.parse(document) : document) as FlowDocument;
    if (!doc || (doc.schema !== undefined && doc.schema !== FLOW_SCHEMA) || !Array.isArray(doc.steps)) {
      throw new ComposeError("invalid_flow", "expected an " + FLOW_SCHEMA + " document");
    }
    const flow = new Flow(this, doc.name ?? "flow");
    for (const step of doc.steps) {
      if (!step || !step.id || !step.operation) {
        throw new ComposeError("invalid_flow", "every step needs an id and an operation");
      }
      flow.add(JSON.parse(JSON.stringify(step)) as FlowStep);
    }
    return flow;
  }
}


`;

function clientsModule(catalog: ComposeCatalog): string {
  const imports = catalog.connectors.map(
    (c, i) =>
      `import { ${c.typescript.client} as Client${i} } from ${JSON.stringify(c.typescript.import)};`,
  );
  const rows = catalog.connectors.map(
    (c, i) =>
      `  ${JSON.stringify(c.id)}: (options: Record<string, unknown>) => new Client${i}(options as never),`,
  );
  return `// Generated by Anvil. Do not edit — regenerate with 'anvil connectors compose'.
// Each composed connector's own generated client, imported from its SDK source.
${imports.join("\n")}

export const CLIENTS = {
${rows.join("\n")}
};
`;
}

/** The TypeScript composite package files, keyed relative to the composite directory. */
export function typescriptCompositeFiles(catalog: ComposeCatalog): Record<string, string> {
  return {
    "typescript/src/catalog.ts": `// Generated by Anvil. Do not edit — regenerate with 'anvil connectors compose'.\nexport const CATALOG = ${JSON.stringify(catalog, null, 2)} as const;\n`,
    "typescript/src/clients.ts": clientsModule(catalog),
    "typescript/src/flow.ts": RUNTIME + TYPESCRIPT_FLOW,
    "typescript/src/index.ts": `// Generated by Anvil. Do not edit — regenerate with 'anvil connectors compose'.\nexport * from "./flow.js";\nexport { CATALOG } from "./catalog.js";\n`,
    "typescript/package.json": `${JSON.stringify(
      {
        name: "@anvil-sdk/compose",
        private: true,
        type: "module",
        description:
          "Generated by Anvil: the composed connectors behind one client, and flows (DAGs of calls) across them.",
        engines: { node: ">=20" },
        scripts: { typecheck: "tsc -p tsconfig.json --noEmit" },
        devDependencies: { typescript: "^5.9.3" },
      },
      null,
      2,
    )}\n`,
    "typescript/tsconfig.json": `${JSON.stringify(
      {
        compilerOptions: {
          target: "ES2022",
          module: "NodeNext",
          moduleResolution: "NodeNext",
          lib: ["ES2022", "DOM"],
          strict: true,
          declaration: true,
          outDir: "dist",
          skipLibCheck: true,
          types: [],
        },
        include: ["src"],
      },
      null,
      2,
    )}\n`,
  };
}
